### ISSUE TITLE
SABnzbd fails to start on my DS216play

### ISSUE THREAD

**Issue by ldoench** [SynoCommunity/spksrc#2633] opened 2017-02-03 19:43 UTC
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ SABnzbd
_Package Version:_ 1.2.0-20

_NAS Model:_ DS 216 Play
_NAS Architecture:_ monaco x16 Series
_DSM version:_ DSM 6.0.2-8451 Update 9

### Expected behavior
It should start after I installed it

### Actual behavior
It gives me this screen: http://imgur.com/a/Qn8uy 
(This package service could not be started)

### Steps to reproduce
_1._ Add SynoCommunity to your package sources
_2._ Install Python and SABnzbd:
_2.1._ Setting  /volume1/downloads  als the Download directory

#### Package log
_Check Package Center:_ No Data

#### Other logs
http://pastebin.com/FecqXzga

**Comment by Dr-Bean** [comment] 2017-02-03 19:57
Please use the search before opening an issue. Duplicate of https://github.com/SynoCommunity/spksrc/issues/2416. The issue is related to #2216, subscribe to it to keep informed of updates.

**Closed by Dr-Bean** 2017-02-03 19:57 UTC
