### ISSUE TITLE
Radarr 3.0.1: Can't add movie

### ISSUE THREAD

**Issue by severdia** [SynoCommunity/spksrc#4317] opened 2020-12-18 23:33 UTC
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Radarr
_Package Version:_ 3.0.1.4259

_NAS Model:_ Synology
_NAS Architecture:_ x64
_DSM version:_ 6.2.3-25426 Update 3

### Expected behavior
Clicking the Add Movie button should add the movie to the queue.

### Actual behavior
The Add Movie button animates, but doesn't add the movie.

### Steps to reproduce
_1._ Search for a movie. 
_2._ Click the search results to open the modal.
_3._ Click Add Movie button.

![bug](https://user-images.githubusercontent.com/355924/102672688-57b61900-4146-11eb-949f-ed9159ab6691.gif)

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by publicarray** [comment] 2020-12-19 22:06
Without logs, I can only guess what the problem is. Maybe a permission issue when modifying the database, a locked database, a buggy browser extension... What does the browser console tell you? Are you blocking WebRTC?

Works on my machine ™

**Comment by publicarray** [comment] 2020-12-19 22:24
In `Settings/Media Management/` have you added a Root Folder and given `sc-download` read & write permissions?

**Comment by severdia** [comment] 2020-12-20 16:09
@publicarray What logs would be helpful? I'm using Safari 14.0.2. Yes, the `sc-download` group exists with the correct permissions. Not blocking any Websockets. Here's the browser log:

![Screen Shot 2020-12-20 at 7 58 12 AM](https://user-images.githubusercontent.com/355924/102717892-f8691d80-4299-11eb-8599-81c589322c40.png)

Radarr was working fine until the latest updates and I haven't made any configuration changes.

**Comment by publicarray** [comment] 2020-12-20 21:05
Thanks that already narrows this down somewhat. 

You can find the logs In the radarr web UI in `System/Log Files`

It might help if you change logging to `trace` in `Settings/General` and try adding a movie again. Make sure to return the log level to info. 

Would you be willing to try a different browser (Firefox or Chrome)?

Thanks for your patience.

**Comment by severdia** [comment] 2020-12-21 16:00
@publicarray OK, turned on trace and attached trace log. I tried to add an example movie three times (you can see this in the log). Yes, I tried both Chrome and Firefox and they have the same issue. 

[radar.trace.txt.zip](https://github.com/SynoCommunity/spksrc/files/5725239/radar.trace.txt.zip)

**Comment by publicarray** [comment] 2020-12-21 21:54
Thanks @severdia, according to the logs the path (I assume `/volume2/Files`) is no longer valid. Can you create a new shared folder and set up the permissions again?

```
2020-12-21 07:51:33.4|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- Path: Path is child of configured recycle bin folder
2020-12-21 07:51:33.4|Trace|Http|Res: 21 [POST] /api/v3/movie: 400.BadRequest (136 ms)
```

FYI:  The Bitru indexer is failing:

```
2020-12-21 07:49:01.1|Debug|IndexerFactory|Temporarily ignoring indexer Bitru till 12/22/2020 00:20:49 due to recent failures.
```

**Comment by publicarray** [comment] 2020-12-21 22:13
CC @Qstick https://github.com/Radarr/Radarr/commit/fd4fb88ce1efa8f673c74f04cd632a3f607565c4

**Comment by Qstick** [comment] 2020-12-21 22:17
That error means you are trying to set the movie root path to a path that is a child folder of your Radarr recycling bin (a good way to wipe the library)... Go into settings and change your recycling bin path or change where movies are stored so it's not in said recycling bin path.

**Comment by severdia** [comment] 2020-12-21 22:19
@publicarray Yes, that path is valid, but I tried to remove and re-add it in the Media Management settings and it wouldn't let me re-add it. 

![Screen Shot 2020-12-21 at 2 02 16 PM](https://user-images.githubusercontent.com/355924/102826560-c806a980-4395-11eb-9520-5b8758add5ee.png)

I selected the right folder and clicked OK, but it wasn't added. It has a similar 400 error in the console.

![Screen Shot 2020-12-21 at 2 10 12 PM](https://user-images.githubusercontent.com/355924/102826839-4b27ff80-4396-11eb-98e4-141965e7ae0c.png)

So I went to the shared folder settings and the folder path/permissions are correct.

![Screen Shot 2020-12-21 at 2 05 39 PM](https://user-images.githubusercontent.com/355924/102826614-e2d91e00-4395-11eb-9732-968d8a33c929.png)

No matter what folder I select, it fails to be added to the settings.  The `sc-download` group is there and has Read/Write permissions on that directory.  The path is` /volume1/Files/Downloads` so it's not in the `#recycle` directory—which is weird it would say it's in that directory when it definitely isn't. This path and setup has not change at all for over a year. The only change have been updating Radarr to the 3.x versions. Yes, I saw that indexer is failing.

**Comment by Qstick** [comment] 2020-12-21 22:22
What do your Radarr recycling bin settings look like?

![Screenshot_20201221-172127.png](https://user-images.githubusercontent.com/376117/102827708-137a8100-43b1-11eb-8b8b-aca425d178f8.png)

**Comment by severdia** [comment] 2020-12-21 22:28
Thanks @qstick. You're right. That settings had `/volume1` in it for some reason. I've never used this feature so I've disabled it and was able to re-add the root folder. And I was able to successfully add a movie!

So I guess the bug here is somehow a value was added to the Recycling Bin setting when updating Radarr. And, like you said, that could have been disastrous if I hadn't discovered it before automatic cleanup happened.

**Comment by publicarray** [comment] 2020-12-21 22:29
Thank @Qstick!

**Comment by Qstick** [comment] 2020-12-21 22:32
Cool. We don't set that path in any migration so it's got to be a previous setting I'd think.

**Comment by publicarray** [comment] 2020-12-26 22:32
I think we can close this as a configuration issue possibly through multiple updates that added /Volumes as a default somewhere or was added manually by accident a long time ago. Ether way I don't see us making any change to the current package.

IIRC Attempting to write to /Volume1 will always fail anyway because packages don't have permissions. So it's not as disastrous as you think.

**Closed by publicarray** 2020-12-26 22:32 UTC
