### ISSUE TITLE
rutorrent create torrent error

### ISSUE THREAD

**Issue by mellowpimp** [SynoCommunity/spksrc#1467] opened 2015-02-03 20:02 UTC
Hello,

The create torrent function in rutorrent does not work for me. i can enter all settings, but when i press create it will try creating the torrent file but after a few seconds it will say " error." and thats it.

i can't find anything in any logfiles. all permissions on directories seem to be fine as far as i can see. 
i have seem more people with this issue, but im not sure what is causing it. didnt no where else to post so seeking here for advice. 

thanks.

**Comment by Oleekae** [comment] 2015-02-04 20:56
same situation friend. Any clues would be welcome

**Comment by mal68** [comment] 2015-02-06 12:42
I have the same issue, have spent some time learning how to make sure the permissions are correct and everything seems to be in order. But it just simply waits a couple of seconds and then says "error"

**Comment by Dr-Bean** [comment] 2016-04-07 18:23
rutorrent 3.7-8 has been released, and I can't reproduce it with that. I'm closing this one, feel free to open a new issue if you still encounter the problem.

**Closed by Dr-Bean** 2016-04-07 18:23 UTC
