### ISSUE TITLE
sabnzb will not start

### ISSUE THREAD

**Issue by schlidda** [SynoCommunity/spksrc#2283] opened 2016-04-25 16:57 UTC
Hi All,

I´ve installed also 1.0.0.5 but it will not start.
do i need to uninstall 0.7.2 ? i´ve stopped it.

thanks!

**Comment by nickveldrin** [comment] 2016-04-25 20:53
Hi. What i've noticed in my time looking at packages, is that it won't let you do stuff if the port will be the same.  Many times, it won't even let you install something if the port is the same as something you've got installed.

You can find a list of services under /usr/syno/etc/services/ and look at the contents of the files there to see some of what you have that could be blocking it.

Otherwise, go to /var/packages/<name_of_package>/scripts and look at the contents of the start-stop-status script to see what user it's trying to run as, what directories it's trying to make logs for, etc, and try to debug it. 

I ran into a lot of little bugs when i was trying to reinstall my packages after having to reload my synology from scratch, and for whatever reason, i had to tweak a lot of little things to make it all work.  A lot of times it was just permissions related, and because i had already established directory structures, etc.

**Comment by schlidda** [comment] 2016-04-26 09:30
Hi, thanks for reply!. 

sorry for the dumb question. but how can i go into this Folder?

regards
schlidda

**Comment by nickveldrin** [comment] 2016-04-26 13:10
This thread should be closed as duplicate of https://github.com/SynoCommunity/spksrc/issues/2207

I found that thread after hunting around.

@schlidda - You need to do manual editting of permissions if you want to work around the problems. If you do, you may break future compatibility if you don't know how to fix/work around things in the future.

**Comment by schlidda** [comment] 2016-04-29 12:08
thanks nick,

it was becuase of the same port. now permission errors.

do i need to change permissions with putty?´or what is needed?

another question. I´ve got a brandwidth upgrade. sabnzb reaches 4,5-4,8 MB/second. 6 are possible. so i guess thats all what i can get? CPU is with ~80%

regards
stephan

**Comment by nickveldrin** [comment] 2016-04-29 12:56
@schlidda - Take a look at that thread i posted earlier to get some more information on how others have resolved the permissions issue.

Regarding your speed, i'm not sure. I've generally found that usually if things are slower, it's likely because your usenet provider is throttling it.

**Comment by schlidda** [comment] 2016-04-29 20:59
no, there is no throttling :) With my last provider i had 20MB/s.


speed via local installed sabnzb: 6,5 MB/s
speed on Synology 4,5-4,8 MB/s

**Comment by cytec** [comment] 2016-04-30 19:22
@schlidda sabnzbd is written in python which isn't a native language but a script language so generally everything is a little bit slower and requires a little bit more CPU... maybe try nzbget if you want to max out your speed... nzbget is written in c and thus a lot faster than sabnzb ;)

**Comment by Dr-Bean** [comment] 2016-05-09 08:24
Can this be closed, or are there still open issues?

**Comment by nickveldrin** [comment] 2016-05-09 09:38
@Dr-Bean It should be closed as a dupe issue as i mentioned above.

**Comment by Dr-Bean** [comment] 2016-05-09 09:42
Not necessarily...there's no mention of DSM6 in here.

**Comment by Dr-Bean** [comment] 2016-05-23 06:22
Closing,  no response.

**Closed by Dr-Bean** 2016-05-23 06:22 UTC
