### ISSUE TITLE
Squidguard 1.5-1 DS415+ No GUI

### ISSUE THREAD

**Issue by falinskip** [SynoCommunity/spksrc#1442] opened 2015-01-08 01:58 UTC
Greetings
I am unable to get to the web gui or find an application for squidguard in the main menu.  Could I get some direction on that or is there a port to go to.  Otherwise seems to function fine, though making changes in the config files a bit of a pain, looking for gui.

**Comment by falinskip** [comment] 2015-01-09 22:46
Additional information.  I did find that Pearl was not installed on my system as well.  I installed Pearl and am still unable to view the files.  Created a sym link in the WWW directory named squidguard to point back to the squidguard directory in VAR and still no luck.  Error message I am getting now is that I have to sign in as admin.  But no login page there.

**Comment by Dr-Bean** [comment] 2015-01-13 10:41
There's an icon in the DSM menu, linking to squidguardmanager. Use the administrator account to see the icon/open the manager.
However, because the package is outdated/the security methods of Synology have been updated, it's possible you cannot gain access without the need of removing/updating some code in `/usr/local/squidguard/share/www/squidguardmgr/squidGuard.cgi` (specifically, [this stuff](https://github.com/SynoCommunity/spksrc/blob/develop/cross/squidguardmanager/patches/squidguardmgr.cgi.patch) doesn't work as-is.

**Comment by falinskip** [comment] 2015-01-19 19:21
Removed all the code in "this stuff" in green - see the manager.  Just get page not found when I click on it.  everything in logs looks good.  Just no gui yet.  Any recommendations?

**Comment by Dr-Bean** [comment] 2015-01-24 15:28
I made the exact same changes, and it's working here...so if it doesn't work, imo, it's a local issue on your side. Did you revert all the changes you made previously (with regards to the manual symlink creation in `/var/www` and whatnot)?

**Comment by Dr-Bean** [comment] 2015-01-31 10:46
Since I am not able to reproduce it, I'll close this. Obviously, PR's to improve the compatibility of Squidguard are welcome.

**Closed by Dr-Bean** 2015-01-31 10:46 UTC

**Comment by transistorgit** [comment] 2015-02-23 20:36
For me, removing the changes from "this stuff" worked (also readd the our lang = 'en_US'; line)
the GUI works now (DS214+ with DSM5.1 5022 Update 2)

**Comment by Dom69** [comment] 2016-03-29 08:42
Hi everybody,

I have the same issue with SquidGuard Manager till the update to DSM 6, all was ok beforre with DSM 5.2.
I've tried to change the parameters of the fire wall no result.

Perhaps changing the squiguard.cgi could help, but "this stuff" is not avalaible any more ... Could any one writes it back for me please?

Other ideas?

Thanks for your help
Best regards

**Comment by Dr-Bean** [comment] 2016-03-29 08:46
@Dom69 Please use #2207. No point in commenting in a closed issue, especially if there's no relation.

**Comment by Dom69** [comment] 2016-03-29 09:34
OK, but could it be possible to have the content of "this stuff" of this thread, please?

**Comment by Dr-Bean** [comment] 2016-03-29 10:02
https://github.com/SynoCommunity/spksrc/blob/master/cross/squidguardmanager/patches/squidguardmgr.cgi.patch
