### ISSUE TITLE
How to update ZNC 1.6?

### ISSUE THREAD

**Issue by iruyanka** [SynoCommunity/spksrc#1733] opened 2015-06-02 00:09 UTC
How to update ZNC 1.6?

I can't find in package center update list.

**Comment by Diaoul** [comment] 2015-06-02 08:55
Update requires some work by SynoCommunity and a push to our repository. That's why you don't see the update.
Someone might eventually get it done if asked nicely.

**Comment by iruyanka** [comment] 2015-06-03 20:34
I waited for updates for three months. I want to use the 1.6 version. If possible, please push.

**Comment by iruyanka** [comment] 2015-06-16 09:51
https://github.com/SynoCommunity/spksrc/issues/1457#issuecomment-72369955

We'll wait for a new stable release of ZNC.

It's meant wait next version of over 1.6 stable?

**Comment by cytec** [comment] 2015-06-16 10:58
@iruyanka i think there was a problem with ZNC 1.6 requiere C++11 which is not supported by most of the Synology 5.1 Toolchains (except x64 i think)

**Comment by piejanssens** [comment] 2015-06-20 10:16
From the ZNC changelog: `Bump compiler requirements to support C++11. This means GCC 4.7+, Clang 3.2+, SWIG 3.0.0+.`

**Comment by Dr-Bean** [comment] 2015-07-21 07:18
@Diaoul As you're the assignee here, I've published 1.6.0 for Alpine/Alpine4k (as it's the current version in spksrc) Might as well release 1.6.0 for x64, and leave the rest on 1.4. Objections?

**Comment by Diaoul** [comment] 2015-07-21 09:02
No objection, I thought I'd have some time to do it :)

**Comment by Dr-Bean** [comment] 2015-07-29 09:49
...and delayed again. I can't get that `push`plugin to work at all: it force-closes here, with both ZNC v1.4 and ZNCv1.6, and on two different arches. So either I publish as-is, or someone else can check if they can reproduce my issues.

**Comment by Dr-Bean** [comment] 2015-08-07 07:43
ZNC 1.6 for x86-64 arches has been published as a beta package. Disclaimer: I cannot get that push module to work, but that might be me: I'm not a regular user of ZNC.

ZNC 1.4 is still available on stable for x86-64 arches and others that cannot be updated due to GCC being too old.

_If_ Synology updates the toolchains to GCC4.7 with the next update, we can revisit this. Seeing as there's nothing else we can do with this issue, let's close it.

**Closed by Dr-Bean** 2015-08-07 07:43 UTC
Labels: status/assigned, update

**Comment by iruyanka** [comment] 2015-08-09 17:57
Thanks. Nice.

" I cannot get that push module to work."

Yes. me too.
I want update push module.

**Comment by iruyanka** [comment] 2016-03-24 13:02
@cytec @Dr-Bean 

I have a queation. DSM 6.0 released. 
ZNC 1.6 requiere C++11 which is not supported by most of the Synology 5.1 Toolchains (except x64 i think)

How about  DSM 6.0 toolchains? Sorry. I don't know about toolchains.

**Comment by cytec** [comment] 2016-03-24 14:32
im not really sure but if i remember correctly __some__ of the DSM 6 toolchains support C++11

**Comment by Argon-** [comment] 2016-09-03 13:10
Looking at existing PRs for DSM 6 toolchains this should widely work once these PRs are applied (DSM 6 toolchains added). Doesn't look like it's going to happen soon though.

**Comment by Zialus** [comment] 2016-11-10 09:46
What are the major roadblocks ATM for migrating to the DSM6 toolchains? I'd really like to update to a newer version of ZNC on my DS213j.

**Comment by cytec** [comment] 2016-11-10 10:20
toolchains aren't the problem... user creation and some other stuff changed with DSM 6 check out https://github.com/SynoCommunity/spksrc/issues/2216 and https://github.com/SynoCommunity/spksrc/pull/2345

**Comment by Zialus** [comment] 2017-11-29 14:52
Can't at least a new package be created for the Armada370 architecture?

I already have a znc user, since I'm using znc 1.4.0, I Just want an updated version of it.
