### ISSUE TITLE
HomeAssistant 0.114.2-7 not able to install

### ISSUE THREAD

**Issue by PA8E** [SynoCommunity/spksrc#4205] opened 2020-10-05 09:24 UTC
### Setup
_Package Name:_ Home Assistant
_Package Version:_ 0.114.2-7

_NAS Model:_ DS212j
_NAS Architecture:_ MARVELL Kirkwood 88F6281
_DSM version:_ DSM 6.2.3-25426 Update 2

### Expected behavior
After installation of Home Assistant the package should start.

### Actual behavior
Package installer tells the Home Assistant package cannot be started. 

### Steps to reproduce
_1._ Install Home Assistant from package installer
_2._ start package

### Package log

``` Mon Oct  5 10:11:19 CEST 2020
===> Step preinst. USER=homeassistant GROUP= SHARE_PATH=
Mon Oct  5 10:11:22 CEST 2020
===> Step postinst. USER=homeassistant GROUP= SHARE_PATH=
Installing service configuration /var/packages/homeassistant/conf/homeassistant.sc
Invoke service_postinst
created virtual environment CPython3.7.7.final.0-32 in 33999ms
  creator CPython3Posix(dest=/volume1/@appstore/homeassistant/env, clear=False, global=True)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/root/.local/share/virtualenv/seed-v1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
Looking in links: /volume1/@appstore/homeassistant/share/wheelhouse
Processing /volume1/@appstore/homeassistant/share/wheelhouse/HAP_python-3.0.0-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/Jinja2-2.11.2-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/MarkupSafe-1.1.1-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/PyISY-1.1.0-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/PyJWT-1.7.1-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/PyYAML-5.3.1-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/aioautomatic-0.6.5-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/aiohttp-3.6.2-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/aiohttp_cors-0.7.0-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/aiohue-2.2.0-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/astral-1.10.1-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/async_timeout-3.0.1-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/attrs-19.3.0-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/boto3-1.14.41-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/certifi-2020.6.20-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/cffi-1.14.1-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/chardet-3.0.4-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/ciso8601-2.1.3-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/colorlog-3.1.4-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/curve25519_donna-1.3-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/distro-1.5.0-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/ecdsa-0.15-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/ed25519-1.5-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/ephem-3.7.7.1-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/gTTS_token-1.1.3-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/gmpy2-2.0.8-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/home_assistant_frontend-20200811.0-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/homeassistant-0.114.2-py3-none-any.whl
ERROR: Could not install packages due to an EnvironmentError: [Errno 28] No space left on device

Granting 'sc-homeassistant' unix ownership on /volume1/@appstore/homeassistant/var
Mon Oct  5 10:45:30 CEST 2020
===> Step preuninst. USER=homeassistant GROUP= SHARE_PATH=
Removing service configuration homeassistant.sc
Mon Oct  5 10:45:40 CEST 2020
===> Step postuninst. USER=homeassistant GROUP= SHARE_PATH=
Removing user sc-homeassistant
Mon Oct  5 10:53:20 CEST 2020
===> Step preinst. USER=homeassistant GROUP= SHARE_PATH=
Mon Oct  5 10:53:23 CEST 2020
===> Step postinst. USER=homeassistant GROUP= SHARE_PATH=
Installing service configuration /var/packages/homeassistant/conf/homeassistant.sc
Invoke service_postinst
created virtual environment CPython3.7.7.final.0-32 in 17516ms
  creator CPython3Posix(dest=/volume1/@appstore/homeassistant/env, clear=False, global=True)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/root/.local/share/virtualenv/seed-v1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
Looking in links: /volume1/@appstore/homeassistant/share/wheelhouse
Processing /volume1/@appstore/homeassistant/share/wheelhouse/HAP_python-3.0.0-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/Jinja2-2.11.2-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/MarkupSafe-1.1.1-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/PyISY-1.1.0-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/PyJWT-1.7.1-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/PyYAML-5.3.1-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/aioautomatic-0.6.5-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/aiohttp-3.6.2-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/aiohttp_cors-0.7.0-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/aiohue-2.2.0-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/astral-1.10.1-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/async_timeout-3.0.1-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/attrs-19.3.0-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/boto3-1.14.41-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/certifi-2020.6.20-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/cffi-1.14.1-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/chardet-3.0.4-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/ciso8601-2.1.3-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/colorlog-3.1.4-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/curve25519_donna-1.3-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/distro-1.5.0-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/ecdsa-0.15-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/ed25519-1.5-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/ephem-3.7.7.1-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/gTTS_token-1.1.3-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/gmpy2-2.0.8-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/home_assistant_frontend-20200811.0-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/homeassistant-0.114.2-py3-none-any.whl
ERROR: Could not install packages due to an EnvironmentError: [Errno 28] No space left on device```

Weird is there is plenty of space left on the NAS (> 500GB):
```df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       2.4G  941M  1.4G  42% /
none            120M  4.0K  120M   1% /dev
/tmp            122M  1.7M  121M   2% /tmp
/run            122M  5.5M  117M   5% /run
/dev/shm        122M  4.0K  122M   1% /dev/shm
/dev/vg1000/lv  1.8T  1.3T  499G  73% /volume1```

**Comment by BenjV** [comment] 2020-10-05 09:49
The issue is "not able to install" instead of "won't start'.
Maybe you have configured the system to use quota?

**Comment by PA8E** [comment] 2020-10-05 09:59
@BenjV thanks for the tip, renamed the issue.
 
I checked the system for using quota, but this function is disabled for all users (including sc-download). I guess there must be some other cause for this error?

**Comment by BenjV** [comment] 2020-10-05 10:49
I have installed homeassistant on my test Nas with only 180Gb of free disk space without any problem.
There must be something strange going on in your Nas.
Maybe check the disk status?

**Comment by PA8E** [comment] 2020-10-05 13:49
Disk status: healthy... 

Should I make a ticket with Synology for this?

**Comment by BenjV** [comment] 2020-10-05 14:59
Useless without any concrete issue.

**Comment by ymartin59** [comment] 2020-10-09 05:23
Trouble comes from not enough free space in /tmp for Python wheels to be extracted when installed by pip. It will be fixed in next version

**Comment by PA8E** [comment] 2020-10-09 08:40
Thanks for your answer Yves. Then I will wait patiently for the next update!

**Comment by PA8E** [comment] 2020-10-14 12:26
Temporary work-around:  sudo mount -o remount, size=5G /tmp/

**Comment by tpola** [comment] 2020-10-23 13:57
@PA8E, that worked for me.
However, with the same setup as yours (DS212J DSM 6.2.3) I had to remove the space char between _remount,_ and _size_ 
`sudo mount -o remount,size=5G /tmp/`

**Closed** 2020-12-05 22:50 UTC
