### ISSUE TITLE
[Package Request] Radarr (CouchPotato and Watcher alternative)

### ISSUE THREAD

**Issue by mrjay000** [SynoCommunity/spksrc#2602] opened 2017-01-16 08:56 UTC
Name: Radarr
Description: This fork of Sonarr aims to turn it into something like CouchPotato.
Website: https://github.com/Radarr/Radarr
Software documentation: https://github.com/Radarr/Radarr/blob/develop/README.md
Build/Installation documentation: see above
Source Code: https://github.com/Radarr/Radarr

Docker images already built.

**Comment by G1zm0** [comment] 2017-01-16 14:53
Duplicate of [2596](https://github.com/SynoCommunity/spksrc/issues/2596)

**Comment by skdenmark** [comment] 2017-01-21 12:57
Looking forward to see Radarr on my DS216Play :)

**Comment by frossmant** [comment] 2017-01-21 12:58
*should* be pretty easy to create since it's just a fork of sonarr.

**Comment by KaraokeStu** [comment] 2017-02-07 17:09
Package has been built and publushed, although there are some issues on DSM 5.x due to the port numbers

**Closed by KaraokeStu** 2017-02-07 17:09 UTC
