### ISSUE TITLE
NZBget Synology "failed to run the package service"

### ISSUE THREAD

**Issue by regblade85** [SynoCommunity/spksrc#2435] opened 2016-08-23 13:03 UTC
Hi,

im not a technical user so here goes.

When i try and install NZBget i get the below msg.
"failed to run the package service"

**Comment by xpunkt** [comment] 2016-08-24 02:37
i have this problem aswell, should there be special setup done before installing ?

currently i created a smp shared drive, named nzb in volume1, the installer i used /volume1/nzb

this allowed me to get it installed, but it failed to start service

**Comment by octan3** [comment] 2016-08-25 15:28
I had the same problem. After the last update (DSM 6.0.2-8451) starts the Services and runs for a minute then stopps (actually it segfaults). See #2407 / its maybe a duplicate of this.

**Comment by KoetseJ** [comment] 2016-09-21 11:50
Figures it out,

nzbget was missing in the /etc/shadow file.

Here is how I fixed it:
ssh [YourAdminAccount]@[Local_IP_Of SYNOLOGY]
sudo su
[Enter your password]
nano /etc/shadow
add the following line to the bottem
nzbget:*:10933:0:99999:7:::
then press ctrl-x and hit y to save the file.

You should now be able to start the package in package manager

**Comment by xpunkt** [comment] 2016-09-21 15:24
maybe it fixes it, but that way of change content in shadow is not supported in any os

**Comment by KoetseJ** [comment] 2016-09-21 15:35
Well actually, It's described as the fix in a issue for a other package on SynoCommunity.

Also It seems that the shadow file is fine even after reboots. As far as I noticed it seems that all SynoCommunity packages are for some reason not properly adding new users. I think this has more to do with the way that all those SynoCommunity packages add those invisible users that are not displayed in the GUI and are all not added to the shadow file.

**Comment by thunfischbrot** [comment] 2016-11-11 12:07
Might be related to https://github.com/SynoCommunity/spksrc/issues/2216

**Comment by flipswitchingmonkey** [comment] 2016-12-29 13:22
Since I ran into that same issue... rather than manually fiddling with the shadow file, which is a bit dangerous potentially, to say the least, why not just create a user nzbget and have all the downloads etc being dealt with within that user's home folder?

**Comment by Safihre** [comment] 2018-02-19 07:53
Test package for new-style NZBGet has been released: #3138.
We no longer compile it here on the repo, but fetch the latest official installer from NZBGet.
During package installation you can choose if you want the latest stable or testing release. After this you can use NZBGet's internal update system to do updates.
We hope to soon publish this on the official repo.

**Closed by Safihre** 2018-02-19 07:53 UTC
