### ISSUE TITLE
Horde fails to run after installation

### ISSUE THREAD

**Issue by Freekers** [SynoCommunity/spksrc#2487] opened 2016-10-12 11:13 UTC
### Setup

_Package Name: Horde
_Package Version: 5.1.0-2 (Groupware Webmail)

_NAS Model: RS814
_NAS Architecture: armadaxp
_DSM version: DSM 6.0.2-8451 Update 2
### Expected behavior

Horde should show up after the installation of the package
PHP Pear and PHP 5.6 are both installed and all PHP modules are enabled. MariaDB is installed as well and user homes are enabled.
### Actual behavior

When browsing to http://ip/horde, the following error is shown (when display_errors in PHP is turned on):

`Warning: require_once(Horde/Autoloader/Default.php): failed to open stream: No such file or directory in /volume1/web/horde/lib/core.php on line 49 Fatal error: require_once(): Failed opening required 'Horde/Autoloader/Default.php' (include_path='/volume1/web/horde/lib:.:/var/packages/PEAR/target') in /volume1/web/horde/lib/core.php on line 49`
### Steps to reproduce

_1._ First, fix the 'incorrect MySQL password' error using the following commands via SSH:

```
sudo mkdir /usr/syno/mysql
sudo mkdir /usr/syno/mysql/bin 
sudo ln -s /usr/bin/mysql /usr/syno/mysql/bin/mysql
```

_2._ Next, install Horde via DSM
_3._ Browse to http://IP/horde
#### Package log

_Check Package Center or `/usr/local/{package}/var/`_

```
Package log is empty
```
#### Other logs

_E.g. `/var/log/messages` or `/var/log/synopkg.log`_

```
2016/10/11 22:00:50 (system) trigger     :
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F20 INFO --no-same-owner
2016/10/11 22:00:50 (system) trigger     :
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F20 INFO --no-same-owner  ret=[0]
2016/10/11 22:00:50 (system) trigger     :
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F20 conf --no-same-owner
2016/10/11 22:00:50 (system) trigger     :
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F20 conf --no-same-owner  ret=[0]
2016/10/11 22:00:50 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F20 scripts/start-stop-status --no-same-owner --no-same-permissions
2016/10/11 22:00:50 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F20 scripts/start-stop-status --no-same-owner --no-same-permissions   ret=[0]
2016/10/11 22:00:50 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F20 scripts/preinst --no-same-owner --no-same-permissions
2016/10/11 22:00:50 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F20 scripts/preinst --no-same-owner --no-same-permissions ret=[0]
2016/10/11 22:00:50 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F20 scripts/postinst --no-same-owner --no-same-permissions
2016/10/11 22:00:50 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F20 scripts/postinst --no-same-owner --no-same-permissions    ret=[0]
2016/10/11 22:00:50 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F20 scripts/preuninst --no-same-owner --no-same-permissions
2016/10/11 22:00:50 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F20 scripts/preuninst --no-same-owner --no-same-permissions   ret=[0]
2016/10/11 22:00:50 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F20 scripts/postuninst --no-same-owner --no-same-permissions
2016/10/11 22:00:50 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F20 scripts/postuninst --no-same-owner --no-same-permissions  ret=[0]
2016/10/11 22:00:50 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F20 scripts/preupgrade --no-same-owner --no-same-permissions
2016/10/11 22:00:50 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F20 scripts/preupgrade --no-same-owner --no-same-permissions  ret=[0]
2016/10/11 22:00:50 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F20 scripts/postupgrade --no-same-owner --no-same-permissions
2016/10/11 22:00:50 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F20 scripts/postupgrade --no-same-owner --no-same-permissions ret=[0]
2016/10/11 22:00:50 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/rm -rf /volume1/@tmp/57FD44F20
2016/10/11 22:00:50 (system) trigger    horde 5.1.0-2:
            End:    /bin/rm -rf /volume1/@tmp/57FD44F20 ret=[0]
2016/10/11 22:00:51 (system) trigger     :
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F30 INFO --no-same-owner
2016/10/11 22:00:51 (system) trigger     :
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F30 INFO --no-same-owner  ret=[0]
2016/10/11 22:00:51 (system) trigger     :
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F30 conf --no-same-owner
2016/10/11 22:00:51 (system) trigger     :
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F30 conf --no-same-owner  ret=[0]
2016/10/11 22:00:51 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F30 scripts/start-stop-status --no-same-owner --no-same-permissions
2016/10/11 22:00:51 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F30 scripts/start-stop-status --no-same-owner --no-same-permissions   ret=[0]
2016/10/11 22:00:51 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F30 scripts/preinst --no-same-owner --no-same-permissions
2016/10/11 22:00:51 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F30 scripts/preinst --no-same-owner --no-same-permissions ret=[0]
2016/10/11 22:00:51 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F30 scripts/postinst --no-same-owner --no-same-permissions
2016/10/11 22:00:51 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F30 scripts/postinst --no-same-owner --no-same-permissions    ret=[0]
2016/10/11 22:00:51 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F30 scripts/preuninst --no-same-owner --no-same-permissions
2016/10/11 22:00:51 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F30 scripts/preuninst --no-same-owner --no-same-permissions   ret=[0]
2016/10/11 22:00:51 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F30 scripts/postuninst --no-same-owner --no-same-permissions
2016/10/11 22:00:51 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F30 scripts/postuninst --no-same-owner --no-same-permissions  ret=[0]
2016/10/11 22:00:51 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F30 scripts/preupgrade --no-same-owner --no-same-permissions
2016/10/11 22:00:51 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F30 scripts/preupgrade --no-same-owner --no-same-permissions  ret=[0]
2016/10/11 22:00:51 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F30 scripts/postupgrade --no-same-owner --no-same-permissions
2016/10/11 22:00:51 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44F30 scripts/postupgrade --no-same-owner --no-same-permissions ret=[0]
2016/10/11 22:00:51 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/rm -rf /volume1/@tmp/57FD44F30
2016/10/11 22:00:51 (system) trigger    horde 5.1.0-2:
            End:    /bin/rm -rf /volume1/@tmp/57FD44F30 ret=[0]
2016/10/11 22:01:00 (system) trigger     :
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 INFO --no-same-owner
2016/10/11 22:01:00 (system) trigger     :
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 INFO --no-same-owner  ret=[0]
2016/10/11 22:01:00 (system) trigger     :
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 conf --no-same-owner
2016/10/11 22:01:00 (system) trigger     :
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 conf --no-same-owner  ret=[0]
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/start-stop-status --no-same-owner --no-same-permissions
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/start-stop-status --no-same-owner --no-same-permissions   ret=[0]
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/preinst --no-same-owner --no-same-permissions
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/preinst --no-same-owner --no-same-permissions ret=[0]
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/postinst --no-same-owner --no-same-permissions
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/postinst --no-same-owner --no-same-permissions    ret=[0]
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/preuninst --no-same-owner --no-same-permissions
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/preuninst --no-same-owner --no-same-permissions   ret=[0]
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/postuninst --no-same-owner --no-same-permissions
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/postuninst --no-same-owner --no-same-permissions  ret=[0]
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/preupgrade --no-same-owner --no-same-permissions
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/preupgrade --no-same-owner --no-same-permissions  ret=[0]
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/postupgrade --no-same-owner --no-same-permissions
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/postupgrade --no-same-owner --no-same-permissions ret=[0]
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/rm -rf /volume1/@tmp/57FD44FC0
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            End:    /bin/rm -rf /volume1/@tmp/57FD44FC0 ret=[0]
2016/10/11 22:01:00 (system) trigger     :
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 INFO --no-same-owner
2016/10/11 22:01:00 (system) trigger     :
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 INFO --no-same-owner  ret=[0]
2016/10/11 22:01:00 (system) trigger     :
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 conf --no-same-owner
2016/10/11 22:01:00 (system) trigger     :
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 conf --no-same-owner  ret=[0]
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/start-stop-status --no-same-owner --no-same-permissions
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/start-stop-status --no-same-owner --no-same-permissions   ret=[0]
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/preinst --no-same-owner --no-same-permissions
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/preinst --no-same-owner --no-same-permissions ret=[0]
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/postinst --no-same-owner --no-same-permissions
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/postinst --no-same-owner --no-same-permissions    ret=[0]
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/preuninst --no-same-owner --no-same-permissions
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/preuninst --no-same-owner --no-same-permissions   ret=[0]
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/postuninst --no-same-owner --no-same-permissions
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/postuninst --no-same-owner --no-same-permissions  ret=[0]
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/preupgrade --no-same-owner --no-same-permissions
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/preupgrade --no-same-owner --no-same-permissions  ret=[0]
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/postupgrade --no-same-owner --no-same-permissions
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/57FD44FC0 scripts/postupgrade --no-same-owner --no-same-permissions ret=[0]
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            Begin:  /bin/rm -rf /volume1/@tmp/57FD44FC0
2016/10/11 22:01:00 (system) trigger    horde 5.1.0-2:
            End:    /bin/rm -rf /volume1/@tmp/57FD44FC0 ret=[0]
2016/10/11 22:01:00 install  :
            Begin:  /bin/rm -rf /volume1/@tmp/pkginstall
2016/10/11 22:01:01 install  :
            End:    /bin/rm -rf /volume1/@tmp/pkginstall    ret=[0]
2016/10/11 22:01:01 install  :
            Begin:  /bin/mkdir -p /volume1/@tmp/pkginstall/package
2016/10/11 22:01:01 install  :
            End:    /bin/mkdir -p /volume1/@tmp/pkginstall/package  ret=[0]
2016/10/11 22:01:01 install  :
            Begin:  /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/pkginstall --no-same-owner
2016/10/11 22:01:01 install  :
            End:    /bin/tar xf /volume1/@tmp/@synopkg/@download/horde/@SYNOPKG_DOWNLOAD_horde -C /volume1/@tmp/pkginstall --no-same-owner  ret=[0]
2016/10/11 22:01:01 install horde 5.1.0-2:
            Begin:  /bin/tar xf /volume1/@tmp/pkginstall/package.tgz -C /volume1/@tmp/pkginstall/package --no-same-owner
2016/10/11 22:01:01 install horde 5.1.0-2:
            End:    /bin/tar xf /volume1/@tmp/pkginstall/package.tgz -C /volume1/@tmp/pkginstall/package --no-same-owner    ret=[0]
2016/10/11 22:01:01 install horde 5.1.0-2:
            Begin:  preinst
2016/10/11 22:01:01 install horde 5.1.0-2:
            End:    preinst ret=[0]
2016/10/11 22:01:01 install horde 5.1.0-2:
            Begin:  /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/horde
2016/10/11 22:01:01 install horde 5.1.0-2:
            End:    /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/horde    ret=[0]
2016/10/11 22:01:01 install horde 5.1.0-2:
            Begin:  /bin/rm -rf /var/packages/horde
2016/10/11 22:01:01 install horde 5.1.0-2:
            End:    /bin/rm -rf /var/packages/horde ret=[0]
2016/10/11 22:01:01 install horde 5.1.0-2:
            Begin:  /bin/mkdir -p /var/packages/horde
2016/10/11 22:01:01 install horde 5.1.0-2:
            End:    /bin/mkdir -p /var/packages/horde   ret=[0]
2016/10/11 22:01:01 install horde 5.1.0-2:
            Begin:  /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/horde/INFO
2016/10/11 22:01:01 install horde 5.1.0-2:
            End:    /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/horde/INFO   ret=[0]
2016/10/11 22:01:01 install horde 5.1.0-2:
            Begin:  /bin/rm -rf /var/packages/horde/scripts
2016/10/11 22:01:01 install horde 5.1.0-2:
            End:    /bin/rm -rf /var/packages/horde/scripts ret=[0]
2016/10/11 22:01:01 install horde 5.1.0-2:
            Begin:  /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/horde/scripts
2016/10/11 22:01:01 install horde 5.1.0-2:
            End:    /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/horde/scripts ret=[0]
2016/10/11 22:01:01 install horde 5.1.0-2:
            Begin:  /bin/rm -rf /var/packages/horde/WIZARD_UIFILES
2016/10/11 22:01:01 install horde 5.1.0-2:
            End:    /bin/rm -rf /var/packages/horde/WIZARD_UIFILES  ret=[0]
2016/10/11 22:01:01 install horde 5.1.0-2:
            Begin:  /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/horde/WIZARD_UIFILES
2016/10/11 22:01:01 install horde 5.1.0-2:
            End:    /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/horde/WIZARD_UIFILES   ret=[0]
2016/10/11 22:01:01 install horde 5.1.0-2:
            Begin:  /bin/rm -rf /var/packages/horde/conf
2016/10/11 22:01:01 install horde 5.1.0-2:
            End:    /bin/rm -rf /var/packages/horde/conf    ret=[0]
2016/10/11 22:01:01 install horde 5.1.0-2:
            Begin:  /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/horde/conf
2016/10/11 22:01:01 install horde 5.1.0-2:
            End:    /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/horde/conf   ret=[0]
2016/10/11 22:01:01 install horde 5.1.0-2:
            Begin:  postinst
/var/packages/horde/scripts/installer: line 60: /etc/php/conf.d/com.synocommunity.packages.horde.ini: No such file or directory
2016/10/11 22:01:14 install horde 5.1.0-2:
            End:    postinst    ret=[0]
2016/10/11 22:01:14 install horde 5.1.0-2:
            Begin:  /bin/rm -rf /volume1/@tmp/pkginstall
/var/packages/horde/scripts/installer: line 106: INSTALL_DIR: command not found
2016/10/11 22:01:14 install horde 5.1.0-2:
            End:    /bin/rm -rf /volume1/@tmp/pkginstall    ret=[0]
2016/10/11 22:01:14 install horde 5.1.0-2 successfully
2016/10/11 22:01:22 install horde: begin to start version 5.1.0-2
2016/10/11 22:01:23 install horde: start version 5.1.0-2 successfully, result 0
/var/packages/horde/scripts/installer: line 122: INSTALL_DIR: command not found
/var/packages/horde/scripts/installer: line 123: INSTALL_DIR: command not found
```

**Comment by janbro1** [comment] 2016-11-29 07:39
I can confirm this behviour, with the workaround stated above I was at least able to install Horde, but it won't fire up. 
DSM 6.0.2-8451 Update 4
Model DS412+
and here are my logs:
vi /var/log/messages
2016-11-28T23:20:53+01:00 nas412 synoscgi_SYNO.Core.Package.Log_1_get[15067]: pkgtool.cpp:2622 Failed to query package status, horde
<hr>
vi /var/log/synopkg.log
2016/11/28 23:19:28 install horde 5.1.0-2:
            End:    /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/horde/conf   ret=[0]
2016/11/28 23:19:28 install horde 5.1.0-2:
            Begin:  postinst
/var/packages/horde/scripts/installer: line 60: /etc/php/conf.d/com.synocommunity.packages.horde.ini: No such file or directory
2016/11/28 23:19:43 install horde 5.1.0-2:
            End:    postinst    ret=[0]
2016/11/28 23:19:43 install horde 5.1.0-2:
            Begin:  /bin/rm -rf /volume1/@tmp/pkginstall
2016/11/28 23:19:43 install horde 5.1.0-2:
            End:    /bin/rm -rf /volume1/@tmp/pkginstall    ret=[0]
2016/11/28 23:19:43 install horde 5.1.0-2 successfully
/var/packages/horde/scripts/installer: line 106: INSTALL_DIR: command not found
2016/11/28 23:19:56 install horde: begin to start version 5.1.0-2
2016/11/28 23:19:56 install horde: start version 5.1.0-2 successfully, result 0
2016/11/28 23:20:39 start horde: begin to start version 5.1.0-2
2016/11/28 23:20:41 start horde: start version 5.1.0-2 successfully, result 0

**Comment by Dr-Bean** [comment] 2016-12-10 17:40
Duplicate of https://github.com/SynoCommunity/spksrc/issues/2333

**Closed by Dr-Bean** 2016-12-10 17:40 UTC
Labels: dsm 6.0
