### ISSUE TITLE
Synology DSM 7 Beta | Lower Permissions

### ISSUE THREAD

**Issue by Kaelber** [SynoCommunity/spksrc#4298] opened 2020-12-09 14:27 UTC
I tested the VMM DSM 7 Preview and since yesterday the DSM 7 Beta is available. I have installed the new Beta and all packages I try to install is with the same message:

I updated my VMM from DSM 7 from Preview to Beta with the same result as expected

![grafik](https://user-images.githubusercontent.com/12963736/101641981-bb4b9280-3a32-11eb-810f-caee70b42553.png)

or similar. My question is about your planning of activities about that.

**Comment by BenjV** [comment] 2020-12-09 14:53
e https://github.com/SynoCommunity/spksrc/issues/4215

**Comment by hgy59** [comment] 2020-12-09 15:21
@publicarray   has created the dsm7 branch in this repo. You can try to build packages using this branch

**Comment by hgy59** [comment] 2020-12-12 12:24
duplicate of #4215

**Closed by hgy59** 2020-12-12 12:24 UTC
Labels: dsm 7.0
