### ISSUE TITLE
Libwebsocket does not compile for armadaxp 5.2

### ISSUE THREAD

**Issue by tedstriker** [SynoCommunity/spksrc#2114] opened 2016-01-30 10:56 UTC
to resemble the error just go to `spksrc/cross/libwebsockets` and `make arch-armadaxp-5.2`

it exits with the following error

---------------------------------------------------------------------
-- Configuring incomplete, errors occurred!
See also "/home/xyz/spksrc/cross/libwebsockets/work-armadaxp-5.2/libwebsockets-1.4-chrome43-firefox-36/CMakeFiles/CMakeOutput.log".
See also "[/home/xyz/spksrc/cross/libwebsockets/work-armadaxp-5.2/libwebsockets-1.4-chrome43-firefox-36/CMakeFiles/CMakeError.log](https://gist.github.com/tedstriker/e8578e7ad7b5946e3895)".
Makefile:21: recipe for target 'myConfigure' failed
make[1]: *** [myConfigure] Error 1
make[1]: Leaving directory '/home/xyz/spksrc/cross/libwebsockets'
../../mk/spksrc.cross-cc.mk:122: recipe for target 'arch-armadaxp-5.2' failed
make: [arch-armadaxp-5.2] Error 2 (ignored)

**Comment by Dr-Bean** [comment] 2016-03-03 10:21
You're not showing the important part of the error here ;) 
Regardless, I can't reproduce this. That could be because I'm running this on a Docker container based off of https://github.com/SynoCommunity/spksrc/pull/2146, but it could just as well be something else.
For starters, clean up your build dir (`make clean`) and try again.

**Comment by Dr-Bean** [comment] 2016-03-18 07:51
@tedstriker I'm going to close this. Feel free to respond if the issue still exists. Please note that you should consider migrating to a 64bit build environment (see README)

**Closed by Dr-Bean** 2016-03-18 07:51 UTC

**Comment by tedstriker** [comment] 2016-03-30 15:32
I'll give it a shot when DSM 6 dev environment is available
