### ISSUE TITLE
OwnCloud Package issues (uninstall, migration fails)

### ISSUE THREAD

**Issue by bzels123** [SynoCommunity/spksrc#2564] opened 2016-12-19 02:55 UTC
_For new Package Requests, see the guidelines_  

### Setup
_Package Name: owncloud
_Package Version: v6.x

_NAS Model:DS1812+
_NAS Architecture: Maria DB
_DSM version: v6.x

### Expected behavior
Tell us what should happen
- I upgade DMS v5 to DSM v6
- I hade to migrate from package Owncloud v6 to v8, not knowing it was not supported

### Actual behavior
Tell us what happens instead
- So after I tried to migrate, owncloud doesn't respond anymore
- So I backed up the DB and tried to uninstall owncloud package but it get stucked with message : "Failed to uninstall the package. Incorrect MySQL root password."
- but my root password works just fine when I try to connect to it through phpMyAdmin
so What should I do next?

Thank you

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by Dr-Bean** [comment] 2016-12-21 09:29
Duplicate of https://github.com/SynoCommunity/spksrc/issues/2136, so I'm closing this one.

**Closed by Dr-Bean** 2016-12-21 09:29 UTC
Labels: dsm 6.0
