### ISSUE TITLE
[Request] Add ZNC Playback Module

### ISSUE THREAD

**Issue by Pretz** [SynoCommunity/spksrc#1457] opened 2015-01-29 04:07 UTC
https://github.com/jpnurmi/znc-playback (http://wiki.znc.in/Playback)

This allows more sophisticated buffer playback for clients such as Textual and Mobile Colloquy

Alternatively, I would be happy to build it myself if `znc-buildmod` were included so modules could be manually added.

Thanks for the ZNC package!

**Comment by Dr-Bean** [comment] 2015-01-30 11:27
I don't think that we can include znc-buildmod in the package...but adding the module is possible.

**Comment by Dr-Bean** [comment] 2015-01-30 20:16
Right...while I say we can add the module, there's a snag. According to the [Playback wiki page](http://wiki.znc.in/Playback): 
```
This external module is a work in progress.
Please note that it requires the latest development version of ZNC.
```
We're using the latest stable of ZNC (1.4), and we'd need 1.6.0-beta1 for this. Tested with 1.4 before I noticed: no go.
I'd prefer to wait until a new stable version of ZNC is released. @Diaoul, your opinion?

**Comment by Diaoul** [comment] 2015-02-01 15:50
We'll wait for a new stable release of ZNC.

**Comment by Dr-Bean** [comment] 2015-02-01 22:41
Adding an upstream tag to this then. @Pretz, maybe you can keep an eye out for an updated version of ZNC too? Then we're less likely to miss it ;)

**Comment by Pretz** [comment] 2015-02-02 01:11
@Dr-Bean absolutely, thanks for the positive response! I completely understand waiting for upstream, I didn't realize that `znc-playback` depended on dev znc when I made the request.

**Comment by dgw** [comment] 2015-02-28 13:14
ZNC 1.6.0 is released as stable since mid-February.

**Comment by iruyanka** [comment] 2015-03-14 01:22
Dr-Bean
Please test add Push module.

https://github.com/SynoCommunity/spksrc/issues/1521

http://wiki.znc.in/Push

Official project page: https://github.com/jreese/znc-push

ZNC Push is a module for ZNC that will send notifications to multiple push notification services, or SMS for any private message or channel highlight that matches a configurable set of conditions. ZNC Push supports multiple push services, including Boxcar, Pushover, and PushBullet.

You can get this module's source code and documentation at the github project page. You should also read compiling modules.

**Comment by Dr-Bean** [comment] 2015-03-15 12:29
Added the module with 831a7b18fc0f15370d6ebeb4527a18edfd20594c. 
The packages will be released on the beta channel *Note: packages not available yet, I'll report here when they are*

**Comment by Dr-Bean** [comment] 2015-03-16 12:04
Well, that's just great :/ ZNC 1.6 was rewritten to use C++11. From what I'm seeing, currently only four of our toolchains support that: x86_64, DSM5.1.
Maybe the 5.2 toolchains will help, haven't tested.

**Comment by Diaoul** [comment] 2015-03-16 13:47
I believe there is a flag to enable C++11 support in GCC but that seems to be limited to recent GCC only...

**Comment by Dr-Bean** [comment] 2015-03-16 13:59
GCC4.7+ apparently. Most of our toolchains, except the x86_64 ones, are based on GCC 4.6.4. 
Same for DSM5.2 beta toolchains, so using those won't help either.

**Comment by Diaoul** [comment] 2015-03-16 15:12
I sent an email to Synology, but I doubt that'll be ready for 5.2.

**Comment by Diaoul** [comment] 2015-03-16 15:14
C++11 is quite new, I don't know the reason ZNC had to make the switch but if possible we should ask upstream to revert this change.

**Comment by cytec** [comment] 2015-03-16 15:21
Well i think that depends on the point of view... C++11 is from 2011 so that are ~4 years which is a not so new in my opinion and especially in `internet time`

**Comment by Diaoul** [comment] 2015-03-16 15:24
Debian stable still uses 4.6: https://packages.debian.org/wheezy/gcc

**Comment by Dr-Bean** [comment] 2015-03-16 15:42
With 1.6, ZNC has made quite some changes to their code based on the new standard (I was briefly considering patching things back myself until I saw that. Nope...), so I don't think that's a viable option. 

Besides, seems to me the issue isn't the standard itself, but the fact we're stuck on such old GCC versions. 4.8/4.9 are current, right?

What about PR #664? Might be an alternative way of looking at it, although it might need some work...

**Comment by Dr-Bean** [comment] 2015-08-07 07:45
ZNC 1.6 for x86-64 arches has been published as a beta package. ZNC 1.4 is still available on stable for that arch and others that cannot be updated due to GCC being too old. 

_If_ Synology updates the toolchains to GCC4.7 with the next update, we can revisit this for the other arches.

**Closed by Dr-Bean** 2015-08-07 07:45 UTC
Labels: enhancement, upstream
