### ISSUE TITLE
https://packages.synocommunity.com/ is down?

### ISSUE THREAD

**Issue by spacezed** [SynoCommunity/spksrc#1768] opened 2015-06-20 20:18 UTC
Hi!, https://packages.synocommunity.com/ is down??, can't get access. any mirror? :'(

**Comment by Diaoul** [comment] 2015-06-20 20:49
Yes it is, I'll try to look into it. We ran out of disk space.

**Comment by spacezed** [comment] 2015-06-20 22:20
I look forward, thank you ;)

**Comment by jhenline** [comment] 2015-06-21 01:48
Looks like it is back up, thanks.

**Comment by Dr-Bean** [comment] 2015-06-21 09:00
@Diaoul Maybe we should remove older package versions when uploading new packages? Maybe keep one or two prev versions around, or something like that.

**Comment by dennisahlin** [comment] 2015-06-21 10:03
It's down again?

**Comment by sjaveed** [comment] 2015-06-26 10:49
Looks like it's down again unless it's just me.  Could someone else verify this?

**Comment by M0UL** [comment] 2015-06-26 13:06
down for me too

**Comment by mb243** [comment] 2015-06-30 18:09
Down for me too. 400 - Bad Request

**Comment by Gwengarion** [comment] 2015-07-03 07:55
I cannot install any package from the synocomm, I click the button and it does nothing. Also, I cannot see all the packages in the site (Git for instance). Does anyone know what the issue is and how to solve it? Thanks!

**Comment by chniko** [comment] 2015-07-03 23:08
@Gwengarion : what kind of Synology you have ?
If it's DS215+ for example (like me) I have the same behaviour.
It's due to the fact that this is a new architecture using a new CPU : `alpine4k`
Have a look at the issue #1756 
If you don't have this model, then it's probably something else.

**Comment by Dr-Bean** [comment] 2015-07-04 04:51
@mb243 You're probably opening `packages.synocommunity.com` in your browser. Don't do that, that URI is only for your NAS. Use https://synocommunity.com in your browser.

Other than that, the server has been up since Diaoul has looked into it afaik, so I think we'll close this issue.

**Closed by Dr-Bean** 2015-07-04 04:51 UTC
