### ISSUE TITLE
403 forbidden error after reinstallion of package in gui

### ISSUE THREAD

**Issue by Banesh009** [SynoCommunity/spksrc#4843] opened 2021-09-06 09:30 UTC
### Setup
_Package Name:_ TVHeadend
_Package Version:_ 4.3.20210612

_NAS Model:_ DS720+
_NAS Architecture:_ geminilake (x64)
_DSM version:_7.0

### Expected behavior
Access to the admin GUI with admin password

### Actual behavior
Server throws error message "403 forbidden" after entering admin credentials

### Steps to reproduce
_1._ install tvheadend package
_2._ deinstall package with complete deletion of all package data
_3._ reinstall package

**Comment by th0ma7** [comment] 2021-09-08 11:26
this is a duplicate of #4758

**Closed by th0ma7** 2021-09-08 11:26 UTC
