### ISSUE TITLE
NAS GPL source for x86 toolchain missing

### ISSUE THREAD

**Issue by Decipher** [SynoCommunity/spksrc#1499] opened 2015-02-18 22:14 UTC
When compiling Domoticz w/OpenZWave + cp210x for the x86 toolchain it fails to download the NAS GPL source files as the file it is looking for doesn't exist.

```
get http://downloads.sourceforge.net/project/dsgpl/Synology%20NAS%20GPL%20Source/5004branch/synogpl-5004-x86.tbz
http://downloads.sourceforge.net/project/dsgpl/Synology%20NAS%20GPL%20Source/5004branch/synogpl-5004-x86.tbz:
2015-02-17 14:34:15 ERROR 404: Not Found.
```

**Comment by Dr-Bean** [comment] 2015-02-18 22:46
Probably because of using `?=` when setting the `ARCH` in the kernel Makefile: that value is used to build the URL too. I downloaded the kernels upfront (using `make kernel-modules`), so I didn't notice.

Until fixed, either use the command above, or, to just get the x86-5.1 kernels, use `cd spksrc/kernel/syno-x86-5.1 && make`. Then you can build your package after that's done.

**Comment by Decipher** [comment] 2015-02-18 22:49
Thanks for the prompt response, will give it a spin ASAP.

**Comment by Decipher** [comment] 2015-02-19 01:23
That seems to have done the job. Won't close the issue for the moment as as you say this is a workaround. Will try to look at resolving the issue correctly when I get a chance if I am capable.

**Comment by Dr-Bean** [comment] 2015-02-19 10:42
Nothing to it ;) Compare https://github.com/SynoCommunity/spksrc/blob/develop/kernel/syno-88f6281-4.3/Makefile#L5 with https://github.com/SynoCommunity/spksrc/blob/develop/kernel/syno-x86-5.1/Makefile#L5.

**Comment by Decipher** [comment] 2015-02-19 22:38
Also needs ```KERNEL_DIR``` in ```mk/spksrc.directories.mk``` updated to use ```PKG_ARCH```.

Testing build of x86 Domoticz SPK, after it's confirmed will do a PR.

**Comment by Dr-Bean** [comment] 2015-02-19 22:43
Well, then we'd probably be better off simply changing `ARCH ?= x64` to `ARCH ?= x86` in the kernel Makefile instead...

**Comment by Decipher** [comment] 2015-02-19 22:55
Yeah, change to KERNEL_DIR didn't work, so I think the required change is much like you say:

```ARCH ?= x86```
```PKG_ARCH = x64```

That way the x64 package will be setup in the correct KERNEL_DIR. It's somewhat inefficient though as it results in potentially the same linux source in multiple directories. Thoughts?

**Comment by Dr-Bean** [comment] 2015-02-19 23:36
Not an issue that it's the potentially the same source; the whole set of x86-64 kernels are potentially identical, because the arch is identical. It's the 'potentially' part that's the problem though ;)

Synology confirmed it's best to use this approach, and, afaik, they do the same thing in their tooling. Along with that, even if the kernels are (mostly) identical now, that's no guarantee for the future. So, let's stick with it :)

**Comment by Dr-Bean** [comment] 2015-03-13 18:02
Merged the PR, thanks for the fix

**Closed by Dr-Bean** 2015-03-13 18:02 UTC
