### ISSUE TITLE
[TVheadend] Permissions fault on playing and recording

### ISSUE THREAD

**Issue by kekukui** [SynoCommunity/spksrc#3621] opened 2019-02-11 01:32 UTC
#### **Platform**
TVH 4.2.8.-15
DS111 / DSM 6.2.1-23824 Update 4

#### **Issue description**

1.  I cannot record anything from the tuner through the TVH web U.I.  (The default connection limits were not changed.)

2.  I can start recordings through Kodi, but the Kodi PVR client claims that recording cannot be stopped due to a permissions error.  (However, the recordings did stop according to the TVH web U.I.)

3.  When I logout from the TVH web interface, I cannot log back in without closing the tab and opening a new one

4.  If I try to play a recording in the web interface, it opens Windows Media Player and prompts for a network password.  When I enter the admin credentials, they are rejected.
______
#### **Package logs**

```
===> Step preuninst. USER=tvheadend GROUP=sc-media SHARE_PATH=
Removing service configuration tvheadend.sc
Fri Feb  1 06:46:57 EST 2019
===> Step postuninst. USER=tvheadend GROUP=sc-media SHARE_PATH=
Removing user sc-tvheadend
Sat Feb  9 03:27:31 EST 2019
===> Step preinst. USER=tvheadend GROUP=sc-media SHARE_PATH=
Sat Feb  9 03:27:34 EST 2019
===> Step postinst. USER=tvheadend GROUP=sc-media SHARE_PATH=
Installing service configuration /var/packages/tvheadend/conf/tvheadend.sc
Adding 'sc-tvheadend' to 'sc-media'
Group Name: [sc-media]
Group Type: [AUTH_LOCAL]
Group ID:   [65536]
Group Members:
0:[sc-tvheadend]
Invoke service_postinst
Fixing fontconfig links
```
> Starting tvheadend command /volume1/@appstore/tvheadend/bin/tvheadend -f -u sc-tvheadend -g tvheadend --http_port 9981 --htsp_port 9982 -c /volume1/@appstore/tvheadend/var -p /volume1/@appstore/tvheadend/var/tvheadend.pid

**Comment by m4tt075** [comment] 2019-02-11 06:58
First of all, please let me know which version you were running, before you've upgraded. As to your questions:

1. As you can record through Kodi but not through the Web UI, I assume you are connecting with different users / user credentials. Please go into the TVH Web UI, ensure "View Level" is set to "Expert"  in the upper right area of the screen. Then go to "Configuration" -> "Users" -> "Access entries". Check whether the "Video Recorder Flags" are set correctly. 
2. This might(!) be related to 1. If not, it is likely not a problem with the backend, but with the frontend. In that case, please report with https://github.com/kodi-pvr/pvr.hts or at the Kodi forum.
3. Yes, same for me. This has to do with browser caching. The implementation in Tvheadend is not ideal. I've never found it to be big issue though. If you want to do something about it, please create a ticket at tvheadend.org.
4. As in 1.. Just check the "Streaming Flags" this time.

**Comment by kekukui** [comment] 2019-02-11 20:34
- The installed version was the last one before the current release.
- Kodi PVR client was using the admin credentials which I specified upon installation of TVheadend.
- You are correct that "**Access Entries**" was the problem:
It appears the TVH admin account by default has only "**Basic**" and "**HTSP**" enabled.  Is this by design, or is it a bug?
- I proceeded to enable "**View All**", "**Manage all**" and "**Failed view**", but the issue persisted until I restarted the TVH service on Syno.  Now any PVR activity in the web UI is immediately reflected in Kodi's PVR client (and the reverse), and everything works great.  Thanks very much!

**Comment by m4tt075** [comment] 2019-02-11 20:49
@kekukui: Glad it is working. Thanks for reporting back. But your question is a good one, really. It is by design of our Synology package, but I've never questioned whether it is a good choice: The default Synology configuration has limited priviledges, because the assumption was that people who want to extent permissions and rights, should do that in the user configuration explicitly. That is the "safe way". On the other hand, the default login credentials are "admin" / "admin, which suggest that you get "maximum" permissions, which - in fact - you won't get. This is indeed inconsistent, but difficult to reconcile.
@ymartin59, @BenjV: There probably is no right or wrong here, but any thoughts on this?

**Comment by BenjV** [comment] 2019-02-12 08:53
I am not very familiar with the tvheadend package but the fact that the default inlog account is admin in an application means that with that login account the complete functionality of the application can be managed and has nothing to do with the Linux admin functionality.
That is something different then managing the outside world mening in this case Linux.

As you know, as of DSM 6 a hidden user will be used to run the package and those users cannot be configured with extra permissions from the DSM gui and they are alson no longer member of the group users.
I strongly advice everybody no to mesh with the privileges of that hidden user, because if you do so the whole application gets admin rights and that is a big security risc.
Also the possibility exists that Synology will tighten the security in future DSM release which could then impact functionality.

So if access to folders or files are needed for the application, the SynoCommunity has created a group for every package to gain those privileges and in the case of tvheadend that group is sc-media.
That group can be managed by means of the DSM gui  to give read/write access to the location where the user wants to place the recorded video's

I am not sure wat @kekukui means by enable "View All", "Manage All" and "Failed View" but I guess that is has to do with setting within the tvheadend application.
If that solved his problem, it has nothing to with the package en/or the privileges of the Linux user.

**Comment by m4tt075** [comment] 2019-02-12 19:21
@BenjV Thanks. Makes perfect sense. And very helpful. Yes, it is not about Linux premissions, "just" about server permissions really. But as the login credentials are only requested on an initial installation, it actually does make sense to start with a rigid "admin" account. As such, we probably should not even ask users to specify a username (with "admin" as default), but just hardcode it to "admin", just ask for a password and extend the server user premissions to "maximum" as one would expect for an admin user. OK, a new entry on my ToDo list...

**Comment by m4tt075** [comment] 2019-02-23 21:20
OK. The remaining issue has been fixed as follows in the meantime: You cannot specify the username anymore. It just is hardcoded to "admin". You just have to specify the password for the "admin" user from now on. As you'd expect, the "admin" user enjoys full prividelges as default. Anything else can and should then be tackled through the Tvheadend Web-UI.

Thanks a lot for the report and the discussion. I'm closing this issue as fixed. Please open another one, if you should still encounter any issues.

**Closed by m4tt075** 2019-02-23 21:20 UTC
