### ISSUE TITLE
TestDisk not working with DSM 6.1.1

### ISSUE THREAD

**Issue by nardew** [SynoCommunity/spksrc#2765] opened 2017-05-18 20:43 UTC
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ TestDisk
_Package Version:_ 7.0-2

_NAS Model:_ DS215j
_NAS Architecture:_ armv7l
_DSM version:_ DSM 6.1.1-15101

### Expected behavior
After running  /usr/local/testdisk/bin/photorec or /usr/local/testdisk/bin/testdisk a console application should start.

### Actual behavior
After running either of the binaries, they end with segmentation fault.

PhotoRec 7.0, Data Recovery Utility, April 2015
Christophe GRENIER <grenier@cgsecurity.org>
http://www.cgsecurity.org
Segmentation fault (core dumped)

### Steps to reproduce
Run installed binaries:
 /usr/local/testdisk/bin/photorec
/usr/local/testdisk/bin/testdisk

#### Package log
None

Insert the package log here
None

#### Other logs
None

**Comment by ymartin59** [comment] 2017-05-23 19:01
Sorry I cannot reproduce as I have no access to a ARM based system. Testdisk package is correct on x86 / x86_64 platforms.

**Comment by ymartin59** [comment] 2017-05-23 19:10
I have just rebuilt package for `armada375` with DSM 6.1 toolchains from my PR #2727. Packed as a zip because of GitHub restriction. May you please download, unpack and manually install this package to test it ? Thank you in advance
[testdisk_armada375-6.1_7.0-2.spk.zip](https://github.com/SynoCommunity/spksrc/files/1023444/testdisk_armada375-6.1_7.0-2.spk.zip)

**Comment by nardew** [comment] 2017-05-25 18:57
Hello Yves, having installed manually the attached file testdisk/photorec is working properly! Thank you very much.

Just out of curiosity, could you tell me what was the issue?

**Comment by ymartin59** [comment] 2017-05-27 19:29
Hello. As package available in repositories are built with DSM 5.x toolchain, there is high risk produced binary cannot work with DSM 6.1 glibc and kernel versions. I have no idea when DSM 6.1 packages may be published to repositories but it is probably time to do so.
Please close this issue. Regards

**Closed** 2017-05-28 08:37 UTC

**Comment by mav1** [comment] 2018-11-06 13:11
> I have just rebuilt package for `armada375` with DSM 6.1 toolchains

Hello, please, can you built package for ds115j (dsm 6.1) ? It has armada370 processor...

**Comment by julienbenjamin** [comment] 2019-11-02 17:23
> I have just rebuilt package for `armada375` with DSM 6.1 toolchains from my PR #2727. Packed as a zip because of GitHub restriction. May you please download, unpack and manually install this package to test it ? Thank you in advance
> [testdisk_armada375-6.1_7.0-2.spk.zip](https://github.com/SynoCommunity/spksrc/files/1023444/testdisk_armada375-6.1_7.0-2.spk.zip)

Could you build a DS414 version for DSM6? Or at least tell how to make sure my toolchain and dependencies are correct to compile testdisk and photorec?

**Comment by julienbenjamin** [comment] 2019-11-10 18:06
Anyone having the same issue with a DS414?

**Comment by hgy59** [comment] 2019-11-10 18:29
@julienbenjamin there is a current PR #3795 for synocli-disk and it updates testdisk to version 7.1

on my armada370 (DS-115j) it shows like this:
```
admin@DSxxxxx:~$ testdisk -v
TestDisk 7.1, Data Recovery Utility, July 2019
Christophe GRENIER <grenier@cgsecurity.org>
https://www.cgsecurity.org

Version: 7.1
Compiler: GCC 4.9
ext2fs lib: none, ntfs lib: none, reiserfs lib: none, ewf lib: none, curses lib: ncurses 6.1
OS: Linux, kernel 3.2.40 (#24922 Mon Aug 19 12:09:30 CST 2019) armv7l
admin@DSxxxxx:~$
admin@DSxxxxx:~$
admin@DSxxxxx:~$
```

You can clone the branch [hgy59:synocli-disk](https://github.com/hgy59/spksrc/tree/synocli-disk) or wait until the PR is merged and published.
If you clone the branch there is a do-it-yourself package that contains testdisk only in the folder /diyskp/testdisk.

**Comment by rp4k** [comment] 2019-11-17 16:00
my issue is that after i install from the synologycommunity repo and i go to the directory using SSH and when i type "testdisk"  nothing happens it says its a bad command.   

DS716+ 
DSM 6.22

**Comment by hgy59** [comment] 2019-11-17 17:31
@rp4k did you install "SynoCli Disk Tools v1.0-1"?
This package contains testdisk Version 7.1 and is available since 4 days.
