### ISSUE TITLE
HTPC Manager custom

### ISSUE THREAD

**Issue by blindpet** [SynoCommunity/spksrc#1570] opened 2015-03-20 14:48 UTC
The original HTPC Manager repo is outdated and the maintainer isn't responding to new pull requests.

Another developer has updated it to include SickRage and Sonarr support and it would be great if we could customize the fork we use to be https://github.com/Hellowlol/HTPC-Manager  just like can be done for SickBeard.

**Comment by Dr-Bean** [comment] 2015-03-24 08:40
Duplicate of #1441, so let's close this one.

**Closed by Dr-Bean** 2015-03-24 08:40 UTC
