### ISSUE TITLE
Mosquitto last update does NOT start any more if Websockets port is defined

### ISSUE THREAD

**Issue by beardsick** [SynoCommunity/spksrc#4210] opened 2020-10-07 11:10 UTC
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Mosquitto
_Package Version:_ 1.6.12-10

_NAS Model:_ DS1019+
_NAS Architecture:_ DSM 6.2.3-25426 Update 2
_DSM version:_ DSM 6.2.3-25426 Update 2

After updating my longtime GOOD WORKING previous Mosquitto version (1.4.14-9 ??) to the latest 1.6.12-10 it refused to start and gave an error: "Failed to run the package service"
De-install and re-install with default .conf settings was running fine with this newest version.
However ... when I add an extra listener on port   9001 websockets    this latest version refused to start giving the same above message.

# =================================================================
# Extra listeners
# =================================================================
## AFTER UPGRADE on 5-10-2020 "Extra listeners" next 2 lines were giving ERROR: "Failed to run the package service" !!! ???
listener 9001
protocol websockets
#=================================================================

Changing the port number to other values than 9001 did not solve the problem.

**Comment by BenjV** [comment] 2020-10-07 14:12
The port is not the problem, the protocol is the problem
Seems to me that the package is not compiled with websockets and so only support mqtt as protocol

**Comment by beardsick** [comment] 2020-10-07 21:29
Thanks BenjV ... this seems a logical explanation ... but why would SynoCommunity do this for their new version if the previous did have websockets working well ?
How can this be solved ?

**Comment by BenjV** [comment] 2020-10-07 21:46
Don't no.
Maybe building needs extra or other options and is just the old build process used.

**Comment by m7b** [comment] 2020-10-08 07:06
Hi together,
I have the same problem after upgrading from version 1.4.14-9 to 1.6.12.10 on my DS215j.

The mosquitto.log says:
`Error: Websockets support not available.`

**Comment by BenjV** [comment] 2020-10-08 10:14
It seems to be a Mosquitto problem and not a SynoCommunity issue.
see:
https://github.com/eclipse/mosquitto/issues/1740

**Comment by beardsick** [comment] 2020-10-08 17:08
Hi all, is there any possibility to download the previous stable version 1.4.14-9 (?) as a  .spk  file for manual install on the Synology ? 
I looked for it but can only find the  .spk  file for the latest version with the bug inside.

**Comment by BenjV** [comment] 2020-10-08 18:25
https://synocommunity.com/package/mosquitto

**Comment by arnebjarne** [comment] 2020-10-10 11:14
> 
> 
> It seems to be a Mosquitto problem and not a SynoCommunity issue.
> see:
> [eclipse/mosquitto#1740](https://github.com/eclipse/mosquitto/issues/1740)
> 
> They say it is fixed, so a new build for this package to upgrade to version 1.6.12 should fix this.

as I read it, it was fixed in 1.6.11...
So this version 1.6.12 must have been compiled without websockets support.

I will try and see if I can compile it myself and see if websockets gets compiled in by default or not.

**Comment by BenjV** [comment] 2020-10-10 11:28
May read the whole thread before already posted information.

**Comment by arnebjarne** [comment] 2020-10-10 11:48
> 
> 
> Maybe you should read the whole thread before posting already posted information.

lol my bad. Anyway trying to rebuild the package myself right now to see if I can fix the problem.

**Comment by hgy59** [comment] 2020-10-10 12:33
> Anyway trying to rebuild the package myself right now to see if I can fix the problem.

@arnebjarne can you confirm this is fixed with my latest commit?

**Comment by arnebjarne** [comment] 2020-10-10 13:02
> 
> 
> > Anyway trying to rebuild the package myself right now to see if I can fix the problem.
> 
> @arnebjarne can you confirm this is fixed with my latest commit?

Hi hgy59.

I think i still miss some of you patches
libwebsockets 3.2.2 fails compiling due to the openssl issue
Compiling with SSL support
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found
  version "1.1.1d")

I will double check your big commit from mosquotto 1.4 to 1.6.12
(nb: I am compiling for DS418 with "make arch-rtd1296)

I get back.

**Comment by arnebjarne** [comment] 2020-10-10 13:25
> 
> 
> > Anyway trying to rebuild the package myself right now to see if I can fix the problem.
> 
> @arnebjarne can you confirm this is fixed with my latest commit?

Hi hgy59.

I can confirm that your latest commit ( https://github.com/ymartin59/spksrc/tree/4044_update_mosquitto ) make mosquitto 1.6.12-10 compile with websockets on arch-rtd1296.
( I was missing your openssl fix - https://github.com/SynoCommunity/spksrc/pull/4191/commits/cbda607efcccafc1781cf4a80a14316012426e21).

I have the version running on my DS418.

**Comment by beardsick** [comment] 2020-10-11 18:14
@BenjV , thanks for the link to the downloads of old versions.
I tried them but they seem for Synology DSM 6.1  and I have DSM 6.2.3-25426 Update 2  ... I got an error.
Am I doing something wrong ?

**Comment by BenjV** [comment] 2020-10-11 18:49
There is no difference for DSM 6.1 and DSM 6.2 packages, they are all compatible.

But the package is already upgraded to 1.6.12-10 so manual download is not needed anymore.

**Comment by ymartin59** [comment] 2020-10-12 15:19
Update 1.6.12-11 published and tested with `protocol websockets`

**Closed by ymartin59** 2020-10-12 15:19 UTC
