### ISSUE TITLE
Debian Chroot not working on DSM 5.2

### ISSUE THREAD

**Issue by danielvonmitschke** [SynoCommunity/spksrc#1734] opened 2015-06-02 13:58 UTC
I tried to install the debian chroot package 7.4-5 (first installed Syno Python 2.7.9-13) and when clicking on "run" it turns back to "stopped".
When opening the Debian Chroot App the status under "Package Informations" just keeps saying "installing" but apparently nothing is happening.

Also the (temporary) help file is not accessible anymore:
https://github.com/SynoCommunity/spksrc/blob/develop/spk/debian-chroot/src/app/help/enu/index.html

thanks

**Comment by piwi82** [comment] 2015-06-02 14:07
I don't use Debian Chroot but you can find the help file in the master branch : https://github.com/SynoCommunity/spksrc/blob/master/spk/debian-chroot/src/app/help/enu/index.html

**Comment by Dr-Bean** [comment] 2015-06-12 09:18
Installing Debian-chroot takes a while. If you can open the Debian-chroot link in the menu, then it appears to be working as expected (well, maybe except for the status reporting in Package Center)

Assuming the issue still occurs, what happens when you run the start-stop-status script manually:
`/var/packages/debian-chroot/scripts/start-stop-status start` (replace `start` with `stop` to stop, or `status` to check status)

**Comment by danielvonmitschke** [comment] 2015-06-12 11:05
@Dr-Bean thank you. i already solved it by building my own spk package.
this one worked flawlessly.
maybe something was wrong with the pre-build package.

**Comment by Dr-Bean** [comment] 2015-06-12 11:59
Well, perfect. Closing as resolved: unless other people come forward that Debian-Chroot doesn't work on their end, I'm going to assume the package is fine ;)

**Closed by Dr-Bean** 2015-06-12 11:59 UTC

**Comment by danielvonmitschke** [comment] 2015-06-12 12:27
@Dr-Bean I forgot to mention that I (manually) built the package with the DSM 5.2 toolchain.
maybe that made the difference.

**Comment by Dr-Bean** [comment] 2015-06-12 12:46
Thanks for the info. Can't reproduce it on 5.2 myself, and I'm not sure the new toolchains will have a big effect on a package such as Debian-chroot. We'll be including the new toolchains at some point though.

**Comment by conichonhaa** [comment] 2015-12-21 20:31
Hi 
I'm on DSM 5.2
I have the same problem with the Debian Chroot App, the status under "Package Informations" just keeps saying "installing" .
I tried to compile myself and it installed, but  the app says "keep installing"
Running the script manually /var/packages/debian-chroot/scripts/start-stop-status start doesn't change anything, when i launch it with status, it says chroot not running
Is is something related to pyhton version installed ?
I'm a bit lost
