### ISSUE TITLE
Empty blocklist in Transmission 4.0.2

### ISSUE THREAD

**Issue by d4niel-P** [SynoCommunity/spksrc#5685] opened 2023-04-05 08:39 UTC
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

Transmission

### Package Version

4.0.2-21

### Device Model

DS214se

### Device Architecture

ARMv7 (armada370)

### Firmware Version

DSM 7.1.1-42962 Update 4

### What happened?

After update to Transmission 4.0.2 blocklist is empty. Update ends with:
![obraz](https://user-images.githubusercontent.com/4502783/230026409-3052983b-a95e-4fb6-942e-1da7fcd8bf7b.png)
WebGUI also shows zero entries:
![obraz](https://user-images.githubusercontent.com/4502783/230027473-a084a2d8-4811-48fe-a273-69be16869bb7.png)

although the same list worked on 3.00-20 and currently has 88 412 entries:
![obraz](https://user-images.githubusercontent.com/4502783/230027755-51ce6ce7-e1ef-4f56-b408-b68e2edb3d85.png)
(example from other devices still running Transmission 3)

I suspect it might be permissions issue but I cannot see anything in logs.
Blocklist link: https://mirror.codebucket.de/transmission/blocklist.p2p.gz

### Reproduction steps

```bash
1. Update blocklist in WebGUI
2. Nothing happens
3. WebGUI shows that blocklist has zero entries
...
```

### Install Log

```log
2023/03/30 21:34:51     upgrade transmission 3.00-20 Begin start-stop-status stop
2023/03/30 21:34:57     upgrade transmission 3.00-20 End start-stop-status stop ret=[0]
2023/03/30 21:34:59     upgrade transmission 3.00-20 Begin preupgrade
2023/03/30 21:34:59     Begin load_variables_from_file
2023/03/30 21:35:00     End load_variables_from_file
2023/03/30 21:35:00     Begin initialize_variables
2023/03/30 21:35:00     End initialize_variables
2023/03/30 21:35:00     ===> Step preupgrade. STATUS=UPGRADE USER=sc-transmission GROUP= SHARE_PATH=
2023/03/30 21:35:00     upgrade transmission 3.00-20 End preupgrade ret=[0]
2023/03/30 21:35:01     upgrade transmission 3.00-20 Begin preuninst
2023/03/30 21:35:01     Begin reload_inst_variables
2023/03/30 21:35:01     End reload_inst_variables
2023/03/30 21:35:02     Begin initialize_variables
2023/03/30 21:35:02     End initialize_variables
2023/03/30 21:35:02     ===> Step preuninst. USER=sc-transmission GROUP= SHARE_PATH=
2023/03/30 21:35:02     upgrade transmission 3.00-20 End preuninst ret=[0]
2023/03/30 21:35:02     upgrade transmission 3.00-20 Begin /bin/rm -rf /volume1/@appstore/transmission
2023/03/30 21:35:03     upgrade transmission 3.00-20 End /bin/rm -rf /volume1/@appstore/transmission ret=[0]
2023/03/30 21:35:03     upgrade transmission 3.00-20 Begin /bin/rm -rf /volume1/@apptemp/transmission
2023/03/30 21:35:03     upgrade transmission 3.00-20 End /bin/rm -rf /volume1/@apptemp/transmission ret=[0]
2023/03/30 21:35:03     upgrade transmission 3.00-20 Begin postuninst
2023/03/30 21:35:03     Begin reload_inst_variables
2023/03/30 21:35:03     End reload_inst_variables
2023/03/30 21:35:03     Begin initialize_variables
2023/03/30 21:35:04     End initialize_variables
2023/03/30 21:35:04     ===> Step postuninst. USER=sc-transmission GROUP= SHARE_PATH=
2023/03/30 21:35:04     upgrade transmission 3.00-20 End postuninst ret=[0]
2023/03/30 21:35:04     upgrade transmission 4.0.2-21 Begin preinst
2023/03/30 21:35:05     Begin load_variables_from_file
2023/03/30 21:35:05     End load_variables_from_file
2023/03/30 21:35:05     Begin initialize_variables
2023/03/30 21:35:05     End initialize_variables
2023/03/30 21:35:05     ===> Step preinst. STATUS=UPGRADE USER=sc-transmission GROUP= SHARE_PATH=
2023/03/30 21:35:05     upgrade transmission 4.0.2-21 End preinst ret=[0]
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 Begin /bin/mkdir -p /volume1/@appstore/transmission -m 755
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 End /bin/mkdir -p /volume1/@appstore/transmission -m 755 ret=[0]
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 Begin /bin/rm -rf /volume1/@appstore/transmission
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 End /bin/rm -rf /volume1/@appstore/transmission ret=[0]
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 Begin /bin/mv -f /volume1/@tmp/synopkg/install.ujXkGi/package /volume1/@appstore/transmission
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 End /bin/mv -f /volume1/@tmp/synopkg/install.ujXkGi/package /volume1/@appstore/transmission ret=[0]
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 Begin /bin/rm -rf /var/packages/transmission
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 End /bin/rm -rf /var/packages/transmission ret=[0]
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 Begin /bin/mkdir -p /var/packages/transmission -m 755
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 End /bin/mkdir -p /var/packages/transmission -m 755 ret=[0]
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 Begin /bin/touch /var/packages/transmission/installing
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 End /bin/touch /var/packages/transmission/installing ret=[0]
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 Begin /bin/mv -f /volume1/@tmp/synopkg/install.ujXkGi/INFO /var/packages/transmission/INFO
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 End /bin/mv -f /volume1/@tmp/synopkg/install.ujXkGi/INFO /var/packages/transmission/INFO ret=[0]
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 Begin /bin/rm -rf /var/packages/transmission/scripts
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 End /bin/rm -rf /var/packages/transmission/scripts ret=[0]
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 Begin /bin/mv -f /volume1/@tmp/synopkg/install.ujXkGi/scripts /var/packages/transmission/scripts
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 End /bin/mv -f /volume1/@tmp/synopkg/install.ujXkGi/scripts /var/packages/transmission/scripts ret=[0]
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 Begin /bin/rm -rf /var/packages/transmission/WIZARD_UIFILES
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 End /bin/rm -rf /var/packages/transmission/WIZARD_UIFILES ret=[0]
2023/03/30 21:35:08     upgrade transmission 4.0.2-21 Begin /bin/mv -f /volume1/@tmp/synopkg/install.ujXkGi/WIZARD_UIFILES /var/packages/transmission/WIZARD_UIFILES
2023/03/30 21:35:09     upgrade transmission 4.0.2-21 End /bin/mv -f /volume1/@tmp/synopkg/install.ujXkGi/WIZARD_UIFILES /var/packages/transmission/WIZARD_UIFILES ret=[0]
2023/03/30 21:35:09     upgrade transmission 4.0.2-21 Begin /bin/rm -rf /var/packages/transmission/conf
2023/03/30 21:35:09     upgrade transmission 4.0.2-21 End /bin/rm -rf /var/packages/transmission/conf ret=[0]
2023/03/30 21:35:09     upgrade transmission 4.0.2-21 Begin /bin/mv -f /volume1/@tmp/synopkg/install.ujXkGi/conf /var/packages/transmission/conf
2023/03/30 21:35:09     upgrade transmission 4.0.2-21 End /bin/mv -f /volume1/@tmp/synopkg/install.ujXkGi/conf /var/packages/transmission/conf ret=[0]
2023/03/30 21:35:29     upgrade transmission 4.0.2-21 Begin postinst
2023/03/30 21:35:29     Begin load_variables_from_file
2023/03/30 21:35:29     End load_variables_from_file
2023/03/30 21:35:29     Begin initialize_variables
2023/03/30 21:35:29     End initialize_variables
2023/03/30 21:35:29     ===> Step postinst. STATUS=UPGRADE USER=sc-transmission GROUP= SHARE_PATH=
2023/03/30 21:35:30     Begin save_wizard_variables
2023/03/30 21:35:30     End save_wizard_variables
2023/03/30 21:35:30     Begin syno_sync_var_folder
2023/03/30 21:35:30     Install files from var folder
2023/03/30 21:35:30     /bin/rsync -avh --ignore-existing --remove-source-files /volume1/@appstore/transmission/var/ /volume1/@appdata/transmission
2023/03/30 21:35:30     sending incremental file list
2023/03/30 21:35:30     ./
2023/03/30 21:35:30     sent 98 bytes  received 19 bytes  234.00 bytes/sec
2023/03/30 21:35:30     total size is 379  speedup is 3.24
2023/03/30 21:35:30     /bin/rsync -avh --remove-source-files /volume1/@appstore/transmission/var/ /volume1/@appdata/transmission
2023/03/30 21:35:31     sending incremental file list
2023/03/30 21:35:31     ./
2023/03/30 21:35:31     settings.json.new
2023/03/30 21:35:31     sent 533 bytes  received 46 bytes  1.16K bytes/sec
2023/03/30 21:35:31     total size is 379  speedup is 0.65
2023/03/30 21:35:31     End syno_sync_var_folder
2023/03/30 21:35:31     Begin service_postinst
2023/03/30 21:35:31     End service_postinst
2023/03/30 21:35:31     upgrade transmission 4.0.2-21 End postinst ret=[0]
2023/03/30 21:35:31     upgrade transmission 4.0.2-21 Begin postupgrade
2023/03/30 21:35:31     Begin load_variables_from_file
2023/03/30 21:35:31     End load_variables_from_file
2023/03/30 21:35:31     Begin initialize_variables
2023/03/30 21:35:31     End initialize_variables
2023/03/30 21:35:31     ===> Step postupgrade. STATUS=UPGRADE USER=sc-transmission GROUP= SHARE_PATH=
2023/03/30 21:35:31     Begin syno_sync_var_folder
2023/03/30 21:35:31     End syno_sync_var_folder
2023/03/30 21:35:32     upgrade transmission 4.0.2-21 End postupgrade ret=[0]
2023/03/30 21:35:36     upgrade transmission 4.0.2-21 Begin start-stop-status start
2023/03/30 21:35:38     upgrade transmission 4.0.2-21 End start-stop-status start ret=[0]
```

### Service Log

```log
Starting transmission command /volume1/@appstore/transmission/bin/transmission-daemon -g /volume1/@appdata/transmission -x /volume1/@appdata/transmission/transmission.pid -e /volume1/@appdata/transmission/transmission.log
```

### Other Logs

```log
2023-04-05T10:07:05+02:00 Backup synopkg[8404]: pkgtool.cpp:1741 chmod failed for /var/packages (Operation not permitted)
2023-04-05T10:07:05+02:00 Backup synopkg[8404]: pkgtool.cpp:1750 chmod failed for /usr/local/etc/rc.d (Operation not permitted)
2023-04-05T10:07:05+02:00 Backup synopkg[8404]: pkgfile.cpp:115 Failed to create directory, path=[/var/cache/synopkg/installed] err=[Permission denied]
2023-04-05T10:07:05+02:00 Backup synopkg[8404]: pkginstalled_repository.cpp:66 Failed to mkdir for file, path=[/var/cache/synopkg/installed/dependency_graph] reason=[Permission denied]
2023-04-05T10:07:05+02:00 Backup synopkg[8404]: pkginstalled_repository.cpp:120 Failed to put graph cache into file, path=[/var/cache/synopkg/installed/dependency_graph] reason=[Permission denied]
2023-04-05T10:07:05+02:00 Backup synopkg[8404]: pkgfile.cpp:115 Failed to create directory, path=[/run/synopkg/lock] err=[Permission denied]
2023-04-05T10:07:05+02:00 Backup synopkg[8404]: pkglock_package_lock.cpp:44 Failed to create dir for lock, path=[/run/synopkg/lock/transmission.lock]
```

**Comment by mreid-tt** [comment] 2023-04-05 12:31
That's very weird. I have the exact same blocklist URL but mine is working:
<img width="269" alt="Screenshot 2023-04-05 at 8 28 12 AM" src="https://user-images.githubusercontent.com/943378/230080515-8ebfcaac-79a9-458f-84dc-9436f0653702.png">

Your installation log looks clean. The other log was from which file?
Also, your service log suggests that additional log entries may be included in `/volume1/@appdata/transmission/transmission.log`. Anything interesting in there?

**Comment by mreid-tt** [comment] 2023-04-05 13:07
Thanks for the feedback. You are correct, that error does seem weird. What happens if you look at that directory? My output looks like this:

```
$ ls -all /run/synopkg/lock/
total 0
drwxr-xr-x 2 root root 300 Apr  4 04:21 .
drwxr-xr-x 5 root root 120 Apr  5 09:00 ..
-rw-r--r-- 1 root root   0 Mar 22 11:56 ActiveInsight.lock
-rw-r--r-- 1 root root   0 Mar 31 07:01 chromaprint.lock
-rw-r--r-- 1 root root   0 Mar 31 07:00 ffmpeg.lock
-rw-r--r-- 1 root root   0 Mar 22 12:00 Node.js_v18.lock
-rw-r--r-- 1 root root   0 Mar  8 21:42 python311.lock
-rw-r--r-- 1 root root   0 Feb 14 05:13 radarr.lock
-rw-r--r-- 1 root root   0 Mar  8 21:42 sabnzbd.lock
-rw-r--r-- 1 root root   0 Apr  4 04:19 sonarr.lock
-rw-r--r-- 1 root root   0 Mar 22 11:57 SurveillanceStation.lock
-rw-r--r-- 1 root root   0 Mar 22 12:01 SynologyApplicationService.lock
-rw-r--r-- 1 root root   0 Mar 22 12:01 SynologyDrive.lock
-rw-r--r-- 1 root root   0 Mar 15 13:43 transmission.lock
-rw-r--r-- 1 root root   0 Mar 30 14:32 VideoStation.lock
```

It may be useful to just reboot your Synology unit to see if that helps since these files are created by the DSM O/S itself.

As for the service logs, you are correct, the two files are the same since the `/var/packages/transmission/var/` path has a symbolic link to `/volume1/@appdata/transmission/`.

**Comment by d4niel-P** [comment] 2023-04-05 13:22
Here you have dir `/run/synopkg/lock/`:
> drwxr-xr-x 2 root root 60 Apr  5 10:07 .
> drwxr-xr-x 4 root root 80 Apr  5 10:08 ..
> -rw------- 1 root root  0 Apr  5 10:07 transmission.lock
I have Node.js or Synology Application Servicem installed in the system but only lock for transmission is here.

I've rebooted NAS and restarted transmission daemon couple times. It didn't fix the issue.

Of course I can reinstall transmission package but I'd like to try less invasive remedies first. ;)

**Comment by mreid-tt** [comment] 2023-04-05 13:25
I note the permissions for your `transmission.lock` is slightly different. Perhaps if the app isn't running you can just delete it with: `sudo rm /run/synopkg/lock/transmission.lock` and start the app up again?

**Comment by mreid-tt** [comment] 2023-04-05 14:21
This is strange. Lot's of weird messages with your DSM. I also run my admin as a created account with the default `admin` disabled as this is a security recommendation.

As for your directory error, the Synology KB has the following: https://kb.synology.com/en-me/DSM/tutorial/ssh_could_not_chdir_to_home_directory

**Comment by d4niel-P** [comment] 2023-04-05 15:22
Yeah, I might have messed up the system a little forcing update to one of the first betas of DSM 7 back in the day. I'll try to dig a bit more and if I don't find solution I'll clean install the package again. Thank you for the help, I really appreciate it.

**Comment by mreid-tt** [comment] 2023-04-26 19:09
Hi @d4niel-P, just following up to see if there are any recent updates to the actions outlined to resolve this issue. Since out last interaction a new version of Transmission (v4.0.3-22) has also been released. Can you please let us know if the issue still persists? If we don't hear back from you in a few days, we'll assume the issue has been resolved and close this ticket. Thank you!

**Comment by d4niel-P** [comment] 2023-04-27 09:10
Hi, it was the first thing I checked after I got notification about the update. Unfortunately list is still empty.

**Comment by d4niel-P** [comment] 2023-04-27 10:55
Sorry, I didn't yet have time for clean install. Config file looks all right, I can edit other settings (even link to blocklist) and they stick between restarts. I'll report after clean install if the issue with empty list still persists.

**Comment by mreid-tt** [comment] 2023-06-17 00:54
@d4niel-P, following up on this. Any progress to resolve and close this issue?

**Comment by mreid-tt** [comment] 2023-06-22 12:52
Closing the issue unless any new feedback is provided, as it has been determined that the issue cannot be replicated.

**Comment by dwardor** [comment] 2023-09-01 10:08
I think I am falling on something similar since updating to DSM 7.2 / transmission 4.0.3-22

My synology NAS has been (for many years now) hosting my nighlty generated blocklist file on : http://localhost/FilteredIPs.p2p.gz [I can still "wget" the file without issue]

transmission has this configured as its blocklist-url
```
grep blocklist settings.json 
    "blocklist-enabled": true,
    "blocklist-url": "http://localhost/FilteredIPs.p2p.gz",
```

However since the recent upgrade to DSM 7.2 / transmission 4.0.3-22 from DSM 6, blocklist-update replies it couldn't fetch blocklist
```
$ ./transmission-remote -n <user:pass> --blocklist-update
Error: Couldn't fetch blocklist: No Response (0)
```

I get nothing more in the transmission.log ("even with --log-level=debug")

--> Is this a permission issue ? where does transmission try to download the blocklist ?

@d4niel-P how did you resolve this ?


P.S. I also tried by setting blocklist-url to https://mirror.codebucket.de/transmission/blocklist.p2p.gz and get the exact same "Error: Couldn't fetch blocklist: No Response (0)"

**Comment by d4niel-P** [comment] 2023-09-01 10:38
> @d4niel-P how did you resolve this ?
> 
I didn't. Clean install of Transmission didn't help at all.
I still suspect it's a permission issue and, since my NAS has some other (minor) ownership / storage quirks, I want to do a completely fresh install of DSM 7.1.x but this operation requires a lot of preparation so I'm postponing until unspecified future. ;)

**Comment by hgy59** [comment] 2023-09-01 11:21
@dwardor I did a first (initial) installation of transmission 4.0.3-22 on a Virtual DSM (on DS-218+)

```
$ cat /etc/VERSION
majorversion="7"
minorversion="2"
major="7"
minor="2"
micro="0"
buildphase="GM"
buildnumber="64570"
smallfixnumber="3"
nano="3"
base="64570"
productversion="7.2"
os_name="DSM"
builddate="2023/08/01"
buildtime="15:18:33"

/var/packages/transmission/target/bin$ ./transmission-remote --blocklist-update
Unexpected response: <h1>401: Unauthorized</h1>
/var/packages/transmission/target/bin$ ./transmission-remote -n admin:admin --blocklist-update
Error: Couldn't fetch blocklist: Not Found (404)
```

so far blocklist was disabled in transmission and the responses above are expected.

Then I enabled blocklist in the Transmission Web UI, entered https://mirror.codebucket.de/transmission/blocklist.p2p.gz as blocklist and pressed _udpate_.
This shows `Blocklist has 80’466 rules` in the web ui.

And the cli command works now
```
/var/packages/transmission/target/bin$ ./transmission-remote -n admin:admin --blocklist-update
localhost:9091/transmission/rpc/ responded: success
```

So, I cannot reproduce the error.

BTW: DS412se is an ARMv7 model (armada370 cpu) and not x86_64.

**Comment by hgy59** [comment] 2023-09-01 11:42
Some steps further

on a DS115j (armada370 too) I get an empty blocklist with the repeated steps of the post above

transmission.log
working (VirtualDSM DSM 7.2)
```
[2023-09-01 13:10:21.863] WRN blocklist.cc:242 Couldn't parse line: '83423' (blocklist.cc:242)
[2023-09-01 13:10:21.863] inf blocklist.cc:68 Blocklist 'blocklist.bin' has 80466 entries (blocklist.cc:68)
[2023-09-01 13:10:37.862] WRN blocklist.cc:242 Couldn't parse line: '83423' (blocklist.cc:242)
[2023-09-01 13:10:37.862] inf blocklist.cc:68 Blocklist 'blocklist.bin' has 80466 entries (blocklist.cc:68)
```

failing (DS115j, DSM 7.1.1)
``` 
[2023-09-01 13:25:41.381] WRN session-id.cc:74 Couldn't create '/tmp/tr_session_id_913zI79k5VVcTpxBYnV3fFO87UHOKptpTUFTNq2XoBkt3fvz': Invalid argument (22) (session-id.cc:74)
[2023-09-01 13:26:09.379] WRN blocklist.cc:242 Couldn't parse line: '83423' (blocklist.cc:242)
[2023-09-01 13:26:09.380] WRN blocklist.cc:505 Couldn't save '/volume1/@appdata/transmission/blocklists/blocklist': Unable to read/write: Invalid argument (22) (blocklist.cc:505)
[2023-09-01 13:26:12.373] WRN blocklist.cc:242 Couldn't parse line: '83423' (blocklist.cc:242)
[2023-09-01 13:26:12.373] WRN blocklist.cc:505 Couldn't save '/volume1/@appdata/transmission/blocklists/blocklist': Unable to read/write: Invalid argument (22) (blocklist.cc:505)
[2023-09-01 13:28:07.376] WRN blocklist.cc:242 Couldn't parse line: '83423' (blocklist.cc:242)

```

**Comment by d4niel-P** [comment] 2023-09-01 11:55
> failing (DS115j, DSM 7.1.1)
That's interesting, thank you for the tests!

7.1.x is the final upgrade for DS214se so I guess its the to upgrade.

**Comment by hgy59** [comment] 2023-09-01 16:28
> * cli command seems to work...
> ```
> $ ./transmission-remote -n admin:admin --blocklist-update
> localhost:9091/transmission/rpc/ responded: success
> ```
> 
> ... but going back to webui still shows there are 0 rules...

It does not work, even it `responded: success`

The var/blocklists/blocklist file is empty

---
this seems the result of `: Unable to read/write: Invalid argument (22) (blocklist.cc:505)`

I already built a package for `arch-armada370-7.1` (instead of arch-armv7-7.1)), but this did not change anything.

the configure output for armada370 is different to armv7 in the following part:
armada370:
```
-- Performing Test NO_LFS_MACROS_REQUIRED - Failed
-- Performing Test FILE_OFFSET_BITS_LFS_MACRO_REQUIRED
-- Performing Test FILE_OFFSET_BITS_LFS_MACRO_REQUIRED - Success
```
armv7 (and others like x64)
```
-- Performing Test NO_LFS_MACROS_REQUIRED - Success
```

the error is generated in the file `libtransmission/file-posix.cc` on line 512:
```
    if (file_size != 0)
    {
        tr_error_prefix(error, "Unable to read/write: ");
        return false;
    }
```

It seams that either the downloaded file is empty or the processing does not work,
but I have not a clue what the real reason is...

on my working virtual DSM, there are two files after the blocklist update
blocklist (a text file)
blocklist.bin (a binary file)

**Comment by dwardor** [comment] 2023-09-01 17:42
For info DS414 is armadaxp

**Comment by mreid-tt** [comment] 2023-09-01 18:16
For reference, I tried with my VirtualDSM setup as follows:

> DSM 7.1.1-42962 Update 4
> DS916+ (INTEL Pentium N3710)
> Transmission v4.0.3-22

I did a clean install and then enabled blocklist, adding the URL as above: https://mirror.codebucket.de/transmission/blocklist.p2p.gz. The operation was successful with the following entries in the service log:

```
[2023-09-01 14:03:06.777] WRN blocklist.cc:242 Couldn't parse line: '83423' (blocklist.cc:242)
[2023-09-01 14:03:06.777] inf blocklist.cc:68 Blocklist 'blocklist.bin' has 80466 entries (blocklist.cc:68)
```

Sorry but I'm unable to replicate the issue with my setup.

**Comment by hgy59** [comment] 2023-09-01 19:39
@mreid-tt this issue is only with ARMv7 archs (at least with armadaxp and armada370)

**Comment by hgy59** [comment] 2023-09-02 16:12
@d4niel-P, @dwardor just found a solution and will create a PR with the fix.

It is hidden deep inside the source code of transmission...

**Closed** 2023-09-09 00:04 UTC
Labels: bug

**Comment by petesimon** [comment] 2024-09-11 05:15
i have the same error as @d4niel-P in Transmission-gtk 4.0.6 in Ubuntu Linux. two different blocklists results in 0 lists added.
