### ISSUE TITLE
Chroot UI in DSM "loading" forever, impossible to close

### ISSUE THREAD

**Issue by Matioupi** [SynoCommunity/spksrc#2507] opened 2016-11-01 06:56 UTC
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:debian-chroot
_Package Version:8.4.7

_NAS Model:3614xs
_NAS Architecture:Bromolow
_DSM version:6.0.2.8451 Update 2

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead
when loading the Chroot UI from within DSM interface, the UI loads with 2 entries in the left menu
First one is "Vue d'ensemble" (global view without localization ?)
Second one is Services
When going to the second one, nothing special happens, but when going to "Vue d'ensemble", a "loading" info panel shows up and stay in that states for as long i've been able to wait...

Trying to closing the UI with the top right X does not work
### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
no package log at given path (replacing {package with debian-chroot

#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by Dr-Bean** [comment] 2016-11-01 09:41
Duplicate of https://github.com/SynoCommunity/spksrc/issues/1910. You might want to check there, of othe comments seems to include a workaround.

**Closed by Dr-Bean** 2016-11-01 09:41 UTC
