### ISSUE TITLE
[REQ] Upgrade TVheadend server package

### ISSUE THREAD

**Issue by Raptorek** [SynoCommunity/spksrc#2170] opened 2016-03-04 19:43 UTC
Hi guys, I wanna ask. Can contributor upgrade server package for Tvheadend? This version is too old, and also is not working with new version of addon for Kodi. Thanks

**Comment by sirjaymz** [comment] 2016-03-04 20:35
https://tvheadend.org/projects/tvheadend/wiki/download
Syno specific
http://syno.dierkse.nl/

**Comment by Dr-Bean** [comment] 2016-03-05 10:40
Duplicate of https://github.com/SynoCommunity/spksrc/issues/1855.

**Closed by Dr-Bean** 2016-03-05 10:40 UTC
