### ISSUE TITLE
DS115 unable to run any synocommunity package?

### ISSUE THREAD

**Issue by JCAndresen** [SynoCommunity/spksrc#2334] opened 2016-05-20 15:03 UTC
Hi there, 

DS115 running the latest DS version

Whenever I download a package (Squidguard, Sonarr, Sabnzbd, LazyLibrarian and couchpotato are the ones I have tried) it installs and then returns a failed to run package after it is installed. 

I tried rebooting the DS115 and I have tried powering it off completely. It gives me the same error. 

I can't see anything in the log of either program. 

Thanks.

**Comment by Dr-Bean** [comment] 2016-05-20 15:20
See #2207 and #2216. I'm going to close this one as duplicate of #2207.

**Closed by Dr-Bean** 2016-05-20 15:20 UTC
