### ISSUE TITLE
new version of sonarr

### ISSUE THREAD

**Issue by manuelramm** [SynoCommunity/spksrc#2417] opened 2016-07-24 18:20 UTC
first of all, sorry for creating an issue for this, but I see no better way:
I installed sonarr from packages.synocommunity and this works fine, but this version is from 2015. How can I update or compile a new version of sonarr? (https://sonarr.tv/#download)
Can somebody help me please or provide me a newer compiled version for my synology ds214+?
Really thanks in advance!!

**Comment by vvhof** [comment] 2016-07-24 19:05
Hey @manuelramm 
just start sonarr and navigate to system/updates. Sonarr has a build in update mechanism and it should have already updated itself!

**Comment by M0UL** [comment] 2016-07-24 20:32
@manuelramm the build in updater is off by default, you need turn it on the settings.

**Comment by KaraokeStu** [comment] 2016-09-15 23:29
Closed as @M0UL provided a valid fix. Not a bug

**Closed by KaraokeStu** 2016-09-15 23:29 UTC
Labels: wontfix
