### ISSUE TITLE
[Firefox Sync Server 1.5] Incorrect MySQL root password

### ISSUE THREAD

**Issue by BenjaminRousseau** [SynoCommunity/spksrc#2307] opened 2016-05-10 17:35 UTC
Hi,

I'm trying to install the package on Synology 6.0.

But at the end of the install, the package is telling me "Incorrect MySQL root password".
I'm sure that the root password is right. What can I do ?

Here is the error : 
"/bin/sh /volume1/@tmp/pkginstall/scripts/preinst" ] /volume1/@tmp/pkginstall/scripts/installer: line 33: /usr/syno/mysql/bin/mysql: No such file or directory

UPDATE
I fixed it by creating a symbolic link from
 /usr/syno/mysql/bin/mysql to  /usr/bin/mysql     AND
 /usr/syno/mysql/bin/mysqldump to  /usr/bin/mysqldump

Thank you.

**Comment by Dr-Bean** [comment] 2016-05-11 07:52
Duplicate of https://github.com/SynoCommunity/spksrc/issues/2093

**Closed by Dr-Bean** 2016-05-11 07:52 UTC
