### ISSUE TITLE
DSM 5.1 Update 4 Python 2.7.9-13 fails to install

### ISSUE THREAD

**Issue by davparker** [SynoCommunity/spksrc#1657] opened 2015-04-19 18:01 UTC
Since DSM 5.1 Update 4, Python 2.7.9-13 fails to install.
"This package is published by an unknown publisher."
I've update the certificate for SynoCommunity.
Other packages in SynoCommunity install properly, other than Python 3.
It suffers from the same issue.
The real problem is I cannot install Debian Chroot due to its dependency on Python  from the SynoCommunity.

**Comment by wind-rider** [comment] 2015-04-19 20:14
I think this is a duplicate of https://github.com/SynoCommunity/spksrc/issues/1646

That issue was closed, but apparently it is not completely solved?

**Comment by davparker** [comment] 2015-04-20 06:12
Yeah, I guess not

**Comment by Diaoul** [comment] 2015-04-20 08:57
Do you have the "Synology and trusted publisher" checked in Package Center?

**Comment by Dr-Bean** [comment] 2015-04-22 09:03
Seems to me to be a local issue...Also, @davparker, what does `I've updated the certificate for SynoCommunity` mean? I mean, you can import a certificate, but where did you get it from?
I'd suggest to remove and readd the repository, see if that helps.

**Closed** 2015-05-02 09:05 UTC

**Comment by davparker** [comment] 2015-05-02 09:08
I abandoned this approach and went with ipkg packages for my needs. Seems more flexible and less consumption of limited resources.

**Comment by Diaoul** [comment] 2015-05-02 09:23
More flexible maybe but not less consumption. Also please note optware is dead.

**Comment by davparker** [comment] 2015-05-02 10:09
Oh yeah, I added it without than B.S. optware. It was just frustrating
dealing with a broken Python, then it wouldn't upgrade. Set me back with
failed services,for too long,  so I sought alternatives while waiting for a
fix/workaround... ..... thanks though.

**Comment by Diaoul** [comment] 2015-05-02 11:17
ipkg is the package manager for optware
