### ISSUE TITLE
qBittorrent for DSM 7.0

### ISSUE THREAD

**Issue by ClassicUA** [SynoCommunity/spksrc#4747] opened 2021-07-20 11:39 UTC
* Name: qBittorrent
* Description: The qBittorrent project aims to provide an open-source software alternative to µTorrent.
* Website: https://www.qbittorrent.org
* Software documentation: 
* Build/Installation documentation: https://github.com/qbittorrent/qBittorrent/wiki
* Source code: https://github.com/qbittorrent/qBittorrent
* License: GPLv2+

**Comment by hgy59** [comment] 2021-07-20 16:56
duplicate of #4235 and #2506

**Comment by once375ml** [comment] 2023-11-15 02:51
IMNKS has solved the toochain and realized it, plz see: 
https://imnks.com/6865.html
https://github.com/userdocs/qbittorrent-nox-static

**Comment by mreid-tt** [comment] 2023-11-25 10:22
Closing to https://github.com/SynoCommunity/spksrc/issues/2506

**Closed by mreid-tt** 2023-11-25 10:22 UTC
Labels: request, status/duplicate

**Comment by mreid-tt** [comment] 2026-01-14 04:11
hey @ClassicUA, we have a new package for qBittorrent in #6902 available for testing. If you have some time I'd appreciate any feedback before we publish it.
