### ISSUE TITLE
Adding SynoCommunity fails in DSM 6.2.3-25426

### ISSUE THREAD

**Issue by bncmy9** [SynoCommunity/spksrc#4071] opened 2020-07-16 22:00 UTC
Hello,

I use SynoCommunity for a long time without any problems. But after I updated DSM to the new version 6.2.3-25426 today, no packages from SynoCommunity are shown anymore. I tried to re-register the package source https://packages.synocommunity.com/. But now this fails with the error message `Invalid location`.

Does anyone have an idea why this happens?

Thank you!

### Setup
_NAS Model:_ DS716+||
_NAS Architecture:_ braswell 64 bit  (INTEL Celeron N3160 Processor)
_DSM version:_ 6.2.3-25426

### Expected behavior
https://packages.synocommunity.com/ added to package sources list

### Actual behavior
Adding package source https://packages.synocommunity.com/ fails with `invalid location`

![image](https://user-images.githubusercontent.com/49808815/87726804-0d5bf500-c7c0-11ea-8d3e-9f19eb439697.png)

**Comment by fgerrits** [comment] 2020-07-16 22:21
I have the same problem with my DS216+II , removed it, and can't add it again.

Did a full factory reset, still the same error 'invalid location'

**Comment by jx-s** [comment] 2020-07-17 00:50
I have the same problem with my DS918+

**Comment by Diaoul** [comment] 2020-07-17 05:37
I confirm the server seems to be throwing 405 errors on POST requests, effectively affecting new users and some others. I'm investigating this.

**Comment by Diaoul** [comment] 2020-07-17 05:46
Should be fixed, report back if you still experience issues.

**Closed by Diaoul** 2020-07-17 05:46 UTC

**Comment by madmaxnz** [comment] 2020-07-17 06:20
Not fixed I am still getting this erro failed to down load , and this is not he same issue 4071 !!!!!!!!

**Comment by jx-s** [comment] 2020-07-17 06:25
![image](https://user-images.githubusercontent.com/11979569/87755223-34a2d880-c839-11ea-8f7e-cff609e11d3b.png)
fixed
ty!

**Comment by madmaxnz** [comment] 2020-07-17 06:31
my issue is no the same issue! 
![2020-07-17_16-30-21](https://user-images.githubusercontent.com/68407487/87755741-ec8cb180-c84a-11ea-9431-d52b5ef2f146.png)
![2020-07-17_16-30-17](https://user-images.githubusercontent.com/68407487/87755743-ed254800-c84a-11ea-995b-7f8eba782f95.png)

**Comment by bncmy9** [comment] 2020-07-17 07:28
It works for me!
@Diaoul thank you!

**Comment by publicarray** [comment] 2020-07-17 10:59
@Diaoul I don't think the problem is fixed.

**Comment by fgerrits** [comment] 2020-07-17 11:52
For me to, thanks !

**Comment by madmaxnz** [comment] 2020-07-17 21:47
@Diaoul  just check now this is still failing

**Comment by muety** [comment] 2021-08-21 16:37
I'm getting the same error on DSM 6.2.4-25556. Any ideas?

**Comment by lemon99ee** [comment] 2023-12-01 06:19
I'm getting the same error on DSM 6.2.4-25556 Update 7
