### ISSUE TITLE
[request] : Mattermost

### ISSUE THREAD

**Issue by romu70** [SynoCommunity/spksrc#2326] opened 2016-05-17 15:47 UTC
Mattermost is an open source alternative to Slack, so it would be great to have it packaged within our Syno. Thanks.

http://www.mattermost.org/

**Comment by Dr-Bean** [comment] 2016-05-18 06:13
Please use the search before opening an issue as per the [guidelines](https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#package-requests).
Duplicate of https://github.com/SynoCommunity/spksrc/issues/2153.

**Closed by Dr-Bean** 2016-05-18 06:13 UTC

**Comment by romu70** [comment] 2016-05-18 06:51
Yes, my bad, sorry.
