### ISSUE TITLE
Location not correct

### ISSUE THREAD

**Issue by tittano** [SynoCommunity/spksrc#1476] opened 2015-02-07 20:41 UTC
When I try to add the source : http://packages.synocommunity.com/ it is unsuccessful 

![capture d ecran 2015-02-07 a 21 40 32](https://cloud.githubusercontent.com/assets/3253836/6093859/0078edc4-af12-11e4-9acc-d142724e5946.png)

**Comment by mal68** [comment] 2015-02-07 23:42
I have similar, but mine says "invalid location"

**Comment by tittano** [comment] 2015-02-07 23:45
Tes translation of my french words :)

**Comment by tittano** [comment] 2015-02-07 23:49
Yes translation of my french words :)

**Comment by Dr-Bean** [comment] 2015-02-08 10:26
Nothing wrong with the repo that I can see. Check out issue https://github.com/SynoCommunity/spksrc/issues/1470:
- IPv6 is not supported (for now), so make sure IPv4 is enabled;
- You might be running into outdated DNS records (change your DNS server to OpenDNS or Google's servers to check)

**Comment by jerebernard** [comment] 2015-02-09 14:50
Same issue for me : 
nslookup packages.synocommunity.com
nslookup: can't resolve 'packages.synocommunity.com'

Synology> nslookup package.synocommunity.com
Server:    192.168.0.254
Address 1: 192.168.0.254

Name:      package.synocommunity.com
Address 1: 176.31.184.40 synocommunity.com

Maybe an issue with the CNAME ? as when I do http://packages.synocommunity.com/ I'm not able to resolve.

**Comment by Dr-Bean** [comment] 2015-02-09 15:04
Your DNS server has outdated records. Change your DNS server, and check again.

**Comment by jerebernard** [comment] 2015-02-09 15:34
I'm using google dns server

**Comment by Dr-Bean** [comment] 2015-02-09 15:46
Your output shows that you're using `192.168.0.254` as your DNS server, which probably is your router.

You might want to try rebooting your router, or set the Google/OpenDNS DNS server fixed in your Synology (which is what I suggested with my previous comments)
Use this command on your Synology to lookup `packages.synocommunity.com`, using one of the Google DNS servers: 
```nslookup packages.synocommunity.com 8.8.8.8```
(or use `-query 8.8.8.8`, I believe that's necessary on Windows clients)

**Comment by jerebernard** [comment] 2015-02-09 15:54
totally right I have change the DNS of my synology to google DNS and it works
so issue is the DNS server of my internet box.

Thanks Dr-Bean :+1:

**Comment by bzels123** [comment] 2015-02-09 16:04
Hi, I got same issues,
put my Synology DNS to 'automatic'  (so it is directly linked to my internet box 254)
nslookup http://packages.synocommunity.com
Server:    212.27.40.240
Address 1: 212.27.40.240 dns1.proxad.net

nslookup: can't resolve 'http://packages.synocommunity.com'

but the google one gives me the same error:

nslookup http://packages.synocommunity.com 8.8.8.8
Server:    8.8.8.8
Address 1: 8.8.8.8 google-public-dns-a.google.com

nslookup: can't resolve 'http://packages.synocommunity.com'
Thank you for your help

**Comment by bzels123** [comment] 2015-02-09 16:08
Hi so I put Google DNS manually, and I was able to add SynoCommunity packages.What I dont understand is why it works with other packages added without Google DNS, thus my Internet Provider DNS? thank you in advance

**Comment by Dr-Bean** [comment] 2015-02-09 16:33
Ok, some additional explanation then: Recently, the DNS records of Synocommunity were changed to be able to provide packages during server maintenance.
After the maintenance was completed, the records were set to point to the repository server again. Nothing special, happens all the time.

Now, it appears that some of you are using DNS servers that are ignoring the last change. That's not something we can affect in any way, it's up to the DNS servers themselves to make sure their records are up-to-date, or refetch the records if they are out-of-date. Part of the DNS specifications.

As one of the previous comments illustrates: You might be using your router as a DNS (caching) server. Maybe your router is not requesting updates for out-of-date DNS records for some reason.
It's also possible, but less likely, that the DNS server your router is using to fullfill DNS requests isn't doing it's job (which are usually DNS servers provided by your ISP).

What to do: Start with rebooting your router to flush the DNS records it might be keeping. If that does not work, check with your internet provider, see if they can have any network issues that might cause this.
Alternatively, a workaround is to set set one or two public DNS servers in your Synology: Google (8.8.8.8/8.8.4.4), OpenDNS (208.67.222.222, 208.67.220.220)

**Comment by bzels123** [comment] 2015-02-09 16:41
Thank you for the explanations
Kind Regards

**Comment by tittano** [comment] 2015-02-11 13:51
I'm sorry but I don't succeed to do the DNS changes.
Is it possible to explain how we can do this step by step in the synology ?

Thanks in advance,

**Comment by Dr-Bean** [comment] 2015-02-11 15:29
There are probably better places to pose that question than here. Anyway. Open Control Panel>Network. On the `General` tab, activate the checkbox called `Manually configure DNS server`. Then, add in one or two of the DNS servers you want to use, like `8.8.8.8`. Click `Apply`. Done.

Note: Adding a manual DNS server is not a solution, but a workaround. The problem still exists, but you won't be affected, for now. 
However, since it's not something SynoCommunity can control, I'll close this issue.

**Closed by Dr-Bean** 2015-02-11 15:29 UTC

**Comment by Diaoul** [comment] 2015-02-16 22:54
That's really weird people are still experiencing this issue now. DNS records have been updated a few weeks ago now. The correct IP address is **176.31.184.40**. Is it possible the problem is with the way the Package Center resolves the hostname? Maybe it uses others DNS entries internally?

**Comment by Dr-Bean** [comment] 2015-02-16 23:03
As far as I know, DNS records are not cached by linux clients (same with common household routers, for that matter), you'd need a DNS server for that.

One interesting observation is that at least some of the people affected seem to be located in France...maybe an issue with a particular ISP (including subsidiaries, as long as they use the same infrastructure)?

**Comment by Dr-Bean** [comment] 2015-02-16 23:15
One ridiculous idea, but it's all I have ;) Change the TTL for the record (CNAME/A?) to 1 min (to minimize disruption), wait 24h for propagation. Then change the record to a different IP for the duration of the TTL, then set it back to the correct IP :P

**Comment by mal68** [comment] 2015-02-16 23:32
I am in Australia, so not sure about the ISP thing

**Comment by Dr-Bean** [comment] 2015-02-16 23:39
How about this: Did you set a particular DNS server in your Synology, and did that solve it for you? If so, what happens after you set the DNS back to automatic?

**Comment by mal68** [comment] 2015-02-16 23:43
I will try setting one and changing back later as I can't right now

**Comment by mal68** [comment] 2015-02-17 09:00
@Dr-Bean Ok So I set OpenDNS and that resolved it, but when I went back to automatic the issue returned

In terms of your "ridiculous idea" I am not really sure where to change those settings sorry

**Comment by Dr-Bean** [comment] 2015-02-17 09:06
The idea was not meant for you, but for Diaoul, don't worry about it :)

As for your problem, there's some questions that might help in pinpointing a cause: 
- Did you reboot the Synology sometime in the last couple days and/or could you do that now?
- If you're somewhat familiar with the command line (Putty), what happens when you give this command: `nslookup packages.synocommunity.com`?
