### ISSUE TITLE
How to install Deluge on a clean DSM 6.0 that doesn't reset on reboot?

### ISSUE THREAD

**Issue by Vilscon** [SynoCommunity/spksrc#2544] opened 2016-12-05 18:54 UTC
Hi there!

Due to certain issues and a history of migrations between previous Diskstations, I choose to move all data to an external hard drive for a moment, and reinstall DSM with a format of my hard drives. One of my issues was that Deluge, the only torrent for DSM with proxy-support, resets the whole configuration after each Diskstation reboot (i.e. update, error). 

I'm aware of the issues with SynoCommunity packages and DSM 6.0, regarding different root access and such. However, I'm not actively following this channel and was hoping for either a solution for this issue or a guide that helps me correctly installing Deluge and all SynoCommunity packages, that don't reset on every reboot.

I repeat: I'm on a clean install of the latest DSM 6.0 (update 5?) and haven't installed any package, nor configured any user account, such as the 'apps' administrator.

Looking forward to your suggestions!

--

### Setup
_Package Name:_Deluge
_Package Version:_Latest, as of 5th of december 2016

_NAS Model:_ DS216+
_NAS Architecture:_ Intel
_DSM version:_ DSM 6.0 update 5

**Comment by Dr-Bean** [comment] 2016-12-06 15:31
Duplicate of https://github.com/SynoCommunity/spksrc/issues/2325. I'll close this one, as the comment there is still valid unfortunately.

**Closed by Dr-Bean** 2016-12-06 15:31 UTC
