### ISSUE TITLE
ruTorrent not saving settings

### ISSUE THREAD

**Issue by kzendra** [SynoCommunity/spksrc#2205] opened 2016-03-24 09:39 UTC
DSM216 v5.2
I open settings of ruTorrent in web page, change port in connection tab and press OK.
After that, there is still yellow exclamation mark showing that I'm not connectable (router is configured proprely). I place mouse pointer over exclamation mark and it shows me port from default random range. 

After restarting ruTorrent (or entire DSM), settings are back to default port range.

**Comment by GoodOmens83** [comment] 2016-03-24 11:23
ruTorrent will not save settings to the rtorrent.rc file upon a restart.  This is by design - to change that behavior refer to their git page.

.rtorrent.rc (notice the . in front of the file, it might be hidden) is stored in /volume1/@appstore/rutorrent/var/ Make your changes there.

**Comment by kzendra** [comment] 2016-03-25 06:59
It may be by design, but it's still an issue. At least, once you press OK on settings page, information that settings will not be saved and why should be displayed.

**Comment by GoodOmens83** [comment] 2016-03-25 11:05
Not disagreeing with you but we don't develop ruTorrent. Open an issue here: https://github.com/Novik/ruTorrent

**Comment by kzendra** [comment] 2016-03-25 11:06
A, sorry, did not know that :-)

**Comment by Dr-Bean** [comment] 2016-04-01 07:43
Closing then, as it's an upstream design decision.

**Closed by Dr-Bean** 2016-04-01 07:43 UTC
