### ISSUE TITLE
[Package Request] Komga

### ISSUE THREAD

**Issue by tatundria** [SynoCommunity/spksrc#6181] opened 2024-07-27 03:23 UTC
### Software Name

Komga

### Brief Description

Komga is a Media server for comics/mangas/BDs/magazines/eBooks with API and OPDS support

### Website

https://komga.org/

### Build/Installation documentation

https://komga.org/docs/category/installation/

### Source code

https://github.com/gotson/komga

### OpenSource License

MIT

**Comment by hgy59** [comment] 2024-07-27 11:51
duplicate of #5391

**Closed** 2024-10-17 15:01 UTC
Labels: request, status/duplicate
