### ISSUE TITLE
FFMPEG 4.2.1 - Cannot convert .mp4 to .jpg

### ISSUE THREAD

**Issue by mnervik** [SynoCommunity/spksrc#3862] opened 2020-01-21 21:29 UTC
### Setup
FFMPEG 
4.2.1-23

DS1517+
avoton (x64)
DSM 6.2.2

### Expected behavior
ffmpeg should create an image from video.mp4 at frame-count 100

### Actual behavior
On version 4.2.1-23 the script creates an empty file, and returns ```Error while opening decoder for input stream #0:1 : Operation not permitted```

- The command works if I downgrade to the previous synoCommunity-ffmpeg release
- The command work on an windows machine running ffmpeg 4.2.1

### Steps to reproduce

1. Install and open GateOne (or connect to the NAS using ssh)
2. ```cd``` into the shared folder
   - The shared folder has a video-file called video.mp4 inside it, that is at least 100 frames long
3. use this command ```/volume1/@appstore/ffmpeg/bin/ffmpeg -ss 100 -i video.mp4 -frames:v 1 -f mjpeg video.jpg -y```

**Comment by th0ma7** [comment] 2020-01-22 13:27
Can you provide the full log ouput?

**Comment by mnervik** [comment] 2020-01-22 13:50
```
mnervik@ds1517:/volume1/testshare$ ls
@eaDir  video.mp4
mnervik@ds1517:/volume1/testshare$ /volume1/@appstore/ffmpeg/bin/ffmpeg -ss 100 -i video.mp4 -frames:v 1 -f mjpeg video.jpg -y
ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 4.9.3 (crosstool-NG 1.20.0) 20150311 (prerelease)
  configuration: --target-os=linux --cross-prefix=/spksrc/toolchains/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu- --prefix=/var/packages/ffmpeg/target --extra-cflags=-I/spksrc/spk/ffmpeg/work-x64-6.1/install/var/packages/ffmpeg/target/include --extra-ldflags=-L/spksrc/spk/f
fmpeg/work-x64-6.1/install/var/packages/ffmpeg/target/lib --extra-libs='-lxml2 -ldl' --pkg-config=/usr/bin/pkg-config --ranlib=/spksrc/toolchains/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ranlib --enable-cross-compile --enable-rpath --enable-pic --enable-shared --enable-g
pl --enable-fontconfig --enable-libass --enable-libbluray --enable-avresample --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libsoxr --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-gnutls --disable-debug --disable-doc --di
sable-static --enable-libfdk-aac --enable-nonfree --extra-cflags='-DSYNO_VIDEOSTATION -DSYNO_AUDIOSTATION -DSYNO_MEDIASERVER -DSYNO_DSM' --extra-cflags=-fno-if-conversion --enable-libaom --arch=x86_64 --enable-vaapi --enable-libmfx
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'video.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 1970-01-01T00:00:00.000000Z
    title           : Sintel
    encoder         : Lavf52.78.5
    copyright       : (c) copyright Blender Foundation | durian.blender.org
    description     : Sintel open movie project
  Duration: 00:14:48.06, start: 0.000000, bitrate: 1164 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1024x436 [SAR 1:1 DAR 256:109], 718 kb/s, 24 fps, 24 tbr, 24 tbn, 48 tbc (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 440 kb/s (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
Error while opening decoder for input stream #0:0 : Operation not permitted
```

**Comment by th0ma7** [comment] 2020-01-22 14:03
Having a video you can share (or one already freely available online) so I can reproduce the issue on my side?

**Comment by mnervik** [comment] 2020-01-22 20:24
- I used the "Sintel" movie (1024x436) and renamed it to ```video.mp4```
  - all downloads are avaliable from https://durian.blender.org/download/
- The exact file I used can be downloaded [here](http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4), but it can also be found [here](http://mirrorblender.top-ix.org/movies/sintel-1024-surround.mp4) and [here](http://ftp.akl.lt/Video/Sintel/sintel-1024-surround.mp4)

**Comment by kc6108** [comment] 2020-01-23 06:18
I downloaded mp4 file and ran the same command:

```
/volume1/@appstore/ffmpeg/bin/ffmpeg -ss 100 -i sintel-1024-surround.mp4 -frames:v 1 -f mjpeg video.jpg -y
```

Here's the output:

```
ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 4.9.3 (crosstool-NG 1.20.0) 20150311 (prerelease)
  configuration: --target-os=linux --cross-prefix=/spksrc/toolchains/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu- --prefix=/var/packages/ffmpeg/target --extra-cflags=-I/spksrc/spk/ffmpeg/work-x64-6.1/install/var/packages/ffmpeg/target/include --extra-ldflags=-L/spksrc/spk/ffmpeg/work-x64-6.1/install/var/packages/ffmpeg/target/lib --extra-libs='-lxml2 -ldl' --pkg-config=/usr/bin/pkg-config --ranlib=/spksrc/toolchains/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ranlib --enable-cross-compile --enable-rpath --enable-pic --enable-shared --enable-gpl --enable-fontconfig --enable-libass --enable-libbluray --enable-avresample --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libsoxr --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-gnutls --disable-debug --disable-doc --disable-static --enable-libfdk-aac --enable-nonfree --extra-cflags='-DSYNO_VIDEOSTATION -DSYNO_AUDIOSTATION -DSYNO_MEDIASERVER -DSYNO_DSM' --extra-cflags=-fno-if-conversion --enable-libaom --arch=x86_64 --enable-vaapi --enable-libmfx
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'sintel-1024-surround.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 1970-01-01T00:00:00.000000Z
    title           : Sintel
    encoder         : Lavf52.78.5
    copyright       : (c) copyright Blender Foundation | durian.blender.org
    description     : Sintel open movie project
  Duration: 00:14:48.06, start: 0.000000, bitrate: 1164 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1024x436 [SAR 1:1 DAR 256:109], 718 kb/s, 24 fps, 24 tbr, 24 tbn, 48 tbc (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 440 kb/s (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
Press [q] to stop, [?] for help
[swscaler @ 0x2173180] deprecated pixel format used, make sure you did set range correctly
Output #0, mjpeg, to 'video.jpg':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    description     : Sintel open movie project
    title           : Sintel
    copyright       : (c) copyright Blender Foundation | durian.blender.org
    encoder         : Lavf58.29.100
    Stream #0:0(und): Video: mjpeg, yuvj420p(pc), 1024x436 [SAR 1:1 DAR 256:109], q=2-31, 200 kb/s, 24 fps, 24 tbn, 24 tbc (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : VideoHandler
      encoder         : Lavc58.54.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
frame=    1 fps=0.0 q=3.4 Lsize=      19kB time=00:00:00.04 bitrate=3745.7kbits/s speed=0.229x    
video:19kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
```

![video](https://user-images.githubusercontent.com/1409652/72961168-c98ab480-3d75-11ea-911f-ed32cb2eabb4.jpg)

**Comment by kc6108** [comment] 2020-01-23 06:30
DS1812+

**Comment by mnervik** [comment] 2020-01-23 23:14
I had some spare time today, so I tried the same command on my older **DS415play**. It does not work there either.
### Input
```
/volume1/@appstore/ffmpeg/bin/ffmpeg -ss 100 -i sintel-1024-surround.mp4 -frames:v 1 -f mjpeg video.jpg -y
```
### Output
```
ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 4.9.3 (crosstool-NG 1.20.0) 20150311 (prerelease)
  configuration: --target-os=linux --cross-prefix=/spksrc/toolchains/syno-evansport-6.1/work/i686-pc-linux-gnu/bin/i686-pc-linux-gnu- --prefix=/var/packages/ffmpeg/target
 --extra-cflags=-I/spksrc/spk/ffmpeg/work-evansport-6.1/install/var/packages/ffmpeg/target/include --extra-ldflags=-L/spksrc/spk/ffmpeg/work-evansport-6.1/install/var/pac
kages/ffmpeg/target/lib --extra-libs='-lxml2 -ldl' --pkg-config=/usr/bin/pkg-config --ranlib=/spksrc/toolchains/syno-evansport-6.1/work/i686-pc-linux-gnu/bin/i686-pc-linu
x-gnu-ranlib --enable-cross-compile --enable-rpath --enable-pic --enable-shared --enable-gpl --enable-fontconfig --enable-libass --enable-libbluray --enable-avresample --
enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libsoxr --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable
-gnutls --disable-debug --disable-doc --disable-static --enable-libfdk-aac --enable-nonfree --extra-cflags='-DSYNO_VIDEOSTATION -DSYNO_AUDIOSTATION -DSYNO_MEDIASERVER -DS
YNO_DSM' --extra-cflags=-fno-if-conversion --enable-libaom --arch=i386
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'sintel-1024-surround.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 1970-01-01T00:00:00.000000Z
    title           : Sintel
    encoder         : Lavf52.78.5
    copyright       : (c) copyright Blender Foundation | durian.blender.org
    description     : Sintel open movie project
  Duration: 00:14:48.06, start: 0.000000, bitrate: 1164 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1024x436 [SAR 1:1 DAR 256:109], 718 kb/s, 24 fps, 24 tbr, 24 tbn, 48 tbc (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 440 kb/s (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
Error while opening decoder for input stream #0:0 : Operation not permitted
```

**Comment by BenjV** [comment] 2020-01-24 11:44
I tried it on my DS116 (arm cpu) and it worked fine.
I also tried it on my windows PC and it also worked fine.

So it seems to be a problem with the build for X64 Nasses.

**Comment by claw111** [comment] 2020-01-24 12:31
I tried it using the sintel video on my **DS415Play** (6.1 evansport) and it failed, so I won't report the log here - it's previously noted in a comment above for the same model.

Incidentally, I have experienced the `Error while opening decoder for input stream #0:0 : Operation not permitted` with a number of different files that have either **video** or **audio** steams at 0:0.  I'll have to downgrade to 4.1-11 in the meantime.  Happy to provide further info or testing if required.

**Comment by reformhaus** [comment] 2020-01-25 18:05
Same Problem on DS218+.
Intel CPU.
DSM 6.2.2.

Ho can i perform a manually downgrade to privious version?

`sysadmin@DS218_NAS:/volume1/Ablage/FFMPEG_Watchfolder/IN$ /volume1/@appstore/ffmpeg/bin/ffmpeg -i TEST.ts -f null -
ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 4.9.3 (crosstool-NG 1.20.0) 20150311 (prerelease)
  configuration: --target-os=linux --cross-prefix=/spksrc/toolchains/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu- --prefix=/var/packages/ffmpeg/target --extra-cflags=-I/spksrc/spk/ffmpeg/work-x64-6.1/install/var/packages/ffmpeg/target/include --extra-ldflags=-L/spksrc/spk/ffmpeg/work-x64-6.1/install/var/packages/ffmpeg/target/lib --extra-libs='-lxml2 -ldl' --pkg-config=/usr/bin/pkg-config --ranlib=/spksrc/toolchains/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ranlib --enable-cross-compile --enable-rpath --enable-pic --enable-shared --enable-gpl --enable-fontconfig --enable-libass --enable-libbluray --enable-avresample --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libsoxr --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-gnutls --disable-debug --disable-doc --disable-static --enable-libfdk-aac --enable-nonfree --extra-cflags='-DSYNO_VIDEOSTATION -DSYNO_AUDIOSTATION -DSYNO_MEDIASERVER -DSYNO_DSM' --extra-cflags=-fno-if-conversion --enable-libaom --arch=x86_64 --enable-vaapi --enable-libmfx
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[h264 @ 0x2168340] SPS unavailable in decode_picture_timing
[h264 @ 0x2168340] non-existing PPS 0 referenced
[h264 @ 0x2168340] SPS unavailable in decode_picture_timing
[h264 @ 0x2168340] non-existing PPS 0 referenced
[h264 @ 0x2168340] decode_slice_header error
[h264 @ 0x2168340] no frame!
[h264 @ 0x2168340] SPS unavailable in decode_picture_timing
[h264 @ 0x2168340] non-existing PPS 0 referenced
[h264 @ 0x2168340] SPS unavailable in decode_picture_timing
[h264 @ 0x2168340] non-existing PPS 0 referenced
[h264 @ 0x2168340] decode_slice_header error
[h264 @ 0x2168340] no frame!
[h264 @ 0x2168340] SPS unavailable in decode_picture_timing
[h264 @ 0x2168340] non-existing PPS 0 referenced
[h264 @ 0x2168340] SPS unavailable in decode_picture_timing
[h264 @ 0x2168340] non-existing PPS 0 referenced
[h264 @ 0x2168340] decode_slice_header error
[h264 @ 0x2168340] no frame!
[mpegts @ 0x2123340] start time for stream 7 is not set in estimate_timings_from_pts
[mpegts @ 0x2123340] PES packet size mismatch
    Last message repeated 4 times
[mpegts @ 0x2123340] Could not find codec parameters for stream 6 (Unknown: none ([5][0][0][0] / 0x0005)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mpegts, from 'TEST.ts':
  Duration: 00:00:52.21, start: 63155.525756, bitrate: 10686 kb/s
  Program 1
    Metadata:
      service_name    : 3sat HD
      service_provider: Unitymedia
    Stream #0:0[0x229]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn, 100 tbc
    Stream #0:1[0x22a](deu): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 256 kb/s
    Stream #0:2[0x22b](deu): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 192 kb/s (visual impaired) (descriptions)
    Stream #0:3[0x22c](deu): Audio: ac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 448 kb/s
    Stream #0:4[0x22d](mul): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 192 kb/s
    Stream #0:5[0x22e](deu): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006)
    Stream #0:6[0x655]: Unknown: none ([5][0][0][0] / 0x0005)
    Stream #0:7[0x669](deu): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006) (hearing impaired)
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> wrapped_avframe (native))
  Stream #0:1 -> #0:1 (mp2 (native) -> pcm_s16le (native))
Error while opening decoder for input stream #0:0 : Operation not permitted`

**Comment by reformhaus** [comment] 2020-01-25 18:25
Package Name: ffmpeg
Package Version: 4.2.1-23

NAS Model: DS218+
NAS Architecture: apollolake (x64)
DSM version: DSM 6.2.2-24922 Update 4

**Input**
```/volume1/@appstore/ffmpeg/bin/ffmpeg -ss 100 -i sintel-1024-surround.mp4 -frames:v 1 -f mjpeg video.jpg -y```

**Output**
```ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 4.9.3 (crosstool-NG 1.20.0) 20150311 (prerelease)
  configuration: --target-os=linux --cross-prefix=/spksrc/toolchains/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu- --prefix=/var/packages/ffmpeg/target --extra-cflags=-I/spksrc/spk/ffmpeg/work-x64-6.1/install/var/packages/ffmpeg/target/include --extra-ldflags=-L/spksrc/spk/ffmpeg/work-x64-6.1/install/var/packages/ffmpeg/target/lib --extra-libs='-lxml2 -ldl' --pkg-config=/usr/bin/pkg-config --ranlib=/spksrc/toolchains/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ranlib --enable-cross-compile --enable-rpath --enable-pic --enable-shared --enable-gpl --enable-fontconfig --enable-libass --enable-libbluray --enable-avresample --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libsoxr --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-gnutls --disable-debug --disable-doc --disable-static --enable-libfdk-aac --enable-nonfree --extra-cflags='-DSYNO_VIDEOSTATION -DSYNO_AUDIOSTATION -DSYNO_MEDIASERVER -DSYNO_DSM' --extra-cflags=-fno-if-conversion --enable-libaom --arch=x86_64 --enable-vaapi --enable-libmfx
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'sintel-1024-surround.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 1970-01-01T00:00:00.000000Z
    title           : Sintel
    encoder         : Lavf52.78.5
    copyright       : (c) copyright Blender Foundation | durian.blender.org
    description     : Sintel open movie project
  Duration: 00:14:48.06, start: 0.000000, bitrate: 1164 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1024x436 [SAR 1:1 DAR 256:109], 718 kb/s, 24 fps, 24 tbr, 24 tbn, 48 tbc (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 440 kb/s (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
Error while opening decoder for input stream #0:0 : Operation not permitted```

**Comment by mnervik** [comment] 2020-01-25 19:56
> Same Problem on DS218+.
> Intel CPU.
> DSM 6.2.2.
> 
> Ho can i perform a manually downgrade to privious version?
> 
> `sysadmin@DS218_NAS:/volume1/Ablage/FFMPEG_Watchfolder/IN$ /volume1/@appstore/ffmpeg/bin/ffmpeg -i TEST.ts -f null - ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers built with gcc 4.9.3 (crosstool-NG 1.20.0) 20150311 (prerelease) configuration: --target-os=linux --cross-prefix=/spksrc/toolchains/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu- --prefix=/var/packages/ffmpeg/target --extra-cflags=-I/spksrc/spk/ffmpeg/work-x64-6.1/install/var/packages/ffmpeg/target/include --extra-ldflags=-L/spksrc/spk/ffmpeg/work-x64-6.1/install/var/packages/ffmpeg/target/lib --extra-libs='-lxml2 -ldl' --pkg-config=/usr/bin/pkg-config --ranlib=/spksrc/toolchains/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ranlib --enable-cross-compile --enable-rpath --enable-pic --enable-shared --enable-gpl --enable-fontconfig --enable-libass --enable-libbluray --enable-avresample --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libsoxr --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-gnutls --disable-debug --disable-doc --disable-static --enable-libfdk-aac --enable-nonfree --extra-cflags='-DSYNO_VIDEOSTATION -DSYNO_AUDIOSTATION -DSYNO_MEDIASERVER -DSYNO_DSM' --extra-cflags=-fno-if-conversion --enable-libaom --arch=x86_64 --enable-vaapi --enable-libmfx libavutil 56. 31.100 / 56. 31.100 libavcodec 58. 54.100 / 58. 54.100 libavformat 58. 29.100 / 58. 29.100 libavdevice 58. 8.100 / 58. 8.100 libavfilter 7. 57.100 / 7. 57.100 libavresample 4. 0. 0 / 4. 0. 0 libswscale 5. 5.100 / 5. 5.100 libswresample 3. 5.100 / 3. 5.100 libpostproc 55. 5.100 / 55. 5.100 [h264 @ 0x2168340] SPS unavailable in decode_picture_timing [h264 @ 0x2168340] non-existing PPS 0 referenced [h264 @ 0x2168340] SPS unavailable in decode_picture_timing [h264 @ 0x2168340] non-existing PPS 0 referenced [h264 @ 0x2168340] decode_slice_header error [h264 @ 0x2168340] no frame! [h264 @ 0x2168340] SPS unavailable in decode_picture_timing [h264 @ 0x2168340] non-existing PPS 0 referenced [h264 @ 0x2168340] SPS unavailable in decode_picture_timing [h264 @ 0x2168340] non-existing PPS 0 referenced [h264 @ 0x2168340] decode_slice_header error [h264 @ 0x2168340] no frame! [h264 @ 0x2168340] SPS unavailable in decode_picture_timing [h264 @ 0x2168340] non-existing PPS 0 referenced [h264 @ 0x2168340] SPS unavailable in decode_picture_timing [h264 @ 0x2168340] non-existing PPS 0 referenced [h264 @ 0x2168340] decode_slice_header error [h264 @ 0x2168340] no frame! [mpegts @ 0x2123340] start time for stream 7 is not set in estimate_timings_from_pts [mpegts @ 0x2123340] PES packet size mismatch Last message repeated 4 times [mpegts @ 0x2123340] Could not find codec parameters for stream 6 (Unknown: none ([5][0][0][0] / 0x0005)): unknown codec Consider increasing the value for the 'analyzeduration' and 'probesize' options Input #0, mpegts, from 'TEST.ts': Duration: 00:00:52.21, start: 63155.525756, bitrate: 10686 kb/s Program 1 Metadata: service_name : 3sat HD service_provider: Unitymedia Stream #0:0[0x229]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn, 100 tbc Stream #0:1[0x22a](deu): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 256 kb/s Stream #0:2[0x22b](deu): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 192 kb/s (visual impaired) (descriptions) Stream #0:3[0x22c](deu): Audio: ac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 448 kb/s Stream #0:4[0x22d](mul): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 192 kb/s Stream #0:5[0x22e](deu): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006) Stream #0:6[0x655]: Unknown: none ([5][0][0][0] / 0x0005) Stream #0:7[0x669](deu): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006) (hearing impaired) Stream mapping: Stream #0:0 -> #0:0 (h264 (native) -> wrapped_avframe (native)) Stream #0:1 -> #0:1 (mp2 (native) -> pcm_s16le (native)) Error while opening decoder for input stream #0:0 : Operation not permitted`


1. Uninstall the package from your device
2. Find Find out what achitecture you need: https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model
3. Download the file with the same achitecture: https://synocommunity.com/package/ffmpeg
4. Manually install the .spk file on your device

**Comment by th0ma7** [comment] 2020-01-28 23:56
Having a new ffmpeg package ready for testing: `4.2.2-24`
Hopefully this issue will be solved with this:
* https://github.com/th0ma7/synology/tree/master/packages

**Comment by reformhaus** [comment] 2020-01-29 09:51
> Having a new ffmpeg package ready for testing: `4.2.2-24`
> Hopefully this issue will be solved with this:
> 
> * https://github.com/th0ma7/synology/tree/master/packages

Fixed my issues on  DS218+ (Without Videostation installed)

**Comment by th0ma7** [comment] 2020-01-29 10:03
Great news! Thnx a lot for the feedback @reformhaus .
Let's wait for @mnervik and see how things goes before closing.

**Comment by claw111** [comment] 2020-01-29 12:21
> Having a new ffmpeg package ready for testing: `4.2.2-24`
> Hopefully this issue will be solved with this:
> 
>     * https://github.com/th0ma7/synology/tree/master/packages

This test package has resolved the issues on my **DS415Play** (6.1 evansport).  How's it for you @mnervik ?

**Comment by mnervik** [comment] 2020-01-29 12:32
Test package working on both **ds415play** and **ds1517+**

**Comment by th0ma7** [comment] 2020-01-31 12:08
This is great news, thnx guys for testing!
Closing the bug as now fixed.
Will eventually be part of next official round of build.
Cheers!

**Closed by th0ma7** 2020-01-31 12:08 UTC

**Comment by ThomasDalla** [comment] 2020-03-31 18:38
Confirmed resolved on a DS216J as well, thanks.
