### ISSUE TITLE
Please update NZBGet to 17.0

### ISSUE THREAD

**Issue by joeyd2** [SynoCommunity/spksrc#2420] opened 2016-07-27 18:15 UTC
Please update NZBGet to 17.0

**Comment by rvdlaar** [comment] 2016-07-29 14:31
What he said

**Comment by 1shez** [comment] 2016-07-30 09:46
What he said

**Comment by benjmd** [comment] 2016-07-31 00:49
What he said

**Comment by KaraokeStu** [comment] 2016-08-03 08:12
Updated as per request, pull request pending

**Comment by rvdlaar** [comment] 2016-08-03 12:00
Awesome. Thanks.

**Comment by KaraokeStu** [comment] 2016-08-03 21:27
No problem

**Comment by KaraokeStu** [comment] 2016-08-04 15:28
I have closed the pull request due to problems with requiring GCC 4.9 or 5.0

**Comment by KaraokeStu** [comment] 2016-08-04 15:52
Please close this issue - it is a duplicate of https://github.com/SynoCommunity/spksrc/issues/2185

**Comment by joeyd2** [comment] 2016-08-04 22:45
So it isn't getting updated? :(

**Comment by KaraokeStu** [comment] 2016-08-05 13:27
It will be supported, but only from DSM 6.x - unless someone knows how to compile GCC 4.9 for DSM 5.x.
And DSM 6.x still has its own set of issues working with custom packages

**Comment by Thaek** [comment] 2016-08-08 07:54
Any news on this? :-) NZBGet 17 was released almost two weeks now and there is a feature that I requested that was implemented in 17, would be very nice if I could test it.

So if I have DSM 6.x can I expect this to be updated?

**Comment by Thaek** [comment] 2016-08-08 08:08
Someone backported NZBGET 17 to work with C++ 11, maybe this will help you for DSM 5.x? http://nuxref.com/2016/08/03/nzbget-v17-centos-7/

**Comment by cytec** [comment] 2016-08-09 18:33
seems like that got already merged (see https://github.com/nzbget/nzbget/pull/256) and is flagged for 17.1 so let's wait for 17.1 to be released (and hopfeully compile for DSM 5x)

**Comment by Thaek** [comment] 2016-08-09 21:10
Wait for 17.1? ;-/ ugg that could take ages, it's not like they create releases every month.  :-(

**Comment by KaraokeStu** [comment] 2016-08-09 21:14
Feel free to amend the package yourself and create the relevant patch for it, however I don't think it would be worth the double effort of us doing that, then undoing it once 17.1 is released.

I wouldn't think it'll be too long for 17.1, given that it will be likely a fair few bugs will have crept  into the new codebase

**Comment by cytec** [comment] 2016-08-10 17:20
@schumi2004 have you tried ncursesw?

**Comment by schumi2004** [comment] 2016-08-11 08:27
@cytec doesn't seem to make any difference.

**Comment by cytec** [comment] 2016-08-11 08:38
@schumi2004 strange... what about `--with-libcurses-includes` and/or `--with-libcurses-libraries` and provide the path to include/lib where curses is located?

**Comment by schumi2004** [comment] 2016-08-11 10:48
I'm not a programmer so i'm not 100% sure where to place these options. 
Should that be something like this? 
CONFIGURE_ARGS = --with-libcurses-includes=$(WORK_DIR)/../../../ncurses-6.0/lib

**Comment by cytec** [comment] 2016-08-11 13:04
something like this should work i think:

`
CONFIGURE_ARGS = --with-libcurses-includes="$(WORK_DIR)/install$(INSTALL_PREFIX)/include" --with-libcurses-libraries="$(WORK_DIR)/install$(INSTALL_PREFIX)/lib"
`

**Comment by schumi2004** [comment] 2016-08-11 13:31
Thank you very much, that worked ;)
I don't think it's usefull to submit a PR for this since there is something about DSM6 toolchains right?

/home/openelec/github/spksrc/spk/nzbget-testing/../../packages/nzbget-testing_alpine-6.0_17.1~testing-12.spk --group=root --owner=root package.tgz INFO PACKAGE_ICON.PNG PACKAGE_ICON_120.PNG scripts WIZARD_UIFILES)
make[1]: Leaving directory '/home/openelec/github/spksrc/spk/nzbget-testing'
03:28:49 {nzbget} ~/github/spksrc/spk/nzbget-testing$

**Comment by cytec** [comment] 2016-08-11 13:42
well... personally i think you can go ahead and create a PR if you got it working... afaik the DSM 6 problem still isn't solved and will require some work on more package... so no need to wait for the fix

**Comment by schumi2004** [comment] 2016-08-11 14:09
I'll see what i can do. This also means i need to add all DMS6 toolchains available. I think i'll split them in 2 separate PR's

**Comment by cytec** [comment] 2016-08-11 15:02
ah... you're talking about 17.1 with DSM 6 Toolchains? thought you where compiling with 5.x ... forget what i said then :D

**Comment by Thaek** [comment] 2016-09-07 08:34
NZBGET 17.1 was released two days ago which allows to compile with GCC 4.8 with the following configure command:
CXXFLAGS="-std=c++11 -O2 -s" ./configure --disable-cpp-check

Can someone compile and update Synocommunity to 17.1?

**Comment by KaraokeStu** [comment] 2016-09-07 08:36
I'll have a quick look and see if I can get it to compile, however I'll need to check to see if I can make it work for 5.x too, as otherwise I'll need to specify a minimum DSM version and it might be best to create a new package for 6.x - what do you think @cytec and @Dr-Bean ?

**Comment by KaraokeStu** [comment] 2016-09-07 09:03
I've tested and this still does not compile using the 5.x toochains, so still can't be done within the framework as it stands until we at least have 6.x toolchains

**Comment by hugbug** [comment] 2016-09-19 09:53
For all waiting - a reminder that nzbget can be installed on most devices via official installer package as documented in [NZBGet - Installation on Linux](https://github.com/nzbget/nzbget/wiki/Installation-on-Linux).

One thing you would need to figure out on your own is how to make it start automatically on boot.

**Comment by Ashkaan** [comment] 2016-09-20 06:48
> For all waiting - a reminder that nzbget can be installed on most devices via official installer package as documented in NZBGet - Installation on Linux.

Yes, but an spk would be so much nicer because it will include the boot stuff too.

**Comment by Thaek** [comment] 2016-10-04 20:05
Still waiting here. Guess I will have to go with the manual installation of the binaries and stop using synocommunity - anyway was nice while it lasted.

**Comment by Ashkaan** [comment] 2016-10-04 20:10
No, don't give up!  There must be someone still interested in working on this!

It sounds like there's an issue supporting old version of DSM.  Can you guys make one that works on 6+?

**Comment by doppelhelix23** [comment] 2016-10-04 22:38
any news on that package?

**Comment by schumi2004** [comment] 2016-10-04 22:56
I will post a link tomorrow of packages that succeeded compiling against dsm6 tool chain. A few failed but didn't checked why they failed.

**Comment by KaraokeStu** [comment] 2016-10-07 15:53
Thanks for the effort @schumi2004

**Comment by schumi2004** [comment] 2016-10-07 19:06
Thanks for the reminder, totally forgot to upload files. Compiling latest git version now, 18.0 if i'm correct will place them in same folder. Will also check what happened with other architectures on why they failed.
https://www.dropbox.com/sh/0vu56iaifllqoga/AAB9zZfCUDwIXX9rB3cBaGgXa?dl=0

**Comment by Ashkaan** [comment] 2016-10-07 22:34
Thank you, @schumi2004 

I can't get it to run on my Avaton system (DS1815+).  I've tried 18, trying 17.1 now.  Anyone else having issues?

**Comment by schumi2004** [comment] 2016-10-07 23:23
Do you get any error or it just wont start via package manager?
Could you try to launch it manually?
/var/packages/nzbget-testing/scripts/start-stop-status start

**Comment by Ashkaan** [comment] 2016-10-07 23:38
It loads like it's going to run (no error) and then just simply never starts.

I tried launching manually and it has no output.  It looks like it thinks it started, but it never actually starts.

**Comment by schumi2004** [comment] 2016-10-08 00:12
That's strange, I'm running the same version on a DS715. 
It's not running twice? ps aux | grep nzbget

**Comment by Ashkaan** [comment] 2016-10-10 00:00
No, not running twice.

Anyone else try it?  Is it working for others?

**Comment by schumi2004** [comment] 2016-10-10 06:55
I think I know what is happening. Are you doing a clean install? If yes then the user could be missing in your shadow file.

**Comment by schumi2004** [comment] 2016-10-10 06:56
Will upload stable version later today.

**Comment by TomVanHaver** [comment] 2016-10-24 17:32
@schumi2004 
Hi, 
Since i heard that unpacking recent packages is incompatible with my current nzb version (16.4 on dsm 6+) i am interested in updating nzbget.

Can i download/install the .spk on the dropbox link above (or somewhere else?)
If not, are there any instructions on how to create such a .spk package ?

Thank you,
Tom.

**Comment by schumi2004** [comment] 2016-10-24 18:01
You can download from DB link above, there aren't any official packages that I'm aware of. 
I would suggest to pick 17.1 stable. Not all architectures are there yet, didn't looked at others why they failed compiling.

**Comment by TomVanHaver** [comment] 2016-10-24 19:02
I have an ds214+ with an Marvell Armada XP cpu, so i guess i need the armada package, correct ?
If this does not work as expected, can i just install the community package again  ?

Is an official 17.x release imminent ?

**Comment by schumi2004** [comment] 2016-10-24 19:35
I think your out of luck since armadaxp failed to compile (it's not on my DB)
Will check tomorow what is wrong with armadaxp.
17.1 is official yes http://nzbget.net/download/
I updated version number also so you can't downgrade, you then need to remove and re-install it. 
Make backups before you proceed then you can easily go back.

**Comment by TomVanHaver** [comment] 2016-10-25 19:01
@schumi2004 Thank you very much for the effort.

Please do not be offended, but i do not know/trust you enough to install the .spk you have build.
What is your relation to the nzb project ? Is it necessary to install the 17.1 update in order to download/process the "latest finds"?
If so, do you have an idea when the official release will be? Or can you point me to a guide to build a version for myself ?

Again thank you very much for your help in advance.

**Comment by schumi2004** [comment] 2016-10-25 21:38
I understand the trust thing. I have no relation to SynoCommunity or nzbget besides getting things to work for my own situation, improve or find bugs and when I can submit things to help community. 
You can drop me an email (my nick @gmail) and I'll send you my source or wait until I have uploaded it on my github and you can validate code and compile it yourself ;)

**Comment by Limb** [comment] 2016-11-12 23:03
@schumi2004 Can you post the changes you made to compile 17.1 to github?

**Comment by schumi2004** [comment] 2016-11-13 17:28
Pushed it to my github (nzbget branch), to lazy to squash commits though.

**Comment by hagabla** [comment] 2016-12-11 15:47
Is it fair to assume that nzbget is no longer supported/provided by synocommunity? Do i have to switch to a different downloader?

**Comment by doppelhelix23** [comment] 2016-12-11 18:46
Hey hagabla
I'll be honest with you: if your are an experienced linux user, install it yourself directly on your Synology ([link](https://github.com/nzbget/nzbget/wiki/Installation-on-Linux)). You will even get direct regular updates. Everything else is wasted time. Sorry. Stay independent!

**Comment by Thaek** [comment] 2016-12-11 18:49
@hagabla Yes NZBGet on SynoCommunity seams pretty dead to me. I would advise you to do a Automatic install as I did. It is described here: https://github.com/nzbget/nzbget/wiki/Installation-on-Linux, it's very straight forward (just 2 commands) and you will also have auto update afterwards. The only thing you have to do manually is go to the task scheduler and configure a user defined script so NZBGet starts on startup.

**Comment by Dr-Bean** [comment] 2016-12-11 18:50
:/ You do realise that SynoCommunity is just a bunch of enthusiasts who volunteer their free time to make packages, right?

**Comment by hagabla** [comment] 2016-12-11 18:52
Yes, and it is very much appreciated but how is it wrong to ask?

**Comment by Dr-Bean** [comment] 2016-12-11 19:04
It's not wrong to ask, but that's not what my comment was about. I was looking at ''no longer provided', 'wasted time', 'stay independent', 'pretty dead'...pretty harsh, considering this is our own bugtracker ;)

**Comment by hagabla** [comment] 2016-12-11 19:10
Well you provided up-to-date nzbget packages, now you don't. So it is no longer provided. I don't see any harshness in my post nor was any intended. Sorry if it came across that way.
Seems i am going to switch to the sabnzbd package provided by synocommunity 
¯\_(ツ)_/¯

**Comment by schumi2004** [comment] 2016-12-11 19:22
You can also compile it yourself and there is a reason for it not being updated ;)

**Comment by hagabla** [comment] 2016-12-11 20:24
@schummelschumi2004
some gcc issue? or what is the reason?

**Comment by schumi2004** [comment] 2016-12-11 20:51
Correct, and DSM6 toolchains etc plus there are still issues with user management in DSM6 i believe. 
And since NZBget needs newer GCC which is only available in DSM6 toolchain and the above issues are still present explains why there isn't a updated NZBget yet.
But you can compile it yourself, all the needed info can be found in this issue

**Comment by hagabla** [comment] 2016-12-12 12:13
@schumi2004 so is it just a matter of time, or is nzbget abandoned?
DSM6 is out for some time now, so if it is only available in DSM6 it should not be a problem? What am i missing?

**Comment by schumi2004** [comment] 2016-12-13 21:34
This should give you some more information 
https://github.com/SynoCommunity/spksrc/issues?q=is%3Aopen+is%3Aissue+label%3A%22dsm+6.0%22
https://github.com/SynoCommunity/spksrc/issues/2216
https://github.com/SynoCommunity/spksrc/issues/2185

**Comment by B-V-** [comment] 2016-12-13 22:48
Some have installed the package source http://www.jadahl.com/synology6/ and from there he has for some synology NAS variants compiled nzbget 17.1 version (depending of used gcc bij NAS).

See this synology forum page where I found the info:
https://forum.synology.com/enu/viewtopic.php?t=122879

**Comment by schumi2004** [comment] 2016-12-14 07:16
I posted also a dropbox link inhere with packages but they aren't official. ;)

**Comment by Ashkaan** [comment] 2016-12-17 22:51
@schumi2004, thanks so much for your work here.  Any chance you can compile a "broadwell" CPU version?  I just upgraded to a DS3617xs.. woohoo

**Comment by schumi2004** [comment] 2016-12-18 12:18
@Ashkaan i think you should use the x64 package.
https://www.dropbox.com/sh/61puw2muw3rdz2r/AAD9iRmRCXSvSOHrBNQpxBZMa?dl=0

**Comment by Ashkaan** [comment] 2016-12-18 16:49
I tried.  It doesn't install.  The architecture has to match.  I ended up using Docker instead.  I really like it because it auto-updates now.

**Comment by schumi2004** [comment] 2016-12-18 19:09
I will have a look at it tomorrow. There is a toolchain for it but i don't see it in spksrc code either but don't know why.

**Comment by d-zalewski** [comment] 2017-02-18 19:06
v18 is out https://github.com/nzbget/nzbget/releases/tag/v18.0

**Comment by TomVanHaver** [comment] 2017-02-24 20:46
Hi, 

Can anyone tell me why there isn't an updated package for syno anymore?
Is it hard to do it for my ds214+ myself (and share it with the community) ?

kind regards, Tom.

**Comment by aamri111** [comment] 2017-02-27 12:29
Hi, when you will be supporting "broadwell" architecture? I upgraded to a DS3617xs :(

**Comment by aamri111** [comment] 2017-02-27 12:30
@Ashkaan how did you manage to map the download folder can you help me with the configuration?

**Comment by cytec** [comment] 2017-02-27 15:52
since there is an issue for v18 now https://github.com/SynoCommunity/spksrc/issues/2675#issuecomment-282358166 i'm gonna close this

**Closed by cytec** 2017-02-27 15:52 UTC
Labels: dsm 6.0, status/help-wanted, status/work-in-progress

**Comment by Ashkaan** [comment] 2017-02-27 16:33
@aamri111, at which step are you having trouble?  What guide are you following?

**Comment by aamri111** [comment] 2017-02-27 17:16
@Ashkaan I installed the nzbget using docker image and I configured my NZB setting. Now I cannot locate the "downloads" folder. I dont know where it is saving downloads or how to configure the downloads folder location.
I did not find any guide unfortunately :(
