### ISSUE TITLE
[Package Request PiHole

### ISSUE THREAD

**Issue by natami** [SynoCommunity/spksrc#2983] opened 2017-11-01 13:53 UTC
Name: PiHole
Deskription: Network-wide ad blocking via your own Linux hardware
Website: https://pi-hole.net
Software documentation: https://github.com/pi-hole/pi-hole/#one-step-automated-install
Build/Installation documentation: https://github.com/pi-hole/pi-hole/
Source code: https://github.com/pi-hole/pi-hole/
License: https://github.com/pi-hole/pi-hole/blob/master/LICENSE

**Comment by cytec** [comment] 2017-11-01 13:57
@natami please use search before opening new issues.

closed: duplicate of https://github.com/SynoCommunity/spksrc/issues/2501

**Closed by cytec** 2017-11-01 13:57 UTC
