### ISSUE TITLE
sabnzbd 3.6.0: DSM7 permissions

### ISSUE THREAD

**Issue by vierins** [SynoCommunity/spksrc#5371] opened 2022-07-16 20:27 UTC
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

sabnzbd

### Package Version

3.6.0

### Device Model

ds118

### Device Architecture

AArch64 (ARMv8)

### Firmware Version

DSM 7.1-42661 Update 3

### What happened?

The folders are using the correct inherent permissions, but my files are still using "sc-sabnzbd" and "Everyone". The permissions will not set correctly if you let sabnzb sort your tv series.

The permission on the folder tab are empty.

### Reproduction steps

```bash
.
```

### Install Log

```log
.
```

**Comment by BenjV** [comment] 2022-07-28 07:22
This is not a bug.

As of DSM 7 Synology is using ACL's for granting permissions.
SabNzbd understands only standard Linux permissions, so if you let SabNzbd change permissions it wil not function as you expected.

**Comment by vierins** [comment] 2022-07-28 08:04
Sabnzbd should not set any permissions. It should use the permissions of the containing folder.

**Comment by BenjV** [comment] 2022-07-28 09:19
As far as I know will SabNzbd only change the permissions if you configure that in it's settings.

But what permissions did you expect?
Because owning the files by sc-sabnzbd is the way it should work.
And I assume that the empty permission on the folder is what you see in Winscp, is because Winscp cannot handel ACL's so it displays nothing.

**Comment by vierins** [comment] 2022-07-28 11:18
Maybe you don't understand my trouble. 
ex. movies: Sabnzd moves the extracted folder to the movie folder. The new folder inherits the permissions of the movie folder. Fine.
ex. tv series: Sabnzd moves the extracted file the series->episodes folder. The series folder inherits the permission of the tv-series folder. The episodes folder didn't get the persmission. sc-sabnzbd ist the owner and the only user who has read/write permissions. Jellyfin, Plex or whatever are not able to play the files.

**Comment by BenjV** [comment] 2022-07-28 14:15
If you give the system internal user sc-jellyfin and sc-plex permissions on the "tv series" folder then they will have access to all folders and files created below that folder.

Beware that maybe not the case is you do that afterwards, they you should apply those permissions then via for example File Station

**Comment by BenjV** [comment] 2022-07-28 15:25
Here it is true

**Comment by hgy59** [comment] 2023-04-25 05:32
@Safihre any hints on this?

**Comment by Safihre** [comment] 2023-04-25 06:13
Too long ago.. We changed quite some things since.
Closing this.

**Closed by Safihre** 2023-04-25 06:13 UTC
Labels: bug
