### ISSUE TITLE
Debian Chroot stay loading

### ISSUE THREAD

**Issue by scornelissen85** [SynoCommunity/spksrc#2486] opened 2016-10-11 20:27 UTC
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_Debian Chroot
_Package Version:_8.4-7

_NAS Model:_DS213j
_NAS Architecture:_armv7l
_DSM version:_6.0.2-8451 Update 2

### Expected behavior
When opening the Debian Chroot app, I see a window with of the lift side "Overview" and the Overview screen with it's details should appear.

### Actual behavior
When opening the window it show loading, and never stop. In the browser console I received a message HTTP 405 POST is not allowed to /3rdparty/debian-chroot/debian-chroot.cgi/direct/router. Probably is Python not allowed to be executed from Apache from this path?

### Steps to reproduce
_1._Log in to Synology portal (http://192.168.1.2:5000)
_2._Make sure Debian Chroot is installed and started
_3._Open Debian Chroot

#### Package log
No log found, only console error as described.

**Comment by belkone** [comment] 2016-10-11 20:45
I have the same problem, anyone know how to fix it?;<

**Comment by KaraokeStu** [comment] 2016-10-13 08:40
Closed as a duplicate of #2489

**Closed by KaraokeStu** 2016-10-13 08:40 UTC
Labels: dsm 6.0

**Comment by belkone** [comment] 2016-10-15 15:22
@scornelissen85 I made a fix for this, look: https://github.com/SynoCommunity/spksrc/issues/1910#issuecomment-253990371
