### ISSUE TITLE
[Mono] Mono 5.8 crashes with Segmentation Fault

### ISSUE THREAD

**Issue by willsthompson** [SynoCommunity/spksrc#3376] opened 2018-07-10 21:21 UTC
### Setup
_Package Name:_ Mono
_Package Version:_ 5.8.0.108-11

_NAS Model:_  DS214
_NAS Architecture:_ MARVELL Armada XP MV78230
_DSM version:_ DSM 6.0.3-8754 Update 8

### Expected behavior
Mono should run.

### Actual behavior
Mono crashes. 

### Steps to reproduce
_1._ Install SynoCommunity Sonarr package
_2._ Mono dependency is automatically installed
_3._ Sonarr starts then stops.
_4._ SSH into DiskStation
_5._ Check Mono version (`/usr/local/mono/bin$ ./mono --version`)
_6._ "Segmentation Fault"

#### Mono log
 _`/usr/local/mono/var/mono_install.log`_
```
Mon Jul  9 11:26:13 CDT 2018
===> Step preuninst. USER= GROUP= SHARE_PATH=
Mon Jul  9 11:26:15 CDT 2018
===> Step postuninst. USER= GROUP= SHARE_PATH=
Mon Jul  9 11:28:22 CDT 2018
===> Step preinst. USER= GROUP= SHARE_PATH=
Mon Jul  9 11:28:25 CDT 2018
===> Step postinst. USER= GROUP= SHARE_PATH=
Invoke service_postinst
```
#### Sonarr log
```
Starting nzbdrone command env PATH=/usr/local/mono/bin:/volume1/@appstore/nzbdrone/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin HOME=/volume1/@appstore/nzbdrone/var LD_LIBRARY_PATH=/volume1/@appstore/nzbdrone/lib /usr/local/mono/bin/mono /volume1/@appstore/nzbdrone/share/NzbDrone/NzbDrone.exe
```
### Solution

Upgrade DSM 6.0.x to DSM 6.2.x. Evidently there is a memory access-related issue with 6.0.x that is not fixed in any of the updates.

**Comment by willsthompson** [comment] 2018-07-10 22:21
**Temporary workaround:** 

1. Install Synology-published Mono package
2. Edit `/var/packages/nzbdrone/scripts/service-setup`
3. Change:

````
MONO_PATH="/usr/local/mono/bin"
MONO="${MONO_PATH}/mono"
````
to
````
#MONO_PATH="/usr/local/mono/bin"
MONO_PATH="/volume1/@appstore/Mono/usr/local/bin"
MONO="${MONO_PATH}/mono"
````
4. Start Sonarr

Thanks to @rfrowe for the assist: https://github.com/SynoCommunity/spksrc/issues/2207#issuecomment-200958470

**Comment by BenjV** [comment] 2018-07-11 14:16
This cannot be the solution because the settings are not different except that you misspelled mono bij using Mono with a capital M

> /usr/local/mono 

is a symlink to

> /volume1/@appstore/mono/usr/local

**Comment by willsthompson** [comment] 2018-07-11 15:41
@BenjV The Synology-provided package installs to `/Mono`, while the (broken) SynoCommunity package installs to `/mono` (and is, as you suggest, symlinked to `/usr/local/mono`). Note the referenced comment using the Synology package for a similar workaround with the same installation directory name.

However, this is not ideal, and I would like to address the broken SynoCommunity package.

**Comment by BenjV** [comment] 2018-07-11 15:58
First of all, if you are using packages from the SynoCommunity (like Sonarr) that uses mono you should use the mono version from the SynoCommunity.
Same as with Python packages they only work with the python of the SynoCommunity and not with the Synology version.

Secondly the mono from Synology is a beta package and is also a very old version.

And lastly, the spelling with the capital M is just a mistake of Synology, all names and path's should be mono and not Mono.
So not the SynoCommunity package is broken but the Synology does conform to the correct naming convention and is faulty.

**Comment by willsthompson** [comment] 2018-07-11 16:13
@BenjV You are misunderstanding the problem, which is explained in the issue. I only installed the Synology package because the SynoCommunity mono package is broken. For example, using the exact command Sonarr uses to launch:

````
env PATH=/usr/local/mono/bin:/volume1/@appstore/nzbdrone/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin HOME=/volume1/@appstore/nzbdrone/var LD_LIBRARY_PATH=/volume1/@appstore/nzbdrone/lib 
/usr/local/mono/bin/mono /volume1/@appstore/nzbdrone/share/NzbDrone/NzbDrone.exe
Segmentation Fault
````

Similarly:

````
env PATH=/usr/local/mono/bin:/volume1/@appstore/nzbdrone/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin HOME=/volume1/@appstore/nzbdrone/var LD_LIBRARY_PATH=/volume1/@appstore/nzbdrone/lib 
/usr/local/mono/bin/mono --version
Segmentation Fault
````

**Comment by BenjV** [comment] 2018-07-11 18:07
The mono installation is not broken.
There was a bug in Sonarr that had a problem with mono as of version 5.10 of mono.
This was fixed in Sonarr version 2.0.0.5153
So most likely you are using an old Sonarr version.

**Comment by willsthompson** [comment] 2018-07-11 18:53
@BenjV If your test NAS is not on Armada XP platform, then you can't accurately test my issue.

As I explained in the comment above, **simply checking the Mono version results in a segfault**. That cannot be related to Sonarr. The segfault occurrs when only the SynoCommunity Mono package is installed and Sonarr is not. The problem is clearly with the SynoCommunity Mono package, most likely something related to the Armada XP distro.

The latest SynoCommunity Sonarr package is v20180303-13, which [according to the release notes](https://synocommunity.com/package/nzbdrone) is running Sonarr version 2.0.0.4472. This is the version I have installed. The Mono package info is in the OP.

**Comment by BenjV** [comment] 2018-07-11 19:13
My test Nas is a armada38x, so not that much different.
The lastest Sonarr package from the SynoCommunity is v20180309-13 which installs Sonarr version 2.0.0.4689.
This version must be updated from within Sonarr to 2.0.0.5528

If you cannot start Sonarr because of this Sonarr bug, you can download this file.
http://download.sonarr.tv/hotfixes/regression-mono-5.10/NLog.dll.gz

unpack it and replace the original with the unpacked dll.
It is located here:
/volume1/@appstore/nzbdrone/share/NzbDrone

**Comment by willsthompson** [comment] 2018-07-11 19:18
@BenjV Mono crashes even without Sonarr installed. It can't be a Sonarr problem. This Mono distro is segfaulting for any command. I think either the Mono ArmadaXP package is corrupt, or it was not compiled correctly.

**Comment by BenjV** [comment] 2018-07-11 19:22
Did you try to reinstall it?

**Comment by BenjV** [comment] 2018-07-11 19:35
Ok I installed mono on my other Nas which is by coincident also an armada XP
I logged in with putty and asked the verion with the correct command;
/usr/local/mono/bin/mono --version

And this is the result

> admin@Nas:~$ /usr/local/mono/bin/mono --version
> Mono JIT compiler version 5.8.0.108 (tarball Sat Feb 24 10:26:45 UTC 2018)
> Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
>         TLS:           __thread
>         SIGSEGV:       normal
>         Notifications: epoll
>         Architecture:  armel,vfp+hard
>         Disabled:      none
>         Misc:          softdebug
>         LLVM:          supported, not enabled.
>         GC:            sgen (concurrent by default)
>

**Comment by willsthompson** [comment] 2018-07-11 19:52
Did you recently install the package? Maybe the hosted package was corrupted recently. I just uninstalled SynoCommunity Mono and reinstalled it, and checking the mono version via SSH still segfaults.

**Comment by BenjV** [comment] 2018-07-11 19:57
I do not use mono on that Nas, so I installed it just before I posted the result.

**Comment by willsthompson** [comment] 2018-07-11 19:59
Is it running the same DSM version? I suppose it could also be an OS problem.

**Comment by BenjV** [comment] 2018-07-11 20:02
My Nas is running DSM 6.2 but that could not explain a segfaults.

Did you use the correct version command?
Because the command you posted in the first topic is wrong.

**Comment by willsthompson** [comment] 2018-07-11 20:49
Okay, the lesson of the day is that **OS upgrades can cause segfaults**. Upgrading to DSM 6.2 fixed the segfaulting mono package.

**Closed** 2018-07-11 20:53 UTC

**Comment by BenjV** [comment] 2018-07-11 21:38
That is impossible, because DSM is not an OS just an gui layer on top of Linux.
And the Linux version does not change during a DSM upgrades.

More likely is that your system got corrupted and the upgrade reinstalled of course your whole system.

No problem, trying to help you was fun.

**Comment by willsthompson** [comment] 2018-07-11 21:44
Hm, not sure that makes sense. If DSM is just a GUI layer, then how could updating it fix a corrupt part of the OS?

**Comment by BenjV** [comment] 2018-07-11 23:38
By upgrading the whole system gets renewed including Linux.

**Comment by ymartin59** [comment] 2018-07-12 21:38
@BenjV Is it relevant to re-publish Sonarr with latest version included to by-pass that buggy version?

**Comment by BenjV** [comment] 2018-07-13 07:22
@ymartin59 Yes it would be wise to update the Sonarr package to the latest available version, because it is a known problem and if it occurs the fix is difficult, because Sonarr will not start anymore so updating is not possible.

Although I did not encounter the problem with the version that is now in the package on my Nas.
So maybe this incompatibility was created in a version between those or maybe not on all cpu architectures.
But better safe then sorry.
