### ISSUE TITLE
Issue with root priviligies on DSM 7.0

### ISSUE THREAD

**Issue by kalatos86** [SynoCommunity/spksrc#4301] opened 2020-12-11 18:20 UTC
Hello,

I would like to request issue with the SynoCommunity packages to run them on DSM 7.0 Beta version. This is all about using root account to install and run them.

I mean about Transmission and ffmpeg

### Setup
_Package Name:_  Transmission 
_Package Version:_ 3.00-19

_Package Name:_  ffmpeg
_Package Version:_ 4.3.1-35

_NAS Model:_ DS218+
_DSM version:_ 7.0 beta

### Expected behavior
Transmission and ffmpeg to start and work in DSM 7.0

### Actual behavior
No possible to run the packages because of error message related to use root account.

### Steps to reproduce
1. Install DSM 7.0 beta
2. Go to the packages center
3. try to run

**Comment by hgy59** [comment] 2020-12-12 12:24
duplicate of #4215

**Closed by hgy59** 2020-12-12 12:24 UTC
Labels: dsm 7.0
