### ISSUE TITLE
Boost library V1.72 (or V1.73) compile error when address model is 32 bits

### ISSUE THREAD

**Issue by Antori91** [SynoCommunity/spksrc#4069] opened 2020-07-15 12:19 UTC
Hello,

I'm a new user and try to cross-compile domoticz using the latest versions of the boost library (i.e 1.72.0 or 1.73.0). When address model is 64 bits (I've tried arch-braswell), it just works fine. But when address model is 32 bits (armada38x for example), the compilation fails. Here is the log:
```
antori@A320MK:~/spksrc/cross/domoticz$ make arch-armada38x
===>  Building package for arch armada38x
make[1]: Entering directory '/home/antori/spksrc/cross/domoticz'
===>  Processing dependencies of domoticz
make[2]: Entering directory '/home/antori/spksrc/cross/boost'
===>  Compiling for boost
cd /home/antori/spksrc/cross/domoticz/work-armada38x-6.1/boost_1_72_0 && env PKG_CONFIG_LIBDIR=/home/antori/spksrc/cross/domoticz/work-armada38x-6.1/install//usr/local/domoticz/lib/pkgconfig WORK_DIR=/home/antori/spksrc/cross/domoticz/work-armada38x-6.1 INSTALL_PREFIX=/usr/local/domoticz TC=syno-armada38x-6.1  LD="/home/antori/spksrc/toolchains/syno-armada38x-6.1/work/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-ld" LDSHARED="/home/antori/spksrc/toolchains/syno-armada38x-6.1/work/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-gcc -shared" CPP="/home/antori/spksrc/toolchains/syno-armada38x-6.1/work/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-cpp" NM="/home/antori/spksrc/toolchains/syno-armada38x-6.1/work/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-nm" CC="/home/antori/spksrc/toolchains/syno-armada38x-6.1/work/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-gcc" AS="/home/antori/spksrc/toolchains/syno-armada38x-6.1/work/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-as" RANLIB="/home/antori/spksrc/toolchains/syno-armada38x-6.1/work/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-ranlib" CXX="/home/antori/spksrc/toolchains/syno-armada38x-6.1/work/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-g++" AR="/home/antori/spksrc/toolchains/syno-armada38x-6.1/work/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-ar" STRIP="/home/antori/spksrc/toolchains/syno-armada38x-6.1/work/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-strip" OBJDUMP="/home/antori/spksrc/toolchains/syno-armada38x-6.1/work/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-objdump" READELF="/home/antori/spksrc/toolchains/syno-armada38x-6.1/work/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-readelf" CFLAGS="-I/home/antori/spksrc/toolchains/syno-armada38x-6.1/work/arm-unknown-linux-gnueabi/arm-unknown-linux-gnueabi/sysroot/usr/include -I/home/antori/spksrc/cross/domoticz/work-armada38x-6.1/install//usr/local/domoticz/include " CPPFLAGS="-I/home/antori/spksrc/toolchains/syno-armada38x-6.1/work/arm-unknown-linux-gnueabi/arm-unknown-linux-gnueabi/sysroot/usr/include -I/home/antori/spksrc/cross/domoticz/work-armada38x-6.1/install//usr/local/domoticz/include " CXXFLAGS="-I/home/antori/spksrc/toolchains/syno-armada38x-6.1/work/arm-unknown-linux-gnueabi/arm-unknown-linux-gnueabi/sysroot/usr/include -I/home/antori/spksrc/cross/domoticz/work-armada38x-6.1/install//usr/local/domoticz/include " LDFLAGS="-L/home/antori/spksrc/toolchains/syno-armada38x-6.1/work/arm-unknown-linux-gnueabi/arm-unknown-linux-gnueabi/sysroot/lib -L/home/antori/spksrc/cross/domoticz/work-armada38x-6.1/install//usr/local/domoticz/lib -Wl,--rpath-link,/home/antori/spksrc/cross/domoticz/work-armada38x-6.1/install//usr/local/domoticz/lib -Wl,--rpath,/usr/local/domoticz/lib " ./b2 --user-config=/home/antori/spksrc/cross/domoticz/work-armada38x-6.1/boost_1_72_0/user-config.jam
./b2: 1: Syntax error: word unexpected (expecting ")")
make[2]: *** [Makefile:66: boost_compile] Error 2
make[2]: Leaving directory '/home/antori/spksrc/cross/boost'
make[1]: *** [../../mk/spksrc.depend.mk:44: depend_target] Error 2
make[1]: Leaving directory '/home/antori/spksrc/cross/domoticz'
make: [../../mk/spksrc.cross-cc.mk:82: arch-armada38x] Error 2 (ignored)
antori@A320MK:~/spksrc/cross/domoticz$ 
```

**Comment by ymartin59** [comment] 2020-07-26 16:49
@hgy59 May you please confirm this point is fixed in your PR with python2 and domoticz updates

**Comment by hgy59** [comment] 2020-07-26 20:54
@ymartin59 as my python2 branch is merged and domoticz was successfully built, I can confirm it works with boost version `1.63.0` as this is current version on the master (see commit c4f7229c91ddfee91d10e1cf13d1cbd4afd71f6f).
It seems to be an issue with newer boost versions (may be I tried newer boost versions too, but this was some time ago and I deleted my python2 branch...).

@Antori91 are there any needs to use a newer boost version?

**Comment by Antori91** [comment] 2020-07-26 21:04
Hello,
Domoticz team recommends to use the latest Boost libraries - at the moment they verified version 1.72 >>> https://www.domoticz.com/wiki/Build_Domoticz_from_source
Also Domoticz needs now python3 to run plugins.
Last, I don't know if it helps, but you will find here some details about the makefiles I use: https://www.domoticz.com/forum/viewtopic.php?f=47&t=32533

**Comment by hgy59** [comment] 2020-07-27 20:59
@Antori91 so far I found that it is a cross compiling issue, not a 32 bit one.
x64 and evansport (32-bit) builds are ok but all cross compiled are not.

the boost build tool `b2` is built for the build platform (i386) with boost 1.69 and built for the host plattform (i.e. arm32, arm64, ppc32, ...) with boost 1.72.
So running ./b2 with cross compilation has a bad exec format and gives a random error of `Syntax error: word unexpected (expecting ")")`  or `Syntax error: Unterminated quoted string`.

So far my analysis, no solution yet.

**Comment by hgy59** [comment] 2020-07-27 22:27
@Antori91 DomotIcz 4.9700 is not meant to use boost 1.72 and 1.73 and fails to build with the following error:

```
[ 60%] Building CXX object CMakeFiles/domoticz.dir/hardware/Pinger.cpp.o
/spksrc/spk/domoticz/work-x64-6.1/domoticz-4.9700/hardware/Pinger.cpp: In member function ‘void pinger::handle_timeout(const boost::system::error_code&)’:
/spksrc/spk/domoticz/work-x64-6.1/domoticz-4.9700/hardware/Pinger.cpp:79:16: error: ‘boost::asio::ip::icmp::resolver’ has no member named ‘get_io_service’
      resolver_.get_io_service().stop();
                ^
```


> Domoticz team recommends to use the latest Boost libraries - at the moment they verified version 1.72 >>> https://www.domoticz.com/wiki/Build_Domoticz_from_source

This must be for latest domoticz version and not current version of synocommunity.

> Also Domoticz needs now python3 to run plugins.

The current synocommunity version already depends on cross/python3.

**Comment by ymartin59** [comment] 2020-07-29 19:31
@hgy59 You may retrieve deleted branch commit hashes from Git reflogs

**Comment by hgy59** [comment] 2020-07-29 19:58
@ymartin59 no need for this. Everthing is Ok in the merged python2.
and all the packages there are waiting for publish...

**Comment by hgy59** [comment] 2023-10-03 19:51
meanwhile we have several boost versions avilable under cross/boost_x.xx
- 1.68
- 1.70
- 1.78
- 1.82

**Closed by hgy59** 2023-10-03 19:51 UTC
