### ISSUE TITLE
ShairPort does not work on DSM6 beta

### ISSUE THREAD

**Issue by federaa** [SynoCommunity/spksrc#1877] opened 2015-10-13 21:17 UTC
##

**Comment by Dr-Bean** [comment] 2015-10-14 16:37
Did you forget to add a description of your problem? I wouldn't mind something a bit more substantial than `it does not work` in the title...
As a starting point some questions, what happens (or does not happen), and what result did you expect? Which model are you running on? Have you tried rebooting the device? You might also want to try reinstalling the package, and see if that helps. We'll have further questions as we go along.

For the record, you're running a beta package on a beta OS, which hasn't been released for more than two days. There might not be an immediate fix (personally, probably not even going to bother with 6.0 beta1, I'll wait for the second beta)

**Comment by Dr-Bean** [comment] 2015-10-20 08:15
https://github.com/mikebrady/shairport-sync/issues/146 has more info. The binary segfaults on 215j/armada375, according to @trifle. I assume the same happens on 414/armadaxp, but that's unconfirmed.

If the error was caused by build issues, that may have been fixed as a new package has just been released. Otherwise, we'll probably wait until DSM6 is a bit further in it's release process.

**Comment by trifle** [comment] 2015-10-20 09:13
Thanks for the heads up. The updated package still segfaults.
(Commenting here since https://github.com/mikebrady/shairport-sync/issues/146 is closed.)

**Comment by lost-carrier** [comment] 2016-03-25 16:06
@trifle, @federaa: I have DSM 6 running now and the old package runs fine over here... can you confirm? Probably we can close this issue...

**Comment by trifle** [comment] 2016-03-26 16:11
@lost-carrier Interesting! I will have access to my disk station towards the end of next week. If you want to, feel free to close the issue and I can re-open it if necessary?

**Comment by aschulm** [comment] 2016-04-02 15:23
Shairport 2.3.11-2 is segfaulting on my DS-214+ which is running DSM 6.0-7321. I'm happy to take a look at this bug.

**Comment by nkildal** [comment] 2016-07-16 20:57
Hi 

Did anyone find a fix for this issue?
I still get a segfault when trying to start shairport-sync 2.3.11-2 on my DS-214+ (armadaxp) running DSM 6.0.1-7393 Update 1

Regards
Nicolai

**Comment by ssbarnea** [comment] 2016-10-20 08:57
Could we have an update on this? I am really interested about making ShairPort work on my Synology.

Excuse me for highjacking this but I have a question that could be answered only by those around this niche use case: shariport on synology.

I want to buy an USB sound card that would work with Synology, preferably one that supports optic output too.  Can you recommend one or point me to a place where I can find a list?

**Comment by ssbarnea** [comment] 2016-10-31 15:41
I was able to make Shairport Sync work on DSM 6 at least for some time but it seems unreliable. 
Playing on "USB Speaker" from DSM Audio seems to work file, even with hi-def audio.

I would want to debug it further but I have no idea where to look.  `/var/log/upstart/pkgctl-shairport-sync.log` seems to contain a single line `start shairport-sync` but `/var/log/messages` contains some serious errors:
```
2016-10-31T15:02:15+00:00 syno root: /usr/syno/etc/rc.sysv/ups-usb.sh start invoked.
2016-10-31T15:02:15+00:00 syno upsmon[1065]: UPS [ups@localhost] connected
2016-10-31T15:18:11+00:00 syno kernel: [787638.579075] shairport-sync[2624]: segfault at 7fdcf5201000 ip 00007fdcf4d76dd5 sp 00007fdcf1b57500 error 4 in libasound.so.2.0.0[7fdcf4d0a000+11d000]
2016-10-31T15:18:24+00:00 syno synoairplayd: rtsp_client.cpp:742 Failed to read first line from buffer
2016-10-31T15:21:54+00:00 syno remote_player_status.cgi: remote_player_status.cpp:399 device is not exist
```

**Comment by Safihre** [comment] 2018-06-24 08:09
Updates (like proper DSM6 support) will be handled in #3040.

**Closed by Safihre** 2018-06-24 08:09 UTC
Labels: dsm 6.0
