### ISSUE TITLE
mosquitto: MQTT-broker won't start up

### ISSUE THREAD

**Issue by binderth** [SynoCommunity/spksrc#2649] opened 2017-02-07 09:50 UTC
install mosquitto package
### Setup
_Package Name:_ mosquitto
_Package Version:_ 1.4.9-5

_NAS Model:_ DS214play
_NAS Architecture:_ INTEL Atom CE5335
_DSM version:_ DSM 6.0.2-8451 Update 9

### Expected behavior
1. install mosquitto package
2. goto "package center" - "installed" - "mosquitto" and select "execute"
3. mosquitto package will start

### Actual behavior
1. install mosquitto package
2. goto "package center" - "installed" - "mosquitto" and select "execute"
3. mosquitto package won't start
4. error-message: "the package Service couldn't be executed" (sorry, i'm using german frontend, should read somehow loke it)
5. the logfile is empty

### Steps to reproduce
_1._ install mosquitto package
_2._ goto "package center" - "installed" - "mosquitto" and select "execute"
_3._ package won't start

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
no log in package center, and ` /usr/local/mosquitto/var``
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_

`/var/log/messages`
```
2017-02-07T10:31:34+01:00 DiskStation synoscgi_SYNO.Core.Package.Installation_1_install[1146]: resource_api.cpp:163 Acquire service-cfg for mosquitto when 0x0001 (done)
2017-02-07T10:32:51+01:00 DiskStation kernel: [912108.405426] init: pkgctl-mosquitto pre-start process (4770) terminated with status 1
2017-02-07T10:32:51+01:00 DiskStation synoscgi_SYNO.Core.Package.Control_1_start[4525]: servicecfg_internal_lib.c:187 Failed to start job [pkgctl-mosquitto][0xD900 privilege.cpp:60]
2017-02-07T10:32:52+01:00 DiskStation synoscgi_SYNO.Core.Package.Control_1_start[4525]: service_initjob_action.c:27 InitJobStart failed, [0xD900 privilege.cpp:60]
2017-02-07T10:32:52+01:00 DiskStation synoscgi_SYNO.Core.Package.Control_1_start[4525]: pkgstartstop.cpp:262 Failed to start pkgctl-mosquitto (err=-1) [0xD900 privilege.cpp:60]
2017-02-07T10:33:17+01:00 DiskStation kernel: [912133.955062] init: pkgctl-mosquitto pre-start process (6375) terminated with status 1
2017-02-07T10:33:17+01:00 DiskStation synoscgi_SYNO.Core.Package.Control_1_start[5940]: servicecfg_internal_lib.c:187 Failed to start job [pkgctl-mosquitto][0xD900 privilege.cpp:60]
2017-02-07T10:33:18+01:00 DiskStation synoscgi_SYNO.Core.Package.Control_1_start[5940]: service_initjob_action.c:27 InitJobStart failed, [0xD900 privilege.cpp:60]
2017-02-07T10:33:18+01:00 DiskStation synoscgi_SYNO.Core.Package.Control_1_start[5940]: pkgstartstop.cpp:262 Failed to start pkgctl-mosquitto (err=-1) [0xD900 privilege.cpp:60]
2017-02-07T10:40:11+01:00 DiskStation kernel: [912547.905764] init: pkgctl-mosquitto pre-start process (13340) terminated with status 1
2017-02-07T10:40:11+01:00 DiskStation synoscgi_SYNO.Core.Package.Control_1_start[13075]: servicecfg_internal_lib.c:187 Failed to start job [pkgctl-mosquitto][0xD900 privilege.cpp:60]
2017-02-07T10:40:13+01:00 DiskStation synoscgi_SYNO.Core.Package.Control_1_start[13075]: service_initjob_action.c:27 InitJobStart failed, [0xD900 privilege.cpp:60]
2017-02-07T10:40:13+01:00 DiskStation synoscgi_SYNO.Core.Package.Control_1_start[13075]: pkgstartstop.cpp:262 Failed to start pkgctl-mosquitto (err=-1) [0xD900 privilege.cpp:60]
~
```
`/var/log/synopkg.log`_
```
2017/02/07 10:31:29	(system) trigger	 :
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 INFO --no-same-owner
2017/02/07 10:31:29	(system) trigger	 :
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 INFO --no-same-owner	ret=[0]
2017/02/07 10:31:29	(system) trigger	 :
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 conf --no-same-owner
/bin/tar: conf: Not found in archive
/bin/tar: Exiting with failure status due to previous errors
2017/02/07 10:31:29	(system) trigger	 :
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 conf --no-same-owner	ret=[2]
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/start-stop-status --no-same-owner --no-same-permissions
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/start-stop-status --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/preinst --no-same-owner --no-same-permissions
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/preinst --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/postinst --no-same-owner --no-same-permissions
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/postinst --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/preuninst --no-same-owner --no-same-permissions
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/preuninst --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/postuninst --no-same-owner --no-same-permissions
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/postuninst --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/preupgrade --no-same-owner --no-same-permissions
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/preupgrade --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/postupgrade --no-same-owner --no-same-permissions
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/postupgrade --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/rm -rf /volume1/@tmp/589993F10
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/rm -rf /volume1/@tmp/589993F10	ret=[0]
2017/02/07 10:31:29	(system) trigger	 :
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 INFO --no-same-owner
2017/02/07 10:31:29	(system) trigger	 :
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 INFO --no-same-owner	ret=[0]
2017/02/07 10:31:29	(system) trigger	 :
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 conf --no-same-owner
/bin/tar: conf: Not found in archive
/bin/tar: Exiting with failure status due to previous errors
2017/02/07 10:31:29	(system) trigger	 :
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 conf --no-same-owner	ret=[2]
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/start-stop-status --no-same-owner --no-same-permissions
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/start-stop-status --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/preinst --no-same-owner --no-same-permissions
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/preinst --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/postinst --no-same-owner --no-same-permissions
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/postinst --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/preuninst --no-same-owner --no-same-permissions
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/preuninst --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/postuninst --no-same-owner --no-same-permissions
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/postuninst --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/preupgrade --no-same-owner --no-same-permissions
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/preupgrade --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/postupgrade --no-same-owner --no-same-permissions
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F10 scripts/postupgrade --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/rm -rf /volume1/@tmp/589993F10
2017/02/07 10:31:29	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/rm -rf /volume1/@tmp/589993F10	ret=[0]
2017/02/07 10:31:32	(system) trigger	 :
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F40 INFO --no-same-owner
2017/02/07 10:31:32	(system) trigger	 :
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F40 INFO --no-same-owner	ret=[0]
2017/02/07 10:31:32	(system) trigger	 :
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F40 conf --no-same-owner
/bin/tar: conf: Not found in archive
/bin/tar: Exiting with failure status due to previous errors
2017/02/07 10:31:32	(system) trigger	 :
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F40 conf --no-same-owner	ret=[2]
2017/02/07 10:31:32	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F40 scripts/start-stop-status --no-same-owner --no-same-permissions
2017/02/07 10:31:32	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F40 scripts/start-stop-status --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:32	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F40 scripts/preinst --no-same-owner --no-same-permissions
2017/02/07 10:31:32	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F40 scripts/preinst --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:32	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F40 scripts/postinst --no-same-owner --no-same-permissions
2017/02/07 10:31:32	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F40 scripts/postinst --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:32	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F40 scripts/preuninst --no-same-owner --no-same-permissions
2017/02/07 10:31:32	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F40 scripts/preuninst --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:32	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F40 scripts/postuninst --no-same-owner --no-same-permissions
2017/02/07 10:31:32	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F40 scripts/postuninst --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:32	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F40 scripts/preupgrade --no-same-owner --no-same-permissions
2017/02/07 10:31:32	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F40 scripts/preupgrade --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:32	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F40 scripts/postupgrade --no-same-owner --no-same-permissions
2017/02/07 10:31:32	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F40 scripts/postupgrade --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:32	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/rm -rf /volume1/@tmp/589993F40
2017/02/07 10:31:32	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/rm -rf /volume1/@tmp/589993F40	ret=[0]
2017/02/07 10:31:33	(system) trigger	 :
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F50 INFO --no-same-owner
2017/02/07 10:31:33	(system) trigger	 :
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F50 INFO --no-same-owner	ret=[0]
2017/02/07 10:31:33	(system) trigger	 :
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F50 conf --no-same-owner
/bin/tar: conf: Not found in archive
/bin/tar: Exiting with failure status due to previous errors
2017/02/07 10:31:33	(system) trigger	 :
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F50 conf --no-same-owner	ret=[2]
2017/02/07 10:31:33	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F50 scripts/start-stop-status --no-same-owner --no-same-permissions
2017/02/07 10:31:33	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F50 scripts/start-stop-status --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:33	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F50 scripts/preinst --no-same-owner --no-same-permissions
2017/02/07 10:31:33	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F50 scripts/preinst --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:33	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F50 scripts/postinst --no-same-owner --no-same-permissions
2017/02/07 10:31:33	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F50 scripts/postinst --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:33	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F50 scripts/preuninst --no-same-owner --no-same-permissions
2017/02/07 10:31:33	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F50 scripts/preuninst --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:33	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F50 scripts/postuninst --no-same-owner --no-same-permissions
2017/02/07 10:31:33	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F50 scripts/postuninst --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:33	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F50 scripts/preupgrade --no-same-owner --no-same-permissions
2017/02/07 10:31:33	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F50 scripts/preupgrade --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:33	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F50 scripts/postupgrade --no-same-owner --no-same-permissions
2017/02/07 10:31:33	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/589993F50 scripts/postupgrade --no-same-owner --no-same-permissions	ret=[0]
2017/02/07 10:31:33	(system) trigger	mosquitto 1.4.9-5:
			Begin:	/bin/rm -rf /volume1/@tmp/589993F50
2017/02/07 10:31:33	(system) trigger	mosquitto 1.4.9-5:
			End:	/bin/rm -rf /volume1/@tmp/589993F50	ret=[0]
2017/02/07 10:31:33	install	 :
			Begin:	/bin/rm -rf /volume1/@tmp/pkginstall
2017/02/07 10:31:33	install	 :
			End:	/bin/rm -rf /volume1/@tmp/pkginstall	ret=[0]
2017/02/07 10:31:33	install	 :
			Begin:	/bin/mkdir -p /volume1/@tmp/pkginstall/package
2017/02/07 10:31:33	install	 :
			End:	/bin/mkdir -p /volume1/@tmp/pkginstall/package	ret=[0]
2017/02/07 10:31:33	install	 :
			Begin:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/pkginstall --no-same-owner
2017/02/07 10:31:33	install	 :
			End:	/bin/tar xf /volume1/@tmp/@synopkg/@download/mosquitto/@SYNOPKG_DOWNLOAD_mosquitto -C /volume1/@tmp/pkginstall --no-same-owner	ret=[0]
2017/02/07 10:31:33	install	mosquitto 1.4.9-5:
			Begin:	/bin/tar xf /volume1/@tmp/pkginstall/package.tgz -C /volume1/@tmp/pkginstall/package --no-same-owner
2017/02/07 10:31:34	install	mosquitto 1.4.9-5:
			End:	/bin/tar xf /volume1/@tmp/pkginstall/package.tgz -C /volume1/@tmp/pkginstall/package --no-same-owner	ret=[0]
2017/02/07 10:31:34	install	mosquitto 1.4.9-5:
			Begin:	preinst
2017/02/07 10:31:34	install	mosquitto 1.4.9-5:
			End:	preinst	ret=[0]
2017/02/07 10:31:34	install	mosquitto 1.4.9-5:
			Begin:	/bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/mosquitto
2017/02/07 10:31:34	install	mosquitto 1.4.9-5:
			End:	/bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/mosquitto	ret=[0]
2017/02/07 10:31:34	install	mosquitto 1.4.9-5:
			Begin:	/bin/rm -rf /var/packages/mosquitto
2017/02/07 10:31:34	install	mosquitto 1.4.9-5:
			End:	/bin/rm -rf /var/packages/mosquitto	ret=[0]
2017/02/07 10:31:34	install	mosquitto 1.4.9-5:
			Begin:	/bin/mkdir -p /var/packages/mosquitto
2017/02/07 10:31:34	install	mosquitto 1.4.9-5:
			End:	/bin/mkdir -p /var/packages/mosquitto	ret=[0]
2017/02/07 10:31:34	install	mosquitto 1.4.9-5:
			Begin:	/bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/mosquitto/INFO
2017/02/07 10:31:34	install	mosquitto 1.4.9-5:
			End:	/bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/mosquitto/INFO	ret=[0]
2017/02/07 10:31:34	install	mosquitto 1.4.9-5:
			Begin:	/bin/rm -rf /var/packages/mosquitto/scripts
2017/02/07 10:31:34	install	mosquitto 1.4.9-5:
			End:	/bin/rm -rf /var/packages/mosquitto/scripts	ret=[0]
2017/02/07 10:31:34	install	mosquitto 1.4.9-5:
			Begin:	/bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/mosquitto/scripts
2017/02/07 10:31:34	install	mosquitto 1.4.9-5:
			End:	/bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/mosquitto/scripts	ret=[0]
2017/02/07 10:31:34	install	mosquitto 1.4.9-5:
			Begin:	/bin/rm -rf /var/packages/mosquitto/conf
2017/02/07 10:31:34	install	mosquitto 1.4.9-5:
			End:	/bin/rm -rf /var/packages/mosquitto/conf	ret=[0]
2017/02/07 10:31:34	install	mosquitto 1.4.9-5:
			Begin:	/bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/mosquitto/conf
2017/02/07 10:31:34	install	mosquitto 1.4.9-5:
			End:	/bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/mosquitto/conf	ret=[0]
2017/02/07 10:31:34	install	mosquitto 1.4.9-5:
			Begin:	postinst
2017/02/07 10:31:34	install	mosquitto 1.4.9-5:
			End:	postinst	ret=[0]
2017/02/07 10:31:34	install	mosquitto 1.4.9-5:
			Begin:	/bin/rm -rf /volume1/@tmp/pkginstall
2017/02/07 10:31:34	install	mosquitto 1.4.9-5:
			End:	/bin/rm -rf /volume1/@tmp/pkginstall	ret=[0]
2017/02/07 10:31:34	install mosquitto 1.4.9-5 successfully
2017/02/07 10:32:50	start mosquitto: begin to start version 1.4.9-5
2017/02/07 10:32:52	stop mosquitto: begin to stop version 1.4.9-5
2017/02/07 10:32:52	stop mosquitto: stop version 1.4.9-5 successfully, result 0
2017/02/07 10:32:59	start mosquitto: start version 1.4.9-5 failed, result 1
2017/02/07 10:33:16	start mosquitto: begin to start version 1.4.9-5
2017/02/07 10:33:18	stop mosquitto: begin to stop version 1.4.9-5
2017/02/07 10:33:18	stop mosquitto: stop version 1.4.9-5 successfully, result 0
2017/02/07 10:33:25	start mosquitto: start version 1.4.9-5 failed, result 1
2017/02/07 10:40:10	start mosquitto: begin to start version 1.4.9-5
2017/02/07 10:40:13	stop mosquitto: begin to stop version 1.4.9-5
2017/02/07 10:40:13	stop mosquitto: stop version 1.4.9-5 successfully, result 0
2017/02/07 10:40:19	start mosquitto: start version 1.4.9-5 failed, result 1
```

**Comment by Dr-Bean** [comment] 2017-02-07 16:23
Yes, that's a known issue on DSM6. #2216 is the underlying cause, subscribe to that issue to keep informed of the overall progress.

I'll close this issue, because it's a duplicate of https://github.com/SynoCommunity/spksrc/issues/2581. When more information specific to the Mosquitto package becomes available, that issue will be updated as well.

**Closed by Dr-Bean** 2017-02-07 16:23 UTC
