### ISSUE TITLE
subliminal run failing

### ISSUE THREAD

**Issue by raspap** [SynoCommunity/spksrc#2107] opened 2016-01-29 09:15 UTC
Hi,

I have been able to install Subliminal through the Synocommunity channel on my NAS, but trying to run it from the Package Center gives an error: "Failed to run the package service".

I am using:
subliminal 0.7.5-12
python 2.7.11-15
DSM 6.0 beta 2

Any idea on how to debug this?

Thanks!
##

**Comment by globoid** [comment] 2016-01-31 10:18
+1

**Comment by FesseCestMoi** [comment] 2016-03-24 16:18
Hi,

The problem is still up on the official dsm6 release.

DSM 6.0-7321

Any news ?

**Comment by doppiej** [comment] 2016-05-12 20:51
Any news on this?
I am also experiencing this problem..

**Comment by Safihre** [comment] 2018-06-24 07:58
Closing due to age, further updates of Subliminal (like DSM6 compatibility) should be part of #2357.

**Closed by Safihre** 2018-06-24 07:58 UTC
Labels: dsm 6.0
