### ISSUE TITLE
[Package Request] Prowlarr

### ISSUE THREAD

**Issue by hurricaneporter** [SynoCommunity/spksrc#4800] opened 2021-08-20 22:59 UTC
* Name: Prowlarr
* Description: Prowlarr is an indexer manager/proxy built on the popular *arr .net/reactjs base stack, to integrate with your various PVR apps.
* Website: https://prowlarr.com/
* Software documentation: https://wiki.servarr.com/en/prowlarr
* Build/Installation documentation: https://wiki.servarr.com/prowlarr/installation
* Source code:  https://github.com/Prowlarr/Prowlarr
* License: GPL 3

**Comment by SheepKid12** [comment] 2021-08-23 00:16
Here's my spksrc branch with Prowlarr (everything appears to compile & run without any errors): https://github.com/SheepKid12/spksrc/tree/add_prowlarr

**Comment by hgy59** [comment] 2021-11-06 11:11
duplicate of #4780

**Closed by hgy59** 2021-11-06 11:11 UTC
Labels: request
