### ISSUE TITLE
Python 3.6 

### ISSUE THREAD

**Issue by brandonscript** [SynoCommunity/spksrc#3645] opened 2019-03-02 16:57 UTC
_NAS Model:_ DS1817+
_NAS Architecture:_ INTEL Atom C2538
_DSM version:_ DSM 6.2.1-23824 Update 1

Yesterday I discovered Python 3.6 was available to install, and I got very excited. So excited in fact, that I took a screenshot:

<img width="409" alt="screen shot 2019-03-01 at 7 59 45 am" src="https://user-images.githubusercontent.com/1480253/53684949-eb47fc80-3cc8-11e9-8cbf-e485832317c8.png">

But today, after installing the update, I only have 3.5, and can only access 3.5:

<img width="608" alt="screen shot 2019-03-02 at 8 55 51 am" src="https://user-images.githubusercontent.com/1480253/53684958-07e43480-3cc9-11e9-960b-28f138d590e7.png">

Is there a reason 3.6 disappeared? Poking at the source, it looks like both 3.5 and 3.6 are bundled in the same package, but I can't figure out how to get 3.6 up and running?

**Comment by chickenandpork** [comment] 2019-03-02 20:02
Let me take a look tonight.  There should only be one version in there, it should have been compiled clean.

**Comment by ymartin59** [comment] 2019-03-03 09:10
Duplicate of #3644. Please follow that one.
@chickenandpork Only x64 version is properly running. So I have un-pubilshed 3.6 until cross-compilation is understood and fixed.

**Closed by ymartin59** 2019-03-03 09:10 UTC

**Comment by chickenandpork** [comment] 2019-03-03 09:31
Ok.  I’ll look as soon as I can.  These were all TravisCI builds in fresh spksrc containers right?  I assume über clean but confirming while I feel bad that I didn’t get a chance to look yet.
