### ISSUE TITLE
ffmpeg 4.4.2-43 cannot find libatomic.so.1

### ISSUE THREAD

**Issue by jesus2099** [SynoCommunity/spksrc#5287] opened 2022-05-27 07:09 UTC
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

ffmpeg

### Package Version

4.4.2-43

### Device Model

DS213+

### Device Architecture

PPC

### Firmware Version

6

### What happened?

Since version 4.4.2-43 on DSM 6, I have this error message:

> `/usr/local/ffmpeg/bin/ffmpeg: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory`

I cannot run `/usr/local/ffmpeg/bin/ffmpeg` any more.

### Reproduction steps

```bash
1. Install latest ffmpeg package
2. Run `/usr/local/ffmpeg/bin/ffmpeg`
```

### Install Log

```log
I am not on the computer, I will paste them here in a few hours.

`/var/log/packages/{package}.log` or for DSM<6: `/var/packages/{package}/target/var/{package}_installer.log`
```

### Service Log

```log
`/var/packages/{package}/var/{package}.log or for DSM<6: /var/packages/{package}/target/var/{package}.log`
```

### Other Logs

```log
`/var/log/messages, /var/log/synopkg.log`
```

**Comment by jesus2099** [comment] 2022-05-27 07:09
Copied over from https://github.com/th0ma7/synology/issues/15

**Comment by hgy59** [comment] 2022-05-27 08:17
@jesus2099 please provide the full DSM version under "Firmware Version", probably this error comes with the latest update "Update 6"?

**Comment by hgy59** [comment] 2022-05-27 10:12
duplicate of #5254

**Closed by hgy59** 2022-05-27 10:12 UTC
Labels: bug

**Comment by jesus2099** [comment] 2022-05-27 10:16
> @jesus2099 please provide the full DSM version under "Firmware Version", probably this error comes with the latest update "Update 6"?

You're right, I have upgraded DSM at the same time.
I have now added the exact version and I found the logs and pasted them, as well.

**Comment by jesus2099** [comment] 2022-05-27 10:18
I see some **_No such file or directory_** in the install logs.
ℹ️ Maybe you could have a look by reopening this ticket?
I already mentioned that this issue caused #5254. :)

**Comment by hgy59** [comment] 2022-05-27 10:31
@jesus2099 please continue this discussion in #5254, as it is related to PPC archs and therefore the same issue.

**Comment by th0ma7** [comment] 2022-05-28 20:00
New ffmpeg version fixing this issue now released

**Comment by jesus2099** [comment] 2022-05-29 22:47
Thanks so much!
@th0ma7,
My DS213+ Package Center (`https://packages.synocommunity.com/`) still only sees ffmepg 4.4.2-43, two days after (rebooted several times, since then).
I do see 4.4.2-44 on [SynoCommunity website](https://synocommunity.com/package/ffmpeg), though.
Is there always a delay, like that?

**Comment by hgy59** [comment] 2022-05-29 22:59
> Is there always a delay, like that?

Yes, it takes up to 48 hours until the package center sees new packages.

_BTW: this time mine was fast and saw the update about one hour ago (i.e. 27h after publishing)._

**Comment by jesus2099** [comment] 2022-05-29 23:12
Thanks for the information! :)

**Comment by jesus2099** [comment] 2022-06-01 09:02
Thank you so much, it works great, now!

**Comment by jesus2099** [comment] 2022-06-06 20:10
Just in case it is linked, I now have this kind of error:

    /usr/local/ffmpeg/bin/ffmpeg: error while loading shared libraries: /var/packages/ffmpeg/target/lib/libx265.so.199: R_PPC_REL24 relocation at 0x0be46cfc for symbol `pthread_mutex_init' out of range

I can create a new ticket.

**Comment by th0ma7** [comment] 2022-06-06 20:20
Please do, thnx
