### ISSUE TITLE
SabNzb-Sickbeard-Couchpotato doesn't work with DSM6

### ISSUE THREAD

**Issue by shabazz95** [SynoCommunity/spksrc#2277] opened 2016-04-21 20:26 UTC
All these three packages doesnt work anymore on DSM6.0.

Is there any solution or simply not compatible ?

"Echec lors du lancement de la réparation du paquet".

**Comment by Paradoxx2015** [comment] 2016-04-22 07:03
Same problem. The app Sickbreard-custon and couchpotato in my case. They work if i SSH (root) and use ./start-stop-status start in script folder for the app. But they will not start thru the package center.

**Comment by Dr-Bean** [comment] 2016-04-22 08:58
Duplicate of #2207 and related to #2216.

**Closed by Dr-Bean** 2016-04-22 08:58 UTC
