### ISSUE TITLE
GateOne Install not possible

### ISSUE THREAD

**Issue by LeZef29** [SynoCommunity/spksrc#5405] opened 2022-08-25 09:47 UTC
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

GateOne

### Package Version

20171125-8

### Device Model

DS120J

### Device Architecture

ARMv7

### Firmware Version

DSM 7.1.1-42951(RC)

### What happened?

Unable to install
![invalid-gateone](https://user-images.githubusercontent.com/112076636/186632013-062c177d-54cf-48b8-b79a-47f0cd151003.png)

### Reproduction steps

```bash
1.try to install
2.Unable to install du to invalid file format.
```

### Install Log

```log
.blabla.nothingmore
```

### Service Log

```log
.blabla.nothingmore
```

### Other Logs

```log
.blabla.nothingmore
```

**Comment by BenjV** [comment] 2022-08-25 10:58
There is no DSM7 version of GateOne available, only DSM 6

**Comment by LeZef29** [comment] 2022-08-25 11:53
Ok xas not aware about this... just DSM is in fault!

**Comment by hgy59** [comment] 2022-08-25 16:27
The fault is in synocommunity repository software. It offers DSM 5/6 packages for DSM 7 (it is mentioned on the readme package: _Despite you see packages of SynoCommunity in the Package Center of your Diskstation with DSM 7, some of the packages are not compatible with DSM 7._)

But nobody has time to fix this....
see https://github.com/SynoCommunity/spkrepo/issues/63

**Comment by WoosterInitiative** [comment] 2022-10-04 18:10
This should be closed as it is a DSM 7 compatibility question, not a bug. There are ~350 open issues, this shouldn't be inflating that number.

**Comment by nurous** [comment] 2022-11-02 12:43
I think this is due to the dependency on Python 2.7 (which AFAIU doesn't install because DSM 7 comes with python 3 installed).

@m4tt075 Any chance you could get it running with python 3 and drop the dependency on the broken `python` package?

**Comment by hgy59** [comment] 2022-11-02 17:44
@nurous gateone does definitifly not run with python3.
See https://github.com/liftoff/GateOne/issues/752, but there is almost no chance that someone ports this source (that is not maintained since 5 years and latest official release was 2012/11/02) to python 3

**Comment by nurous** [comment] 2022-11-03 02:16
Could it be replaced with something that is maintained like [Hyper](https://hyper.is/)?

**Comment by hgy59** [comment] 2022-11-03 18:24
@nurous are you sure that hyper can be used with a web browser on the client? So far I think it is an electron app, that does not run in a browser, and therefore it is not a solution for headless systems (i.e. without a desktop).

**Comment by hgy59** [comment] 2022-11-04 11:10
There are some alternatives to gateone.
I successfully tested "Shell In A Box" (https://github.com/shellinabox/shellinabox).
**But none of such applications will ever run on DSM 7, as root privileges are required.**

For shell access you should consider to use SSH with a client like PuTTY.
If one really (really?) needs shell access from remote, use SSH over VPN.

**Closed by hgy59** 2022-11-04 11:10 UTC
Labels: bug
