### ISSUE TITLE
Owncloud 8.1.1-7: Failed to install "owncloud": "Incorrect MySQL root password"

### ISSUE THREAD

**Issue by caco3** [SynoCommunity/spksrc#2136] opened 2016-02-13 19:10 UTC
I am failing to install owncloud 8.1.1-7 on Synology DSM 6beta2.

It always ends with the error "Incorrect MySQL root password".

I made sure the trust level is correct, even had it on "Any publisher".
I have phpMyAdmin installed and checked that the root password is matching and working.
Also I created a folder /volume1/owncloud" beforehand.

Is there a way to see any log output?
##

**Comment by the1ts** [comment] 2016-02-25 21:22
I think that owncloud has the same issues with Synology DSM 6Beta as Newznab has. Namely mysql is nolonger at /usr/syno/mysql/bin/mysql, so the installer.sh fails on the preinst stage through failing to find the mysql binary, not login.

Seems we'll need to have some tests for DSM version to change at least that variable.

**Comment by ongobongo** [comment] 2016-03-06 08:02
So a quick-fix in the meantime would be:
```
sudo mkdir /usr/syno/mysql
sudo mkdir /usr/syno/mysql/bin
sudo ln -s /bin/mysql /usr/syno/mysql/bin/mysql
```

**Comment by gliderguider** [comment] 2016-03-25 15:59
I've also just encountered this issue, and had also created the owncloud folder beforehand.

**Comment by symera** [comment] 2016-03-26 14:19
Same issue here while trying to install Roundcube on DSM6.
@the1ts I guess the binary is now located in `/<volume>/@appstore/MariaDB/usr/bin/mysql`

**Comment by supachupa** [comment] 2016-03-31 02:42
hi there.. based on your previous comments, I as able to get this installed by:
1. create directory: /usr/syno/mysql/bin
2.  ln -s /user/local/bin/mysql /usr/syno/mysql/bin/mysql
Now I just have "Can't create or write into the data directory /volume1/owncloud" to contend with...

**Comment by chbwien** [comment] 2016-04-15 14:53
Same problem here: DSM 6 and the password is wrong whatever I do... Any solution for that???

**Comment by supachupa** [comment] 2016-04-15 22:10
I had to SSH in and set the mysql root password manually to fix this.  
http://www.herlitz.nu/2013/07/31/administering-a-synology-mysql-server/ <http://www.herlitz.nu/2013/07/31/administering-a-synology-mysql-server/>

**Comment by Vitriia** [comment] 2016-04-21 10:50
@supachupa , it works ? Can you explain us how you fix it ? Thx :)

**Comment by chbwien** [comment] 2016-04-21 11:15
I have given up. I've installed owncloud myselve (without the package):

- Installed MariaDB
- Created an owncloud user and an owncloud table
- Created a shared directory and set the rights via console to root:http 0770
- Added the owncloud directoy to the php basedir
- Installed the latest 9 version of owncloud (with the owncloud user, the owncloud table and the /volume1/owncloud shared directory)

Everything works as expected and you can do the backup using hyperbackup (MariaDB, web/owncloud, shared owncloud diectory). You have to add another directory to the php basedir as explained by the owncloud status.

**Comment by gnacho** [comment] 2016-05-19 05:49
Same problem here. Is not just owncloud, any package with Mariadb dependency is failing to install. I even restore the Synology to factory defaults but the problem persists.

**Comment by gnacho** [comment] 2016-05-28 16:38
What worked for me

```
mkdir /usr/syno/mysql
mkdir /usr/syno/mysql/bin 
ln -s /usr/bin/mysql /usr/syno/mysql/bin/mysql

```
source: https://github.com/SynoCommunity/spksrc/issues/2217

**Comment by gnacho** [comment] 2016-06-06 20:06
And had to do it again after upgrade DSM :(

**Comment by buzter** [comment] 2016-06-15 09:53
Hello, I had the same problem. But then I found this tutorial and it works perfectly for me now: https://forum.synology.com/enu/viewtopic.php?t=116708

**Comment by Dr-Bean** [comment] 2016-06-15 10:17
@buzter This is a bugtracker for SynoCommunity packages. It's fine if you don't use one of our packages, we don't mind that at all, but you don't need to suggest a manual installation as an alternative here.

**Comment by buzter** [comment] 2016-06-15 10:43
**@Dr-Bean** Okay, I understand. Sorry for that.
I really tried to make Your package work. But I failed. So I only wanted to show how to make OC work in other ways.

**Comment by Dr-Bean** [comment] 2016-06-15 10:45
Sure, but that doesn't belong here. Your suggestion is the same as saying: "Hey, if your car has a flat tire because of bad road conditions. Don't repair the car, just get yourself a kitcar instead: after building it, it works fine for me!"

We know the package doesn't work on DSM6...that's why the issue is open, and labeled as such.

**Comment by supachupa** [comment] 2016-06-15 11:11
Dear “Dr” Bean

Not sure if your analogy works or if I can come up with one that works better, but it’s more like needing to get to work when your car breaks down and your neighbour offers a workaround while you wait for the dealer to get through the backlog.  You do sound a little unnecessarily defensive, for some reason.  The spirit of open source is that we’re all helping each other for free.. so if we’re finding workarounds, it’s meant to help each other get things working until the packages are fixed.. nothing more.  Do you think we are happy to sit around for a few months until things get fixed when we can fix it ourselves? No.  If need be, I could compile a kernel from scratch and build up an OS that suits my purposes.. spending many hours in the process, but I sure as hell don’t want to waste my time on that shit anymore. We all acknowledge that a package is the most efficient way for the masses… so keep up the good work, but don’t get defensive if we circumvent slow processes.  We do so because we want stuff now and we also don’t want to press you knowing that it’s all voluntary.  Once things are fixed, we will gladly use that method! 

Thanks for your hard work.

**Comment by Dr-Bean** [comment] 2016-06-15 12:03
Okay, I didn't wan tto get into a discussion about it. Again, this is not a generic discussion forum to talk about all things Synology or Owncloud. This is a package bugtracker. Feel free to contribute, but please keep it focused on the package.

**Comment by graffen** [comment] 2016-06-20 09:05
Any update on when this issue will be fixed? Should I hold my breath (it's been open since Feb 13th it seems) or just go for the manual install?

**Comment by gnacho** [comment] 2016-06-20 09:23
Didn't work my solution?

**Comment by mettix** [comment] 2016-06-23 15:02
It freaks me out.. I want to uninstall owncloud I have this error also for like ages :( all 'fixed' wont work for me. Or I must have missed one..

**Comment by gitty8** [comment] 2016-06-25 12:25
Hi, im getting same error - ANY updates?

**Comment by mettix** [comment] 2016-07-04 13:18
So, I have made a backup of my NAS, did a format and did a restore of settings, files but no applications :)

**Comment by fuuman** [comment] 2016-07-06 10:47
Same problem here. Solution would be awesome. It's really annoying.

**Comment by MathieuMH** [comment] 2016-07-06 18:18
I'm encountering this issue as well. Running DSM6, and unable to install OwnCloud. I'dd like a more permanent solution instead of doing it every time I install a new update.

**Comment by jknaebel** [comment] 2016-09-26 19:39
Hallo to all.
Take a look at the date of my comment......
OpenCloud is still not running on DSM 6.
Any solutions? Any updates?

Thanks.

**Comment by KaraokeStu** [comment] 2016-09-26 20:09
Unfortunately we're still having issues with DSM 6 and our packages. We are looking at possible solutions, but it's not simple and it affects all packages, not just this one.

**Comment by benpaddlejones** [comment] 2016-10-25 22:45
I can confirm this issue is still present in 8.1.1-7 on a DS215j running DSM 6.0.2-8451 Update 2 with vol1/ownCloud created a HTML permisisons applied before trying install.

**Comment by tofuSCHNITZEL** [comment] 2017-02-03 17:24
any news?

**Comment by magefesa** [comment] 2017-02-13 11:37
Same question ... Any solution ? Thanks to all who hav spend some time with this  !

**Comment by tchwpkgorg** [comment] 2017-02-16 15:31
@Dr-Bean "This is a bugtracker for SynoCommunity packages. It's fine if you don't use one of our packages, we don't mind that at all, but you don't need to suggest a manual installation as an alternative here."

This is normally a sane advice, but this issue is opened already for a year! So either close the issue as "wontfix" and remove owncloud package, because it's broken, or make a fix I would say.

**Comment by ymartin59** [comment] 2017-03-26 16:48
I did an installation from scratch on DSM 6.0.1 (virtual machine):
- install packages Web station, Apache 2.2, PHP 5.6 and MariaDB (no root password set)
- run `sudo mkdir /volume1/owncloud`
- install owncloud package providing only database password (leave defaults for others)
- Web station configurations: PHP extensions and `open_basedir` appended with `:/dev/urandom:/volume1/owncloud`

May you please try again after resetting MariaDB root password ? Or after reinstalling MariaDB ?

WARNING: do not uninstall `owncloud` package on DSM 6, or you will lost management interface !! Fix to apply on SSH: `synoservice --enable DSM; synoservice --start DSM`

**Comment by ymartin59** [comment] 2017-03-26 16:50
I am working on ownCloud package fixes for DSM 6.0: typically check preconditions on packages, document post-configuration in webstation if cannot be scripted

**Comment by Remvis** [comment] 2017-05-04 13:19
Is there some progress in the 'new' owncloud package for DSM6.0?

Manual installation doesn't work for me!

**Comment by Sigawan** [comment] 2018-02-06 06:15
Installation of the owncloud package on the latest  DSM 6.1.5 15254 fails with the same error as most other packages hosted at synocommunity 'incorrect mysql root password'

Is any work being done on this generic problem in the years since it was first reported?

**Comment by ymartin59** [comment] 2018-02-09 06:17
There is no chance ownClound package to be upgraded - I should probably disabled it just now. I plan a brand new DSM 6 package for NextCloud.

**Comment by LinuxArchitects** [comment] 2018-07-22 14:07
That works for me 👍 

`ssh admin@syno`
`sudo su - `
`find / -type f -iname "mysql"`

/run/lock/subsys/mysql
/volume1/@appstore/MariaDB/etc/logrotate.d/mysql
**/volume1/@appstore/MariaDB/usr/bin/mysql**

`mkdir -p /usr/syno/mysql/bin`
`ln -s /volume1/@appstore/MariaDB/usr/bin/mysql /usr/syno/mysql/bin/mysql`

**Comment by wuseman** [comment] 2018-10-11 02:51
## This works nowadays. 

```ruby
mkdir -p /usr/syno/mysql/bin
ln -s /usr/bin/mysql /usr/syno/mysql/bin/mysql
chmod +x /usr/syno/mysql/bin/mysql
mkdir /volume1/private/owncloud
```

**Comment by 53645714n** [comment] 2018-10-11 08:17
> ## This works nowadays.
> 
> ```ruby
> mkdir -p /usr/syno/mysql/bin
> ln -s /usr/bin/mysql /usr/syno/mysql/bin/mysql
> chmod +x /usr/syno/mysql/bin/mysql
> mkdir /volume1/private/owncloud
> ```

Yes, this works for me!

**Comment by SukkoPera** [comment] 2019-10-22 19:25
Does not work for me. owncloud installs successfully but then its web interface cannot be accessed.

I found this in my logs:
```
/var/packages/owncloud/scripts/installer: line 63: /etc/php/conf.d/com.synocommunity.packages.owncloud.ini: No such file or directory
/var/packages/owncloud/scripts/installer: line 64: /etc/httpd/sites-enabled-user/com.synocommunity.packages.owncloud.conf: No such file or directory
```

**Comment by dirksu** [comment] 2019-12-31 21:15
update:
mysql now resides in /bin and still needs to be linked to /usr/syno/mysql/bin/mysql
and a manual creation of /volume1/owncloud was necessary.

**Comment by mreid-tt** [comment] 2023-03-31 12:00
Hello! It appears that this issue has been open for a while without any recent updates. A new version of ownCloud (v10.12-9) has been released, which may address this issue. The latest version defaults to using SQLite instead of MariaDB (newer MySQL), which provides faster setup times.

However, upgrading from ownCloud v8.1.1 to v10.12 is not a direct upgrade path, and you will need to manually backup your configuration and files to reapply them to the new version. Please take your time to test the latest version and let us know if the issue persists. If we do not hear from you in the next few days, we will assume that the issue has been resolved and close this ticket. Thank you!

**Closed** 2023-04-02 17:46 UTC
Labels: dsm 6
