### ISSUE TITLE
ffmpeg  libraries: libgomp.so.1: cannot open shared object file

### ISSUE THREAD

**Issue by Saincho** [SynoCommunity/spksrc#2498] opened 2016-10-24 13:40 UTC
_For new Package Requests, see the guidelines_  
### Setup

_Package Name:_ ffmpeg
_Package Version:_ 3.1.2-3

_NAS Model:_xpenology
_NAS Architecture:_i686
_DSM version:_5.2
### Expected behavior

Execute in console ffmpeg commnad not working
### Actual behavior

error message:
./ffmpeg: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
### Steps to reproduce

_1._
_2._
_3._
#### Package log

_Check Package Center or `/usr/local/{package}/var/`_

```
Insert the package log here
```
#### Other logs

_E.g. `/var/log/messages` or `/var/log/synopkg.log`_

```
Insert log here
```

**Comment by cytec** [comment] 2016-10-24 14:39
@GuillaumeSmaha you got this too?

**Comment by Saincho** [comment] 2016-10-24 16:21
I have the library in / lib but I guess it is not the required version. 
Where I can get the right version? 
What I copy directory?

**Comment by GuillaumeSmaha** [comment] 2016-10-24 17:13
@cytec I will check it

**Comment by GuillaumeSmaha** [comment] 2016-10-24 19:12
No problem on my DSM (D415+ x64 DSM 6.2)
I'll check the library dependencies

**Comment by GuillaumeSmaha** [comment] 2016-10-24 19:28
On the package for x64 :
LD_LIBRARY_PATH=./lib ldd bin/ffmpeg 

	linux-vdso.so.1 =>  (0x00007ffd62dd1000)
	libavdevice.so.57 => ./lib/libavdevice.so.57 (0x00007f5ae6bce000)
	libavfilter.so.6 => ./lib/libavfilter.so.6 (0x00007f5ae67c1000)
	libavformat.so.57 => ./lib/libavformat.so.57 (0x00007f5ae63b6000)
	libavcodec.so.57 => ./lib/libavcodec.so.57 (0x00007f5ae4e63000)
	libpostproc.so.54 => ./lib/libpostproc.so.54 (0x00007f5ae4c3d000)
	libswresample.so.2 => ./lib/libswresample.so.2 (0x00007f5ae4a21000)
	libswscale.so.4 => ./lib/libswscale.so.4 (0x00007f5ae479b000)
	libavutil.so.55 => ./lib/libavutil.so.55 (0x00007f5ae4523000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5ae4205000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5ae3fe7000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5ae3c20000)
	libfribidi.so.0 => ./lib/libfribidi.so.0 (0x00007f5ae3a05000)
	libfreetype.so.6 => ./lib/libfreetype.so.6 (0x00007f5ae3732000)
	libfontconfig.so.1 => ./lib/libfontconfig.so.1 (0x00007f5ae34e4000)
	libass.so.5 => ./lib/libass.so.5 (0x00007f5ae32a9000)
	libssl.so.1.0.0 => ./lib/libssl.so.1.0.0 (0x00007f5ae3038000)
	libcrypto.so.1.0.0 => ./lib/libcrypto.so.1.0.0 (0x00007f5ae2bde000)
	librtmp.so.1 => ./lib/librtmp.so.1 (0x00007f5ae29c0000)
	libz.so => ./lib/libz.so (0x00007f5ae27a5000)
	libbluray.so.1 => ./lib/libbluray.so.1 (0x00007f5ae2566000)
	libx265.so.87 => ./lib/libx265.so.87 (0x00007f5ae1f0b000)
	libx264.so.148 => ./lib/libx264.so.148 (0x00007f5ae1b62000)
	libvpx.so.4 => ./lib/libvpx.so.4 (0x00007f5ae173f000)
	libvorbisenc.so.2 => ./lib/libvorbisenc.so.2 (0x00007f5ae1489000)
	libvorbis.so.0 => ./lib/libvorbis.so.0 (0x00007f5ae1251000)
	libvo-amrwbenc.so.0 => ./lib/libvo-amrwbenc.so.0 (0x00007f5ae102c000)
	libtheoraenc.so.1 => ./lib/libtheoraenc.so.1 (0x00007f5ae0de8000)
	libtheoradec.so.1 => ./lib/libtheoradec.so.1 (0x00007f5ae0bcb000)
	libspeex.so.1 => ./lib/libspeex.so.1 (0x00007f5ae09a8000)
	libopus.so.0 => ./lib/libopus.so.0 (0x00007f5ae0739000)
	libopenjp2.so.7 => ./lib/libopenjp2.so.7 (0x00007f5ae04f0000)
	libopencore-amrwb.so.0 => ./lib/libopencore-amrwb.so.0 (0x00007f5ae02d4000)
	libopencore-amrnb.so.0 => ./lib/libopencore-amrnb.so.0 (0x00007f5ae0096000)
	libmp3lame.so.0 => ./lib/libmp3lame.so.0 (0x00007f5adfe09000)
	libfdk-aac.so.1 => ./lib/libfdk-aac.so.1 (0x00007f5adfb13000)
	libsoxr.so.0 => ./lib/libsoxr.so.0 (0x00007f5adf89c000)
	/lib64/ld-linux-x86-64.so.2 (0x000056196020b000)
	libpng16.so.16 => ./lib/libpng16.so.16 (0x00007f5adf65c000)
	libexpat.so.1 => ./lib/libexpat.so.1 (0x00007f5adf427000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5adf223000)
	libxml2.so.2 => ./lib/libxml2.so.2 (0x00007f5adee59000)
	libnuma.so.1 => ./lib/libnuma.so.1 (0x00007f5adec4d000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5ade8c5000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5ade6ac000)
	libogg.so.0 => ./lib/libogg.so.0 (0x00007f5ade4a4000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f5ade276000)

And without the lib from the package, I have this libs :

	linux-vdso.so.1 =>  (0x00007ffd4294e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0ae708e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0ae6e70000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0ae6aa9000)
	/lib64/ld-linux-x86-64.so.2 (0x000055a55779a000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0ae20ac000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0ae174e000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0ae1535000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f0ae10ff000)


Maybe we should add `--disable-libgomp` for a set of archs

**Comment by cytec** [comment] 2016-10-25 14:46
seems like a good idea. et least for those arches which are missing libgomp

**Comment by GuillaumeSmaha** [comment] 2016-10-25 16:53
If I understand libgomp is a part of gcc to use OpenMP and OpenACC.
When it compiles for i686, it uses the  gcc version provided by Synology for this arch so the version of libgomp should be egal to the version installed on the NAS.
I will check the version of libgomp of i686 for DSM 5.2.

@Saincho Could you give us the result of the command `find /usr -name "*libgomp*"` ?

**Comment by Saincho** [comment] 2016-10-25 18:23
I have the library in / lib but I guess it is not the required
version. Where I can get the right version? What I copy directory?


2016-10-24 16:39 GMT+02:00 cytec <notifications@github.com>:

**Comment by Saincho** [comment] 2016-10-25 21:58
find /usr -name *libgomp* no result. The command find / -name libgomp* result in /lib/libgomp.so.1

the command LD_LIBRARY_PATH=./lib ldd bin/ffmpeg produces:
        linux-vdso.so.1 (0x00007fffd2caa000)
        libavdevice.so.57 => /usr/local/ffmpeg/lib/libavdevice.so.57 (0x00007f031f1f6000)
        libavfilter.so.6 => /usr/local/ffmpeg/lib/libavfilter.so.6 (0x00007f031ede5000)
        libavformat.so.57 => /usr/local/ffmpeg/lib/libavformat.so.57 (0x00007f031e9db000)
        libavcodec.so.57 => /usr/local/ffmpeg/lib/libavcodec.so.57 (0x00007f031d3e9000)
        libpostproc.so.54 => /usr/local/ffmpeg/lib/libpostproc.so.54 (0x00007f031d1bc000)
        libswresample.so.2 => /usr/local/ffmpeg/lib/libswresample.so.2 (0x00007f031cfa0000)
        libswscale.so.4 => /usr/local/ffmpeg/lib/libswscale.so.4 (0x00007f031cd12000)
        libavutil.so.55 => /usr/local/ffmpeg/lib/libavutil.so.55 (0x00007f031ca9d000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f031c79f000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f031c583000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f031c1d7000)
        libfribidi.so.0 => /usr/local/ffmpeg/lib/libfribidi.so.0 (0x00007f031bfbe000)
        libfreetype.so.6 => /usr/local/ffmpeg/lib/libfreetype.so.6 (0x00007f031bcea000)
        libfontconfig.so.1 => /usr/local/ffmpeg/lib/libfontconfig.so.1 (0x00007f031ba9c000)
        libass.so.5 => /usr/local/ffmpeg/lib/libass.so.5 (0x00007f031b861000)
        libssl.so.1.0.0 => /usr/local/ffmpeg/lib/libssl.so.1.0.0 (0x00007f031b5f1000)
        libcrypto.so.1.0.0 => /usr/local/ffmpeg/lib/libcrypto.so.1.0.0 (0x00007f031b1ab000)
        librtmp.so.1 => /usr/local/ffmpeg/lib/librtmp.so.1 (0x00007f031af8d000)
        libz.so => /usr/local/ffmpeg/lib/libz.so (0x00007f031ad72000)
        libbluray.so.1 => /usr/local/ffmpeg/lib/libbluray.so.1 (0x00007f031ab37000)
        libx265.so.87 => /usr/local/ffmpeg/lib/libx265.so.87 (0x00007f031a504000)
        libx264.so.148 => /usr/local/ffmpeg/lib/libx264.so.148 (0x00007f031a148000)
        libvpx.so.4 => /usr/local/ffmpeg/lib/libvpx.so.4 (0x00007f0319d45000)
        libvorbisenc.so.2 => /usr/local/ffmpeg/lib/libvorbisenc.so.2 (0x00007f0319a9a000)
        libvorbis.so.0 => /usr/local/ffmpeg/lib/libvorbis.so.0 (0x00007f0319867000)
        libvo-amrwbenc.so.0 => /usr/local/ffmpeg/lib/libvo-amrwbenc.so.0 (0x00007f0319643000)
        libtheoraenc.so.1 => /usr/local/ffmpeg/lib/libtheoraenc.so.1 (0x00007f03193f9000)
        libtheoradec.so.1 => /usr/local/ffmpeg/lib/libtheoradec.so.1 (0x00007f03191da000)
        libspeex.so.1 => /usr/local/ffmpeg/lib/libspeex.so.1 (0x00007f0318fb7000)
        libopus.so.0 => /usr/local/ffmpeg/lib/libopus.so.0 (0x00007f0318d47000)
        libopenjp2.so.7 => /usr/local/ffmpeg/lib/libopenjp2.so.7 (0x00007f0318afd000)
        libopencore-amrwb.so.0 => /usr/local/ffmpeg/lib/libopencore-amrwb.so.0 (0x00007f03188e1000)
        libopencore-amrnb.so.0 => /usr/local/ffmpeg/lib/libopencore-amrnb.so.0 (0x00007f03186a5000)
        libmp3lame.so.0 => /usr/local/ffmpeg/lib/libmp3lame.so.0 (0x00007f0318418000)
        libfdk-aac.so.1 => /usr/local/ffmpeg/lib/libfdk-aac.so.1 (0x00007f0318120000)
        libsoxr.so.0 => /usr/local/ffmpeg/lib/libsoxr.so.0 (0x00007f0317eb5000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f031f405000)
        libpng16.so.16 => /usr/local/ffmpeg/lib/libpng16.so.16 (0x00007f0317c74000)
        libexpat.so.1 => /usr/local/ffmpeg/lib/libexpat.so.1 (0x00007f0317a41000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f031783d000)
        libxml2.so.2 => /usr/local/ffmpeg/lib/libxml2.so.2 (0x00007f031747a000)
        libnuma.so.1 => /usr/local/ffmpeg/lib/libnuma.so.1 (0x00007f031726e000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f0316f91000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f0316d80000)
        libogg.so.0 => /usr/local/ffmpeg/lib/libogg.so.0 (0x00007f0316b7a000)
        libgomp.so.1 => not found

**Comment by sirjaymz** [comment] 2016-10-31 18:22
What can i do to assist in resolving this? 
DSM 5.2-5967 on DS1813+
When building based on the current spk/ffmpeg/Makefile ffmpeg in repos, i get same error, after installing and running onto 1813+.

**Comment by GuillaumeSmaha** [comment] 2016-10-31 20:10
Ok, I am sure that the bug is due to a version of gcc which is different on your DSM and on the compiling environment.
Now, there is 2 solutions :
- Fix the compiling environement
- Disable OpenMP on ffmpeg to exclude libgomp.

@sirjaymz I don't have things to ask yet but soon, I will need some checks on your DSM (I will give the command to execute).

**Comment by horfic** [comment] 2016-11-07 17:29
i got the same error

NAS Model: xpenology
NAS Architecture: x86_64
DSM version: 5.2-5565
Kernel: 3.10.35

**Comment by GuillaumeSmaha** [comment] 2016-11-07 19:17
I can reproduce with DSM 5.2-5967 (XPEnology) on the VM.

**Comment by GuillaumeSmaha** [comment] 2016-11-07 22:09
Ok I find a way to fix the issue

**Comment by GuillaumeSmaha** [comment] 2016-11-08 03:58
Fix is pushed. Now, I wait to check on DSM 6.0

**Comment by GuillaumeSmaha** [comment] 2016-11-08 04:22
Checked on DSM 6.0

**Comment by cytec** [comment] 2016-11-09 10:06
new version is published

**Closed by cytec** 2016-11-09 10:06 UTC

**Comment by GuillaumeSmaha** [comment] 2016-11-09 14:25
@Saincho @sirjaymz @horfic  Can you update and check if it works ?

**Comment by horfic** [comment] 2016-11-09 17:25
works for me, thanks for the quick fix

**Comment by Saincho** [comment] 2016-11-10 08:15
Seems to work without errors. Thank you so much.

**Comment by sirjaymz** [comment] 2016-11-17 03:27
Works +1 . DSM 5.2-5967 on DS1813+
