### ISSUE TITLE
New Python error with update

### ISSUE THREAD

**Issue by lostkt87** [SynoCommunity/spksrc#1744] opened 2015-06-07 05:35 UTC
Hello, not sure if anyone else is  experiencing the same issue. But after I updated Python sickbeard and Mylar. Bot have Python related errors... I've uninstalled all 3  then reinstalled, and still get the same thing.... 

Also is there a way to get the previous version of Python. Like a download link for an evansport synology ds214play. 

Thank you for your time and any help suggested.

**Comment by martymoose** [comment] 2015-06-07 07:22
same here  she's a dead after update  DS412

**Comment by Dr-Bean** [comment] 2015-06-07 08:12
Both the Sickbeard and the Mylar package worked when I tested. Couple questions:
- Check the log file. It's visible in DSM, but it's also available in `/usr/local/your-package/var`, makes for easier copy/pasting.
- Can you log in via command line (Putty), and enter the following command, followed by an enter:
`/var/packages/sickbeard/scripts/start-stop-status start`
For Mylar:
`/var/packages/mylar/scripts/start-stop-status start`

If there's output of either the command line or in the log, put it here (over 10 lines? put it on gist.github.com or pastebin, and link to it here)

**Comment by lostkt87** [comment] 2015-06-07 12:57
Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "/usr/local/python/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/volume1/@appstore/mylar/share/mylar/mylar/importer.py", line 451, in addComictoDB
shutil.copy(coverfile, comiclocal)
File "/usr/local/python/lib/python2.7/shutil.py", line 120, in copy
copymode(src, dst)
File "/usr/local/python/lib/python2.7/shutil.py", line 91, in copymode
os.chmod(dst, mode)
OSError: [Errno 1] Operation not permitted: '/volume1/Comics/Marvel/Groot (2015)/cover.jpg'

**Comment by lostkt87** [comment] 2015-06-07 12:59
This is what I'm getting anytime I add a series. Worked just fine before I updated Python. I can't add anything. And sickbeard starts, but when I try to add shows, it searches forever.

**Comment by Dr-Bean** [comment] 2015-06-07 13:12
>Operation not permitted: '/volume1/Comics/Marvel/Groot (2015)/cover.jpg'

That looks like a permissions issue to me. The `users` group should have read/write permissions on each of those directories (so `Comics`, `Marvel`, `Groot (2015)`. Unless you manually changed the package user or something like that.

As for Sickbeard, can't reproduce it. Check the debug log of Sickbeard. If might have issues with connecting to tvdb/tvrage, but there's nothing that we can do about that. 
On that note, the original Sickbeard repository hasn't seen a lot of development for quite a while now. In general, that might not be a problem, but getting bugs or issues fixed is a lot harder when there are no active developers.

**Comment by gborri** [comment] 2015-06-08 13:20
For me the problem is related to cheetah module:

DiskStation> python SickBeard.py
The Python module Cheetah is required

>>> import Cheetah
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named Cheetah

**Comment by gborri** [comment] 2015-06-08 13:21
looking around i have seen that there is a python executable in dir /usr/nbin that is 2.7.9.
the module shouldn't override this executable?

**Comment by Dr-Bean** [comment] 2015-06-13 08:31
@lostkt87 @martymoose Any updates to report?

**Comment by lostkt87** [comment] 2015-06-13 12:03
All good now

**Comment by Dr-Bean** [comment] 2015-06-17 12:04
Thanks  for the feedback @lostkt87. I'll close the issue as solved.

@martymoose Feel free to respond with detailed information and/or logs if you're still experiencing this issue. It's most likely a local issue, but if needed, we can probably help with that.

**Closed by Dr-Bean** 2015-06-17 12:04 UTC
Labels: status/more-info-needed
