### ISSUE TITLE
Syncthing connection error after upgrade to version 11.15

### ISSUE THREAD

**Issue by BenjV** [SynoCommunity/spksrc#1792] opened 2015-07-18 10:22 UTC
After I upgraded to version 11.15 the gui has problems giving commands to syncthing. Every time I try to do something (like adding a device) I get a popup screen with an error message like:

Connecting Error
Syncthing seems to be experiencing a problem processing your request. Please refresh the page or restart Syncthing if the problem persists.

**Comment by Dr-Bean** [comment] 2015-07-18 17:52
Armv5 arch?
If so, quickfix: download https://github.com/syncthing/syncthing/releases/download/v0.11.15/syncthing-linux-arm-v0.11.15.tar.gz, extract the binary and put it in `/usr/local/syncthing/bin`.

Ref https://github.com/SynoCommunity/spksrc/pull/1631.

**Comment by Dr-Bean** [comment] 2015-07-19 08:46
Seems that setting `CGO_ENABLED=0` in `cross/syncthing/Makefile` fixes the arm build for ARMv5/88f6281. Can't test other ARM arches unfortunately, and x64 doesn't seem to have an issue with it.

This also follows the approach Syncthing for their build env. (https://github.com/syncthing/build/blob/master/Dockerfile#L54, with a little bit of background here: https://github.com/calmh/gonative/blob/master/gonative.go#L27).

For now, I'll disable CGO for arm only and release a new package later today for all arm-based arches.
 
/cc @cytec.

**Comment by Dr-Bean** [comment] 2015-07-19 09:23
Syncthing 0.11.15-5 has been released for ARM-based arches (88f6281, alpine/4k, armada*, comcerto2k) 
@BenjV Please check if this solves your issues.

**Comment by BenjV** [comment] 2015-07-19 12:12
I have a DS414 which has a armadasXp (armv7l).
Version 0.11.15-5 does not work at all.
It says "unknown device) in the top left corner where it normally displays the name of the NAS.

By the way windows does not have this problem

**Comment by Dr-Bean** [comment] 2015-07-19 12:24
Yes, Syncthing is a bit on the heavy side for some devices, the cpu/mem usage depends a lot on the amount and total size of the dirs you're syncing.
It especially takes a while before the interface is started and for Syncthing to complete reading the configuration from a cold start.

**Comment by Dr-Bean** [comment] 2015-07-19 12:57
I noticed that Syncthing 0.11.16 was just released. 
That means that if the auto-update is done, it'll replace our Syncthing binary with one created by the Syncthing devs, invalidating your test...

**Comment by BenjV** [comment] 2015-07-19 13:02
I tested with 11.15-5
I disabled the auto update.
I'll try 11.15-6 later

**Comment by BenjV** [comment] 2015-07-19 14:21
I did an upgrade to 11.15-6
All is functioning ok.

Side remark. 11.15-5 and 11.15-6 are not syncing with eachother.
So the same version on both sides is needed

**Comment by Dr-Bean** [comment] 2015-07-19 14:32
To be clear, you mean that package `0.11.15-5` (format: syncthing version-package version) does not sync with package `0.11.15-5` - which has been auto-updated to syncthing `0.11.16`?

That doesn't make sense to me. The syncthing release notes are mentioned here: https://github.com/syncthing/syncthing/releases. There's nothing that prevents 0.11.15 to sync with 0.11.16 from what I can see, and I did not release a new package version.

**Comment by BenjV** [comment] 2015-07-19 14:45
There is no error, but my windows versie autoupdated tot 11.15-6 and the Nas stayed on 11.15-5
After that, the Nas site of the sync stayed "out-of-sync" and would not sync anymore.

Although there was nothing to sync because nothing changed on this Pc site but it stayed in the status "out of sync" and never reached the status "up to date".

After I upgraded the Nas to 11.15-6 both sites(after a rescan) got the status "up to date" again.

**Comment by Dr-Bean** [comment] 2015-07-19 15:26
Err...the Syncthing version is `0.11.15` or `0.11.16`. The appended `-5` is our package revision, it's not part of the Syncthing version format.
So, I assume you mean that your Syncthing installation on Windows autoupdated from `0.11.15` to `0.11.16`, while the Syncthing version on your NAS stayed on `0.11.15`. (using the latest package revision, which is `5`). Yes?

If the above is the correct scenario, then I cannot reproduce the issue. I have a NAS on 0.11.15 (using the `-5` package revision), and a Windows client on 0.11.16. After sync was completed (and data was actually available), the status changed to 'Up to Date' as expected.

Seeing as the original issue has been resolved, I think we can close this. Agree?

**Comment by cytec** [comment] 2015-07-19 16:19
@Dr-Bean yeah i've came across some errors with CGO_ENABLED on arm devices too, trying to build another go package... i don't really know why but good to know disable CGO did the trick for you :)

**Comment by Dr-Bean** [comment] 2015-07-20 09:42
Fixed with https://github.com/SynoCommunity/spksrc/commit/95fe7ed24c2f8bbe4d38dd2439d7cfcc814617ac

**Closed by Dr-Bean** 2015-07-20 09:42 UTC
