### ISSUE TITLE
[Package Request] gitea package for DSM7

### ISSUE THREAD

**Issue by Wuszek** [SynoCommunity/spksrc#4749] opened 2021-07-21 15:42 UTC
Name: gitea
Description: The goal of this project is to make the easiest, fastest, and most painless way of setting up a self-hosted Git service. Using Go, this can be done with an independent binary distribution across all platforms which Go supports, including Linux, macOS, and Windows on x86, amd64, ARM and PowerPC architectures. Want to try it before doing anything else? Do it with the online demo! This project has been forked from Gogs since 2016.11 but changed a lot.
Website: https://docs.gitea.io/en-us/
Software documentation: https://docs.gitea.io/en-us/
Build/Installation documentation: https://docs.gitea.io/en-us/
Source Code: https://github.com/go-gitea/gitea
Licence: https://github.com/go-gitea/gitea/blob/master/LICENSE

There is a script, that build package for DSM6.x and it works fine, but it should be updated to handle DSM7 correctly.
https://github.com/flipswitchingmonkey/gitea-spk

**Comment by hgy59** [comment] 2021-07-21 15:46
duplicate of #4256

**Comment by Wuszek** [comment] 2021-07-21 15:51
Actually my request is specific about package for DSM7, so linked solution in #4256 will not solve it (package will not install with root access)

**Comment by hgy59** [comment] 2021-07-21 15:54
@Wuszek you have to request this in the repository of the linked solution, as it is not based on synocommunity.

**Comment by Wuszek** [comment] 2021-07-21 16:12
I doubt it is possible, because this repository has not been updated for several years (the author has not accepted my PR for over a year). Therefore, I hope that we will be able to produce the package for DSM6 and DSM7 with the help of the synocommunity, and accessible from synocommunity store.

**Closed** 2022-01-02 20:44 UTC
Labels: request, upstream
