### ISSUE TITLE
BETA Test Syncthing!

### ISSUE THREAD

**Issue by crazyscow** [SynoCommunity/spksrc#1011] opened 2014-05-19 14:13 UTC
Syncthing is similiar to btsync, however its open source, for more information go to http://syncthing.net/

Thanks to @cytec he was able to create a working version of Syncthing for the Synology NAS. 
its in beta. and you can get it on the Package Center by adding http://cytec.us/spk/

dont forget to say thanks to cytec! =D

**Comment by ffreling** [comment] 2015-01-15 21:04
Is the package supposed to create the associated sc-syncthing group automatically?
I can't see it in the Control Panel and if I create one I am not sure how to put the syncthing user into that group.

I think I have some permission issues so for now I am running it as root (not ideal).

I was also wondering if the latest package was logging properly, to have more information in case of errors.

Thanks for the port :)

**Comment by tuochi** [comment] 2015-02-06 20:33
I have now the Synology 215j, can someone compile it also for the armada 375 cpu? please!!!
Thanks in advance!

**Comment by MoOx** [comment] 2015-03-04 06:21
FYI, it clearly seems that pulse is already dead. We should go foward focused on Syncthing. Any idea of the ETA ?

**Comment by cytec** [comment] 2015-03-04 11:34
there already is a spk for syncthing (0.9.4) in the repo.

**Comment by benhylau** [comment] 2015-03-05 02:37
Also want to try this out on 215j. Would be great if someone can compile this for Armada 375.

**Comment by benhylau** [comment] 2015-03-07 23:50
I see 375 in toolchains, is there a reason why the SPK isn't available [here](http://cytec.us/spk/)?

**Comment by tuochi** [comment] 2015-03-08 14:19
Here for 215j: http://www.share-online.biz/dl/FVK1DWKNU7C

If you get a permission denied error like this:
Stopping folder "FolderName" - open /yourSyncPath/.stfolder: permission denied

change permission/owner like this:

chmod 0755 /yourSyncPath/
chown syncthing:users -R /yourSyncPath/

**Comment by fbreve** [comment] 2015-03-09 19:06
So, what happened to sc-syncthing group?
I installed from the repository and I can't find this group.

**Comment by benhylau** [comment] 2015-03-10 05:15
Thanks @tuochi and @Diaoul I see armada 375 on here now: https://synocommunity.com/package/syncthing

**Comment by Dr-Bean** [comment] 2015-03-16 12:32
The missing arches for syncthing (6c9506ee0a3271a19b0308c31bdb91a8dfe74393) have been published on the repository.

**Comment by Dr-Bean** [comment] 2015-03-16 12:59
@cytec...what's that `v` doing in there: `SPK_VERS = v0.10.5`? ;)

**Comment by cytec** [comment] 2015-03-16 14:45
@Dr-Bean a typo, can be removed i think :/

**Comment by gpopesc** [comment] 2015-03-21 22:28
Hello, I have the architecture 88f6281. First I install the the version 0.9.4 from Synocomunity which works great. Then I tried to install your latest version, but the package doesn't start. I tried with manual command /var/packages/syncthing/scripts/start-stop-status start, without any luck. Any thoughts how I can solve it? There is any log where I can see the any errors?

**Comment by Dr-Bean** [comment] 2015-03-21 22:54
@cytec I completely missed that edit :) You're probably right. 
That means that the following arches should be repackaged/reuploaded: `evansport cedarview bromolow armadaxp armada370 88f628x`.
Let's check if the group is created when reinstalling one of those packages, and if so, bump the version and reupload the packages.

**Comment by indusninja** [comment] 2015-03-24 11:09
I have the same problem. But its a bit worst for me. I installed the 0.9.4 version from Synocommunity and then moved over to manually install the latest spk from cytec. Now, I can't go back to the package shown on the Synocommunity list (i.e. 0.9.4). Every time I install the package, it installs 0.10.4 and doesn't run (illegal instruction (core dumped) error). I'm running it on a DS413j, i.e. 88f6282 and used the 88f6281 version from cytec.

**Comment by gpopesc** [comment] 2015-03-25 11:17
Yes, it happen now to me. I tried to fix it (uninstalled and installed several times both versions) and now I can not start either the old version(it is strange that it shows in description the new version from Cytec) For the time being i will stick to bittorrent sync, until cytec will fix it. I like more syncthing, it can be more customized and it is a really sync app on android devices (bittorrent makes only backup).

**Comment by cytec** [comment] 2015-03-25 13:03
I've disabled syncthing in my repository now.
So from now on you should only see synocommunity releases!

**Comment by sfmcnally** [comment] 2015-03-25 21:51
@cytec 
I'm not seeing syncthing in either repo now

**Comment by crazyscow** [comment] 2015-03-25 22:01
you need to check show betas in the package manager settings on your DSM ;)

**Comment by sfmcnally** [comment] 2015-03-25 23:34
Thanks man!

On Wednesday, March 25, 2015, crazyscow <notifications@github.com> wrote:

> you need to check show betas in the package manager settings on your DSM ;)
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/SynoCommunity/spksrc/issues/1011#issuecomment-86231859>
> .
>


-- 
Sent from my iPhone
Sean McNally
sfmcnally@gmail.com
859.583.3062 (cell)

**Comment by devjta** [comment] 2015-03-26 13:38
@cytec So WE (QORIQ) users will never be able to get Syncthing? And what did you mean with, you dont have the PPC binaries? What are you missing? The cross-compiler?

**Comment by cytec** [comment] 2015-03-26 13:50
@devjta nope. go doesn't run on ppc.

**Comment by devjta** [comment] 2015-03-26 14:04
@cytec So cross-compiling GO for PPC does not work or GO itself refuses to work on the NAS (after successfully build)?
And are there any go converter to C/C++, python, java, etc?

**Comment by jdbancal** [comment] 2015-03-26 14:44
I get a similar error as @indusninja on DS213 air (also armv5te) with the version of syncthing fetched from SynoCommunity in the Package center, version 0.10.5-2 : 

    DiskStation> /opt/bin/strace -f ./syncthing       
    execve("./syncthing", ["./syncthing"], [/* 18 vars */]) = 0
    getpid()                                = 26413
    --- SIGILL (Illegal instruction) @ 0 (0) ---
    +++ killed by SIGILL (core dumped) +++
    Illegal instruction (core dumped)

These are arm architectures, so shouldn't be affected by the portability of Go to PPC, right?

This may be related to https://github.com/syncthing/syncthing/issues/749 ...

Additional info : 

    DiskStation> uname -a
    Linux DiskStation 2.6.32.12 #5022 Wed Jan 7 14:19:44 CST 2015 armv5tel GNU/Linux synology_88f6282_213air

    DiskStation> cat /proc/cpu
    /proc/cpu/     /proc/cpuinfo
    DiskStation> cat /proc/cpuinfo 
    Processor	: Feroceon 88FR131 rev 1 (v5l)
    BogoMIPS	: 1589.24
    Features	: swp half thumb fastmult edsp 
    CPU implementer	: 0x56
    CPU architecture: 5TE
    CPU variant	: 0x2
    CPU part	: 0x131
    CPU revision	: 1
    
    Hardware	: Synology 6282 board
    Revision	: 0000
    Serial		: 0000000000000000

**Comment by cytec** [comment] 2015-03-26 15:32
@devjta you need a native go installation to compile go for that platform (or at least a toolchain/cross tool of go) which is not available for PPC. So there is no way to make any go app running on PPC arch... 

@jdbancal we already build a static version of go so that shouldn't be it. maybe there is something wrong with the binary stripping... i don't have access to a VM atm so i'm not able to compile a static-unstripped binary but maybe someone else can?

**Comment by devjta** [comment] 2015-03-26 15:38
@cytec The question is, is go not able to cross-compile for PPC or has NEVER ANYONE done it before??
So who provides the go-binaries for all other Syno-plattforms or where can I even find that (didnt find any repo with it)? 
As I have some knowledge about cross-compiling (or compiling on the device itself), 
I will give it a try. But just, if it is possible (in theory).

**Comment by cytec** [comment] 2015-03-26 15:43
@devjta you can't. Period. except if you are going to write a working go compiler for ppc yourself. No one has done it because there is no compiler to compile binaries for ppc... 

go comes with compilers for x86, x86_64, and ARM and according to the go mailinglist: `We have no immediate plans for PPC support `

**Comment by devjta** [comment] 2015-03-26 15:54
@cytec Well, Google has no plans for it, but you/we have the cross-compile binaries for x86, so cross-compiling GO for PPC should be possible (in theory!!)
As I cross compiled many things for SH4, mips and mipsel stuff, I will give it a try. And I also compiled some programs on the DS213+ NAS itself (also on mipsel routers). It just takes forever (compared to cross compiling).

Googles all.bash and make.bash have CC_FOR_TARGET and CXX_FOR_TARGET flags..

**Comment by cytec** [comment] 2015-03-26 16:35
@devjta i think you don't understand what i am saying:

1. to compile go code, you need a go compiler (gc) for that arch.
2. there is no compiler for pcc
3. it's irrelevant that we have toolchains (gcc etc) from synology for ppc... gc (the go compiler) doesn't use them (except for c bindings)
4. you are not able to compile it for ppc as there is simply no support for that arch in the whole go language

**Comment by sfmcnally** [comment] 2015-03-26 21:57
Has anyone sucessfully updated to the latest syncthing on a synology box? I'm at 0.10.5 and it is getting a lot of errors when syncing with a windows box with 0.10.29.

**Comment by jdbancal** [comment] 2015-03-27 05:29
@cytec 
 - Are you saying that an arm virtual machine is needed in order to compile syncthing for that architecture?
 - Concerning go compilers, just a question out of curiosity: Do you have any idea where the first go compiler come from on the architectures where it exists? I mean it must have been compiled by some other compiler, right? Sorry if this questions shows my blatant lack of knowledge about compilers and new programming languages, I'm just not very familiar with these things...

**Comment by cytec** [comment] 2015-03-27 11:20
@jdbancal basically yes. you don't need a full virtual machine for your target os, but you'll need at last the keychains to compile c code and some libraries (gcc etc). then go automatically provides compilers for x86, x86_64, and ARM.
about where they came from... they are created by go if you tell go to create them.

**Comment by jdbancal** [comment] 2015-03-28 09:39
So this cannot be done on the NAS itself through the compiler provided by ipkg?
If this is possible and you know of a deterministic set of instructions that would produce such static-unstripped binary for syncthing (starting with a description of where the sorce code should be downloaded from), I could give it a try.

**Comment by Diaoul** [comment] 2015-03-28 10:26
I requested gccgo support in the toolchains back in june 2014. I received no response from Synology. I'm following up.

**Comment by jdbancal** [comment] 2015-03-28 12:15
Ok, thanks @Diaoul !

**Comment by NickPyz** [comment] 2015-03-30 20:54
Questions for @cytec and @Diaoul :

At the present time, the Syncthing community contributions page still points users to the cytec Package Source ... which is now terminated as of 5 days ago. Here's the Syncthing wiki page, which I will be happy to edit to the correct source at SynoCommunity:

https://github.com/syncthing/syncthing/wiki/Community-Contributions

If we point users to SynoCommunity, they will see version 0.9.4-2, which is quite a few versions behind the latest Syncthing releases. ST is at 0.10.30, and 0.11.x is already in the pipeline. So here are my questions: 

(1) Are the download versions (17 different processor architectures) ALL @ 0.9.4-4? 
(2) Can they all be upgraded to version 0.10.x from within the ST web-ui?

Your answers will help minimize confusion at the ST site, where there has been a recent influx of new users, with lots of questions. Thank you!

**Comment by cytec** [comment] 2015-03-30 21:56
@NickPyz i don't know exactly which version those SPKs are but you should be able to update through ST's web-ui...

**Comment by tenjaa** [comment] 2015-03-31 08:20
@NickPyz I could not update 0.9.4, but that seemed to be a bug caused by syncthing. It was also mentioned on their changelog.
So I compiled the current version from Synocommunity myself (10.5). But I still can't update via the GUI. All ports should be forwarded properly (UPnP is available), but I am not sure where the mistake is made (my config, compiling, bug in syncthing, ....).
But for the curious here is my compiled version of 10.5 including the sc-syncthing group for armada370 (DS213J,DS115J): http://s000.tinyupload.com/?file_id=33407579513652980664

**Comment by devjta** [comment] 2015-04-07 15:19
@cytec Do you know about that project: gccgo - https://golang.org/doc/install/gccgo ? Is that compiler PPC able?At least I found some packages for PPC (PCs) and gccgo compiler! But I think the problem is that the gcc is to old (toolchain) and has no gccgo support in it (or not the version syncthing needs).

But maybe in the future ;-) Too bad, that SyncThing was written in Go :/

**Comment by cytec** [comment] 2015-04-07 15:36
@devjta yup im aware of that but like you said, there is no support in synologys toolchains atm and personally i don't think that this will change in the future... the last ppc based device is from 2013 i think and if i remember correctly synology is/was switching to armv7 for the 400 series in 2014

**Comment by NickPyz** [comment] 2015-05-06 16:22
I just wanted to notify all that Syncthing has released a version upgrade from v.0.10.x to v.0.11.x. This is from the release notes:
---------------------------------------------------------------------------------------
"Syncthing v0.11 does not support synchronizing with older versions (v0.10 or older). When a connection is established between a v0.11 device and a v0.10 device, an error will be printed to the console and the connection is closed. This means you need to upgrade a cluster of devices together. Syncthing v0.11 will rehash all files on first startup."
----------------------------------------------------------------------------------------
On my Syno server, the version hosted on Synocommunity (presently v0.10.30-3) was easily upgraded using the Syncthing Web-GUI "upgrade" button. It was a 2 step process. 1st the application jumped from 0.10.30 to 0.10.31. After that, another "upgrade" button appeared pushing me up into 0.11.2

**Comment by crazyscow** [comment] 2015-05-18 17:36
@NickPyz 
In your previous posts you wrote that you weren't able to upgrade via the GUI, what did you change in order to upgrade to v0.11.xx?
since nobody else wrote here i guess i'm the only one that can't upgrade. Actually im more curious to know if its any better then v0.10 because otherwise i dont really mind. 

thanks

**Comment by NickPyz** [comment] 2015-05-19 14:50
@crazyscow 

Sorry if I confused ... the upgrade via the GUI was trouble-free. There was an "upgrade" button in v0.10.30 which took me to v0.10.31. After the restart, another "upgrade" button appeared, which took me to v0.11.2. Since then, I have upgraded again. At the present time I have v0.11.5 on my Synology.

If all your devices are at v0.10.x - then you are probably ok. However, keep in mind that devices with v0.10 and others with v0.11 will not sync with each other.

Here is a link to the Syncthing changelog at github, where you can see what's new / better in the v.0.11.x release: https://github.com/syncthing/syncthing/releases

**Comment by crazyscow** [comment] 2015-05-20 15:48
@NickPyz 
im guessing you had the upgrade button after you installed v. 10.30-3 because i dont have a a upgrade button. 
So my question was if you did anything in order to receive that upgrade button, in the syncthing gui. in case you dont understand, just ignore it, im happy as long as syncthing works, i was just curious to know if you did anything to get the red upgrade button to show up.

**Comment by NickPyz** [comment] 2015-05-21 14:20
@crazyscow 

I didn't do anything to receive the "Upgrade" button - it just appears whenever an upgrade is available. Check that you have "Automatic Upgrades" enabled in Syncthing > Settings.

I originally installed Syncthing on my Syno from the cytec repository. It was v0.9.4-2. From that version until v0.11.5, I have been receiving the "Upgrade" button and updating from the WebGUI.
 
NOTE: DSM Package Manager still shows me at v.0.9.4-2 - which I ignore. I never update Syncthing from DSM Package Manager, only from the WebGUI.

**Comment by crazyscow** [comment] 2015-05-21 18:58
@NickPyz 
oh ok thanks. I was also on v.0.9.4-2 before and after i read your message on github saying that you had no problem upgrading i thought you were on the new version, which is now on the synocommunity repo, so i upgraded to this version v.0.10.30-3. Now i dont have the update button. 
too bad, i guess im stuck on 10.30-3 for now :)

thanks for the reply.

**Comment by qlxltd** [comment] 2015-06-15 16:07
Is there a step by step guide how to install from binary?

**Comment by NickPyz** [comment] 2015-06-15 20:30
@crazyscow @Diaoul 

According to Jakob Borg, who is the primary Syncthing developer, version 0.10.30 had a broken upgrade system. This might explain crazycow's problem with no upgrade button. Details in the following thread from the Syncthing Forum:

https://forum.syncthing.net/t/synology-ds412-update-to-latest-version/3024/2

Since this is the only version available in Synocommunity packages. other new users will get trapped with no version upgrade option. This should resolve by releasing a compiled Synology version based on 0.11.1 or later (presently @ 0.11.9).

Thanks.

**Comment by tcaleshu** [comment] 2015-06-26 14:22
Any chance anyone has an old package file lying around? The synocommunity 0.10.30 does not, as @NickPyz says, have an upgrade package. So I'm stuck without a client to sync the synology to other devices running current revisions...

Sounds like pretty much an package version will update properly.

**Comment by cytec** [comment] 2015-06-26 15:16
i think i still have some `0.10.11` spk's flying around somewhere... which arch?

**Comment by tcaleshu** [comment] 2015-06-26 15:51
its a DS414 - armadaxp

**Comment by crazyscow** [comment] 2015-06-27 09:24
@cytec do you have one for cedarview, too? would be awesome.

**Comment by Dr-Bean** [comment] 2015-07-16 11:19
Syncthing 0.11.15-4 has been published on the repository.

**Comment by Dr-Bean** [comment] 2015-07-19 09:24
Syncthing 0.11.15-5 has been released for ARM-based arches (88f6281, alpine/4k, armada*, comcerto2k). See https://github.com/SynoCommunity/spksrc/issues/1792.

**Comment by jokogr** [comment] 2015-08-23 10:54
Hello,
I would like to ask two things:

1. Is it safe to upgrade syncthing using the "Automatic upgrades" option?
2. How to ensure that my normal NAS users have access to files which have only owner access? E.g., a file in the system reports permissions and ownership as such: "-rw-------    1 syncthin users" and it is not listed at all on my SMB network mount from my workstation.

**Comment by Dr-Bean** [comment] 2015-08-24 10:28
1: Yes.
2: Check the Syncthing FAQ or their forums. For example: http://docs.syncthing.net/users/faq.html#how-to-configure-multiple-users-on-a-single-machine or https://forum.syncthing.net/t/sync-file-ownership-and-permissions/143.
Owner-only permissions simply won't work if multiple users should be able to access the files. I'd suggest to set the appropriate permissions (read or r/w) for the `users` group on those files.

**Comment by reyman** [comment] 2015-11-04 15:21
Hi, i'm not seeing Syntching for ds213+ , any news about portage on architecture : 
`DS213+	Freescale QorIQ P1022 ppc	1.067	2	2	yes	qoriq	64-bit@DDR3 512MB`

**Comment by cytec** [comment] 2015-11-04 17:06
@reyman nope, see https://github.com/SynoCommunity/spksrc/issues/1011#issuecomment-44748868 and following comments. go itself is not compatible with PowerPC arches

**Comment by Dr-Bean** [comment] 2015-11-30 15:26
I've removed the beta tag from Syncthing, I believe we've done enough testing over time ;) 
Our package release is now at 0.12.5, although the internal update function of Syncthing should work for the people that want to keep up-to-date with the latest.

Packages on the repo will be updated later. In the mean time, I'll close this issue. In the future, questions about the Syncthing package can be asked by opening a new issue.

**Closed by Dr-Bean** 2015-11-30 15:26 UTC
Labels: beta

**Comment by reyman** [comment] 2016-01-22 13:57
Hi @Dr-Bean and @cytec, it seems there is ppc package on syncthing now : https://syncthing.net/
Don't know how it works.

**Comment by cytec** [comment] 2016-01-22 15:21
@reyman yeah... ppc64 i think that was mentioned in another issue already... idk if synology ppc models are 64models

**Comment by Dr-Bean** [comment] 2016-01-22 16:13
Unfortunately none of the PPC models that Synology has released are compatible with PPC64.

**Comment by safersurfing** [comment] 2016-03-10 12:57
Been having problems with my Synology DS715 .. installed the package and got it to run (had to change unser in the start-stop script to root. The package runs, but I cannot access it via the Web UI. Any ideas why that could be? DSM 5. Alpine processor.

**Comment by MoOx** [comment] 2016-10-02 15:03
Getting the same problem currently. When I installed it, no issue with web GUI, but with current version (0.14.7) can't access the web GUI :/

**Comment by MoOx** [comment] 2016-10-02 19:00
Ok nevermind, it's an issue with my router/port. When accessing via *.synology.me, it's not working, when using local url address (192.168...) it is.

**Comment by hwmrocker** [comment] 2017-01-28 10:16
@cytec sorry to spam you here, but i wanted to install syncting.spk on my sonology but your repository has it no longer. could you provide me the binary file somehow?

**Comment by cytec** [comment] 2017-01-28 15:31
@hwmrocker that's right syncthing is available through https://synocommunity.com for a while now ;)

**Comment by hwmrocker** [comment] 2017-01-30 21:39
@cytec many thanks!
