### ISSUE TITLE
[REQUEST] HTPC Manager Custom Package [$25]

### ISSUE THREAD

**Issue by Logan09** [SynoCommunity/spksrc#1441] opened 2015-01-07 23:34 UTC
There is a fork of HTPC Manager that supports Sonarr available - https://github.com/Hellowlol/HTPC-Manager

A custom package which allowed users to choose their fork would be great.

**Comment by Hellowlol** [comment] 2015-01-12 16:03
Anything I can do to make this (except for making the package) happen let me know.

**Comment by M0UL** [comment] 2015-05-13 14:25
as a sonarr user this would be great

**Comment by Ltek** [comment] 2015-05-27 13:38
:+1: 
really want to update to Hellow's branch. Someone please mod the currently posted HTPC-Manager package to use Hellow's branch

**Comment by EZarnosky** [comment] 2015-06-05 23:07
Is anyone looking at this? If a Custom package is too much of a headache, what about a package containing the https://github.com/Hellowlol/HTPC-Manager fork?

**Comment by Hellowlol** [comment] 2015-06-06 00:54
I added a small bounty since I can't do this myself.

**Comment by EZarnosky** [comment] 2015-06-06 01:33
I see your $10 and raise you $5. :P

I would really like to see this, so I figure it is worth spending a little money of if the package is built right.

**Comment by Dr-Bean** [comment] 2015-06-06 08:32
I say this is a request a starter should be able to handle with some effort, so if anyone wanted a chance to contribute, here it is ;)

Here are some basic pointers whoever picks this up:
- No `-custom` package, we'd rather move the functionality into the main packages.
- The recent sickrage package should work fine as an example. The main repository from styxit should be used as default.
- Note that in the current htpcmanager package, the git clone is done in the `/share/htpcmanager` dir, that should be moved to `/var/htpcmanager` for package upgrade purposes. 
- Verify that upgrading from the current package to the new one works.

I might take a look myself, but not immediately, so if anyone jumps in, that's fine with me.

**Comment by Hellowlol** [comment] 2015-06-06 18:58
Sounds good :)

**Comment by cytec** [comment] 2015-06-07 01:31
That fork definitively looks interesting for me too. maybe i'll take a look at this :)

**Comment by Hellowlol** [comment] 2015-06-07 06:10
My fork has some "requirements" that styxit does not have. None of this are required but some modules will not work/have reduced features

Paramiko (vnstat)
Pyopenssl 
Open hardware monitor (stats)
smartmontools (stats)

**Comment by Dr-Bean** [comment] 2015-06-07 08:23
@cytec Yeah, that's the idea. I don't particularly like the clone-on-install, but that's the price.

@Hellowlol About psutil: it contains C-extensions. We don't have the ability to compile on a Synology (applies to a lot of the consumer-grade NAS). If we have to cross-compile it, the compile time of the package goes up from 2 minutes to 45 or so. HTPCManager is quite lightweight otherwise, so we might skip that one.

**Comment by Hellowlol** [comment] 2015-06-07 09:00
Aw, that would be a :/, well you can't if you can't. It just happens to be my favorite module. Does synology has access to a package manager like apt-get?

**Comment by Dr-Bean** [comment] 2015-06-07 09:07
No...that's more or less the reason this project exists in the first place ;)

**Comment by Hellowlol** [comment] 2015-06-07 11:21
Hehe, I should have thought that myself :p

**Comment by cytec** [comment] 2015-06-07 17:04
Well vnstast can be installed with ipkg but maybe we can provide something like an extra SPK containing those tools? 

So that we have a small HTPC-Manager SPK wich just installs HTPC-Manager itself and a "addon" for those tools which need croas compilation?

**Comment by Dr-Bean** [comment] 2015-06-07 17:14
The issue isn't the cross-compiling in itself ;) 
Currently, HTPCmanager is a noarch package. If we add psutil (Python module, mentioned in the requirements file over on @Hellowlol's fork), we need to cross-compile that.

That means that HTPCmanager is no longer noarch, so we need to compile the 20-something packages, including the cross-compilation of Python, at ~45 minutes per package (or however long it takes to cross-compile Python). Only for this particular fork, because the original doesn't use it.

**Comment by Hellowlol** [comment] 2015-06-07 17:33
Psutil is also in stout version btw. It's not unique for mine

**Comment by Diaoul** [comment] 2015-06-07 20:01
What about putting that in the Python SPK?

**Comment by cytec** [comment] 2015-06-08 08:23
here you go:
https://github.com/SynoCommunity/spksrc/pull/1747

**Comment by Diaoul** [comment] 2015-06-08 08:26
@cytec: that doesn't solve the psutil issue.

**Comment by Diaoul** [comment] 2015-06-08 08:29
Also as that will replace the old package you need to add safeguards to prevent package update from a previous version and force reinstall and you need to replace "fork" with "source" in "Choose your fork" as we don't provide the "original" by other means.

**Comment by cytec** [comment] 2015-06-08 08:56
@Diaoul psutil is optional and HTPC-Manager is working without it as well... if it __must__ (for whatever reasons) be included i think it would be best to go with your approach and add it to the python SPK itself.

Any hints on how to force the reinstall stuff?

**Comment by Diaoul** [comment] 2015-06-08 09:41
Take a look at HAProxy I believe there are some versions that force reinstall.
Yes it's the same in french.

**Comment by Dr-Bean** [comment] 2016-01-20 09:42
Noticed this was still open. Custom forks were made possible via https://github.com/SynoCommunity/spksrc/pull/1747. `psutil` was added to the Python package with https://github.com/SynoCommunity/spksrc/issues/1981 (https://github.com/SynoCommunity/spksrc/commit/46317af0341f2fa56ed081e81c62c471210ce147).

@Logan09 Probably best if you close this, so @cytec can pick up the bounty for starting the work ;)

**Comment by Logan09** [comment] 2016-01-20 10:24
Hadn't realised this had been implemented. Awesome. Will close the thread as suggested. Thanks.

**Closed** 2016-01-20 10:25 UTC
Labels: bounty, request

**Comment by Dr-Bean** [comment] 2016-01-20 10:50
Oversight on our part, I meant to report this back when the actual changes were implemented.
Let us know if everything works as expected (applies to other readers here too ;)).

**Comment by Logan09** [comment] 2016-01-21 14:28
Seems to all be working perfectly. Many thanks to all involved in getting this working. Much appreciated.

**Comment by Hellowlol** [comment] 2016-01-21 14:32
Thanks for making this happen. I didn't understand how to accept the bounty claim so we just have to left the time pass to get some $$
