### ISSUE TITLE
OwnCloud (Failed to uninstall the package, Incorrect MySQL root password)

### ISSUE THREAD

**Issue by mikhailalexander** [SynoCommunity/spksrc#2252] opened 2016-04-11 10:43 UTC
Hi,

Recently upgraded to DSM 6 like many others not thinking about the community packages I had installed. I was no longer interested in having OwnCloud or MariaDB on my Synology.

Went to remove Owncloud being told that the MySQL root password was incorrect. I've reset the password in MariaDB and deleted all databases without success being told the same error multiple times.

I assume the binaries for MariaDB or OwnCloud have been moved in the update thus not allowing me to remove it anymore. Any chance I'd have in moving/copying those to their original locations to initiate the removal process from my Synology or possibly removing some files through SSH forcing the uninstallation process to simply delete itself and cause no issues in the future?

Really looking to have a wipe as a last resort since I have over 2TB of Data I'd rather not backup and restore. With that said, is there any way I can wipe the Synology's config and files without deleting any data? Permissions aren't an issue, just ensuring that data isn't lost.

Any assistance appreciated.

**Comment by Dr-Bean** [comment] 2016-04-13 09:23
Duplicate of #2136. See also https://github.com/SynoCommunity/spksrc/issues/2093#issuecomment-209329276

**Closed by Dr-Bean** 2016-04-13 09:23 UTC
