### ISSUE TITLE
Subliminal 0.7.5-12 fails to start on DSM 6.0.2-8451 Update 9

### ISSUE THREAD

**Issue by DaveHamilton** [SynoCommunity/spksrc#2631] opened 2017-02-02 18:57 UTC
### Setup
_Package Name:_ Subliminal
_Package Version:_ 0.7.5-12

_NAS Model:_ DS1815+
_NAS Architecture:_ avoton (x86_64)
_DSM version:_ DSM 6.0.2-8451 Update 9

### Expected behavior
I have never used Subliminal before. I downloaded it from SynoCommunity and I would expect it to start.

### Actual behavior
I can download it successfully but get "Failed to run the package service." in the GUI. As a note, I previously had Python 2.7.13-16 installed from SynoCommunity.

### Steps to reproduce
_1._ Download package fresh
_2._ Action -> Run

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_

No Data in Package Center log and no log files in /usr/local/subliminal/var/
#### Other logs
_`/var/log/synopkg.log`:_
```
2017/02/02 13:52:57	start subliminal: begin to start version 0.7.5-12
2017/02/02 13:52:58	stop subliminal: begin to stop version 0.7.5-12
2017/02/02 13:52:58	stop subliminal: stop version 0.7.5-12 successfully, result 0
2017/02/02 13:53:05	start subliminal: start version 0.7.5-12 failed, result 1
```
_`/var/log/synoservice.log`:_
```
2017-02-02T13:52:57-05:00 DiskStation synoscgi_SYNO.Core.Package.Control_1_start[13881]: service_start.c:74 synoservice: [pkgctl-subliminal] starting ...
2017-02-02T13:52:58-05:00 DiskStation synoscgi_SYNO.Core.Package.Control_1_start[13881]: service_start.c:180 synoservice: [pkgctl-subliminal] start failed.[0xD900 privilege.cpp:60]
2017-02-02T13:52:58-05:00 DiskStation synoscgi_SYNO.Core.Package.Control_1_start[13881]: service_stop.c:23 synoservice: [pkgctl-subliminal] stopping ...
2017-02-02T13:52:58-05:00 DiskStation synoscgi_SYNO.Core.Package.Control_1_start[13881]: service_stop.c:38 synoservice: [pkgctl-subliminal] is already stopped.
2017-02-02T13:52:58-05:00 DiskStation synoscgi_SYNO.Core.Package.Control_1_start[13881]: service_stop.c:86 synoservice: [pkgctl-subliminal] stopped.
```

**Comment by Dr-Bean** [comment] 2017-02-02 23:05
Subliminal, as a lot of other packages, isn't ready for DSM6 yet. In the case of Subliminal, there are two things at play: 
- User handling in DSM6 was changed by Synology. Subscribe to #2216;
- The GUI doesn't work due to changes made by Synology. See #2357.

Having said that, subliminal is CLI-based. Instructions on how to use it via command-line are available at http://subliminal.readthedocs.io/en/latest/user/usage.html.

Marking as duplicate of https://github.com/SynoCommunity/spksrc/issues/2357, so I'll close this one.

**Closed by Dr-Bean** 2017-02-02 23:05 UTC
