### ISSUE TITLE
[request] Add NZBHydra Package

### ISSUE THREAD

**Issue by Elfman72** [SynoCommunity/spksrc#2164] opened 2016-03-02 16:44 UTC
Description: NZBHydra - Search multiple NZB indexers simultaneously.
Website: [NZBHydra Git](https://github.com/theotherp/nzbhydra)
Documentation: https://github.com/theotherp/nzbhydra/wiki
Build/Installation documentation: https://github.com/theotherp/nzbhydra
http://www.htpcguides.com/install-nzbhydra-windows-for-universal-usenet-searching/
http://www.htpcguides.com/install-nzbhydra-ubuntu-universal-usenet-searching/
Source Code: https://github.com/theotherp/nzbhydra
License:

This is a fairly new project that is the "spiritual successor" to NZBMegasearch as it is no longer in active development.  Hydra is in active development. I have also created a request issue with the creator so he is aware of this project as well and will link it here shortly.  Thanks!

https://github.com/theotherp/nzbhydra/issues/166

**Comment by Dr-Bean** [comment] 2016-03-03 09:45
Duplicate of #2120, so I'm going to close this one.

**Closed by Dr-Bean** 2016-03-03 09:45 UTC
Labels: status/duplicate
