### ISSUE TITLE
Secure the ruTorrent page with a password

### ISSUE THREAD

**Issue by dolphinkite** [SynoCommunity/spksrc#2330] opened 2016-05-18 17:38 UTC
Hi,

I know I'm not the only one with this problem: I'm running ruTorrent on my Synology NAS, but I am also running a public-facing website on my NAS. The consequence is that the ruTorrent interface is available for anyone to see and use from the internet - not an acceptable situation.

I used to secure it with a .htaccess page, but as of DSM6.0, this isn't working anymore (or I don't know how to do it). I think it would be a valuable addition to this package to include a mechanism to password-restrict the access to ruTorrent.

Can this be added to a feature request list? I don't know how actively ruTorrent is being developed/maintained, but I'm sure many will appreciate such a feature.

Thanks

**Comment by Oleekae** [comment] 2016-05-18 17:45
++ 1 for those who do run it from an official package (and haven't bootstrapped our DSM)

**Comment by Dr-Bean** [comment] 2016-05-18 17:51
Please use search before opening issues, see the guidelines: https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#issues.
Duplicate of https://github.com/SynoCommunity/spksrc/issues/2206

**Closed by Dr-Bean** 2016-05-18 17:51 UTC
