### ISSUE TITLE
Cannot Connect to Repo

### ISSUE THREAD

**Issue by Ashkaan** [SynoCommunity/spksrc#2563] opened 2016-12-18 01:21 UTC
_For new Package Requests, see the guidelines_  

### Setup
_NAS Model:_DS3617xs
_NAS Architecture:_broadwell
_DSM version:_6.0.2-8451 Update 6

### Expected behavior
I should be able to add the repo.

### Actual behavior
![image](https://cloud.githubusercontent.com/assets/5667978/21290801/33fc6a18-c47d-11e6-9f07-bd4592d5e5c6.png)

### Steps to reproduce
Step 1
Log into your NAS as administrator and go to Main Menu → Package Center → Settings and set Trust Level to Synology Inc. and trusted publishers.
Step 2
In the Package Sources tab, click Add, type SynoCommunity as Name and http://packages.synocommunity.com/ as Location and then press OK to validate.

**Comment by Dr-Bean** [comment] 2016-12-18 14:46
Duplicate of https://github.com/SynoCommunity/spksrc/issues/2509, so closing.

**Closed by Dr-Bean** 2016-12-18 14:46 UTC
