### ISSUE TITLE
Unable to install Mono package on DSM 7.0

### ISSUE THREAD

**Issue by gus70** [SynoCommunity/spksrc#4322] opened 2020-12-20 20:46 UTC
Unable to install Mono package running DSM 7.0.
The error received is that the Mono package only runs as root. The recommendation from Synology is to contact the package developer and tell them to change the privilege settings on the package.

See error screenshot attached:
![image](https://user-images.githubusercontent.com/40617723/102724011-3ede6c80-42da-11eb-8fba-516499854dc8.png)

**Comment by publicarray** [comment] 2020-12-21 09:15
DSM7 support for all packages is still under development. See #4215. Contributions to the dsm7 branch are welcome.

**Comment by maxiiss** [comment] 2020-12-23 17:41
Thanks for working on this support. I hope you may find a solution soon.

**Comment by favoretti** [comment] 2021-01-15 11:13
I built mono from dsm7 branch, it installed successfully. Any ideas why this one is still open? :) Are there issues with using it?

**Comment by gus70** [comment] 2021-01-15 11:38
> I built mono from dsm7 branch, it installed successfully. Any ideas why this one is still open? :) Are there issues with using it?

You "built" Mono. This issue report is about using the Mono package from Synocommunity using the Package Center. Totally different thing.

**Comment by favoretti** [comment] 2021-01-15 17:15
Ahh, I see. Sorry for the confusion.

**Comment by maxiiss** [comment] 2021-01-20 20:55
I see you move this post to "Done", 

Just for you to know, for me the issue is still here.
![Capture d’écran de 2021-01-20 21-49-44](https://user-images.githubusercontent.com/10705263/105233396-16ac8c80-5b6a-11eb-8c9b-62f0cc02b60f.png)

Best regards

**Comment by gus70** [comment] 2021-01-21 02:17
> I see you move this post to "Done",
> 
> Just for you to know, for me the issue is still here.
> ![Capture d’écran de 2021-01-20 21-49-44](https://user-images.githubusercontent.com/10705263/105233396-16ac8c80-5b6a-11eb-8c9b-62f0cc02b60f.png)
> 
> Best regards

I agree that it is confusing to see this in the "done" section of the project...but its status is still "open" therefore I don't know what that really means.

**Comment by hgy59** [comment] 2021-01-24 16:55
I tend to close all such issues for packages not compatible with DSM7.
As DSM7 is still under development here and no packages for DSM7 are published yet, it is boring to manage such issues for each of the > 100 packages that are provided here.

I think the base problem is that the packages are shown in the package center in DSM, dispite the fact that the provided os_min_ver is < 7.0. This pretends that packages are available.

@ymartin59  shall we ask synology what we need to change, for that DSM7 does not show incompatible packages?

**Comment by publicarray** [comment] 2021-01-24 20:46
We just need to set the os_max_ver in the info file. I don't remember if that variable is exposed on the server though.

**Comment by gus70** [comment] 2021-01-24 20:55
I would like to see a least by the time DSM 7.0 becomes officially released that the Mono package gains compatibility. 

Sure there are other solutions to get Mono running but they are a bit less than practical for less technical users. You can compile from source or you can leverage a Mono install via a Docker container. I would prefer though to be able to continue to have the ease of a Package Center installation for Mono. I support a number of applications and I'd like to keep things as simple as possible for my users.

I just hope that this is not forgotten. I greatly appreciate the work done by this Synology Community.

**Comment by th0ma7** [comment] 2021-01-24 20:57
> We just need to set the os_max_ver in the info file. I don't remember if that variable is exposed on the server though.

That might end-up being an interesting idea to set `os_max_ver` to `$(MAJOR).99` type-thing?  Thus compatible to DSM-x.99 always.

**Comment by favoretti** [comment] 2021-01-24 21:55
> EDIT: If I re-read your post I get a different meaning. So not sure what you meant. Did you mean to say that you manually installed Mono and therefore you deduce that there should be no trouble creating a new package for the Package Center?

I mean than when I take DSM7 branch of this repo and yes, build a arch-x64-7.0 package, I can manually install it using package center, so no reason to not to make it available?

**Comment by publicarray** [comment] 2021-01-25 08:30
@favoretti Please just wait until #4395 is merged. We are getting closer. The main reason is that packages need to be tested, there have been significant changes to DSM7 some documentation needs updating. 

@gus70 Everyone works a bit different in open source but here is what I think: Please help out rather than ask for package releases for a beta DSM or ETA for DSM7 support. Generally I just ignore such requests. You can compile, install & report bugs for instance or help update the [wiki](https://github.com/SynoCommunity/spksrc/wiki). @hgy59 is public editing on?
We work on this in our own time. And you benefit from this for free. Yes sometimes things do get left behind but mono is a requirement for some of other packages, so I don't see this happening here.

**Comment by publicarray** [comment] 2021-01-25 09:19
Oh just noticed, what I said above is also addressed by @hgy59 in the README too: https://github.com/SynoCommunity/spksrc#dsm-7

**Closed** 2021-01-25 09:20 UTC
Labels: dsm 7.0

**Comment by favoretti** [comment] 2021-01-25 09:34
@publicarray don't get me wrong, I'm not in a rush and I can perfectly build stuff that I miss, I appreciate all the work you folks are doing here. My question was merely a statement that it "works on my machine", albeit maybe worded a bit incorrectly. If you need any help with getting DSM7 out there - I'll be happy to help. So far everything that I've tried to build in dsm7 branch just works, aside of Deluge, where boost is barfing on me. Trying to find a solution, but unsuccessful so far.

**Comment by gus70** [comment] 2021-01-25 18:08
> @gus70 Everyone works a bit different in open source but here is what I think: Please help out rather than ask for package releases for a beta DSM or ETA for DSM7 support. Generally I just ignore such requests. **You can compile, install & report bugs** for instance or help update the [wiki](https://github.com/SynoCommunity/spksrc/wiki). @hgy59 is public editing on?
> We work on this in our own time. And you benefit from this for free. Yes sometimes things do get left behind but mono is a requirement for some of other packages, so I don't see this happening here.

I'm sorry that my follow-up post wording clearly says that I was requesting that packages get released for beta operating systems. That is not my intention. But my original request was not of that nature. My original request still stands and I see it as a **but report**, the package is available because it shows up and and I can install it and then I get the error message about root privilege. Do with that what you will. My work here is done fellas. Thank you all for your time. I'm not personally benefiting from free work. I also for free support some software that requires Mono for a community of weather station software users is all.

**Comment by gidoBOSSftw5731** [comment] 2021-06-02 16:28
As an update to this, they released a release candidate today (https://www.synology.com/en-us/releaseNote/DSM#ver_41882) and have a help guide on what the package situation is: 

> Synology has added a strict requirement on DSM 7.0 to prevent packages not signed by Synology from running with root privileges.
_https://www.synology.com/en-us/knowledgebase/DSM/tutorial/Third_Party/_


Therefore, I think it is now required to reevaluate what packages require root access and which do not, as they are pushing in this direction hard and, as of now, almost no packages are on track to be available on the upcoming release.

**Comment by hgy59** [comment] 2021-06-02 19:16
> Therefore, I think it is now required to reevaluate what packages require root access and which do not, as they are pushing in this direction hard and, as of now, almost no packages are on track to be available on the upcoming release.

You find detailed information in #4524 about packages that require root permissions.
Almost all pure CLI packages (no services, no web apps) are compatible with DSM7 and some of them are already published to the synocommunity package server and can successfully be installed in DSM7.

You find detail in the linked issue.

We could even make mono package for DSM7, but IMHO mono is not state of the art anymore and we should publish only packages that are migrated to .net for DSM7.

**Comment by DigitalBox98** [comment] 2021-06-04 17:31
FYI I've got mono version 6.12 running for my NAS (braswell) on DSM 7.0
I can propose a PR if someone would like to test.

**Comment by superpippo82xxx** [comment] 2021-06-05 12:24
> 
> 
> FYI I've got mono version 6.12 running for my NAS (braswell) on DSM 7.0
> I can propose a PR if someone would like to test.

@DigitalBox98 can you share your patch for mono, i'm on armadaxp and x64
thanjs

**Comment by DigitalBox98** [comment] 2021-06-06 19:04
@superpippo82xxx, a PR has been proposed. You can test it if needed.

**Comment by shoaaaib** [comment] 2021-07-07 17:44
> @superpippo82xxx, a PR has been proposed. You can test it if needed.

hi there, i am new to all this and just updated to DSM 7 and mono is not working, thus sonar, radarr, jacket, transmission.

can you help in how to fix that?
