### ISSUE TITLE
meson build error

### ISSUE THREAD

**Issue by th0ma7** [SynoCommunity/spksrc#4379] opened 2021-01-09 14:37 UTC
### Setup
_Package Name:_ `glib`
_Package Version:_ latest

_NAS Model:_ N/A
_NAS Architecture:_ N/A
_DSM version:_ N/A

### Expected behavior
Tentative to build from `cross/glib` leads to the following error:
```
$ make arch-hi3535-6.1
../../mk/spksrc.cross-meson-env.mk:43: *** meson config file not found: /x86_64.cfg.  Stop.
```

### Actual behavior
Somewhere prior to https://github.com/SynoCommunity/spksrc/commit/d582ca93c2ae22acccfd6c9b9270e7a4b91bceae it would be all right directly from `cross/`

**Comment by th0ma7** [comment] 2021-01-09 14:53
Commenting out the following solved the issue for me:
```
### disable error handling for target dependency-list
##ifneq ($(strip $(DEPENDENCY_WALK)),1)
##  ifeq ($(strip $(MESON_CFG_FILE)),)
##    $(error No meson config file defined for $(ARCH))
##  else
##    ifeq ($(wildcard $(MESON_CFG_DIR)/$(MESON_CFG_FILE)),)
##      $(error meson config file not found: $(MESON_CFG_DIR)/$(MESON_CFG_FILE))
##    endif
##  endif
##endif
```
Would that be related to where we initiate the build from?  Ability to test-out a single dependency really is a must without having to go through the burden of a full `spk`.

**Comment by hgy59** [comment] 2021-01-09 16:34
@th0ma7 

I cannot reproduce your issue.

Do you have 2259f8ddd164f868802ac0c479f17c8d9fe993c7 where the error occurred?

The dependency-list target is for the generation of dependency lists only and must not be used in other makefiles to iterate over dependen packages (this was fixed with 2259f8ddd164f868802ac0c479f17c8d9fe993c7).

**Comment by npmccallum** [comment] 2021-01-10 19:16
I'm experiencing a similar issue while trying to make a new package that depends on glib.

**Comment by th0ma7** [comment] 2021-01-12 01:25
@hgy59 I think I've found why...
In master currently I do have the changes associated to #4356 but not #4349 but when `git show 2259f8d` I do see it.
Looking at it more closely, have a look at https://github.com/SynoCommunity/spksrc/blob/master/mk/spksrc.cross-meson-env.mk and check its history.  I believe you discarded some of your previous changes when applying #4356 over such as the change from `error` to `warning` calls.

Indeed, the following patch solves things:
```
$ git diff
diff --git a/mk/spksrc.cross-meson-env.mk b/mk/spksrc.cross-meson-env.mk
index c49b44be..253fcf9c 100644
--- a/mk/spksrc.cross-meson-env.mk
+++ b/mk/spksrc.cross-meson-env.mk
@@ -37,10 +37,10 @@ endif
 # disable error handling for target dependency-list
 ifneq ($(strip $(DEPENDENCY_WALK)),1)
   ifeq ($(strip $(MESON_CFG_FILE)),)
-    $(error No meson config file defined for $(ARCH))
+    $(warning No meson config file defined for $(ARCH))
   else
     ifeq ($(wildcard $(MESON_CFG_DIR)/$(MESON_CFG_FILE)),)
-      $(error meson config file not found: $(MESON_CFG_DIR)/$(MESON_CFG_FILE))
+      $(warning meson config file not found: $(MESON_CFG_DIR)/$(MESON_CFG_FILE))
     endif
   endif
 endif
```

**Comment by th0ma7** [comment] 2021-01-13 01:08
@hgy59 want me to create a PR to fix the issue?  Didn't wanted to collide once more ;)

**Closed** 2021-01-14 19:54 UTC
Labels: bug, framework
