### ISSUE TITLE
Syncthing - options.conf not working as expected

### ISSUE THREAD

**Issue by MoisieSyncthing** [SynoCommunity/spksrc#3761] opened 2019-08-22 12:31 UTC
Synology DS1815+
Intel Atom C2538
DSM 6.2.2-24922 Update 2

Syncthing package 1.1.0-16

Using the `options.conf` file isn't working as expect for me. Here's some details:

In `/var/packages/syncthing/scripts/start-stop-status` there's this line:

```
start-stop-daemon -o -S -b -p ${PID_FILE} -m -c ${EFF_USER} -k 002 -x "${SERVICE_EXE}" -- "${SERVICE_OPTIONS}"
```

In `/usr/local/syncthing/var/options.conf` there's this:

```
# Example: uncomment this to start syncthing with all devices paused
#SYNCTHING_OPTIONS="${SYNCTHING_OPTIONS} -paused"
```

Even uncommenting this line stops the Syncthing binary from launching successfully - though Package Centre thinks it's running.

Presumably this is a conflict with the `-- ` in the quoted line of the `start-stop-status` script?

**Comment by acolomb** [comment] 2019-08-22 16:38
So Syncthing starts with the line commented out, but not when it is uncommented?

**Comment by MoisieSyncthing** [comment] 2019-08-22 16:39
Yes - that's right. I'm wanting to apply some different options - but even the example option isn't working for me.

**Comment by acolomb** [comment] 2019-08-22 16:40
Any error messages you can find in the log file?

Sorry I'm terse right now, gotta go someplace...

**Comment by MoisieSyncthing** [comment] 2019-08-22 16:58
> Sorry I'm terse right now, gotta go someplace...

No worries - grateful for the response!

> Any error messages you can find in the log file?

The only relevant log file I can currently find is `/usr/local/syncthing/var/syncthing.log`, which just contains:

```
Starting syncthing command /volume1/@appstore/syncthing/bin/syncthing -home=/volume1/@appstore/syncthing/var -paused
```
...which is what I'd expect. However, the line which writes this to the log is differently constructed from the line that actually executes the command:

Logging:
```
echo "Starting ${DNAME} command ${SERVICE_EXE} ${SERVICE_OPTIONS} " >> ${LOG_FILE}
```

Execution:
```
 start-stop-daemon -o -S -b -p ${PID_FILE} -m -c ${EFF_USER} -k 002 -x "${SERVICE_EXE}" -- "${SERVICE_OPTIONS}"
```

**Comment by acolomb** [comment] 2019-08-22 17:10
The `--` separates arguments meant for `start-stop-daemon` from those to be passed to the actual executable. So it doesn't look wrong at least.

Since the Package Center shows success, I rather think that Syncthing is started but quits on its own rather quickly. So Syncthing's own log would be useful, but I've never found where that goes either...

In my testing, Package Center correctly showed when the daemon failed.

**Comment by acolomb** [comment] 2019-08-22 17:15
Maybe this is the problem:

> -b, --background
>               Typically used with programs that don't detach on their own. This option will force start-stop-daemon to fork before starting the process, and force it into the background.  Warning:
>               start-stop-daemon cannot check the exit status if the process fails to execute for any reason. This is a last resort, and is only meant for programs that either make no sense forking
>               on their own, or where it's not feasible to add the code for them to do this themselves.
>

**Comment by MoisieSyncthing** [comment] 2019-08-22 17:26
> The -- separates arguments meant for start-stop-daemon from those to be passed to the actual executable. So it doesn't look wrong at least.

Hmmm - I'm no expert, but I'm not sure that stands. At the moment I'm hacking a solution by manually editing the start-stop-status script as follows:

```
start-stop-daemon -o -S -b -p ${PID_FILE} -m -c ${EFF_USER} -k 002 -x "${SERVICE_EXE}" -logfile /volume1/Logs/syncthing.log
```

This appears to work fine - but I'd rather have the options where they should be, rather than having them blown away whenever the package is going to get updated.

> So Syncthing's own log would be useful, but I've never found where that goes either...

Haha! Well that's what I'm trying to do here - get the Syncthing log written to disk!

**Comment by acolomb** [comment] 2019-08-22 17:32
I might have some time to investigate next week. The `start-stop-daemon` is used from busybox and its documentation also mentions the correct `--` separator. So currently no idea where it goes wrong, sorry.

**Comment by BenjV** [comment] 2019-08-22 18:19
Maybe the bash expansion of the  SERVICE_OPTIONS is the problem like in this issue:
https://stackoverflow.com/questions/1661193/start-stop-daemon-quoted-arguments-misinterpreted

**Comment by MoisieSyncthing** [comment] 2019-08-22 23:18
No worries, and no hurries - I appreciate your consideration!

**Comment by fgma** [comment] 2019-08-25 07:40
The issue is probably the one fixed in https://github.com/SynoCommunity/spksrc/pull/3689/files. Have a look at mk/spksrc.service.start-stop-daemon in that PR. The original version of the code did not work when adding multiple arguments so I had to remove the quotes around ${SERVICE_OPTIONS}.

**Comment by ymartin59** [comment] 2019-08-26 07:55
As minio has been merged, you may rebuild syncthing for your architecture and confirm custom command-line options no longer breaks service startup.

**Comment by MoisieSyncthing** [comment] 2019-08-27 07:34
> Have a look at mk/spksrc.service.start-stop-daemon in that PR. The original version of the code did not work when adding multiple arguments so I had to remove the quotes around ${SERVICE_OPTIONS}.

Bingo - that seems to have done it, thank you so much!

Now options.conf works for me with both the example option, and additional custom options. Many thanks!

**Comment by acolomb** [comment] 2019-09-15 18:26
So the only thing needed to close this issue is to re-publish Syncthing with the changes in `mk/spksrc.service.start-stop-daemon`?

I will make a PR to include the most recent Syncthing stable version as well.  It has some partly backwards-incompatible changes, so it's better when users see an up-to-date version for the SPK as well.   It auto-updates anyway right after installation, but publishind a recent version would save on migrations being done.

**Comment by MoisieSyncthing** [comment] 2019-09-19 22:20
> So the only thing needed to close this issue is to re-publish Syncthing with the changes in mk/spksrc.service.start-stop-daemon?

Yes - that works for me. Many thanks!

**Closed** 2019-10-21 20:57 UTC
