### ISSUE TITLE
Can't see the SynoCommunity Packages in Virtual DSM.

### ISSUE THREAD

**Issue by Birdy-Syno** [SynoCommunity/spksrc#2539] opened 2016-11-27 14:32 UTC
Hi SynoCommunity,

I have a three DSM environments running on my DS716+II
1 - **DS716+II**    DSM 6.1-14871 (Host)
2 - **VirtualDSM** DSM 6.1-14871
3 - **VirtualDSM** DSM 6.0.2-8451 Update 4

In environment:
1 - I do see your Packages.
2 - I do not see your Packages.
3 - I do not see your Packages.

The source location are the same in the three environments.

If I add other source locations to the Package Center, then I do see the Packages of those source locations.

Is it possible to fix this ?
If you need more information, please ask for it.

Thanks.
Birdy-Syno

**Comment by piwi82** [comment] 2016-11-29 11:41
The [`kvmx64`](https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model) architecture is not yet supported by SynoCommunity. This should be added [here](https://github.com/SynoCommunity/spksrc/blob/master/mk/spksrc.common.mk#L41).

**Comment by Dr-Bean** [comment] 2016-12-01 14:36
Duplicate of #2219. The arch has to be added to `TC_ARCH` when the DSM6.x toolchains are added. See https://github.com/SynoCommunity/spksrc/issues/2219#issuecomment-204292868.

The line in common.mk helps with determining if arches are supported by certain packages, I don't think we use it anywhere else (correct me if I'm wrong...)

**Comment by cyrus1977** [comment] 2016-12-02 12:16
Isn't this something that needs to be added central or can i just add to my local config ?

**Comment by Dr-Bean** [comment] 2016-12-08 12:24
The addition of x64 arches recognition is done via https://github.com/SynoCommunity/spksrc/commit/1b10900e3a8d4d88c69b90469d9315788a404284. This doesn't help anything without having the actual toolchains added to spksrc though, but I'd thought I'd put in in already ;)

**Comment by Dr-Bean** [comment] 2017-01-11 12:29
Done via 31e654b3526dbb6c21472551ed43203557aca741. This is currently a separate branch, but will be merged into master.

**Closed by Dr-Bean** 2017-01-11 12:29 UTC
Labels: repo, status/duplicate

**Comment by Dr-Bean** [comment] 2017-01-11 12:47
...and in case it's not clear, packages won't show up yet. See https://github.com/SynoCommunity/spksrc/issues/2216#issuecomment-271852804 for more info.
