### ISSUE TITLE
Syncthing 0.10.30 on Synology drive - where's the logs?

### ISSUE THREAD

**Issue by markyuk** [SynoCommunity/spksrc#1778] opened 2015-06-30 14:52 UTC
Hi there

I'm receiving Folder "XXX" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s really frequently on some remaining few MBs on a 200+GB folder structure.

Problem is - there's no logs created that I can see!  Where do they go?  I've installed from 0.10.30 build from SynoCommunity packages.

Clicking "Logs" in Package Center / Syncthing is blank.  And I've read somewhere that it normally logs to stdout if nothing is set.  How do I make sure the log is captured and I can read it?

If this is the wrong place to ask, please tell me and i'll pop this elsewhere :-)

Thanks!

**Comment by piwi82** [comment] 2015-06-30 16:28
This package could use logger : https://github.com/jedie/syncthing/wiki/Syncthing-in-Synology-DSM#creating-file-usrlocalsyncthingbinrunsyncthing

**Comment by Dr-Bean** [comment] 2015-07-02 09:40
Does https://github.com/syncthing/syncthing/pull/2001 address this? It's not part of an official Syncthing release yet, but that probably won't be too long off.

Seeing as I was working on updating the package, should we add the logger functionality anyway? There's no other method to get logs out of Syncthing that I'm aware of.

@markyuk In the meantime, you can run Syncthing directly from the command line (over SSH via Putty/Terminal) like this:
`/usr/local/syncthing/bin/syncthing --home /usr/local/syncthing/var`. That might enable you to see the cause of the issues. Stop the Syncthing package first. Use Ctrl-C to abort/kill the process again.

**Comment by Dr-Bean** [comment] 2015-07-16 11:16
Syncthing 0.11.15-4 has been published on the repository. 
@markyuk, can you please check if the Syncthing interface shows a more clear message to you? (To be clear: I mean the web interface of Syncthing itself, the log file in Package Center won't show anything)

**Comment by Dr-Bean** [comment] 2015-07-30 15:05
Closing this for now, as it should be covered with https://github.com/syncthing/syncthing/pull/2001 from what I understand. 

If it turns out it isn't, then preferably, an issue is opened on the Syncthing bugtracker to improve their logging/interface. If they find it's something we can fix on our side, then we can reopen this issue.

**Closed by Dr-Bean** 2015-07-30 15:05 UTC
Labels: enhancement, status/more-info-needed, update
