### ISSUE TITLE
DS216PLAY, CouchPotato and Failed to run package service

### ISSUE THREAD

**Issue by SiCliffy** [SynoCommunity/spksrc#2473] opened 2016-09-27 06:38 UTC
Hello all,

I have recently bought a DS216PLAY and have been going about installing CouchPotato. I have installed Python and Git. When I try to run CP, it errors with the common 'Failed to run package service' message.

I have updated to all the latest updates.

My big problem is I am an absolute newbie when it comes to SSH and all that. I don't even know how to run it or really get into it. 

I have downloaded iTerminal for my iPad to try and run SSH but I don't really know what I'm doing. I also have a laptop running Windows 10 if that would be better to run SSH.

So, my double question is; how do I fix my CP issue and can someone show me in really basic basic steps?

Thanks.

**Comment by thunfischbrot** [comment] 2016-11-11 11:56
Having similar issues with Couchpotato, NZBget, SABnzdb. Regarding your SSH issue: Enable the admin account on your Diskstation, give it a password, download Putty, enter your Diskstations IP address, press open, enter admin, enter the admin password. That should get you to the shell.

**Comment by Dr-Bean** [comment] 2016-11-15 20:22
Duplicate of https://github.com/SynoCommunity/spksrc/issues/2104, indeed related to #2216, and there's another (large) issue for general DSM6 compatibility issues.

**Closed by Dr-Bean** 2016-11-15 20:22 UTC
