### ISSUE TITLE
ruTorrent not compiling / rakshasa.no down

### ISSUE THREAD

**Issue by capkokoon** [SynoCommunity/spksrc#1749] opened 2015-06-09 19:27 UTC
Hi everyone,

Since rakshasa.no is down for several weeks, it might be a good time to modify the ruTorrent package so it can clone the libtorrent and rtorrent repositories directly from GitHub rather than downloading archives. I tried to make the modifications myself (adding new urls and new checksum), but the compilation fails when it tries to patch the libtorrent configure file for cross compiling ..
Any help on that would be much appreciated :)

Repos :
- libtorrent : https://github.com/rakshasa/libtorrent
- rtorrent : https://github.com/rakshasa/rtorrent

**Comment by Dr-Bean** [comment] 2015-06-10 12:41
I would suggest using the releases tagged on Github, instead of cloning the source. Anyway, you need to run `./autogen.sh` first, and then apply the patch (assuming it still applies cleanly).

**Comment by capkokoon** [comment] 2015-06-10 23:32
Yep, it works thanks to the autogen.sh script (the patch applies), until a certain point ... It appears that libtool is missing from the toolchains (even though it is set up on my VM)

##kokoon@debian:~/spksrc/spk/rutorrent$ make arch-armadaxp
===>  Building package for arch armadaxp
make[1]: Entering directory '/home/kokoon/spksrc/spk/rutorrent'
===>  Processing dependencies of rutorrent
make[2]: Entering directory '/home/kokoon/spksrc/cross/rtorrent'
===>  Compiling for rtorrent
BUSYBOX_CONFIG=usrmng daemon nice
ARCH=armadaxp
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
USER=kokoon
CXXFLAGS=-I/home/kokoon/spksrc/toolchains/syno-armadaxp-5.1/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/include -mcpu=marvell-pj4 -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=hard -DSYNO_MARVELL_ARMADA370 -DSYNO_PLATFORM=MARVELL_ARMADA370 -I/home/kokoon/spksrc/spk/rutorrent/work-armadaxp-5.1/install//usr/local/rutorrent/include
XDG_SEAT=seat0
SSH_AGENT_PID=984
WORK_DIR=/home/kokoon/spksrc/spk/rutorrent/work-armadaxp-5.1
LDSHARED=/home/kokoon/spksrc/toolchains/syno-armadaxp-5.1/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-gcc -shared
SHLVL=1
HOME=/home/kokoon
OLDPWD=/home/kokoon/spksrc/cross/rtorrent
DESKTOP_SESSION=default
LDFLAGS=-L/home/kokoon/spksrc/toolchains/syno-armadaxp-5.1/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/lib -mcpu=marvell-pj4 -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=hard -L/home/kokoon/spksrc/spk/rutorrent/work-armadaxp-5.1/install//usr/local/rutorrent/lib -Wl,--rpath-link,/home/kokoon/spksrc/spk/rutorrent/work-armadaxp-5.1/install//usr/local/rutorrent/lib -Wl,--rpath,/usr/local/rutorrent/lib
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-Xe9MszjDUS,guid=aa58b7efaf77340a35413cdf5578baeb
MAKEFLAGS=w -- ARCH=armadaxp TCVERSION=5.1
CPP=/home/kokoon/spksrc/toolchains/syno-armadaxp-5.1/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-cpp
TC=syno-armadaxp-5.1
STRIP=/home/kokoon/spksrc/toolchains/syno-armadaxp-5.1/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-strip
LOGNAME=kokoon
_=/usr/bin/make
WINDOWID=35651590
TCVERSION=5.1
AR=/home/kokoon/spksrc/toolchains/syno-armadaxp-5.1/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ar
READELF=/home/kokoon/spksrc/toolchains/syno-armadaxp-5.1/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-readelf
USERNAME=kokoon
AS=/home/kokoon/spksrc/toolchains/syno-armadaxp-5.1/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-as
XDG_SESSION_ID=1
TERM=xterm
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
WINDOWPATH=7
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
GDM_LANG=en_US.UTF-8
SESSION_MANAGER=local/debian:@/tmp/.ICE-unix/947,unix/debian:/tmp/.ICE-unix/947
CFLAGS=-I/home/kokoon/spksrc/toolchains/syno-armadaxp-5.1/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/include -mcpu=marvell-pj4 -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=hard -DSYNO_MARVELL_ARMADA370 -DSYNO_PLATFORM=MARVELL_ARMADA370 -I/home/kokoon/spksrc/spk/rutorrent/work-armadaxp-5.1/install//usr/local/rutorrent/include
XDG_RUNTIME_DIR=/run/user/1000
XDG_MENU_PREFIX=gnome-
MAKELEVEL=3
DISPLAY=:0
XDG_CURRENT_DESKTOP=GNOME
LANG=en_US.UTF-8
XAUTHORITY=/var/run/gdm3/auth-for-kokoon-HTdpa9/database
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
XDG_SESSION_DESKTOP=default
MAKEOVERRIDES=${-*-command-variables-*-}
CPPFLAGS=-I/home/kokoon/spksrc/toolchains/syno-armadaxp-5.1/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/include -mcpu=marvell-pj4 -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=hard -DSYNO_MARVELL_ARMADA370 -DSYNO_PLATFORM=MARVELL_ARMADA370 -I/home/kokoon/spksrc/spk/rutorrent/work-armadaxp-5.1/install//usr/local/rutorrent/include
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
SHELL=/bin/bash
GDMSESSION=default
CXX=/home/kokoon/spksrc/toolchains/syno-armadaxp-5.1/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-g++
SPKSRC_WIZARDS_DIR=src/wizard/
GPG_AGENT_INFO=/run/user/1000/keyring/gpg:0:1
GJS_DEBUG_OUTPUT=stderr
XDG_VTNR=7
INSTALL_DIR=/home/kokoon/spksrc/spk/rutorrent/work-armadaxp-5.1/install
PWD=/home/kokoon/spksrc/spk/rutorrent/work-armadaxp-5.1/rtorrent-0.9.4
XDG_DATA_DIRS=/usr/share/gnome:/usr/local/share/:/usr/share/
LD=/home/kokoon/spksrc/toolchains/syno-armadaxp-5.1/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ld
CC=/home/kokoon/spksrc/toolchains/syno-armadaxp-5.1/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-gcc
RANLIB=/home/kokoon/spksrc/toolchains/syno-armadaxp-5.1/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ranlib
MFLAGS=-w
VTE_VERSION=3801
INSTALL_PREFIX=/usr/local/rutorrent
PKG_CONFIG_LIBDIR=/home/kokoon/spksrc/spk/rutorrent/work-armadaxp-5.1/install//usr/local/rutorrent/lib/pkgconfig
NM=/home/kokoon/spksrc/toolchains/syno-armadaxp-5.1/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-nm
OBJDUMP=/home/kokoon/spksrc/toolchains/syno-armadaxp-5.1/work/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-objdump
/bin/sh: 1: libtool: not found
Makefile:30: recipe for target 'myCompile' failed
make[2]: *** [myCompile] Error 127
make[2]: Leaving directory '/home/kokoon/spksrc/cross/rtorrent'
../../mk/spksrc.depend.mk:44: recipe for target 'depend_target' failed
make[1]: *** [depend_target] Error 2
make[1]: Leaving directory '/home/kokoon/spksrc/spk/rutorrent'
../../mk/spksrc.spk.mk:417: recipe for target 'arch-armadaxp' failed
make: [arch-armadaxp] Error 2 (ignored)##

**Comment by Dr-Bean** [comment] 2015-06-11 08:47
A copy of `libtool` is generated in the working directory during execution of ./configure (or more specifically in the case of libtorrent: because `GNU_CONFIGURE = 1` is set).
So, either you skipped executing `./configure`, or one of the previous steps failed to execute correctly.

I'd suggest to work step by step. 
First, verify that, at the very least, all the requirements are installed. There might be new requirements specific to this case, because the compile process for libtorrent changed.
See if you can succesfully compile `cross/libtorrent-rakshasa` by itself. Solve problems you run into, and note that those problems don't necessarily mean the make process breaks immediately. Check previous output, check logs if available.
Make sure to clean the working directory after changing things in the setup, e.g use `make clean`.
Only then move over to build the SPK.

**Comment by Dr-Bean** [comment] 2015-06-12 08:53
Found it. Replace `@$(RUN) ; libtool` with `@$(RUN) ; ./libtool` in rtorrent's Makefile.

**Comment by capkokoon** [comment] 2015-06-13 10:09
It works ! Is there a way to include the execution of autogen.sh in the Makefile script ? atm I have to stop the compilation to force ./autogen.sh and then relaunch it.

**Comment by Dr-Bean** [comment] 2015-06-13 13:13
Sure. Several ways in fact, but you need to get to know spksrc ;) The most sensible way is to override [`PRE_PATCH_TARGET`](https://github.com/SynoCommunity/spksrc/blob/master/mk/spksrc.patch.mk#L45), because you want to do something _before_ the actual application of the patches. `PRE_PATCH_TARGET` is executed before `PATCH_TARGET`, so that's what you want.

To do that, set `PRE_PATCH_TARGET = myPrePatch`. In `myPrePatch`, you can add your own recipe, which would be something like `@$(RUN) ; ./autogen.sh`.

As example: `cross/rtorrent` already does the same thing for [PRE_CONFIGURE_TARGET](https://github.com/SynoCommunity/spksrc/blob/master/cross/rtorrent/Makefile#L17): it's defined as [myPreConfigure](https://github.com/SynoCommunity/spksrc/blob/master/cross/rtorrent/Makefile#L24), so instead of the normal recipe, a different recipe, specific to rtorrent, is executed

**Comment by capkokoon** [comment] 2015-06-15 13:58
Ok thanks ! See pull request #1758 :)

**Comment by Dr-Bean** [comment] 2015-06-15 14:41
Thanks, but I assume you want to take this a step further, right? Even though fixing download sites is fine in itself (and appreciated!), it's of little use of the package doesn't work correctly.

There are a lot of open issues regarding rutorrent unfortunately, and even though some of those might be caused by configuration issues/user error, those should at least be checked to see if we can do something about it.
Until that's done, there's no reason to to bump rutorrent's SPK_REV or release an updated version of the package.

**Comment by capkokoon** [comment] 2015-06-17 11:20
Yup. I would be glad to help, but I might not have the technical background to be of use here .. I'll try :)

**Comment by capkokoon** [comment] 2015-06-18 12:01
#1712 fixed

**Comment by capkokoon** [comment] 2015-06-18 12:05
#691 fixed

**Comment by Dr-Bean** [comment] 2015-06-19 08:02
ty :)

**Comment by Dr-Bean** [comment] 2015-07-21 07:15
Fixed sites with https://github.com/SynoCommunity/spksrc/commit/7a2e8e1db7c5f7bc45320864cb61debb7d11be0e. I guess we can close this one.

**Closed by Dr-Bean** 2015-07-21 07:15 UTC
