### ISSUE TITLE
[Package Request] neovim

### ISSUE THREAD

**Issue by etcusrvar** [SynoCommunity/spksrc#4471] opened 2021-03-05 04:43 UTC
* Name: neovim
* Description: Vim-fork focused on extensibility and usability
* Website: https://github.com/neovim/neovim
* Software documentation: https://github.com/neovim/neovim
* Build/Installation documentation: https://github.com/neovim/neovim
* Source code:  https://github.com/neovim/neovim
* License: https://github.com/neovim/neovim/blob/master/LICENSE

I can work on adding this myself as time permits. Or others can if they have bandwidth.

But I'm unclear if it should be a standalone package, or if it should be incuded in synocli-file or other syno-* package.

**Comment by hgy59** [comment] 2021-11-06 11:26
duplicate of #3871

**Closed by hgy59** 2021-11-06 11:26 UTC
Labels: request
