### ISSUE TITLE
selfoss no longer updates feeds

### ISSUE THREAD

**Issue by coppolajj** [SynoCommunity/spksrc#1817] opened 2015-08-16 00:21 UTC
My install of selfoss (2.13) no longer updates it feeds.  I need to log in as root to force an update...
  `php /var/services/web/selfoss/update.php`

the refresh sources button gives me the following error...
  `Can not refresh sources: Internal Server Error`

any ideas?

**Comment by Dr-Bean** [comment] 2015-08-17 08:04
Dupe of #1764.

**Closed by Dr-Bean** 2015-08-17 08:04 UTC
