### ISSUE TITLE
some Borg Backup stop with borg.remote.ConnectionClosed

### ISSUE THREAD

**Issue by Nono-m0le** [SynoCommunity/spksrc#4260] opened 2020-11-06 23:50 UTC
I thought it was a Borg issue, so I raise at ticket a borgbackup main repo first (see here: https://github.com/borgbackup/borg/issues/5457 )
But it turns out it may be an "SSH issue", which I find strange, knowing that out of 5 VMS, it's not always the same which is faulty.

### Setup
_Package Name:_ Borg
_Package Version:_ 1.1.13-6

_NAS Model:_ DS213j
_NAS Architecture:_ dunno
_DSM version:_ DSM 6.2.3-25426 Update 2

### Expected behavior
I'm running a dedicated server with XEN and few VM on it.
All VM should be backup without issue.

### Actual behavior
Sometimes, some backup failed. It's never at the same time, from the same VM or even at the same files (see link to the issue above).

### Steps to reproduce
_1._ run backup from each VM everyday
_2._ wait for the first backup to fail

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
can't seems to find anything on /user/local/borgbackup/var/
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
neither messages or synopkg.log show anything interesting
```

**Comment by BenjV** [comment] 2020-11-07 09:36
If it is not reproduceable in other VM's with the same software it must be something outside the environment.
Most likely a network issue when the server on the other times out and close the connection.

**Comment by Nono-m0le** [comment] 2020-11-08 00:40
Well, it is reproduceable, but not on demand ...
Here is the thing, every night from 1AM to 6AM, I'm executing the borg create on 5 differents VMs:
Here are my states of the week:
01/11: VM1; VM2 failed, the 3 others suceed
02/11: VM3; VM1; VM2 failed, the 2 others suceed
03/11: VM3, VM1, VM2 failed, the 2 others suceed
04/11: VM4, VM1, VM2 failed, the 2 others suceed
05/11: All 5 VMs succeed
06/11: All 5 VMs succeed
07/11: VM1, VM2 failed, the 3 others suceed

I tend to agree, that's could be a connection issue, but so frequently ? I would understand once every week or month a fail, but not almost every night.

**Comment by BenjV** [comment] 2020-11-08 10:41
With this variation it cannot be a problem of the package nor of the Borg backup software.
I don't know Borg backup but lots of backup software is not capable of handeling the variations in response delay of the remote server.
In other words they are designed to function in Lan and not over the internet.

I would suggest to use software that is designed to work via the internet.

**Comment by wereii** [comment] 2022-03-10 20:00
Hey, @Nono-m0le have you ever resolved this? 

It's really weird, normal ssh connections work flawlessly and never time out, even when I force something like `sleep 3000` on the NAS to simulate no transfer of data thru the ssh connection but `borg serve` seems to keep disconnecting especially when the client starts doing `borg prune` or `borg create` (takes more then 10 minutes).

**Comment by Nono-m0le** [comment] 2022-03-10 22:55
Hi @wereii actually not, but I stopped using my Syno for this purpose so I can't reproduce the issue. I guess I'll have to close this ticket ?

**Comment by th0ma7** [comment] 2022-03-11 13:33
I published an updated version of borgbackup a few days ago.  Issue might be resolved by now?
https://synocommunity.com/package/borgbackup

**Comment by wereii** [comment] 2022-03-11 14:21
I am already on v1.2.0-10. 
I think when I had older borg version (one that used the older python, not py3.10) these disconnects did not happen.

This is `DS220j` with `DSM 6.2.4-25556 Update 5`. 
Any other ssh connection works alright and does not disconnect when inactive, but this almost looks like the server (NAS) `borg serve` (`command="..."` in authorized_keys) "timeouts" as I am always getting "Connection closed by remote host" on the client.

`/var/log/messages` shows nothing as well as other logs, only that the ssh connection closes, but it's rather hard to examine if it's ssh that closes the connection or borg itself. 
I am wondering if it's possible that the DSM itself is somehow conservative with connections and kills the process but then again I would expect to see some logs.

**Comment by mreid-tt** [comment] 2024-11-08 01:58
Hi @Nono-m0le, is this still an issue with the latest version of Borg Backup? Since there hasn’t been an update on this for a while, I’m reviewing and cleaning up old issues.

**Closed** 2024-11-08 05:35 UTC
