### ISSUE TITLE
ruTorrent didnt load (initially) but now cant use

### ISSUE THREAD

**Issue by a7mag3ddon** [SynoCommunity/spksrc#4411] opened 2021-01-29 09:24 UTC
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ ruTorrent
_Package Version:_ 3.10-10

_NAS Model:_ DS1515+
_NAS Architecture:_ 
_DSM version:_ DSM 6.2.3-25426 Update 3

### Expected behavior

installed package rutorrent from package centre, initially when i tried to access using link on info page it took me to the DSM login screen, googled and found the fixes, installed apache, php and webstation. Can now access when clicking link (1st question should i need to install all of that to access rutorrent internally? no good instructions)

Current problem, when i tried to add torrent file, access settings etc nothing happens. Click world, brows to torrent click ADD dialoge bpx resets back to browse for torrent. when clicking on settings and other things get errors in the log screen.....

[29.01.2021 09:22:47] WebUI started.
[29.01.2021 09:22:47] Bad response from server: (500 [error,getplugins]) Internal Server Error
[29.01.2021 09:22:49] JS error: [http://192.168.2.21/rutorrent/js/webui.js : 765] TypeError: this.systemInfo is undefined

### Steps to reproduce
_1._ install rutorrent
_2._ try and use, wont work - install webstation, apache, php to get initially working
_3._ browse to //ip.address.of.nas/rutorrent then try adding a torrent file or access settings

#### Package log
Not sure how to get these
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by smaarn** [comment] 2021-01-30 11:13
Hello,

Would it be possible to have the contents of the following file: `/var/packages/rutorrent/target/var/rutorrent_install.log` ?

This should contain logs which could help us regarding checking the root cause for your errors (most presumably file rights errors).

**Comment by smaarn** [comment] 2021-01-30 11:16
You should be able to get this file by logging via WinSCP - if you're a Windows user - or Cyberduck - if you're a Mac one - to your DiskStation.

**Comment by smaarn** [comment] 2021-01-30 11:16
(provided that ssh access is enabled on your DiskStation, of course)

**Comment by a7mag3ddon** [comment] 2021-01-31 10:57
Apologies for the delay replying, i went away for the weekend just as you replied! Please let me know if theres anything in the following LOG that i shouldnt be posting publicly so i can remove :-)

Thu Jan 28 21:43:06 GMT 2021
===> Step preuninst. USER=rutorrent GROUP=sc-download SHARE_PATH=/volume1/Vol1/RomSets/Pleasuredome_Torrents
Removing service configuration rutorrent.sc
Thu Jan 28 21:43:07 GMT 2021
===> Step postuninst. USER=rutorrent GROUP=sc-download SHARE_PATH=/volume1/Vol1/RomSets/Pleasuredome_Torrents
Removing user sc-rutorrent
Invoke service_postuninst
Thu Jan 28 21:43:08 GMT 2021
===> Step Removing web interface. USER=rutorrent GROUP=sc-download SHARE_PATH=/volume1/Vol1/RomSets/Pleasuredome_Torrents
Thu Jan 28 21:54:46 GMT 2021
===> Step preinst. USER=rutorrent GROUP=sc-download SHARE_PATH=/volume1/Vol1/RomSets/Pleasuredome_Torrents
Invoke service_preinst
Thu Jan 28 21:54:47 GMT 2021
===> Step postinst. USER=rutorrent GROUP=sc-download SHARE_PATH=/volume1/Vol1/RomSets/Pleasuredome_Torrents
Installing service configuration /var/packages/rutorrent/conf/rutorrent.sc
Adding 'sc-rutorrent' to 'sc-download'
Group Name: [sc-download]
Group Type: [AUTH_LOCAL]
Group ID:   [65537]
Group Members: 
0:[sc-deluge]
1:[sc-rutorrent]
Configuring /volume1/Vol1/RomSets/Pleasuredome_Torrents
Granting 'sc-download' group permissions on /volume1/Vol1/RomSets/Pleasuredome_Torrents
ACL version: 1 
Archive: is_inherit,has_ACL,is_support_ACL 
Owner: [carl(user)] 
--------------------- 
	 [0] group:sc-download:allow:rwxpdDaARWcC-:fd--  (level:0)
	 [1] group:sc-download:allow:rwxpdDaARWc--:fd--  (level:1)
	 [2] user:carl:allow:rwxpdDaARWc--:fd--  (level:2)
	 [3] user:peecee:allow:rwxpdDaARWc--:fd--  (level:2)
	 [4] user::allow:rwxpdDaARWc--:fd--  (level:2)
	 [5] group:administrators:allow:rwxpdDaARWc--:fd--  (level:2)
	 [6] user::allow:r-x---a-R-c--:fd--  (level:2)
	 [7] user:guest:allow:r-x---a-R-c--:fd--  (level:2)
Invoke service_postinst
Granting 'sc-download' group permissions on /volume1/Vol1/RomSets/Pleasuredome_Torrents
ACL version: 1 
Archive: is_inherit,has_ACL,is_support_ACL 
Owner: [carl(user)] 
--------------------- 
	 [0] group:sc-download:allow:rwxpdDaARWcC-:fd--  (level:0)
	 [1] group:sc-download:allow:rwxpdDaARWc--:fd--  (level:1)
	 [2] user:carl:allow:rwxpdDaARWc--:fd--  (level:2)
	 [3] user:peecee:allow:rwxpdDaARWc--:fd--  (level:2)
	 [4] user::allow:rwxpdDaARWc--:fd--  (level:2)
	 [5] group:administrators:allow:rwxpdDaARWc--:fd--  (level:2)
	 [6] user::allow:r-x---a-R-c--:fd--  (level:2)
	 [7] user:guest:allow:r-x---a-R-c--:fd--  (level:2)
/var/packages/rutorrent/scripts/service-setup: line 187: /usr/local/python3/bin/virtualenv: No such file or directory
/var/packages/rutorrent/scripts/service-setup: line 189: /volume1/@appstore/rutorrent/env/bin/pip: No such file or directory
Fixing shared folder rights for /volume1/@appstore/rutorrent/tmp
(synoacltool.c, 455)Unknown error 
Fixing shared folder access for everyone
ACL version: 1 
Archive: has_ACL,is_support_ACL 
Owner: [sc-rutorrent(user)] 
--------------------- 
	 [0] everyone::allow:r-x----------:fd--  (level:0)
Fixing shared folder access for user:sc-rutorrent
ACL version: 1 
Archive: has_ACL,is_support_ACL 
Owner: [sc-rutorrent(user)] 
--------------------- 
	 [0] everyone::allow:r-x----------:fd--  (level:0)
	 [1] user:sc-rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
Fixing shared folder access for group:rutorrent
ACL version: 1 
Archive: has_ACL,is_support_ACL 
Owner: [sc-rutorrent(user)] 
--------------------- 
	 [0] everyone::allow:r-x----------:fd--  (level:0)
	 [1] group:rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
	 [2] user:sc-rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
Fixing shared folder access for user:http
ACL version: 1 
Archive: has_ACL,is_support_ACL 
Owner: [sc-rutorrent(user)] 
--------------------- 
	 [0] everyone::allow:r-x----------:fd--  (level:0)
	 [1] user:http:allow:rwxp-D-------:fd--  (level:0)
	 [2] user:sc-rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
	 [3] group:rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
Fixing shared folder access for group:http
ACL version: 1 
Archive: has_ACL,is_support_ACL 
Owner: [sc-rutorrent(user)] 
--------------------- 
	 [0] everyone::allow:r-x----------:fd--  (level:0)
	 [1] group:http:allow:rwxp-D-------:fd--  (level:0)
	 [2] group:rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
	 [3] user:sc-rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
	 [4] user:http:allow:rwxp-D-------:fd--  (level:0)
find ${folder} -mindepth 1 -type d -exec synoacltool -enforce-inherit {} \;
Fixing shared folder access for /var/services/web
ACL version: No ACL 
Archive: None 
Owner: [sc-rutorrent(user)] 
==================================================== 
User/Group: [sc-rutorrent/sc-download,rutorrent]

Final permission: [rwxp-DaARWcCo] 

Fixing shared folder rights for /var/services/web/rutorrent/share
(synoacltool.c, 455)Unknown error 
Fixing shared folder access for everyone
(synoacltool.c, 140)It's Linux mode
Fixing shared folder access for user:sc-rutorrent
(synoacltool.c, 140)It's Linux mode
Fixing shared folder access for group:rutorrent
(synoacltool.c, 140)It's Linux mode
Fixing shared folder access for user:http
(synoacltool.c, 140)It's Linux mode
Fixing shared folder access for group:http
(synoacltool.c, 140)It's Linux mode
find ${folder} -mindepth 1 -type d -exec synoacltool -enforce-inherit {} \;
Granting 'sc-rutorrent' unix ownership on /volume1/@appstore/rutorrent/var
Thu Jan 28 22:30:32 GMT 2021
===> Step preuninst. USER=rutorrent GROUP=sc-download SHARE_PATH=/volume1/Vol1/RomSets/Pleasuredome_Torrents
Removing service configuration rutorrent.sc
Thu Jan 28 22:30:33 GMT 2021
===> Step postuninst. USER=rutorrent GROUP=sc-download SHARE_PATH=/volume1/Vol1/RomSets/Pleasuredome_Torrents
Removing user sc-rutorrent
Invoke service_postuninst
Thu Jan 28 22:30:34 GMT 2021
===> Step Removing web interface. USER=rutorrent GROUP=sc-download SHARE_PATH=/volume1/Vol1/RomSets/Pleasuredome_Torrents
Thu Jan 28 22:33:21 GMT 2021
===> Step preinst. USER=rutorrent GROUP=sc-download SHARE_PATH=/volume1/Vol1/RomSets/Pleasuredome_Torrents
Invoke service_preinst
Thu Jan 28 22:33:23 GMT 2021
===> Step postinst. USER=rutorrent GROUP=sc-download SHARE_PATH=/volume1/Vol1/RomSets/Pleasuredome_Torrents
Installing service configuration /var/packages/rutorrent/conf/rutorrent.sc
Adding 'sc-rutorrent' to 'sc-download'
Group Name: [sc-download]
Group Type: [AUTH_LOCAL]
Group ID:   [65537]
Group Members: 
0:[sc-deluge]
1:[sc-rutorrent]
Configuring /volume1/Vol1/RomSets/Pleasuredome_Torrents
Granting 'sc-download' group permissions on /volume1/Vol1/RomSets/Pleasuredome_Torrents
ACL version: 1 
Archive: is_inherit,has_ACL,is_support_ACL 
Owner: [carl(user)] 
--------------------- 
	 [0] group:sc-download:allow:rwxpdDaARWcC-:fd--  (level:0)
	 [1] group:sc-download:allow:rwxpdDaARWc--:fd--  (level:1)
	 [2] user:carl:allow:rwxpdDaARWc--:fd--  (level:2)
	 [3] user:peecee:allow:rwxpdDaARWc--:fd--  (level:2)
	 [4] user::allow:rwxpdDaARWc--:fd--  (level:2)
	 [5] group:administrators:allow:rwxpdDaARWc--:fd--  (level:2)
	 [6] user::allow:r-x---a-R-c--:fd--  (level:2)
	 [7] user:guest:allow:r-x---a-R-c--:fd--  (level:2)
Invoke service_postinst
Granting 'sc-download' group permissions on /volume1/Vol1/RomSets/Pleasuredome_Torrents
ACL version: 1 
Archive: is_inherit,has_ACL,is_support_ACL 
Owner: [carl(user)] 
--------------------- 
	 [0] group:sc-download:allow:rwxpdDaARWcC-:fd--  (level:0)
	 [1] group:sc-download:allow:rwxpdDaARWc--:fd--  (level:1)
	 [2] user:carl:allow:rwxpdDaARWc--:fd--  (level:2)
	 [3] user:peecee:allow:rwxpdDaARWc--:fd--  (level:2)
	 [4] user::allow:rwxpdDaARWc--:fd--  (level:2)
	 [5] group:administrators:allow:rwxpdDaARWc--:fd--  (level:2)
	 [6] user::allow:r-x---a-R-c--:fd--  (level:2)
	 [7] user:guest:allow:r-x---a-R-c--:fd--  (level:2)
Granting 'sc-download' group permissions on /volume1/Vol1/test
ACL version: 1 
Archive: is_inherit,has_ACL,is_support_ACL 
Owner: [peecee(user)] 
--------------------- 
	 [0] group:sc-download:allow:rwxpdDaARWcC-:fd--  (level:0)
	 [1] user:carl:allow:rwxpdDaARWc--:fd--  (level:1)
	 [2] user:peecee:allow:rwxpdDaARWc--:fd--  (level:1)
	 [3] user::allow:rwxpdDaARWc--:fd--  (level:1)
	 [4] group:administrators:allow:rwxpdDaARWc--:fd--  (level:1)
	 [5] user::allow:r-x---a-R-c--:fd--  (level:1)
	 [6] user:guest:allow:r-x---a-R-c--:fd--  (level:1)
Granting 'sc-download' group basic permissions on /volume1/Vol1/test
ACL version: 1 
Archive: is_inherit,has_ACL,is_support_ACL 
Owner: [peecee(user)] 
--------------------- 
	 [0] group:sc-download:allow:r-x---a-R----:---n  (level:0)
	 [1] user:carl:allow:rwxpdDaARWc--:fd--  (level:1)
	 [2] user:peecee:allow:rwxpdDaARWc--:fd--  (level:1)
	 [3] user::allow:rwxpdDaARWc--:fd--  (level:1)
	 [4] group:administrators:allow:rwxpdDaARWc--:fd--  (level:1)
	 [5] user::allow:r-x---a-R-c--:fd--  (level:1)
	 [6] user:guest:allow:r-x---a-R-c--:fd--  (level:1)
/var/packages/rutorrent/scripts/service-setup: line 187: /usr/local/python3/bin/virtualenv: No such file or directory
/var/packages/rutorrent/scripts/service-setup: line 189: /volume1/@appstore/rutorrent/env/bin/pip: No such file or directory
Fixing shared folder rights for /volume1/@appstore/rutorrent/tmp
(synoacltool.c, 455)Unknown error 
Fixing shared folder access for everyone
ACL version: 1 
Archive: has_ACL,is_support_ACL 
Owner: [sc-rutorrent(user)] 
--------------------- 
	 [0] everyone::allow:r-x----------:fd--  (level:0)
Fixing shared folder access for user:sc-rutorrent
ACL version: 1 
Archive: has_ACL,is_support_ACL 
Owner: [sc-rutorrent(user)] 
--------------------- 
	 [0] everyone::allow:r-x----------:fd--  (level:0)
	 [1] user:sc-rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
Fixing shared folder access for group:rutorrent
ACL version: 1 
Archive: has_ACL,is_support_ACL 
Owner: [sc-rutorrent(user)] 
--------------------- 
	 [0] everyone::allow:r-x----------:fd--  (level:0)
	 [1] group:rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
	 [2] user:sc-rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
Fixing shared folder access for user:http
ACL version: 1 
Archive: has_ACL,is_support_ACL 
Owner: [sc-rutorrent(user)] 
--------------------- 
	 [0] everyone::allow:r-x----------:fd--  (level:0)
	 [1] user:http:allow:rwxp-D-------:fd--  (level:0)
	 [2] user:sc-rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
	 [3] group:rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
Fixing shared folder access for group:http
ACL version: 1 
Archive: has_ACL,is_support_ACL 
Owner: [sc-rutorrent(user)] 
--------------------- 
	 [0] everyone::allow:r-x----------:fd--  (level:0)
	 [1] group:http:allow:rwxp-D-------:fd--  (level:0)
	 [2] group:rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
	 [3] user:sc-rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
	 [4] user:http:allow:rwxp-D-------:fd--  (level:0)
find ${folder} -mindepth 1 -type d -exec synoacltool -enforce-inherit {} \;
Fixing shared folder access for /var/services/web
ACL version: No ACL 
Archive: None 
Owner: [sc-rutorrent(user)] 
==================================================== 
User/Group: [sc-rutorrent/sc-download,rutorrent]

Final permission: [rwxp-DaARWcCo] 

Fixing shared folder rights for /var/services/web/rutorrent/share
(synoacltool.c, 455)Unknown error 
Fixing shared folder access for everyone
(synoacltool.c, 140)It's Linux mode
Fixing shared folder access for user:sc-rutorrent
(synoacltool.c, 140)It's Linux mode
Fixing shared folder access for group:rutorrent
(synoacltool.c, 140)It's Linux mode
Fixing shared folder access for user:http
(synoacltool.c, 140)It's Linux mode
Fixing shared folder access for group:http
(synoacltool.c, 140)It's Linux mode
find ${folder} -mindepth 1 -type d -exec synoacltool -enforce-inherit {} \;

**Comment by a7mag3ddon** [comment] 2021-01-31 11:04
also, did i need to install all the other stuff as well? i get the feeling that was a fix from before it was available in the package centre, i have deluge on there as well (disabled at the moment) at it didnt need anything like webstation, php etc.

**Comment by smaarn** [comment] 2021-01-31 17:02
> also, did i need to install all the other stuff as well? i get the feeling that was a fix from before it was available in the package centre, i have deluge on there as well (disabled at the moment) at it didnt need anything like webstation, php etc.

Well, if by "other stuff" you mean "WebStation" and "php" you do need to install them as `rutorrent` is a php wrapper around `rtorrent`. The spk should be updated to mention that `WebStation` is required. The installed php version may not be critical (WebStation handles it).
I cannot speak for deluge itself.

**Comment by smaarn** [comment] 2021-01-31 17:22
I checked your logs and there are several things worth noting:

1. The errors around pip and virtualenv are "normal" if you don't have Python 3 SPK installed (it seems that the SPK dependencies are not properly declared, will work on it)
2. There are errors occurring around the `synoacltool -del xxxx` commands (`(synoacltool.c, 455)Unknown error`), I'll try to check those
3. It seems that the core issue is with the rights defined for the `/var/services/web/rutorrent/share` folder (in this folder lies everything around plugins and php code which needs to be executed by both `rtorrent` and `rutorrent`). This is described by the following log sequence:
```
Fixing shared folder rights for /var/services/web/rutorrent/share
(synoacltool.c, 455)Unknown error
Fixing shared folder access for everyone
(synoacltool.c, 140)It's Linux mode
Fixing shared folder access for user:sc-rutorrent
(synoacltool.c, 140)It's Linux mode
Fixing shared folder access for group:rutorrent
(synoacltool.c, 140)It's Linux mode
Fixing shared folder access for user:http
(synoacltool.c, 140)It's Linux mode
Fixing shared folder access for group:http
(synoacltool.c, 140)It's Linux mode
find ${folder} -mindepth 1 -type d -exec synoacltool -enforce-inherit {} ;
```

Would you be able to tell me the outcome of the following commands: 

* `synoacltool -get /var/services/web/rutorrent/share`
* `synoacltool -get /ver/services/web/rutorrent`
* `synoacltool -get /var/services/web`

It may be a case which we never faced so far :/

**Comment by a7mag3ddon** [comment] 2021-01-31 18:27
hello,

yes of course heres the results of each.


    synoacltool -get /var/services/web/rutorrent/share
(synoacltool.c, 359)It's Linux mode

    synoacltool -get /ver/services/web/rutorrent
(synoacltool.c, 359)Path not found

    synoacltool -get /var/services/web
#(synoacltool.c, 359)It's Linux mode

**Comment by a7mag3ddon** [comment] 2021-01-31 18:29
I have also checked /ver/services/web/rutorrent folder and there are files there, just in case you were going to ask me to check.

**Comment by hgy59** [comment] 2021-01-31 19:29
> Well, if by "other stuff" you mean "WebStation" and "php" you do need to install them as `rutorrent` is a php wrapper around `rtorrent`. The spk should be updated to mention that `WebStation` is required. The installed php version may not be critical (WebStation handles it).

This was addressed long ago (#2591)

**Comment by a7mag3ddon** [comment] 2021-02-01 10:18
> 
> 
> > Well, if by "other stuff" you mean "WebStation" and "php" you do need to install them as `rutorrent` is a php wrapper around `rtorrent`. The spk should be updated to mention that `WebStation` is required. The installed php version may not be critical (WebStation handles it).
> 
> This was addressed long ago (#2591)

Sorry i dont understand what you mean by addressed, are those programs needed to be installed or not? because if they arent required i couldnt get it working without them.

**Comment by hgy59** [comment] 2021-02-01 17:14
> Sorry i dont understand what you mean by addressed, are those programs needed to be installed or not? because if they arent required i couldnt get it working without them.

I only wanted to tell that this bug was found and an issue created in Jan 2017 but nobody did care about this, until now....

**Comment by a7mag3ddon** [comment] 2021-02-05 07:59
What do i need to do to fix the install? Did you mamage to work it out from my logs?

Thanks

**Comment by th0ma7** [comment] 2021-02-05 11:54
Just a thought but I believe this may solve your issue:
1. Enable ACL support (see https://github.com/SynoCommunity/spksrc/wiki/Permission-Management)
2. Uninstall completely `rutorrent` then reinstall

**Comment by a7mag3ddon** [comment] 2021-02-05 12:12
ACL support is per folder ? Which do i enable it for. Also ive always been on DSM 6 so wont have been on the old method.

**Comment by a7mag3ddon** [comment] 2021-02-05 12:15
Ok confirmed,  Convert to Windows ACL is greyed out on all my folders within Control Panel > shared folder

**Comment by smaarn** [comment] 2021-02-06 18:01
> Ok confirmed, Convert to Windows ACL is greyed out on all my folders within Control Panel > shared folder

This may not actually be an issue since it's only related to shared folders and to shared folders created with DSM 5 and doesn't apply. On my NAS this option is also greyed out and ACL do work.
One question though: **is the `web` directory in the shared folders ?**

The real issue here is that ACLs are, indeed, mandatory in our use case.

**Comment by a7mag3ddon** [comment] 2021-02-06 18:50
Yes it is

**Comment by a7mag3ddon** [comment] 2021-02-07 11:51
Did the logs show anything not setup correctly?

**Comment by smaarn** [comment] 2021-02-07 12:25
> Did the logs show anything not setup correctly? 

Well, that's the thing. They basically say that it failed setting up ACL rights on the web related resources (which is the rutorrent layer wrapper). 

The issue here is that I don't know if there is a way to fix this manually since the issue is about defining ACL rights. 😞

**Comment by smaarn** [comment] 2021-02-07 16:27
To be more specific, the issues which are being reported in the logs (and which explain why you can't have rutorrent work properly) is that the following rights need to be granted on `/var/services/web/rutorrent/share/`:

- `everyone::allow:r-x----------:fd--`
- `user:sc-rutorrent:allow:rwxpdDaARWc--:fd--`
- `group:rutorrent:allow:rwxpdDaARWc--:fd--`
- `user:http:allow:rwxp-D-------:fd--`
- `group:rutorrent:allow:rwxpdDaARWc--:fd--`

If you fix this issue it should work, but then, I'm still in awe to understand what could possibly have gone wrong.

**Comment by a7mag3ddon** [comment] 2021-02-07 16:29
What if i remove the Web folder completely after uninstall rutorrent and start again now i have all the dependancies installed which i didnt the first couple of times.

**Comment by smaarn** [comment] 2021-02-07 16:36
> What if i remove the Web folder completely after uninstall rutorrent and start again now i have all the dependancies installed which i didnt the first couple of times.

It could actually be an option but then, if possible, I would suggest you also reinstall `WebStation` before reinstalling rutorrent (I don't know who manages its initial installation to be honest).

**Comment by TrYkeRm4N** [comment] 2021-02-20 13:57
anyone manage to install rutorrent on dsm7?

**Comment by a7mag3ddon** [comment] 2021-02-20 14:16
Whatever works for 6 should also work 7 sadly not managed it

**Comment by TrYkeRm4N** [comment] 2021-02-20 15:04
when you update to dsm7 seems that programs that uses root privileges are not allowed. And the comunity rutorrent package was one of these.

**Comment by a7mag3ddon** [comment] 2021-02-20 15:07
DSM is still beta i wont be updating anytime soon

**Comment by TrYkeRm4N** [comment] 2021-02-20 15:12
I will manage it with a docker container. Still really thanks for your kind and really fast reply!!

**Comment by a7mag3ddon** [comment] 2021-02-20 16:48
What do mean? Rutorrent works in a docker?

**Comment by TrYkeRm4N** [comment] 2021-02-20 17:12
Yes, I just download thinks image:
https://hub.docker.com/r/linuxserver/rutorrent
I follow the steps that the developer wrote and its working fine. It just took 3 minutes. It not a lower performance than the native dsm6 package but still works really fine.

**Comment by mreid-tt** [comment] 2023-07-03 00:38
Hello @a7mag3ddon, it seems that this issue has been open for some time without any recent updates. Could you kindly provide us with an update on your experience with ruTorrent? If you are still encountering difficulties, we suggest giving the latest release, v4.1.5-15, a try as it may help resolve the issue. However, if you have already tested it or if the problem has been resolved, do let us know.

**Comment by mreid-tt** [comment] 2023-07-09 10:24
Closing the issue due to a lack of recent updates. However, please note that if the issue persists, it can be reopened for further investigation.

**Closed by mreid-tt** 2023-07-09 10:24 UTC
