### ISSUE TITLE
Impossible to install Horde v5.1.0-2

### ISSUE THREAD

**Issue by rodo37** [SynoCommunity/spksrc#2586] opened 2017-01-08 10:10 UTC
When I try to install the HORDE package on my DS116 I always have the following message:
"Incorrect MySQL root password"
During the installation therefore impossible to go further ....
I'm using DSM 6.1-15022

**Comment by Dr-Bean** [comment] 2017-01-08 16:39
Please use the search before opening an issue. Duplicate of https://github.com/SynoCommunity/spksrc/issues/2333

**Closed by Dr-Bean** 2017-01-08 16:39 UTC
