### ISSUE TITLE
Jackett unable to self-update

### ISSUE THREAD

**Issue by Stanzilla** [SynoCommunity/spksrc#5249] opened 2022-05-04 21:45 UTC
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

Jackett

### Package Version

0.17.668-14

### Device Model

Synology DS1621+

### Device Architecture

x86_64

### Firmware Version

7.1

### What happened?

Self-Update is erroring out, seems to be the same issue that Radarr has with the `tmp` directory

### Reproduction steps

```bash
1. Hit the "check for updates button"
2. Check logs
```

### Install Log

```log
N/A
```

### Other Logs

```log
2022-05-04 23:39:34 | Error | Error performing update. System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/tmp/JackettUpdate-v0.20.1010-637873043723739710/Jackett/JackettUpdater' with working directory '/'. Permission denied    at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)    at System.Diagnostics.Process.Start()    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)    at Jackett.Common.Services.UpdateService.StartUpdate(String updaterExePath, String installLocation, Boolean isWindows, Boolean noRestart, Boolean trayIsRunning) in /home/vsts/work/1/s/src/Jackett.Common/Services/UpdateService.cs:line 354    at Jackett.Common.Services.UpdateService.CheckForUpdates() in /home/vsts/work/1/s/src/Jackett.Common/Services/UpdateService.cs:line 139
```

**Comment by bakerboy448** [comment] 2022-05-05 01:59
The root cause appears to be that /tmp is no longer executable on DSM7.1

the jackett package will need to be updated by the synology community to use the alt tmp dir

**Comment by hgy59** [comment] 2022-10-30 21:03
@Stanzilla chan you please check, whether this issue is fixed by #5311 and Jacket Version  0.20.1171-15 released on 06/13/2022?

**Comment by Stanzilla** [comment] 2022-10-30 21:11
Is there something newer than -15?

**Comment by bakerboy448** [comment] 2022-10-30 21:12
Jackett has had dozens of updates since then, so the base package should be able to update / be tested to update internally.

**Comment by Stanzilla** [comment] 2022-10-30 21:13
Oh right, I forgot what this was about. Yes it works.

**Comment by neogamaes** [comment] 2022-12-29 08:04
I have the same issue of tmp directory permission preventing Jackett to be updated. 
Any solution identified? 
Simply need to wait for a package update from synocommunity ?

**Comment by hgy59** [comment] 2022-12-29 08:13
@neogamaes this should have been fixed in version v0.20.1171-15 with #5311

**Comment by hgy59** [comment] 2022-12-29 08:28
Retested with `DSM 7.1.1-42962 Update 3` on DS218+ (x64, apollolake)
- jacket successfully updated to v0.20.2451
- the folder /var/packages/jackett/tmp contains files owned by sc-jackett:sc-jackett, so it is writeable

**Closed by hgy59** 2022-12-29 08:28 UTC
Labels: bug

**Comment by neogamaes** [comment] 2022-12-29 10:34
I've seen you were using DSM 7.1.1 update 3. I was using update 2.
I have thus updated DSM to update 3 but still got the exact same problem even though jackett is running v0.20.2297...

**Comment by hgy59** [comment] 2022-12-29 12:35
@neogamaes could you please create a new issue, so we can track exactly your problem.

**Comment by neogamaes** [comment] 2022-12-29 12:43
Is it possible to simply reopen #13818 since that's the initial one I created?

**Comment by bakerboy448** [comment] 2022-12-29 12:44
Assuming you mean https://github.com/Jackett/Jackett/issues/13818  no.

The jackett team has nothing to do with the 3rd party maintained, created, developed, and supported SynoComm package.

**Comment by bakerboy448** [comment] 2022-12-29 12:45
Assuming you mean https://github.com/Jackett/Jackett/issues/13818  no.

The jackett team has nothing to do with the 3rd party maintained, created, developed, and supported SynoComm package.

**Comment by neogamaes** [comment] 2022-12-29 12:48
Oh I see. Sorry for my misunderstanding.  I will create a new issue.
