### ISSUE TITLE
virtualenv in python3-package does not work?

### ISSUE THREAD

**Issue by wind-rider** [SynoCommunity/spksrc#1647] opened 2015-04-12 20:14 UTC
I'm trying to build a package based on SynoCommunity's python3 package.

Running it does not work well. It seems that the virtualenv directory is not created.

When trying to run virtualenv manually, I get:

```````
-ash: /usr/local/python3/bin/virtualenv-3.4: not found
``````

I also tried the virtualenv (without -3.4 suffix), but it gives the same result.

**Comment by Dr-Bean** [comment] 2015-04-13 09:40
Confirmed. Not sure why that is right now.
This might be a workaround: `/usr/local/python3/bin/python -m pip install virtualenv`, then try again.

**Comment by wind-rider** [comment] 2015-04-13 21:37
Thank you for the quick reply, I'll look at it next weekend :) this week is a busy one for me

**Comment by Diaoul** [comment] 2015-04-19 15:50
Is this something we can fix? Or an upstream bug/feature?

**Comment by wind-rider** [comment] 2015-04-19 16:01
I don't know, building with python is new for me. Maybe @Dr-Bean knows?

**Comment by Dr-Bean** [comment] 2015-04-19 16:29
The shebangs of `/usr/local/python3/bin/virtualenv` and `/usr/local/python3/bin/pip` are wrong.

I don't think it's a generic upstream issue. It might be related to https://www.python.org/dev/peps/pep-0453: I believe PEP453 is responsible for placing `/usr/local/python3/bin/pip3.4` and `/usr/local/python3/bin/virtualenv-3.4`, and look at those shebangs.
Otherwise, I haven't done any troubleshooting, so no idea what's up with that.

**Comment by Diaoul** [comment] 2015-04-19 18:02
Maybe [this](https://github.com/SynoCommunity/spksrc/blob/master/mk/spksrc.python-module.mk#L33) is wrong?

**Comment by Dr-Bean** [comment] 2015-04-19 18:12
Yes, after rethinking my previous comment, the PEP can't be related. So, it's likely something went wrong with processing the PLIST entries.
Seems there are two seperate issues then?

- `@PYTHON_VERSION@` isn't processed correctly. That accounts for the unchanged shebang of `pip3.4` and `virtualenv-3.4` files
- The incorrect shebang of `pip` and `virtualenv` seems to be caused by `PYTHON_INTERPRETER` being set to `python` instead of `python3.4` (or a missing `python` symlink to `python3.4`, that'd work too)

**Comment by Dr-Bean** [comment] 2015-04-19 18:19
My second suggestion above is correct: https://github.com/SynoCommunity/spksrc/blob/master/cross/python3/Makefile#L76. Did Python 3.4 remove the `python` symlink then, or what happened there?

**Comment by Dr-Bean** [comment] 2015-04-19 18:28
Oh, right. The first issue is caused by `STRIP_TARGET` failing on the incorrect PLIST for PyYAML, so it skips the subsequent entries. Python3 creates a `_yaml.cpython-34m.so`, not a `_yaml.so`, so that PLIST needs an adjustment.

**Comment by Dr-Bean** [comment] 2015-04-19 18:45
Euh, wrong. That needs to be fixed too, but that's unrelated to this issue. Python2 and Python3 both suffer from the same issue, we just never caught it:
```
Fixing shebang for bin/pip@PYTHON_VERSION@... failed!
```
And that accounts for the unchanged shebang. How does that supposed to work, @Diaoul?

**Comment by wind-rider** [comment] 2015-04-19 19:14
I fixed that PyYaml PLIST in my pull request :)

**Comment by Dr-Bean** [comment] 2015-04-21 17:19
Fixed PYTHON_INTERPRETER  with https://github.com/SynoCommunity/spksrc/commit/d08d1d3ec3d7b74637100203a155b9827264b658, which should fix the `pip` and `virtualenv` commands.

Not sure there's an easy fix for the other issue with `@PYTHON_VERSION@` , although maybe I'm just not seeing it.

**Comment by Dr-Bean** [comment] 2015-04-22 09:29
@Diaoul How about replacing `@PYTHON_VERSION@` in the PLIST with `*` instead?

**Comment by Diaoul** [comment] 2015-04-22 12:02
OK for me

**Comment by Dr-Bean** [comment] 2015-04-24 09:48
Fixed with https://github.com/SynoCommunity/spksrc/commit/d8ca19eacfefd4f8968091eacf6dea53dd3fab07. We can probably delay the release of a new package until the PyYAML module is added via @wind-rider's PR.

**Closed by Dr-Bean** 2015-04-24 09:48 UTC
Labels: bug
