### ISSUE TITLE
Unable to compile openIPMI for Zabbix

### ISSUE THREAD

**Issue by chrisistheking** [SynoCommunity/spksrc#1945] opened 2015-11-19 12:21 UTC
Fairly new to this so please go easy on me ;)

I was making progress compiling Zabbix from source for cedarview until I reached openIPMI. I cannot for the life of me get this to compile. I am getting the error below:

libOpenIPMIpthread.so: undefined reference to `pthread_condattr_setclock'
collect2: ld returned 1 exit status
Makefile:702: recipe for target 'test_handlers' failed
make[4]: *** [test_handlers] Error 1
make[4]: Leaving directory '/home/hallasc/spksrc/cross/openipmi/work-cedarview/OpenIPMI-2.0.21/unix'
Makefile:503: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/hallasc/spksrc/cross/openipmi/work-cedarview/OpenIPMI-2.0.21'
Makefile:414: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/hallasc/spksrc/cross/openipmi/work-cedarview/OpenIPMI-2.0.21'
../../mk/spksrc.compile.mk:36: recipe for target 'compile_target' failed
make[1]: *** [compile_target] Error 2
make[1]: Leaving directory '/home/hallasc/spksrc/cross/openipmi'
../../mk/spksrc.cross-cc.mk:102: recipe for target 'arch-cedarview' failed
make: [arch-cedarview] Error 2 (ignored)

My makefile is as follows:
PKG_NAME = openipmi
PKG_VERS = 2.0.21
PKG_EXT = tar.gz
PKG_DIST_NAME = OpenIPMI-$(PKG_VERS).$(PKG_EXT)
# PKG_DIST_SITE = http://downloads.sourceforge.net/project/$(PKG_NAME)/OpenIPMI%202.0%20Library/$(PKG_VERS)
PKG_DIST_SITE = http://downloads.sourceforge.net/project/$(PKG_NAME)/OpenIPMI%202.0%20Library
PKG_DIR = OpenIPMI-$(PKG_VERS)

DEPENDS = cross/popt cross/ncurses cross/openssl

HOMEPAGE = http://openipmi.sourceforge.net/
COMMENT  = OpenIPMI is an effort to create a full-function IPMI system to allow full access to all IPMI information on a server and to abstract it to a level that will make it easy to use.
LICENSE  =

GNU_CONFIGURE = 1
CONFIGURE_ARGS = --with-openssl=yes
ENV += LIBS=-lrt

include ../../mk/spksrc.cross-cc.mk

I am using Ubuntu 15.10 x86 using Vitrualbox VM

Any help would be greatly apprecieted!

Chris

**Comment by Dr-Bean** [comment] 2015-11-20 09:39
Can't reproduce it on Debian Jessie. If a `make clean` doesn't work, then I'd suggest to set up a Debian VM and try with that. 
Note that you'll see a couple more errors along the way, related to optional packages and the way OpenIPMI is installed by default.

**Comment by chrisistheking** [comment] 2015-11-20 12:21
Thanks for the quick response :) ill have a go on Debian Jessie and see if i get the same issue. I used the ENV += LIBS=-lrt due to another error i was getting (cant remember the exact related file)

I noticed the makefile here included the -lrt option:
https://www.puzzle-it.nu:8443/blob/spksrc.git/master/cross%2Fopenipmi%2FMakefile

Ill update this thread as soon as ive tested this on Debian

Cheers
Chris

**Comment by chrisistheking** [comment] 2015-11-20 17:20
Unfortunately I got the same error in Debian Jessie x86  :(

/bin/bash ../libtool  --tag=CC   --mode=link /home/hallasc/spksrc/toolchains/syno-cedarview/work/x86_64-linux-gnu/bin/x86_64-linux-gnu-gcc -Wall -Wsign-compare -I../include -I../include -I/home/hallasc/spksrc/cross/openipmi/work-cedarview/install//usr/local/include   -L/home/hallasc/spksrc/cross/openipmi/work-cedarview/install//usr/local/lib -Wl,--rpath-link,/home/hallasc/spksrc/cross/openipmi/work-cedarview/install//usr/local/lib -Wl,--rpath,/usr/local/lib  -o test_heap test_heap.o  -lrt
libtool: link: /home/hallasc/spksrc/toolchains/syno-cedarview/work/x86_64-linux-gnu/bin/x86_64-linux-gnu-gcc -Wall -Wsign-compare -I../include -I../include -I/home/hallasc/spksrc/cross/openipmi/work-cedarview/install//usr/local/include -Wl,--rpath-link -Wl,/home/hallasc/spksrc/cross/openipmi/work-cedarview/install//usr/local/lib -Wl,--rpath -Wl,/usr/local/lib -o test_heap test_heap.o  -L/home/hallasc/spksrc/cross/openipmi/work-cedarview/install//usr/local/lib -lrt
/home/hallasc/spksrc/toolchains/syno-cedarview/work/x86_64-linux-gnu/bin/x86_64-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I..   -I/home/hallasc/spksrc/cross/openipmi/work-cedarview/install//usr/local/include  -Wall -Wsign-compare -I../include -I../include -I/home/hallasc/spksrc/cross/openipmi/work-cedarview/install//usr/local/include  -MT test_handlers.o -MD -MP -MF .deps/test_handlers.Tpo -c -o test_handlers.o test_handlers.c
mv -f .deps/test_handlers.Tpo .deps/test_handlers.Po
/bin/bash ../libtool  --tag=CC   --mode=link /home/hallasc/spksrc/toolchains/syno-cedarview/work/x86_64-linux-gnu/bin/x86_64-linux-gnu-gcc -Wall -Wsign-compare -I../include -I../include -I/home/hallasc/spksrc/cross/openipmi/work-cedarview/install//usr/local/include   -L/home/hallasc/spksrc/cross/openipmi/work-cedarview/install//usr/local/lib -Wl,--rpath-link,/home/hallasc/spksrc/cross/openipmi/work-cedarview/install//usr/local/lib -Wl,--rpath,/usr/local/lib  -o test_handlers test_handlers.o libOpenIPMIposix.la libOpenIPMIpthread.la ../utils/libOpenIPMIutils.la  -lrt
libtool: link: /home/hallasc/spksrc/toolchains/syno-cedarview/work/x86_64-linux-gnu/bin/x86_64-linux-gnu-gcc -Wall -Wsign-compare -I../include -I../include -I/home/hallasc/spksrc/cross/openipmi/work-cedarview/install//usr/local/include -Wl,--rpath-link -Wl,/home/hallasc/spksrc/cross/openipmi/work-cedarview/install//usr/local/lib -Wl,--rpath -Wl,/usr/local/lib -o .libs/test_handlers test_handlers.o  -L/home/hallasc/spksrc/cross/openipmi/work-cedarview/install//usr/local/lib ./.libs/libOpenIPMIposix.so ./.libs/libOpenIPMIpthread.so ../utils/.libs/libOpenIPMIutils.so -lrt
./.libs/libOpenIPMIpthread.so: undefined reference to `pthread_condattr_setclock'
collect2: ld returned 1 exit status
Makefile:702: recipe for target 'test_handlers' failed
make[4]: *** [test_handlers] Error 1
make[4]: Leaving directory '/home/hallasc/spksrc/cross/openipmi/work-cedarview/OpenIPMI-2.0.21/unix'
Makefile:503: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/hallasc/spksrc/cross/openipmi/work-cedarview/OpenIPMI-2.0.21'
Makefile:414: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/hallasc/spksrc/cross/openipmi/work-cedarview/OpenIPMI-2.0.21'
../../mk/spksrc.compile.mk:36: recipe for target 'compile_target' failed
make[1]: *** [compile_target] Error 2
make[1]: Leaving directory '/home/hallasc/spksrc/cross/openipmi'
../../mk/spksrc.cross-cc.mk:102: recipe for target 'arch-cedarview' failed
make: [arch-cedarview] Error 2 (ignored)


Any ideas?

**Comment by Dr-Bean** [comment] 2015-11-20 17:50
Are you working with a outdated fork of spksrc or something? There are several mentions of `/xyz/spksrc/toolchains/syno-cedarview/` , but that dir hasn't existed for quite a while now. There should be a version appended, e.g. `syno-cedarview-5.2`, corresponding with an actual dir with the same name.

**Comment by Dr-Bean** [comment] 2015-11-27 09:35
Closing. Please reopen if you still run into issues (after making sure your fork is up-to-date ;))

**Closed by Dr-Bean** 2015-11-27 09:35 UTC
