### ISSUE TITLE
ruTorrent errors (3.10-9)

### ISSUE THREAD

**Issue by darrell2691** [SynoCommunity/spksrc#4296] opened 2020-12-09 02:12 UTC
_For new Package Requests, see the guidelines_  

**Package Name:** ruTorrent
**Package Version:** 3.10-9
**NAS Model:** DS1819+
**NAS Architecture:** Intel Atom C3538
**DSM version:** DSM 6.2.3-25426 Update 2

**Actual behavior**
Updated ruTorrent from 3.7/8 to 3.10-9 and receive such errors

**Package log**
_Check Package Center or `/usr/local/{package}/var/`_
[09.12.2020 09:43:47] WebUI started.
[09.12.2020 09:43:48] Webserver user doesn't have read/write/execute access to the torrents directory. You cannot add torrents via ruTorrent. (/volume1/web/rutorrent/share/users/darrell/torrents)
[09.12.2020 09:43:48] Webserver user doesn't have read/write/execute access to the settings directory. ruTorrent settings cannot be saved. (/volume1/web/rutorrent/share/users/darrell/settings)
[09.12.2020 09:43:48] rTorrent user must have read/execute access to the torrents directory. You cannot add torrents via ruTorrent. (/volume1/web/rutorrent/share/users/darrell/torrents)
[09.12.2020 09:43:48] rTorrent user must have read/write/execute access to the settings directory. (/volume1/web/rutorrent/share/users/darrell/settings)
[09.12.2020 09:43:48] unpack: Plugin will not work. rTorrent user can't access external program (php).
[09.12.2020 09:43:48] loginmgr: Some functionality will be unavailable. rTorrent user can't access external program (php).
[09.12.2020 09:43:48] ratio: Some functionality will be unavailable. rTorrent user can't access external program (php).
[09.12.2020 09:43:48] autotools: Plugin will not work. rTorrent user can't access external program (php).
[09.12.2020 09:43:48] rss: Plugin will not work. rTorrent user can't access external program (php).
[09.12.2020 09:43:48] datadir: Plugin will not work. rTorrent user can't access external program (php).
[09.12.2020 09:43:48] scheduler: Plugin will not work. rTorrent user can't access external program (php).
[09.12.2020 09:43:48] _task: Plugin will not work. rTorrent user can't access external program (php).
[09.12.2020 09:43:48] xmpp: Plugin will not work. rTorrent user can't access external program (php).
[09.12.2020 09:43:48] retrackers: Plugin will not work. rTorrent user can't access external program (php).
[09.12.2020 09:43:48] rutracker_check: Plugin will not work. rTorrent user can't access external program (php).
[09.12.2020 09:43:48] trafic: Plugin will not work. rTorrent user can't access external program (php).
[09.12.2020 09:43:48] create: Plugin will not work. rTorrent user can't access external program (php).
[09.12.2020 09:43:48] history: Plugin will not work. rTorrent user can't access external program (php).
[09.12.2020 09:43:48] screenshots: Plugin will not work. rTorrent user can't access external program (ffmpeg).
[09.12.2020 09:43:48] rss: Some functionality will be unavailable. rTorrent user can't access external program (curl).
[09.12.2020 09:43:48] _task: Plugin will not work. rTorrent user can't access external program (pgrep).
[09.12.2020 09:43:48] _cloudflare: Plugin will not work. rTorrent user can't access external program (python).
[09.12.2020 09:43:48] spectrogram: Plugin will not work. rTorrent user can't access external program (sox).
[09.12.2020 09:43:48] mediainfo: Plugin will not work. rTorrent user can't access external program (mediainfo).
[09.12.2020 09:43:48] Bad response from server: (500 [error,list]) Warning: XMLRPC call is failed.
[09.12.2020 09:43:49] _cloudflare plugin: cloudscraper module can't be loaded in Python

**Comment by th0ma7** [comment] 2020-12-09 02:36
Duplicate of #4295, please provide input to already opened issue. Closing.

**Closed by th0ma7** 2020-12-09 02:36 UTC
