### ISSUE TITLE
Mono for DS216j

### ISSUE THREAD

**Issue by mouski87** [SynoCommunity/spksrc#3214] opened 2018-03-09 12:13 UTC
### Setup
_Package Name: Mono

_NAS Model: 216j
_NAS Architecture: DS216j - synology_armada38x_ds216j
_DSM version: DSM 6.1.5-15254 Update 1

Was looking to upgrade Mono (due to Radarr update process not working with Mono 4.6) via Package Center but it is not showing the same Mono v5.8.0.108-11 as listed on the package. Is it possible to have it available for update for the 216j?

**Comment by Safihre** [comment] 2018-03-09 12:19
We are aware, @ymartin59 will get it published soon.
Duplicate of #3208.

**Closed by Safihre** 2018-03-09 12:19 UTC

**Comment by mouski87** [comment] 2018-03-09 12:20
Apologies, thank you.

**Comment by jasonmotec** [comment] 2018-03-10 00:01
Thank you so much guys - it is now updated :)

By the way, for @mouski87 and @maxromanovsky - to refresh the Package Center to see the new updates... in Package Center, click on 'Community' to show all the packages coming from packages.synocommunity.com, then click on the 'Refresh' button, and this will then show all required packages that have updates
