### ISSUE TITLE
Issue on Sickbeard,Headphones,Couchpotato due to python 2.7.14-18

### ISSUE THREAD

**Issue by Dark2004** [SynoCommunity/spksrc#3179] opened 2018-02-26 17:57 UTC
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_
_Package Version:_

_NAS Model:DS211j
_NAS Architecture:
_DSM version:DSM 6.2-22259 

### Expected behavior
Package should start correctly

### Actual behavior
Package should start but it failed seeing impossible to repair them

### Steps to reproduce
1 install Python version 2.7.14-18
2 try to start Sickbeard /Couchpotato/Headphones

**Comment by Safihre** [comment] 2018-02-26 18:12
Did these packages used to work before?
How did you install those? Because they don't work on DSM 6.2 directly with the packages that are currently on the repository.
There are testing packages available for those in #3138, have you tried those?

**Comment by Dark2004** [comment] 2018-02-26 18:54
Hello,
Package was working fine before i received a notification to update this morning Python and once i have installed nothing work packages do not want to start.

I have update version of Couchpotato available in your folder but even if the package have been updated still the issue to start it so i'm a little bit stuck.

**Comment by Safihre** [comment] 2018-02-26 18:55
When you click on Show Log in the Package Center, what does it say?

**Comment by Dark2004** [comment] 2018-02-26 19:01
There is no such things in 6.2 no possibility to display logs in the package center.

**Comment by Dark2004** [comment] 2018-02-26 19:33
Do you have some idea as it's real mess?Can i downgrade the version of python easily?

thanks

**Comment by Safihre** [comment] 2018-02-26 19:35
Of the package that you got from #3138, install it, click the Refresh button (in package center on the details page of the package).
Now try to run it. 
After that, on the bottom, there should be Show Logs link.

**Comment by Dark2004** [comment] 2018-02-26 19:57
On 6.2 beta version there is no such option only way is to look into logs

**Comment by Safihre** [comment] 2018-02-26 20:33
That's strange, why is your Couchpotato log directory on another drive?
And what happens for the other packages if you install the newer version and extract the log?

**Comment by Dark2004** [comment] 2018-02-27 06:19
Hello,
It’s because i have setup my log to be store in volume2.Other does not work headphones get the same issue.

There is a means to apply python fallback as i’m stuck now?

Thanks

**Comment by Safihre** [comment] 2018-02-27 06:47
Oke then with these new packages, all you have to do is go into File Station and give read/write permissions on your log folder to the group `sc-download` and make sure to click the 'Apply to sub-folders/files'. All the new packages are part of this group and therefore they should start again. 
I have no clue how the python update could possibly cause this 🤒

**Comment by Dark2004** [comment] 2018-02-27 07:40
Hello,
I have added full right (r/w) to sc-download & sc-media but still new package does not want to start...

I have installed sickrage from your package ans this one is working.

**Comment by Safihre** [comment] 2018-02-27 07:43
Try giving `sc-download` also permissions on `/volume2/downloads` (and sub-folders/file).

**Comment by ymartin59** [comment] 2018-02-27 19:10
@Safihre What is your opinion about Python package upgrade ? Should I publish all python-related application packages first before submitting python upgrade itself ? Or do a full all-in-one upgrade step ?

**Comment by Safihre** [comment] 2018-02-27 19:25
@ymartin59 As far as I understand, the packages should be completly separate from the Python. I tested that on all 3 systems (old packages+new python _and_ new packages+old python). I don't see how they would affect each other... So I am amazed that @Dark2004 is having problems related to the update.

All I can think off is to triple check that the production package is correct with busybox etc. But I just installed DSM6.2 on my DS112j and there I am not getting the 2.7.14-18 update, so I can only test with my own Travis-compiled one. Or do you maybe have the direct link for me for the real production package?

I would first do Python for another arch before we start with Python Generic Service packages

**Comment by ymartin59** [comment] 2018-02-27 19:42
@Safihre I have deactivate package because of this first report to avoid impact on other users. Now I just enabled it temporarily again - you should get it from Package Center

**Comment by Dark2004** [comment] 2018-02-27 20:03
Hello,
Yes still the same issue for my Package already installed i do not know why. I have give full right to sc-download but issue still there.

Maybe it's linked to DSM 6.2 beta version

**Comment by ymartin59** [comment] 2018-02-27 20:29
Great ! We have at least acheived DSM 6.1 support and 6.2 already breaks it ?

**Comment by Dark2004** [comment] 2018-02-27 20:31
I do not know but the version of NZBGET it's the only one which work by updating my versions which i guess it's not using python upgrade so for me the issue is on the last python upgrade

**Comment by Safihre** [comment] 2018-02-27 21:14
No, on my DS112j with DSM 6.2-23511 which has the exact same CPU architecture everything works fine so it's not DSM6.2.
I am 100% sure that if you were to do a fresh-install of these packages that they work fine, the problem is just in some custom configuration. 
The packages currently in the package center do not run on DSM6.x (the `su: permission denied` thing) so it must have been manually edited. I did that too, by editing `start-stop-status` and the old Couchpotato also works then.

All the Python package does is provide the `python` executable, it doesn't make any permission changes etc..

**Comment by Dark2004** [comment] 2018-02-28 06:06
Hello,
Where i can editing the start-stop-status for old package?

thanks

**Comment by ymartin59** [comment] 2018-02-28 06:59
@Safihre As far as I understand, the best option is to build and publish all packages altogether...

**Comment by Safihre** [comment] 2018-02-28 08:04
@ymartin59 I think you are right.. Seems to be the best option,

**Comment by ymartin59** [comment] 2018-03-01 21:22
@Safihre OK... so the most important point is now to get the full python (not monty) package list...

**Comment by Safihre** [comment] 2018-03-08 09:02
Closing this, as the issue seems to be generally permission related and not Python-package related.

**Closed by Safihre** 2018-03-08 09:02 UTC
