### ISSUE TITLE
Jacket Works but Crashes Frequently

### ISSUE THREAD

**Issue by sea3pea0** [SynoCommunity/spksrc#1995] opened 2015-12-10 22:38 UTC
[This](https://gist.github.com/sea3pea0/0c599b738221c3086ef6) is what the logs look like from the last time this happened.
##

**Comment by Dr-Bean** [comment] 2015-12-11 10:16
That seems to me to be a Jackett bug, e.g. when disconnects/timeouts occur somewhere in the process. It could be related to Mono 4.2.1 specifically though. You could try and compile an older version of Mono 4, and see what that does.

**Comment by sea3pea0** [comment] 2015-12-12 01:16
I think you are right that it could be related to Mono 4.2.1 because I had Jackett working okay in a manual install. I remember I had to try different versions of mono until I could find one that would let jackett work without crashing. Also it could be that I had a "respawn" in my upstart script so that it would restart itself after crashes. It's quite possible that my manual install of jackett was crashing and respawning quite often. Would it be possible to have jacket restart automatically after a crash with the spkrsrc package?

**Comment by Dr-Bean** [comment] 2015-12-14 09:10
Adding an auto-restart function in the package to work around crashing software seems the wrong approach to me. We'd be better off if the software didn't crash in the first place...I would suggest to report it to the Jackett devs.

**Comment by sea3pea0** [comment] 2015-12-15 00:27
Yea I understand. Well initially I tried to work with the original developer to get the bugs ironed out but we really didn't get anywhere. The developer just dismissed the problems as bugs with mono. Since jackett is under new development it might be worth a try to see if the new developers can work out the bugs.

**Comment by Dr-Bean** [comment] 2016-01-13 09:36
@sea3pea0 Any update?

**Comment by sea3pea0** [comment] 2016-01-13 10:16
@Dr-Bean I got caught up with other things, but I just [posted](https://github.com/Jackett/Jackett/issues/185) here, so hopefully I'll have an update about this soon.

**Comment by sea3pea0** [comment] 2016-01-14 23:12
@Dr-Bean So the response to this was that the problem is with mono and it seems there may be a plan to remove the need for mono but until then nothing can be done about the problem.

**Comment by sea3pea0** [comment] 2016-01-20 10:31
@Dr-Bean Someone posted (this)[https://github.com/mafredri/jackett-apkg/commit/e61c68208e2139595266185f7d62d1eb43e582d0] as a workaround in the other thread relating to this issue.

**Comment by krazeykow** [comment] 2016-04-15 15:19
Is there a version of mono that works with Jackett? I'm running mono 4.4.0 and I keep getting crashes on my Debian seedbox.

**Comment by kaso17** [comment] 2017-01-25 17:52
Jackett v0.7.932 (pre release) contains an attempt to fix this.
Please try it and let us know the result.
https://github.com/Jackett/Jackett/issues/969

**Comment by silentmiles** [comment] 2017-04-19 08:01
I have the latest installed - .1296 - and this is still a problem. What are the chances of this getting fixed? I've seen people suggest that the problem may be in Mono, but I have both Sonarr and Radarr installed, both of which use Mono, and they have no problems.

**Comment by kaso17** [comment] 2017-04-20 11:38
@silentmiles can you please provide a log file showing a crash with the new version?

**Comment by silentmiles** [comment] 2017-04-20 14:17
I assume this is the correct log? /usr/local/jackett/var/.config/Jackett/log.txt

When the problem occurs, Jackett just becomes unresponsive. I get a blank page at /Admin/Dashboard and both Sonarr and Radarr report all of the Jackett indexers as failed. The Jackett log does not show anything.

I tried enabling enhanced logging via the web app... but that setting does not appear to be sticky. When Jackett is restarted, it reverts to normal logging. Is this the intended behaviour? Can I enable enhanced logging permanently via a configuration file setting?

**Comment by kaso17** [comment] 2017-04-20 14:46
Please start jackett with the `-t -l` arguments to make it persistent.
If there's nothing in the log it's another problem.
I remember someone else having issues with jackett on his syno device. Using the docket version fixed it for him (not sure what's the difference in the environment)

**Comment by silentmiles** [comment] 2017-04-20 15:55
> Please start jackett with the -t -l arguments to make it persistent.

What file must I edit to do this? I need this change to be affective whenever the package is restarted.

**Comment by kaso17** [comment] 2017-04-20 15:59
I don't know the init system/script used by the syno distribution.
@Dr-Bean can you help?

**Comment by ymartin59** [comment] 2018-01-01 21:50
Related to #3070

**Comment by m4tt075** [comment] 2018-01-09 18:08
Thanks to @kaso17 's fixes, `Jackett 0.8.490` has been merged into master. That means that the packages for `DSM 5.2` systems should be available via the SynoCommunity repo shortly (if they aren't already). For the time being, you can find `DSM 6.1` builds for `Jackett` on [this link here](https://github.com/m4tt075/spksrc/releases/tag/Jackett-0.8.490). Once installed, you can run further upgrades via the Jackett web-interface. These are beta packages. Therefore, please do report any kind of issues you should encounter.

**Comment by ymartin59** [comment] 2018-02-25 06:15
Mono and Jackett updates published

**Closed by ymartin59** 2018-02-25 06:15 UTC
Labels: upstream
