### ISSUE TITLE
[sabnzbd] par2 issue with libgomp.so.1

### ISSUE THREAD

**Issue by jms667** [SynoCommunity/spksrc#2735] opened 2017-04-11 12:43 UTC
Hello,
Probably since I have upgraded to sabnzbd1.2.3 (running on a xpenology box), corrupted files are not repaired with PAR2 anymore. Executing par2 comand will lead to the following error msg : 

> error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory

But libgomp.so.1 is located in /lib directory.
I have posted in sabnzb forum, but dev it's not a sabnzbd issue but more probably a packaging issue. Please see this post : https://forums.sabnzbd.org/viewtopic.php?f=2&t=22568
 
I have the same issue with  sabnzbd-testing.

Thanks for your help.

### Setup
_Package Name:_ sabnzbd 1.2.3-22 AND sabnzbd-testing 2.0.0RC1-22
_Package Version:_ sabnzbd 1.2.3-22 AND sabnzbd-testing 2.0.0RC1-22

_NAS Model:_ XPEnology box
_NAS Architecture:_ x86
_DSM version:_ DSM 5.2-5967

### Expected behavior
When corrupted downloaded files are detected, they should be repaired with PAR2.

### Actual behavior
PAR2 repairing fails.
PAR2 command fails with the following error msg : 
> error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory

### Steps to reproduce
_1._ Install sabnzbd OR sabnzbd-testing package
_2._ Launch PAR2 command 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
2017-04-07 18:59:15,606::DEBUG::[newsunpack:1194] Starting par2: ['/usr/local/sabnzbd/bin/nice', '-n15', '/usr/local/sabnzbd/bin/par2', 'r', '', '/volume1/data/Download-Temp/incomplete/13e
2017-04-07 18:59:15,650::DEBUG::[newsunpack:1510] PAR2 output was
/usr/local/sabnzbd/bin/par2: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
2017-04-07 18:59:15,650::INFO::[newsunpack:1034] Par verify failed on /volume1/data/Download-Temp/incomplete/13eb7275007d3a2217068c7b3a004de6.01/13eb7275007d3a2217068c7b3a004de6.par2!
```
#### Additional log
```
NANOBOOT> ls -l /lib/libgomp.so.1
-r-xr-xr-x    1 root     root         50984 Apr 26  2016 /lib/libgomp.so.1
NANOBOOT>
NANOBOOT> /volume1/@appstore/sabnzbd/bin/par2
/volume1/@appstore/sabnzbd/bin/par2: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
NANOBOOT>
NANOBOOT> /volume1/@appstore/sabnzbd-testing//bin/par2
/volume1/@appstore/sabnzbd-testing//bin/par2: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
NANOBOOT>
```

**Comment by KaraokeStu** [comment] 2017-04-15 17:55
Hi, I've got some further tests to do later on 2.0.0 so will take a look when I get a chance

**Comment by jms667** [comment] 2017-04-16 19:21
Thanks KaraokeStu. Hope you will have time to check this because its really annoying.
Perhaps could you quickly launch par2 command in order to check if you will get the same error message ?

**Comment by KaraokeStu** [comment] 2017-04-16 20:40
I'm running xpenology on jun's loader for dsm 6 and the par commands all work perfectly.

I'll test on the dsm 5 virtual box as soon as I get the chance

**Comment by jms667** [comment] 2017-05-11 12:05
Hi, is there something new about this issue ?

A couple of days a go, I figured out that I had a second xpenology test vm running on my esx (running same DSM version as my 'production' one). I started it again and noticed that sabnzbd was running version 1.0.3-16. I did a copy of the par2 binary from testing DSM to production DSM. Now, execution of the par2 command is again working fine (no libgomp.so.1 error anymore) :

`NANOBOOT> /volume1/@appstore/sabnzbd/bin/par2
Not enough command line arguments.
par2cmdline version 0.4, Copyright (C) 2003 Peter Brian Clements.

par2cmdline comes with ABSOLUTELY NO WARRANTY.

This is free software, and you are welcome to redistribute it and/or modify
it under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2 of the License, or (at your
option) any later version. See COPYING for details.


Usage:

  par2 c(reate) [options] <par2 file> [files] : Create PAR2 files
  par2 v(erify) [options] <par2 file> [files] : Verify files using PAR2 file
  par2 r(epair) [options] <par2 file> [files] : Repair files using PAR2 files

You may also leave out the "c", "v", and "r" commands by using "parcreate",
"par2verify", or "par2repair" instead.

Options:

  -b<n>  : Set the Block-Count
  -s<n>  : Set the Block-Size (Don't use both -b and -s)
  -r<n>  : Level of Redundancy (%%)
  -c<n>  : Recovery block count (Don't use both -r and -c)
  -f<n>  : First Recovery-Block-Number
  -u     : Uniform recovery file sizes
  -l     : Limit size of recovery files (Don't use both -u and -l)
  -n<n>  : Number of recovery files (Don't use both -n and -l)
  -m<n>  : Memory (in MB) to use
  -v [-v]: Be more verbose
  -q [-q]: Be more quiet (-q -q gives silence)
  --     : Treat all remaining CommandLine as filenames

If you wish to create par2 files for a single source file, you may leave
out the name of the par2 file from the command line.`

Hope it will help.

**Comment by Safihre** [comment] 2017-05-18 11:12
Another user reporting the same error:
https://forums.sabnzbd.org/viewtopic.php?f=2&t=22657

**Comment by byronmccollum** [comment] 2017-05-21 17:57
I have the same issue.

```
Synology> cd /volume1/@appstore/sabnzbd/bin/
Synology> ./par2
./par2: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
Synology> 
```

DSM 5.2-5644
SABnzbd 2.0.0-24

**Comment by Safihre** [comment] 2017-05-21 19:16
@KaraokeStu What could this be? Can you inspect the distributed packages to see if the file is actually present? Or could some platforms not have the right header files for some reason?

Second thing: par2cmdline itself now has merged the OpenMP changes and also applied some fixes, maybe we should switch to that? 
https://github.com/Parchive/par2cmdline/releases

If you have time 😉

**Comment by KaraokeStu** [comment] 2017-05-21 21:21
It does seem quite strange. If the standard par2cmdline now has the changes, I see no reason not to switch back. It'll be around 2 weeks, though, as I'll be on holiday!

**Comment by flobroed** [comment] 2017-06-01 17:22
Same here... :( 

@jms667 can you share that module? I really would like to have this functionality back on mine.

**Comment by jms667** [comment] 2017-06-01 19:26
@flobroed : Sure, here it is
[https://mega.nz/#!TNgyhYKZ!R_J7DByfdld6ioG02M_w1dCVqBVnocjj2zcErnpjNww](url)
Just replace `/volume1/@appstore/sabnzbd/bin/par2` with this one.

**Comment by flobroed** [comment] 2017-06-02 17:42
Damn, no luck on my synology... 

Anything I'm missing out?

xxxx> /volume1/@appstore/sabnzbd/bin/par2
/volume1/@appstore/sabnzbd/bin/par2: line 1: can't open AZ: no such file
/volume1/@appstore/sabnzbd/bin/par2: line 1:ELF: not found
/volume1/@appstore/sabnzbd/bin/par2: line 1: Q3FWD
 not found
/volume1/@appstore/sabnzbd/bin/par2: line 2: syntax error: unexpected ")"

**Comment by byronmccollum** [comment] 2017-06-02 18:33
@flobroed I'm guessing different CPU architectures. The binary @jms667 linked is x84_64. I'd guess the DS210J is a different architecture.

**Comment by flobroed** [comment] 2017-06-02 18:38
Is there any way to downgrade the sabnzb package? Anyone having an older package available?

**Comment by Safihre** [comment] 2017-06-02 18:46
Does the system have any tools to compile available? You could just compile it yourself then:https://sabnzbd.org/wiki/installation/multicore-par2 (at the bottom)

**Comment by Safihre** [comment] 2017-06-03 07:48
@KaraokeStu When you get back, could you also take a look at the Python package? 
Users have reported crazy memory usages, not just for SABnzbd but also SickRage using 350MB idle (on DSM6) after doing some work. Or SAB using 600MB after downloading something and returning back to idle.
Looks like all the compiler settings for Python haven't been touched in years, maybe it's something there?

**Comment by flobroed** [comment] 2017-06-03 12:47
Hi guys.
Thanks for the help. I managed to manually compile par2cmdline and it's working again. :)

`xxx> ls -la par2*
lrwxrwxrwx    1 root     root            19 Jun  3 14:41 par2 -> /usr/local/bin/par2
-rwxr-xr-x    1 sabnzbd  root        334272 Apr 17 14:04 par2_backsave
lrwxrwxrwx    1 root     root             4 Apr 17 14:04 par2create -> par2
lrwxrwxrwx    1 root     root             4 Apr 17 14:04 par2repair -> par2
lrwxrwxrwx    1 root     root             4 Apr 17 14:04 par2verify -> par2
xxx> par2 -V
par2cmdline version 0.7.2
`
If anyone stumbles upon this thread: During the comple I had an issue with aclocal, which had been provided as part of automake through ipkg. This was NOT working at all.

I resorted to also compiling libtool and automake from source and thus replacing the ipkg versions. Instruction for that can be found here: http://www.synology-forum.de/showthread.html?41226-hocr2pdf-auf-ds411-II/page2 (you just have to update the links for the respective websites, as the thread is 2 years old).

Anyway: Would be nice to fix this for v5 users on DSM for good, as the version in the SABnzbd package is obviously broken.

Best regards from Germany.

**Comment by Safihre** [comment] 2017-06-03 16:01
The version does work for many other people. It seems some specific tool chains are not working and need to be fixed!

**Comment by KaraokeStu** [comment] 2017-06-05 13:23
This should now be resolved, I'm going to publish the new SPKs for the sabnzbd versions shortly.

@jms667  and @flobroed could you test on your architectures once you see the new version?

**Comment by jms667** [comment] 2017-06-05 14:51
@KaraokeStu : Yes, no problem.

**Comment by KaraokeStu** [comment] 2017-06-05 15:20
Builds are now published - thanks in advance everyone!

**Comment by KaraokeStu** [comment] 2017-06-05 15:28
Just so you know on "par2 create" I'm still getting the libgomp.so and libstdc.so errors, however it does still work correctly - it is just unable to get the version information

**Comment by KaraokeStu** [comment] 2017-06-05 15:31
It appears to be because I've build the binaries against the DSM 5.x toolchains, but am running them on the DSM 6.x live system. The code, however, does still work!

**Comment by jms667** [comment] 2017-06-05 16:33
After upgrading to 2.0.1-26, I still have the same error output running par2 binary.
`NANOBOOT> ./par2
./par2: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory`
Is it 'normal' ? How can I check that sabnzbd will process par2 repairing correctly without downloading new corrupted stuff ?

**Comment by KaraokeStu** [comment] 2017-06-05 16:46
See now that's a new issue for me... I'll look into this further - what architecture are you using?

**Comment by KaraokeStu** [comment] 2017-06-05 16:47
To test, try finding a file that's at least 100MB.

Then type `par2 create test.par2 testfile.xyz` where testfile.xyz is your file.

If it creates the par2 files, then it'll be able to create, verify and repair fine

**Comment by jms667** [comment] 2017-06-05 18:46
Same issue, test fails.

`NANOBOOT> /volume1/@appstore/sabnzbd/bin/par2 create temp.par2 file.mp4
/volume1/@appstore/sabnzbd/bin/par2: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory`

I guess my architecture is bromolow/x86_64. Hardware is a HP N54L.

`NANOBOOT> cat /proc/cpuinfo | grep "processor\|model name"
processor       : 0
model name      : AMD Turion(tm) II Neo N54L Dual-Core Processor
processor       : 1
model name      : AMD Turion(tm) II Neo N54L Dual-Core Processor`

And software is xpenology, fake 3615xs Synology hosted by an ESXi6 vm.

`NANOBOOT> uname -a
Linux NANOBOOT 3.10.35 #1 SMP Sun Jul 17 16:02:22 CEST 2016 x86_64 GNU/Linux synology_bromolow_3615xs`

**Comment by KaraokeStu** [comment] 2017-06-05 19:24
That's really weird, as other than an Intel cpu, I'm running the same. What's your DSM version?

**Comment by jms667** [comment] 2017-06-05 19:35
DSM version: DSM 5.2-5967

**Comment by KaraokeStu** [comment] 2017-06-06 15:00
OK, so I've narrowed it down and got it working with DSM 5.x, however we lose the mutli-threading at the moment.

@Dr-Bean, @cytec or @Diaoul any ideas how to get this to cross-compile with openmp support?

**Comment by KaraokeStu** [comment] 2017-06-07 15:34
@Safihre I've managed to get things working by statically linking par2cmdline - anyone have any issues with par2 being 4.5Mb rather than 500Kb?

**Comment by Safihre** [comment] 2017-06-07 15:51
For the windows binary of par2cmdline the same thing happened. Here he applied the Strip command to reduce the size: https://github.com/Parchive/par2cmdline/issues/94#issuecomment-304469889

But then again, I doubt it really matters since 4.5MB is not a lot..

**Comment by KaraokeStu** [comment] 2017-06-08 09:04
Tested and confirmed working on both DSM 5 and DSM 6

**Closed by KaraokeStu** 2017-06-08 09:04 UTC

**Comment by Safihre** [comment] 2017-06-08 09:22
Thanks a lot!!

**Comment by jms667** [comment] 2017-06-08 09:38
Yes ! Thanks @KaraokeStu.
I've also tested on my xpenology box. It's working again.
