### ISSUE TITLE
SickRage update failed, uninstall/reinstall not working

### ISSUE THREAD

**Issue by olivermandic** [SynoCommunity/spksrc#2088] opened 2016-01-19 15:38 UTC
I installed SickRage on a RS814+ (w/ DSM 5.2-5644 Update 2). It worked fine until I tried to update it via a link it offered to me in the UI.
Well, it failed. Royally.
Now, even after uninstalling and reinstalling, I can't get it to start.
When I try to start it, it tries for about 45 minutes, then gives up.

I don't really know where to look for hints like an error log etc. – maybe someone could push me in the right direction?

**Comment by cytec** [comment] 2016-01-19 16:05
seems like an upstream problem to me... we don't have anything to do with the updater provided by SickRage

**Comment by olivermandic** [comment] 2016-01-19 16:16
Well, how do I get rid of whatever is causing it not to work anymore?
Seems to me like the uninstall does not erase quite everything thus rendering a fresh install defunct.

**Comment by cytec** [comment] 2016-01-19 16:20
i'm guessing that there is something broken upstream. So you will install a defunct version. Does manual installation work? btw have you seen https://github.com/SynoCommunity/spksrc/issues/2087

**Comment by olivermandic** [comment] 2016-01-19 16:22
Ah, OK, I get it.
I'll try that one.

**Comment by Dr-Bean** [comment] 2016-01-20 10:06
Duplicate of #2087. I would suggest to read the last couple of comments there :).

**Closed by Dr-Bean** 2016-01-20 10:06 UTC
Labels: bug, upstream
