### ISSUE TITLE
Ombi Request

### ISSUE THREAD

**Issue by muzzy182uk** [SynoCommunity/spksrc#4281] opened 2020-12-03 12:36 UTC
[Package Request] Ombi

Content: 

Name: Ombi
Description: Media Request Tool
Website: https://ombi.io/
Software documentation: https://github.com/tidusjar/Ombi
Build/Installation documentation: https://github.com/tidusjar/Ombi/releases
Source code: https://github.com/tidusjar/Ombi/releases
License: GPL, GPL-2.0 License

**Comment by ycflash** [comment] 2022-08-03 03:42
+1

**Comment by hgy59** [comment] 2022-08-03 16:36
duplicate of #2601

**Closed by hgy59** 2022-08-03 16:36 UTC
Labels: request, dotnet
