### ISSUE TITLE
Latest TVHeadend won't run with new ffmpeg 4.4.1-41

### ISSUE THREAD

**Issue by madfiddler** [SynoCommunity/spksrc#5232] opened 2022-04-23 23:44 UTC
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

TVHeadend

### Package Version

4.3.20220414-32

### Device Model

Synology DS918+

### Device Architecture

x86_64

### Firmware Version

7.0.1-42218 Update 3

### What happened?

I originally uninstalled TVH and reinstalled it since I wasn't aware of the ffmpeg issue, but since upgrading ffmpeg TVH still will not run

### Reproduction steps

```bash
1. Click run in the package manager
2.
3.
...
```

### Install Log

```log
Sat Apr 23 16:58:37 IST 2022
Starting tvheadend command tvheadend -f -C -u sc-tvheadend -g tvheadend --http_port 9981 --htsp_port 9982 -c /volume1/@appdata/tvheadend -p /volume1/@appdata/tvheadend/tvheadend.pid -l /volume1/@appdata/tvheadend/tvheadend.log --debug ""
2022-04-23 16:58:38.482 [  ERROR]:config: unknown subsystem '""'
2022-04-23 16:58:38.482 [   INFO]:main: Log started
2022-04-23 16:58:38.531 [   INFO]:http: Starting HTTP server 0.0.0.0:9981
2022-04-23 16:58:38.532 [   INFO]:htsp: Starting HTSP server 0.0.0.0:9982
2022-04-23 16:58:38.582 [   INFO]:config: backup: migrating config from 4.3~b871020 (running 4.3~26713c1)
2022-04-23 16:58:38.582 [   INFO]:config: backup: running, output file /volume1/@appdata/tvheadend/backup/4.3~b871020.tar.bz2
2022-04-23 16:58:38.583 [   INFO]:spawn: Executing "/bin/tar"
2022-04-23 16:58:43.529 [   INFO]:config: backup: completed
2022-04-23 16:58:43.586 [   INFO]:config: loaded
2022-04-23 16:58:43.588 [  ALERT]:CRASH: Signal: 11 in PRG: tvheadend (4.3~26713c1) [308218f8df6e17f122ba1cf60ba5e029c39202ce] CWD: /
2022-04-23 16:58:43.588 [  ALERT]:CRASH: Fault address 0x7f6e02536f80 (Access error)
2022-04-23 16:58:43.588 [  ALERT]:CRASH: Loaded libraries: linux-vdso.so.1 /var/packages/tvheadend/target/lib/libhdhomerun.so /var/packages/tvheadend/target/lib/libdvbcsa.so.1 /var/packages/tvheadend/target/lib/libssl.so.1.1 /var/packages/tvheadend/target/lib/libcrypto.so.1.1 /var/packages/tvheadend/target/lib/libz.so /var/packages/tvheadend/target/lib/libpcre2-8.so.0 /var/packages/tvheadend/target/lib/liburiparser.so.1 /var/packages/ffmpeg/target/lib/libavfilter.so.7 /var/packages/ffmpeg/target/lib/libswresample.so.3 /var/packages/ffmpeg/target/lib/libavresample.so.4 /var/packages/ffmpeg/target/lib/libswscale.so.5 /var/packages/ffmpeg/target/lib/libavformat.so.58 /var/packages/ffmpeg/target/lib/libavcodec.so.58 /var/packages/ffmpeg/target/lib/libavutil.so.56 /var/packages/ffmpeg/target/lib/libva.so.2 /var/packages/ffmpeg/target/lib/libva-drm.so.2 /lib64/libdl.so.2 /lib64/libpthread.so.0 /lib64/libm.so.6 /var/packages/tvheadend/target/lib/libiconv.so.2 /lib64/librt.so.1 /lib64/libc.so.6 /var/packages/ffmpeg/target/lib/libpostproc.so.55 /var/
2022-04-23 16:58:43.588 [  ALERT]:CRASH: Register dump [23]: 00000000000000ca000000000000000100000000000000a200007f6dff19bf6000007fff4dd369c000007fff4dd36c200000000000024b2500007fff4dd36ba000007fff4dd3699800007f6dff19bf1000007fff4dd3699800007f6e02536f2000000000000000b200007f6e02554fe0000000000000000000007fff4dd3699000007f6e0205ecb5000000000001020200000000000000330000000000000007000000000000000efffffffe7ffbfa1700007f6e02536f80
2022-04-23 16:58:43.588 [  ALERT]:CRASH: STACKTRACE
2022-04-23 16:58:43.588 [   INFO]:config: scanfile (re)initialization with path <none>
2022-04-23 16:58:43.669 [  ALERT]:CRASH:  0x561972e88f5a 0x561972c99000
2022-04-23 16:58:43.674 [  ALERT]:CRASH:  0x7f6dff19ec20 0x7f6dff18d000
2022-04-23 16:58:43.678 [  ALERT]:CRASH:  0x7f6e0205ecb5 0x7f6e01f5e000
2022-04-23 16:58:43.683 [  ALERT]:CRASH:  0x7f6dff19bec7 0x7f6dff18d000
2022-04-23 16:58:43.687 [  ALERT]:CRASH:  0x561972f662ba 0x561972c99000
2022-04-23 16:58:43.695 [  ALERT]:CRASH:  0x561972e39e46 0x561972c99000
2022-04-23 16:58:43.695 [  ALERT]:CRASH: __libc_start_main+0xea  (/lib64/libc.so.6)
2022-04-23 16:58:43.700 [  ALERT]:CRASH:  0x561972e3cc0a 0x561972c99000
```

### Service Log

```log
2022/04/23 00:15:29     start tvheadend 4.3.20220414-32 Begin start-stop-status stop
2022/04/23 00:15:29     start tvheadend 4.3.20220414-32 End start-stop-status stop ret=[0]
2022/04/23 00:15:31     start tvheadend 4.3.20220414-32 Begin start-stop-status start
2022/04/23 00:15:33     start tvheadend 4.3.20220414-32 End start-stop-status start ret=[0]
2022/04/23 00:15:38     start tvheadend 4.3.20220414-32 Begin start-stop-status stop
2022/04/23 00:15:38     start tvheadend 4.3.20220414-32 End start-stop-status stop ret=[0]
2022/04/23 00:15:41     start tvheadend 4.3.20220414-32 Begin start-stop-status start
2022/04/23 00:15:42     start tvheadend 4.3.20220414-32 End start-stop-status start ret=[0]
2022/04/23 16:58:33     start tvheadend 4.3.20220414-32 Begin start-stop-status stop
2022/04/23 16:58:33     start tvheadend 4.3.20220414-32 End start-stop-status stop ret=[0]
2022/04/23 16:58:37     start tvheadend 4.3.20220414-32 Begin start-stop-status start
2022/04/23 16:58:38     start tvheadend 4.3.20220414-32 End start-stop-status start ret=[0]
```

**Comment by th0ma7** [comment] 2022-04-24 01:50
This is a duplicate of #5222
You can download latest update v4.4.1-42 for ffmpeg manually that will resolve your issue.
https://synocommunity.com/package/ffmpeg

Re-open as needed, cheers!

**Closed by th0ma7** 2022-04-24 01:50 UTC
Labels: bug

**Comment by madfiddler** [comment] 2022-04-25 16:19
Thank you, all good now!
