### ISSUE TITLE
Redis fails to run

### ISSUE THREAD

**Issue by greeneka** [SynoCommunity/spksrc#1690] opened 2015-05-16 12:41 UTC
Hi,

I have a DS415Play and have installed the Redis package, but it refuses to start.

Clicking "View Log" on the package center gives "No Data" and looking in /var/log/synopkg.log shows:
start redis: begin to start version 2.8.13-3
start redis: start version 2.8.13-3 successfully, result 0

Any help/pointers much appreciated!

**Comment by Diaoul** [comment] 2015-05-19 18:41
Try to run it from command line. Binaries are in `/usr/local/redis/bin`
Let us know the result.

**Comment by Diaoul** [comment] 2015-06-02 08:57
@greeneka: any updates?

**Comment by greeneka** [comment] 2015-06-02 20:56
Apologies for the delay in replying.

It looks like it's actually running, but the package center does not recognise it as running for some reason...

DiskStation> ps | grep redis
10011 redis    21592 S    /usr/local/redis/bin/redis-server *:6379

![image](https://cloud.githubusercontent.com/assets/12472587/7946990/0bd9694a-0972-11e5-80a6-ea5017e8f8ab.png)

I do not know what needs to be set in order for the package center to see that it's running ok?

Thanks for the replies!

**Comment by Diaoul** [comment] 2015-06-02 21:08
The startup script is in `/var/packages/redis/scripts/start-stop-status` check it out, if you can find something wrong please report back so we can fix this.

**Comment by greeneka** [comment] 2015-06-02 21:46
The startup script seems to behave ok - if you stop redis using the script and then "Run" using the package center it starts ok, the only problem appears to be that the package center does not recognise that redis is running.

I'm not clear on what the package center does to decide whether the app is running - perhaps there is some specific return value that needs to come out of the script?

**Comment by Diaoul** [comment] 2015-06-02 21:57
Yes, run the same script with `status` instead of `start`, this should output the correct status, if not, the script needs investigating.
The part responsible to report the status is this: https://github.com/SynoCommunity/spksrc/blob/master/spk/redis/src/dsm-control.sh#L29-L36
This is pretty standard so I'm not sure what's wrong. Maybe redis can't create the pid file for some reason?

**Comment by greeneka** [comment] 2015-06-02 22:17
Interesting - my script does not have the LOG_FILE set:

DiskStation> cat start-stop-status
#!/bin/sh

# Package
PACKAGE="redis"
DNAME="Redis"

# Others
INSTALL_DIR="/usr/local/${PACKAGE}"
PATH="${INSTALL_DIR}/bin:/usr/local/bin:/bin:/usr/bin:/usr/syno/bin"
USER="redis"
REDIS="${INSTALL_DIR}/bin/redis-server"
PID_FILE="${INSTALL_DIR}/var/redis.pid"
CFG_FILE="${INSTALL_DIR}/var/redis.conf"


start_daemon ()

Editing it and adding the LOG_FILE means that clicking "view log" in the package center now works - but, the package center is still not recognising that it's running, it still lists it as "stopped" despite the fact it is running.

The script does appear to return the correct status, so I've no idea why the package center is misbehaving.

Thanks for your help so far!

**Comment by greeneka** [comment] 2015-06-02 22:59
Ok - tried chown-ing to a non-root user (to match other packages dirs) with no joy.

Also tried removing all "echo"s from the script, just in case that was confusing things.

Finally tried *always* returning 0, regardless of actual status.

All to no avail - at this stage I think I'm going to call it quits (for today, at least)

**Comment by Dr-Bean** [comment] 2015-09-11 17:07
This is caused by https://github.com/SynoCommunity/spksrc/blob/master/spk/redis/Makefile#L5. Package Center gets confused when the dir doesn't actually exist. It should probably be added to `redis_extra_install`.

**Comment by Dr-Bean** [comment] 2015-09-15 09:14
Fixed with https://github.com/SynoCommunity/spksrc/commit/420b87277569434efb169ac6798e0ebff0d4fea3, along with an update of Redis to 3.0.4

**Closed by Dr-Bean** 2015-09-15 09:14 UTC

**Comment by Dr-Bean** [comment] 2015-10-26 11:58
redis 3.0.5-5 has been published on the repository, and that should solve the problem you saw.
