### ISSUE TITLE
Python 2.7.9 update breaks SABnzbd 7.20.13

### ISSUE THREAD

**Issue by dakhdakh** [SynoCommunity/spksrc#1580] opened 2015-03-22 16:11 UTC
Just updated to Python 2.7.9 on an 1812+, and I now cannot retrieve nzb files from http://nzb.su/ or https://www.oznzb.com/, when using Sabnzbd. This means that Couchpotato or Sickbeard do not work with SABnzbd either.

I  get "WAIT xx sec / Trying to fetch NZB from https://[oznzb url]/[SOMEFEEDID]" in SABnzbd.

Manually uploading the .nzb file into Sabnzbd works fine. 

Is it possible to revert back to Python 2.7.8?

I have a Synology DS 1812+. Hope you can help, please. Thank you.

**Comment by Dr-Bean** [comment] 2015-03-22 16:13
Dupe of https://github.com/SynoCommunity/spksrc/issues/1575. Please post there.

**Closed by Dr-Bean** 2015-03-22 16:13 UTC
