### ISSUE TITLE
invalid location on DSM 6.0 via DOCKER (DS916+)

### ISSUE THREAD

**Issue by tparvais** [SynoCommunity/spksrc#2579] opened 2017-01-02 14:57 UTC
_NAS Model:_ 916+
_DSM version:_ DSM 6.0.2-8451 Update 7

### Expected behavior
When trying to add http://packages.synocommunity.com/ as packet source, I get "Invalid Location"

This works on my DSM default, but not via Docker-DSM

Of course, I checkled DNS issue, etc... it's ok

Any idea ?

**Comment by Dr-Bean** [comment] 2017-01-02 15:03
Correct. Duplicate of https://github.com/SynoCommunity/spksrc/issues/1889

**Closed by Dr-Bean** 2017-01-02 15:03 UTC

**Comment by tparvais** [comment] 2017-01-02 15:05
that's a pity as virtualDSM is a nice tool to test different packages without endangering the generic install...

**Comment by Dr-Bean** [comment] 2017-01-02 15:10
I'm not saying it won't be added, but there are other dependencies that need to be handled first.
