### ISSUE TITLE
ruTorrent - bad response from server

### ISSUE THREAD

**Issue by mal68** [SynoCommunity/spksrc#4336] opened 2020-12-28 00:31 UTC
### Setup
_Package Name:_ ruTorrent
_Package Version:_ 3.10-10

_NAS Model:_ DS415+
_NAS Architecture:_ x64
_DSM version:_ DSM 6.2.3-25426 Update 3

### Expected behavior
Installed and ran the updated rutorrent package for the first time in years, I changed the default download directory, left all other settings as default

clicked on the link within the package expecting it to open the functioning web ui

The link was http://xxxxxx.synology.me/rutorrent/

### Actual behavior
the web ui was opened but it doesn't work

the webui log shows

[28.12.2020 11:02:57] WebUI started.
[28.12.2020 11:02:57] Bad response from server: (500 [error,getplugins]) Internal Server Error

### Steps to reproduce
_1._ install
_2._ change download directory (not sure if this is important)
_3._ run

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_

This is the log from the rutorrent_install
```

Mon Dec 28 11:01:48 AEDT 2020
===> Step preuninst. USER=rutorrent GROUP=sc-download SHARE_PATH=/volume1/Media
Removing service configuration rutorrent.sc
Mon Dec 28 11:01:50 AEDT 2020
===> Step postuninst. USER=rutorrent GROUP=sc-download SHARE_PATH=/volume1/Media
Removing user sc-rutorrent
Invoke service_postuninst
Mon Dec 28 11:01:51 AEDT 2020
===> Step Removing web interface. USER=rutorrent GROUP=sc-download SHARE_PATH=/volume1/Media
Mon Dec 28 11:02:33 AEDT 2020
===> Step preinst. USER=rutorrent GROUP=sc-download SHARE_PATH=/volume1/Media
Invoke service_preinst
Mon Dec 28 11:02:34 AEDT 2020
===> Step postinst. USER=rutorrent GROUP=sc-download SHARE_PATH=/volume1/Media
Installing service configuration /var/packages/rutorrent/conf/rutorrent.sc
Adding 'sc-rutorrent' to 'sc-download'
Group Name: [sc-download]
Group Type: [AUTH_LOCAL]
Group ID:   [65536]
Group Members: 
0:[sc-transmission]
1:[sc-rutorrent]
Configuring /volume1/Media
Invoke service_postinst
/var/packages/rutorrent/scripts/service-setup: line 187: /usr/local/python3/bin/virtualenv: No such file or directory
/var/packages/rutorrent/scripts/service-setup: line 189: /volume1/@appstore/rutorrent/env/bin/pip: No such file or directory
Fixing shared folder rights for /volume1/@appstore/rutorrent/tmp
(synoacltool.c, 455)Unknown error 
Fixing shared folder access for everyone
ACL version: 1 
Archive: has_ACL,is_support_ACL 
Owner: [sc-rutorrent(user)] 
--------------------- 
	 [0] everyone::allow:r-x----------:fd--  (level:0)
Fixing shared folder access for user:sc-rutorrent
ACL version: 1 
Archive: has_ACL,is_support_ACL 
Owner: [sc-rutorrent(user)] 
--------------------- 
	 [0] everyone::allow:r-x----------:fd--  (level:0)
	 [1] user:sc-rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
Fixing shared folder access for group:rutorrent
ACL version: 1 
Archive: has_ACL,is_support_ACL 
Owner: [sc-rutorrent(user)] 
--------------------- 
	 [0] everyone::allow:r-x----------:fd--  (level:0)
	 [1] group:rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
	 [2] user:sc-rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
Fixing shared folder access for user:http
ACL version: 1 
Archive: has_ACL,is_support_ACL 
Owner: [sc-rutorrent(user)] 
--------------------- 
	 [0] everyone::allow:r-x----------:fd--  (level:0)
	 [1] user:http:allow:rwxp-D-------:fd--  (level:0)
	 [2] user:sc-rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
	 [3] group:rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
Fixing shared folder access for group:http
ACL version: 1 
Archive: has_ACL,is_support_ACL 
Owner: [sc-rutorrent(user)] 
--------------------- 
	 [0] everyone::allow:r-x----------:fd--  (level:0)
	 [1] group:http:allow:rwxp-D-------:fd--  (level:0)
	 [2] group:rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
	 [3] user:sc-rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
	 [4] user:http:allow:rwxp-D-------:fd--  (level:0)
find ${folder} -mindepth 1 -type d -exec synoacltool -enforce-inherit {} \;
Fixing shared folder access for /var/services/web
ACL version: 1 
Archive: has_ACL,is_support_ACL 
Owner: [root(user)] 
--------------------- 
	 [0] group:http:allow:r-x---a-R-c--:fd--  (level:0)
	 [1] user:http:allow:r-x---a-R-c--:fd--  (level:0)
	 [2] user:sc-rutorrent:allow:--x----------:---n  (level:0)
	 [3] group:administrators:allow:rwxpdDaARWc--:fd--  (level:0)
	 [4] user:admin:allow:rwxpdDaARWc--:fd--  (level:0)
==================================================== 
User/Group: [sc-rutorrent/sc-download,rutorrent]

Final permission: [--x----------] 

Fixing shared folder rights for /var/services/web/rutorrent/share
(synoacltool.c, 455)Unknown error 
Fixing shared folder access for everyone
ACL version: 1 
Archive: has_ACL,is_support_ACL 
Owner: [sc-rutorrent(user)] 
--------------------- 
	 [0] everyone::allow:r-x----------:fd--  (level:0)
Fixing shared folder access for user:sc-rutorrent
ACL version: 1 
Archive: has_ACL,is_support_ACL 
Owner: [sc-rutorrent(user)] 
--------------------- 
	 [0] everyone::allow:r-x----------:fd--  (level:0)
	 [1] user:sc-rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
Fixing shared folder access for group:rutorrent
ACL version: 1 
Archive: has_ACL,is_support_ACL 
Owner: [sc-rutorrent(user)] 
--------------------- 
	 [0] everyone::allow:r-x----------:fd--  (level:0)
	 [1] group:rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
	 [2] user:sc-rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
Fixing shared folder access for user:http
ACL version: 1 
Archive: has_ACL,is_support_ACL 
Owner: [sc-rutorrent(user)] 
--------------------- 
	 [0] everyone::allow:r-x----------:fd--  (level:0)
	 [1] user:http:allow:rwxp-D-------:fd--  (level:0)
	 [2] user:sc-rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
	 [3] group:rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
Fixing shared folder access for group:http
ACL version: 1 
Archive: has_ACL,is_support_ACL 
Owner: [sc-rutorrent(user)] 
--------------------- 
	 [0] everyone::allow:r-x----------:fd--  (level:0)
	 [1] group:http:allow:rwxp-D-------:fd--  (level:0)
	 [2] group:rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
	 [3] user:sc-rutorrent:allow:rwxpdDaARWc--:fd--  (level:0)
	 [4] user:http:allow:rwxp-D-------:fd--  (level:0)
find ${folder} -mindepth 1 -type d -exec synoacltool -enforce-inherit {} \;


```

This is the log from rtorrent

`1609113758 W Ignoring rtorrent.rc.`

**Comment by vtopc** [comment] 2021-02-16 20:25
Have the same logs, I guess the problem is due to `/var/packages/rutorrent/scripts/service-setup: line 187: /usr/local/python3/bin/virtualenv: No such file or directory` error

**Comment by vtopc** [comment] 2021-02-16 21:25
> Have the same logs, I guess the problem is due to `/var/packages/rutorrent/scripts/service-setup: line 187: /usr/local/python3/bin/virtualenv: No such file or directory` error

OK, so installing `Python3` package for the community resolved that error 
```
ls -la /usr/local | grep python3
lrwxrwxrwx  1 root root   26 Feb 16 22:58 python3 -> /volume1/@appstore/python3
```

but ruTorrent still not working.

---

@mal68, where can I get webui log?

**Comment by vtopc** [comment] 2021-02-16 21:49
> @mal68, where can I get webui log?

nvm, found

**Comment by vtopc** [comment] 2021-02-23 08:59
@mal68 , did it helped?
> OK, so installing `Python3` package from the community resolved that error

**Comment by mreid-tt** [comment] 2023-07-03 00:36
Hello @mal68, it seems that this issue has been open for some time without any recent updates. Could you kindly provide us with an update on your experience with ruTorrent? If you are still encountering difficulties, we suggest giving the latest release, v4.1.5-15, a try as it may help resolve the issue. However, if you have already tested it or if the problem has been resolved, please let us know.

**Comment by mreid-tt** [comment] 2023-07-09 10:24
Closing the issue due to a lack of recent updates. However, please note that if the issue persists, it can be reopened for further investigation.

**Closed by mreid-tt** 2023-07-09 10:24 UTC
