### ISSUE TITLE
'Home Assistant' does not start on DS220j

### ISSUE THREAD

**Issue by BlueWhaleSEO** [SynoCommunity/spksrc#4269] opened 2020-11-21 13:55 UTC
### Setup
_Package Name:_ [Home Assistant ](https://synocommunity.com/package/homeassistant)
_Package Version:_ 0.114.2-7 

_NAS Model:_ [DS220j](https://global.download.synology.com/download/Document/Hardware/DataSheet/DiskStation/20-year/DS220j/enu/Synology_DS220j_Data_Sheet_enu.pdf?_ga=2.211685909.1610306812.1605904614-1003422424.1605904614&_gl=1*2o7ql3*_ga*MTAwMzQyMjQyNC4xNjA1OTA0NjE0*_ga_9Q8XT3X20D*MTYwNTk2Njg4NC41LjAuMTYwNTk2Njg4NC4w) 
_NAS Architecture:_ rtd1296 
_DSM version:_ DSM 6.2.3-25426 Update 2 

### Expected behavior
After package gets visually installed (alongside [Python3 v3.7.7-15 package](https://synocommunity.com/package/python3) as dependency), clicking on 'Run' (or ticking 'Run after installation' box) should start Home Assistant. 

### Actual behavior
An error is shown: 'Failed to run the package service.'. 
Package installation doesn't prompt for any user input either (no new user or new folder setup, etc).
There is 40GB space still available on volume1. 

### Steps to reproduce
_1._ Go to Package Center > Community.
_2._ Click 'Run' on Home Assistant package.

#### Package log
_Home Assistant log: `/var/packages/homeassistant/target/var/homeassistant.log`_
```
Starting homeassistant command /volume1/@appstore/homeassistant/env/bin/hass -v --config /volume1/@appstore/homeassistant/var/config --pid-file /volume1/@appstore/homeassistant/var/homeassistant.pid --log-file /volume1/@appstore/homeassistant/var/homeassistant.log --daemon 
/var/packages/homeassistant/scripts/start-stop-status: line 49: /volume1/@appstore/homeassistant/env/bin/hass: No such file or directory 
```
#### Other logs
_Install log: `/var/packages/homeassistant/target/var/homeassistant_install.log`_
```
Granting 'sc-homeassistant' unix ownership on /volume1/@appstore/homeassistant/var
===> Step preuninst. USER=homeassistant GROUP= SHARE_PATH=
Removing service configuration homeassistant.sc
Sat Nov 21 12:48:27 GMT 2020
===> Step postuninst. USER=homeassistant GROUP= SHARE_PATH=
Removing user sc-homeassistant
Sat Nov 21 13:41:28 GMT 2020
===> Step preinst. USER=homeassistant GROUP= SHARE_PATH=
Sat Nov 21 13:41:29 GMT 2020
===> Step postinst. USER=homeassistant GROUP= SHARE_PATH=
Installing service configuration /var/packages/homeassistant/conf/homeassistant.sc
Invoke service_postinst
created virtual environment CPython3.7.7.final.0-64 in 3499ms
  creator CPython3Posix(dest=/volume1/@appstore/homeassistant/env, clear=False, global=True)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/root/.local/share/virtualenv/seed-v1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
Looking in links: /volume1/@appstore/homeassistant/share/wheelhouse
Processing /volume1/@appstore/homeassistant/share/wheelhouse/HAP_python-3.0.0-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/Jinja2-2.11.2-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/MarkupSafe-1.1.1-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/PyISY-1.1.0-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/PyJWT-1.7.1-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/PyYAML-5.3.1-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/aioautomatic-0.6.5-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/aiohttp-3.6.2-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/aiohttp_cors-0.7.0-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/aiohue-2.2.0-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/astral-1.10.1-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/async_timeout-3.0.1-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/attrs-19.3.0-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/boto3-1.14.41-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/certifi-2020.6.20-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/cffi-1.14.1-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/chardet-3.0.4-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/ciso8601-2.1.3-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/colorlog-3.1.4-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/curve25519_donna-1.3-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/distro-1.5.0-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/ecdsa-0.15-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/ed25519-1.5-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/ephem-3.7.7.1-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/gTTS_token-1.1.3-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/gmpy2-2.0.8-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/home_assistant_frontend-20200811.0-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/homeassistant-0.114.2-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/homekit-0.17.0-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/idna_ssl-1.1.0-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/ifaddr-0.1.7-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/ledcontroller-1.3.0-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/multidict-4.7.6-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/mutagen-1.41.0-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/netdisco-2.8.1-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/netifaces-0.10.9-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/oauth2client-4.0.0-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/paho_mqtt-1.5.0-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/phue-1.1-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/pushbullet.py-0.11.0-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/pycparser-2.20-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/pycryptodome-3.9.8-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/pycsspeechtts-1.0.3-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/pyephem-3.7.7.0-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/pyephember-0.3.1-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/pyfritzhome-pre_dsm6_526_g76373b41-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/pyfttt-0.3.2-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/pyotp-2.2.6-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/pysabnzbd-1.1.0-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/pysnmp-4.4.12-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/python_libnmap-0.7.0-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/python_nmap-0.6.1-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/python_pushover-0.3-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/python_slugify-4.0.1-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/python_wink-1.10.5-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/pytz-2020.1-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/requests-2.24.0-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/ruamel.yaml-0.15.100-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/six-1.15.0-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/text_unidecode-1.3-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/tlslite_ng-0.7.5-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/transmissionrpc-0.11-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/typing-3.7.4.3-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/ua_parser-0.10.0-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/urllib3-1.25.10-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/user_agents-2.1-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/voluptuous-0.11.7-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/voluptuous_serialize-2.4.0-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/wakeonlan-1.1.6-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/websocket_client-0.37.0-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/xbee_helper-0.0.7-py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/xmltodict-0.12.0-py2.py3-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/yarl-1.5.1-cp37-none-any.whl
Processing /volume1/@appstore/homeassistant/share/wheelhouse/zeroconf-0.28.0-py3-none-any.whl
Installing collected packages: HAP-python, Jinja2, MarkupSafe, PyISY, PyJWT, PyYAML, aioautomatic, aiohttp, aiohttp-cors, aiohue, astral, async-timeout, attrs, boto3, certifi, cffi, chardet, ciso8601, colorlog, curve25519-donna, distro, ecdsa, ed25519, ephem, gTTS-token, gmpy2, home-assistant-frontend, homeassistant, homekit, idna-ssl, ifaddr, ledcontroller, multidict, mutagen, netdisco, netifaces, oauth2client, paho-mqtt, phue, pushbullet.py, pycparser, pycryptodome, pycsspeechtts, pyephem, pyephember, pyfritzhome, pyfttt, pyotp, pysabnzbd, pysnmp, python-libnmap, python-nmap, python-pushover, python-slugify, python-wink, pytz, requests, ruamel.yaml, six, text-unidecode, tlslite-ng, transmissionrpc, typing, ua-parser, urllib3, user-agents, voluptuous, voluptuous-serialize, wakeonlan, websocket-client, xbee-helper, xmltodict, yarl, zeroconf
  Attempting uninstall: MarkupSafe
    Found existing installation: MarkupSafe 1.1.1
    Not uninstalling markupsafe at /volume1/@appstore/python3/lib/python3.7/site-packages, outside environment /volume1/@appstore/homeassistant/env
    Can't uninstall 'MarkupSafe'. No files were found to uninstall.
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 5.3
    Not uninstalling pyyaml at /volume1/@appstore/python3/lib/python3.7/site-packages, outside environment /volume1/@appstore/homeassistant/env
    Can't uninstall 'PyYAML'. No files were found to uninstall.
  Attempting uninstall: cffi
    Found existing installation: cffi 1.14.0
    Not uninstalling cffi at /volume1/@appstore/python3/lib/python3.7/site-packages, outside environment /volume1/@appstore/homeassistant/env
    Can't uninstall 'cffi'. No files were found to uninstall.
ERROR: Could not install packages due to an EnvironmentError: [Errno 28] No space left on device
```

**Comment by hgy59** [comment] 2020-11-21 20:54
This is a duplicate of #4205

**Closed by hgy59** 2020-11-21 20:54 UTC
