### ISSUE TITLE
Package source unavailable in Docker DSM

### ISSUE THREAD

**Issue by dArk4psyco** [SynoCommunity/spksrc#2328] opened 2016-05-17 22:16 UTC
in Docker DSM i can not add Synocommunity package source.
Message "invalid location" appears.
I have set the Trust Level to Synology Inc. and trusted publishers.

**Comment by Dr-Bean** [comment] 2016-05-18 06:10
Use the search before opening an issue as per the [guidelines](https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#issues)
Duplicate of https://github.com/SynoCommunity/spksrc/issues/1889.

**Closed by Dr-Bean** 2016-05-18 06:10 UTC
