### ISSUE TITLE
Jellyfin service doesn't start on DS213j (armada370)

### ISSUE THREAD

**Issue by piwi82** [SynoCommunity/spksrc#5030] opened 2021-12-30 14:52 UTC
### Setup
_Package Name:_ Jellyfin 
_Package Version:_ 10.7.7-4

_NAS Model:_ DS213j
_NAS Architecture:_ armada370
_DSM version:_ 7.0.1-42218

### Expected behavior
When started, the package status should show status "Installed".

### Actual behavior
The package doesn't start and always shows status "Launch" in Package Center.
No Jellyfin process visible using `ps -aux`

### Steps to reproduce
_1._ Install Jellyfin package
_2._ Launch the package

#### Package log
_Installer log:_ `/var/log/packages/{package}.log`
```
2021/12/30 15:16:14     install jellyfin 10.7.7-4 Begin start-stop-status start
2021/12/30 15:16:14     install jellyfin 10.7.7-4 End start-stop-status start ret=[0]
2021/12/30 15:17:09     start jellyfin 10.7.7-4 Begin start-stop-status stop
2021/12/30 15:17:09     start jellyfin 10.7.7-4 End start-stop-status stop ret=[0]
2021/12/30 15:17:17     start jellyfin 10.7.7-4 Begin start-stop-status start
2021/12/30 15:17:17     start jellyfin 10.7.7-4 End start-stop-status start ret=[0]
2021/12/30 15:21:36     start jellyfin 10.7.7-4 Begin start-stop-status stop
2021/12/30 15:21:36     start jellyfin 10.7.7-4 End start-stop-status stop ret=[0]
2021/12/30 15:21:45     start jellyfin 10.7.7-4 Begin start-stop-status start
2021/12/30 15:21:45     start jellyfin 10.7.7-4 End start-stop-status start ret=[0]
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
2021-12-30T15:16:15+01:00 isaac coredump[27797]: Process jellyfin[27773](/volume1/@appstore/jellyfin/share/jellyfin) dumped core on signal [4]. Core file [/volume1/@jellyfin.core.gz]. Cmdline [/volume1/@appstore/jellyfin/share/jellyfin --service --package-name synology -d /volume1/@appdata/jellyfin/data -C /volume1/@appdata/jellyfin/cache -c /volume1/@appdata/jellyfin/config -l /volume1/@appdata/jellyfin/log -w /volume1/@appstore/jellyfin/web --ffmpeg /var/packages/ffmpeg/target/bin/ffmpeg ]
2021-12-30T15:16:20+01:00 isaac coredump[27797]: Core file [/volume1/@jellyfin.core.gz] size [2877494]
2021-12-30T15:16:54+01:00 isaac synopkg[28114]: pkgtool.cpp:2373 Package jellyfin stops but service pkgctl-jellyfin.service start, ret=[3]
2021-12-30T15:17:18+01:00 isaac coredump[28762]: Process jellyfin[28737](/volume1/@appstore/jellyfin/share/jellyfin) dumped core on signal [4]. Core file [/volume1/@jellyfin.core.gz]. Cmdline [/volume1/@appstore/jellyfin/share/jellyfin --service --package-name synology -d /volume1/@appdata/jellyfin/data -C /volume1/@appdata/jellyfin/cache -c /volume1/@appdata/jellyfin/config -l /volume1/@appdata/jellyfin/log -w /volume1/@appstore/jellyfin/web --ffmpeg /var/packages/ffmpeg/target/bin/ffmpeg ]
2021-12-30T15:17:26+01:00 isaac coredump[28762]: Core file [/volume1/@jellyfin.core.gz] size [2895428]
2021-12-30T15:21:46+01:00 isaac coredump[30727]: Process jellyfin[30694](/volume1/@appstore/jellyfin/share/jellyfin) dumped core on signal [4]. Core file [/volume1/@jellyfin.core.gz]. Cmdline [/volume1/@appstore/jellyfin/share/jellyfin --service --package-name synology -d /volume1/@appdata/jellyfin/data -C /volume1/@appdata/jellyfin/cache -c /volume1/@appdata/jellyfin/config -l /volume1/@appdata/jellyfin/log -w /volume1/@appstore/jellyfin/web --ffmpeg /var/packages/ffmpeg/target/bin/ffmpeg ]
2021-12-30T15:21:54+01:00 isaac coredump[30727]: Core file [/volume1/@jellyfin.core.gz] size [2877207]
```

**Comment by publicarray** [comment] 2022-01-01 09:33
I'm sorry, but it appears your NAS's CPU is not officially supported by .NET see #4528

**Comment by piwi82** [comment] 2022-01-07 11:59
Thank you for this answer !
The Jellyfin package shouldn't be built for armada370 and other architectures not supported by .NET.
Hoping a developer will add `UNSUPPORTED_ARCHS = $(ARMv5_ARCHS) $(OLD_PPC_ARCHS)` to [Jellyfin makefile](https://github.com/SynoCommunity/spksrc/blob/master/cross/jellyfin/Makefile).

**Comment by publicarray** [comment] 2022-01-07 12:18
Some arm cpus do work though. And ppc isn't build anyway. I suppose we can try to find the exact architectues that don't work. the problem is that it differs for raddar and jellyfin. There is a PR that had them disabled for some arches but it was reversed when someone reported that one was working on their CPU. https://github.com/SynoCommunity/spksrc/pull/4824#issuecomment-908227903

**Comment by th0ma7** [comment] 2022-01-07 12:28
isn't possible to simply add `armada370` to the list?

**Comment by hgy59** [comment] 2022-01-07 14:18
> isn't possible to simply add `armada370` to the list?

no, this only fails for `make arch-armada370-6.1` etc. 
`make arch-armv7-6.1` still succeeds and in the INFO file contains the whole list of the generic archs.
for armv7 this is
`armada370 armada375 armada38x alpine alpine4k armadaxp comcerto2k monaco`

The solution (that is missing) would be to avoid all unsupported archs in the INFO file, when building generic for a generic arch.

**Comment by ta264** [comment] 2022-05-11 18:16
@piwi82 I have tried to compile a version of dotnet that would support armada370.  Would you be able to help me test it?  With a view to supporting Radarr.

**Comment by mreid-tt** [comment] 2023-02-03 16:32
With the release of [Jellyfin 10.8.9](https://synocommunity.com/package/jellyfin) to the SynoCommunity repository, it removes all support for 32-bit architectures (includes all ARMv7 archs). As such, I recommend that this ticket be closed as these platforms will no longer be supported moving forward.

**Closed** 2023-02-09 12:13 UTC
Labels: dotnet
