### ISSUE TITLE
libstdc++6 needed for zigbee2mqtt in virtual environment, how to add?

### ISSUE THREAD

**Issue by schumi2004** [SynoCommunity/spksrc#3686] opened 2019-04-15 08:57 UTC
I'm trying to install zigbee2mqtt server on my DS715 (Alpine) using a virtual Python3 environment as described here: https://www.zigbee2mqtt.io/information/virtual_environment.html

Createing the venv is easy but getting zigbee2mqtt installed is an issue.
After following the setup steps and reporting an issue https://github.com/Koenkk/zigbee2mqtt/issues/1415 i was told i should install libstdc++6

Can anyone guide me how to have this installed?
I don't have apt-get and it will not work using pip.
Should i modify the Python3 package to include libstdc++6 or is there a better/quicker way to have this available on my system?

**Comment by chickenandpork** [comment] 2019-04-15 14:59
The root cause seems to be that the upstream binary was compiled for the wrong platform.

Caveat: I’ve been trying to find a block of time to rebuild the python cross-compile.  I would not block your project on the unknown eta of that.

The hint is that it’s looking for a core system library — I would disagree with the advice you have received, but honestly I don’t know the full story why someone would suggest installing a core system library.  Maybe I can research more of that thread.

I see “npm” and “node:” so it may be a node.js app?  This is surprising, as though either the node.js is not the “alpine” arch you need for your ds715, or node.js some some FFI (foreign function interface, iirc?)  I think the more reliable fix would be in his node.js is installed.

I’m not 100% sure, and I’m sorry if I’m re-walking ground you’ve gone over.  I’m on a bus on a small screen with good intentions but poor bandwidth :(

**Comment by schumi2004** [comment] 2019-04-15 18:09
@chickenandpork I did saw your previous comment and i appreciate the time and effort you put in it so far. thanks. 
I will do some more research also but my knowledge is limited. Already had to reinstall DSM because of this :)

**Comment by schumi2004** [comment] 2019-04-17 07:12
I think the problem lies in the fact that for Alpine architecture no version information is available and thus zigbee2mqtt fails.
I'm not sure if it is wise to copy lib from Ubuntu like suggested by user here https://bugs.alpinelinux.org/issues/4903 but i think that could solve the problem.

Maybe it's possible to create a package for zigbee2mqtt but not sure if that will work.

**Comment by ymartin59** [comment] 2019-05-31 13:07
I think process is really similar to what I tried to get python-openzwave #3638 for homeassistant... in some cases, python module build process makes assumption of standard linux distribution and ignore cross-compilation situation...

**Comment by hgy59** [comment] 2023-09-08 19:56
closing this, as we have cross/libstc++ available (at least since #4484)

**Closed by hgy59** 2023-09-08 19:56 UTC
