### ISSUE TITLE
mosquitto 1.4.8 update

### ISSUE THREAD

**Issue by timoline** [SynoCommunity/spksrc#2297] opened 2016-05-03 18:18 UTC
Its almost a year ago.... :-)
Can you please update mosquitto to 1.4.8 ?
http://mosquitto.org/download/

And please enable websockets by default 
#1723

Thanx

**Comment by Dr-Bean** [comment] 2016-05-09 08:15
PR's welcome.

**Comment by sarfata** [comment] 2016-05-13 06:10
@Dr-Bean here you go! Let me know if I need to change anything. First time contribution here.

**Comment by timoline** [comment] 2016-05-13 07:56
Great, thx !

i'm not sure it makes any difference, but shouldn't the listener 9001 include the local address ?

listener 1883
listener 9001 127.0.0.1
protocol websockets

**Comment by sarfata** [comment] 2016-05-13 17:46
If you include the local address then you would not be able to connect from other computer on the network. I think what most people want to do is use a browser based MQTT client and that requires port 9001 being available on every interfaces.

We should do much much better in terms of security and include a password file and a way to edit it but I have no idea how you would do that. Is there a way to do that for packages (I mean without having to SSH in)?

**Comment by tedstriker** [comment] 2016-06-13 22:36
afaik wizard files could be used for initial configuration. When I remember it correct, the [Notification Forwarder](https://www.cphub.net/?id=40&pid=534) on cphub.net heavily used them in a streamlined way.
Besides having that icing on the cake, I'd highly appreciate to have an updated version of mosquitto that is compatible with DSM 6's start/stop scripts. Further config improvement could be added later on.
What has to be done, to have this PR merged into the main branch and the repo?

**Comment by rosterloh** [comment] 2016-07-26 13:56
#2411

**Comment by KaraokeStu** [comment] 2016-09-20 14:22
Closed as a duplicate of https://github.com/SynoCommunity/spksrc/issues/2418

**Closed by KaraokeStu** 2016-09-20 14:22 UTC
Labels: request, status/duplicate, update
