### ISSUE TITLE
Please add DS119J support: armada37xx architecture

### ISSUE THREAD

**Issue by michass** [SynoCommunity/spksrc#3477] opened 2018-10-03 12:36 UTC
Please add DS119J support 

_NAS Model: DS119J
_NAS Architecture: Armada 3720
_DSM version: 6.2

**Comment by William0702** [comment] 2018-10-20 19:51
PLease add support 4 DS119J!

Cannot add Syno.Community as Source...

Model DS119J
Armada 3720
DSM 6.2.1 vers 23824

**Comment by ymartin59** [comment] 2018-10-20 21:01
This new architecture `armada37xx` is not supported yet.

**Comment by michass** [comment] 2018-10-20 21:02
But why?

Pobierz aplikację Outlook dla systemu Android<https://aka.ms/ghei36>

________________________________

**Comment by ymartin59** [comment] 2018-10-20 21:05
Maybe answers there: https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#my-architecture-is-not-listed-in-the-package-details-can-it-be-made-available

**Comment by michass** [comment] 2018-10-20 21:06
But jadahl have domoticz package for this architecture

Pobierz aplikację Outlook dla systemu Android<https://aka.ms/ghei36>

________________________________

**Comment by ymartin59** [comment] 2018-10-21 07:10
We have to wait for Synology to publish toolchain to build for `armada37xx` architecture - at the moment, not available: https://sourceforge.net/projects/dsgpl/files/DSM%206.2%20Tool%20Chains/

**Comment by Jumbotroll** [comment] 2018-10-22 07:01
I don't know why synology has removed toolchain from sourceforge, but I did download toolchain and kernel for armada37xx last month. 

Regards
Jadahl

**Comment by michass** [comment] 2018-10-22 07:32
> I don't know why synology has removed toolchain from sourceforge, but I did download toolchain and kernel for armada37xx last month.
> 
> Regards
> Jadahl

Maybe can you share?
:D

**Comment by William0702** [comment] 2018-11-04 19:49
Jadahl, could you please share?

**Comment by michass** [comment] 2018-11-05 14:34
@Jumbotroll please :)

**Comment by ymartin59** [comment] 2018-11-06 21:51
@Jumbotroll I have read somewhere that chip supplier delivered a "proprietary" version of GCC to compile for armada37xx... which may be a reason why Synology is not allowed to redistribute it as other DSM toolchains.

**Comment by KosakAlmighty** [comment] 2018-11-06 23:12
Is there chance it will never be released? Because I think I will return my DS119j.

**Comment by ymartin59** [comment] 2018-11-11 11:09
The only relevant point I see to make progress:  armada37xx owners should publish posts on Synology forum and submit support requests to Synology so that to get this architecture toolchain published like others at SourceForge location.

**Comment by William0702** [comment] 2018-11-11 16:51
@ymartin59 made a support request.. awaiting their answer. I will post their return here.
Still hoping that @Jumbotroll will help the community by sharing though..

**Comment by ymartin59** [comment] 2018-11-17 20:04
I think I discovered answer. Synology has replaced original "Tool Chain" by development "toolkit" where armada37xx is available: https://sourceforge.net/projects/dsgpl/files/toolkit/DSM6.2/
That toolkit is really large and even redistribute Oracle Java 7 and 8 (not sure it is compliant with Oracle license)

I fear it will cost lot of efforts to adapt spksrc build chain to this new "standard" from Synology

**Comment by William0702** [comment] 2018-11-17 21:00
Nice, good find!!

What is your expectation in the matter?
Do you think this new "standard"  of Synology will be the next standard for all new models/architectures?

And do you think the effort will be put in to the devolpment for the support for the Armada37xx line?

Tnx!

**Comment by ymartin59** [comment] 2018-11-18 10:33
"old" Synology "Tool Chains" archive is maximum 50 MiB large per architecture whereas "toolkit" consists in a base linux system (Python 2.7 and 3.4, Ruby, NodeJS, Perl, LLVM, TCL, PHP, Apache Flex, Java 6, 7 and 8 => 800 MiB) and a per architecture environment with gcc and java 7, 8 (so around 300 MiB)
This a is show-stopper in our plans to build on cloud service where we cannot afford to download 1 GiB compiler for each package build.An option may be to include base and compiler in Docker image, which will become itself really large (or else we have to maintain an image per architecture)

As an immediate work-around, I am trying to re-create a "tool chain" for "armada37xx" created from "toolkit" content (only required libraries for gcc, no java) with hope it is far enough to generate our package with current spksrc build chain.

My opinion is there is no chance to get Synology to maintain "classical toolchains" archive in addition to toolkits, even if Docker/cloud based compilation argument may change their mind about it.

Another question: there is chance that rtd1296 and armada37xx compiler produces compatible binaries (depending on supplier specific optimizations in gcc "variants"). @hgy59 As our "cross-compiler and kernel expert", may you be kind to check if spksrc may provide a "aarch64" generic package for both architectures (the same way we did for x64)

CC @Safihre @m4tt075  @Diaoul

**Comment by Safihre** [comment] 2018-11-18 12:55
Damn, that would suck if they stick with this "kit" thing! Working on packages was already hard enough as it is with all the different systems + permissions handeling 😢

**Comment by Jumbotroll** [comment] 2018-11-18 16:41
Here you go guys..
http://www.jadahl.com/synosource/DSM_6.2_22259/
I will close this url very soon...

**Comment by hgy59** [comment] 2018-11-18 19:48
@ymartin59 
> Another question: there is chance that rtd1296 and armada37xx compiler produces compatible binaries (depending on supplier specific optimizations in gcc "variants"). @hgy59 As our "cross-compiler and kernel expert", may you be kind to check if spksrc may provide a "aarch64" generic package for both architectures (the same way we did for x64)
> 

It looks very good. 
The two toolkits provided by synology for rtd1296 (ds.rtd1296-6.2.env.txz) and armada37xx (ds.armada37xx-6.2.dev.txz) differ only in 5 header files (../usr/include/linux/netfilter...)
and some of these header files differ even between rtd1296 toolchain and rtd1296 toolkit.
So the rtd1296 toolchain/compiler can be used for generic aarch64 builds.

Maybe there will be compilation problems for packages depending on "netfilter", but I would encourage to try generic aarch64 packages.

I can not make any suggestion for the kernel modules, but as far as I can remember only the LIRC package depends on kernel module.

**Comment by ymartin59** [comment] 2018-11-18 21:39
@hgy59 Many thanks. I will generate some test packages that way. It would be great if ARMv7 toolchains would be closer, because list is quite long: `alpine armada370 armada375 armada38x armadaxp comcerto2k monaco hi3535 ipq806x northstarplus` ... and I am not comfortable to request you to review all of theses, but I would be pleased to reduce the generated packages set the same way with one or some generic/common binaries.

**Comment by William0702** [comment] 2018-11-24 10:54
Hmm,

Wenn I try to add SB or CP I get an error that Python and Git are missing on the packageserver..

Any ideas?

**Comment by ymartin59** [comment] 2018-11-25 14:57
Python and Git SynoCommunity packages are not available for your architecture yet.

**Comment by ymartin59** [comment] 2018-11-26 20:53
As a first trial, here is "tmux" package created with rtd1296 toolchain but declared as compatible with armada37xx: 
[tmux_aarch64-6.1_2.3-3.spk.zip](https://github.com/SynoCommunity/spksrc/files/2617278/tmux_aarch64-6.1_2.3-3.spk.zip)
May you please install it manually on your systems and check if it works

**Comment by KosakAlmighty** [comment] 2018-11-26 22:51
Have you guys managed to download origin toolchain for this architecture, which was later removed and then posted here by not specified user for very short time?

**Comment by KosakAlmighty** [comment] 2018-11-27 07:33
@ymartin59 I tested the tmux package and I can confirm it works on DS119j without problem.
![tmux](https://user-images.githubusercontent.com/10359620/49065713-1e3ca900-f21f-11e8-8bad-3b8c61587e1a.PNG)

**Comment by William0702** [comment] 2018-11-28 21:08
had to order a new disk for the DS119J, wich will arrive friday.
I'll try to test this weekend..

**Comment by William0702** [comment] 2018-11-29 19:45
@ymartin59 
Tested it and it works!!

**Comment by KosakAlmighty** [comment] 2018-12-03 07:39
Just out of curiosity, how long it takes till new packages are compiled?

**Comment by William0702** [comment] 2018-12-04 06:05
Daar Santa. 

For xmas i woud like to  have git, CP, transmission and SB this year. And  if i forgot something to get these packages running in my Ds119j, be so kind to add as you please.  

Thank you Santa 🎅🎅🎅

**Comment by KosakAlmighty** [comment] 2018-12-04 06:53
Oh my bad, I thought the packages are generated automatically. I reading
readme now, I will dig in on weekend and see if I can make some packages :)

Once more thanks for all your work.

**Closed** 2018-12-07 22:07 UTC
Labels: arch

**Comment by ymartin59** [comment] 2018-12-09 18:00
@William0702 You should find packages in your DSM Package Center. If not, just report here.

**Comment by ymartin59** [comment] 2018-12-09 21:54
... Sorry not yet. python 2.7 is still pending...

**Comment by William0702** [comment] 2018-12-14 08:58
@ymartin59 

Happily installing the packages.
Thanks for all the support!!

**Comment by ymartin59** [comment] 2018-12-20 09:33
Python should be available now - and so applications requiring python 2.17
