### ISSUE TITLE
Syncthing Not Starting, after update to 1.19.0.25

### ISSUE THREAD

**Issue by tenwa** [SynoCommunity/spksrc#5142] opened 2022-03-02 14:30 UTC
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

Syncthing

### Package Version

1.19.0.26

### Device Model

DS620slim

### Device Architecture

x86_64

### Firmware Version

DSM 7.0.1-42218 Update 2

### What happened?

Having updated to version 1.19.0-25, when trying to start syncthing, i'm getting the following error in the sycnthing.log

```
WARNING: Failed to initialize config: config file version (36) is newer than supported version (35). If this is expected, use --allow-newer-config to override.
[monitor] 11:31:17 INFO: Syncthing exited: exit status 1

```

How can I resolve this?

### Reproduction steps

```bash
1. Got DSM Package Centre
2. Start Syncthing
3. After a few seconds, the syncthing service fails to start, and I end back at the option to run the service, checked the log file, and see the above error.
```

### Install Log

```log
Wed Mar  2 11:31:14 GMT 2022
Begin service_prestart
End service_prestart
Starting syncthing command /volume1/@appstore/syncthing/bin/syncthing serve --home=/volume1/@appdata/syncthing  
[start] 11:31:14 INFO: syncthing v1.19.0 "Fermium Flea" (go1.17.5 linux-amd64) root@publish 2022-02-03 19:51:15 UTC
[start] 11:31:14 WARNING: Failed to initialize config: config file version (36) is newer than supported version (35). If this is expected, use --allow-newer-config to override.
[monitor] 11:31:14 INFO: Syncthing exited: exit status 1
[start] 11:31:15 INFO: syncthing v1.19.0 "Fermium Flea" (go1.17.5 linux-amd64) root@publish 2022-02-03 19:51:15 UTC
[start] 11:31:15 WARNING: Failed to initialize config: config file version (36) is newer than supported version (35). If this is expected, use --allow-newer-config to override.
[monitor] 11:31:15 INFO: Syncthing exited: exit status 1
[start] 11:31:16 INFO: syncthing v1.19.0 "Fermium Flea" (go1.17.5 linux-amd64) root@publish 2022-02-03 19:51:15 UTC
[start] 11:31:16 WARNING: Failed to initialize config: config file version (36) is newer than supported version (35). If this is expected, use --allow-newer-config to override.
[monitor] 11:31:16 INFO: Syncthing exited: exit status 1
[start] 11:31:17 INFO: syncthing v1.19.0 "Fermium Flea" (go1.17.5 linux-amd64) root@publish 2022-02-03 19:51:15 UTC
[start] 11:31:17 WARNING: Failed to initialize config: config file version (36) is newer than supported version (35). If this is expected, use --allow-newer-config to override.
[monitor] 11:31:17 INFO: Syncthing exited: exit status 1
[monitor] 11:31:18 WARNING: 4 restarts in 4.203793074s; not retrying further
```

**Comment by julienguyonnet** [comment] 2022-03-06 15:50
Same behavior for me. Same DSM version, syncthing only package added.

**Comment by tenwa** [comment] 2022-03-09 10:15
Thanks for that, got it up and running again.

**Comment by Git-Forked** [comment] 2022-03-09 16:12
SSH into system, get to /var/packages/syncthing 
then tried to get into the /var folder
error: "Permission denied"
try: sudo cd var
error:  "cd: command not found"
try: su
error: "Permission denied"

**Comment by sandos187** [comment] 2022-03-09 16:15
> SSH into system, get to /var/packages/syncthing then tried to get into the /var folder error: "Permission denied" try: sudo cd var error: "cd: command not found" try: su error: "Permission denied"

Try 'sudo su'
then you switched to root and are able to user 'cd', but be careful! ;-(

**Comment by Git-Forked** [comment] 2022-03-09 16:23
Be careful of what? 
the rest was easy. 
$ mv config.xml config.xml.crashed
$ cp config.xml.v35 config.xml

**Comment by Git-Forked** [comment] 2022-03-09 16:25
However.. syncthing still does not start.

**Comment by sandos187** [comment] 2022-03-09 16:42
> 

Take a look in sycnthing.log in the same directory as your config.xml

**Comment by sandos187** [comment] 2022-03-09 16:52
> What command for viewing the file works in Synology? `less syncthing.log` `nano syncthing.log` 'Command not found'

you could just 'cat' it. Just 'cat syncthing.log'

**Comment by Git-Forked** [comment] 2022-03-09 16:54
Log shows: 
WARNING: Failed to initialize config: failed to load config: open /volume1/@appstore/syncthing/var/config.xml: permission denied

**Comment by Git-Forked** [comment] 2022-03-09 17:06
I likely need to `chown` the new file to the proper user, since I used cp instead of mv and cp copied the new file as root.

**Comment by tenwa** [comment] 2022-03-09 17:10
Thats what I had to do, just make it look like the other config files, and it sould work.

**Comment by Git-Forked** [comment] 2022-03-09 17:11
Tried: 
`chown syncthing:sc-syncthing config.xml`
"invalid user"

**Comment by tenwa** [comment] 2022-03-09 17:12
both parts need to be sc-syncthing I think so sc-syncthing:sc-syncthing should work.

**Comment by Git-Forked** [comment] 2022-03-09 17:13
The other files show: 
sc-syncthing syncthing
(group) (user)

**Comment by tenwa** [comment] 2022-03-09 17:15
Ah my showed sc-syncthing for both.

**Comment by Git-Forked** [comment] 2022-03-09 17:17
I tried your suggestion, but it shows sc-syncthing for both, which was expected, but the other files show 'syncthing' as the user.

**Comment by Git-Forked** [comment] 2022-03-09 17:18
I gave it a shot anyways, and attempted to run it, and surprisingly it did run.  So, should I not worry about the owner being different than the other files?

**Comment by tenwa** [comment] 2022-03-09 17:25
I've just check my old dsm 6 nas, and that has sc-syncthing sycnthing, but also it did not have a problem upgrading. 

Sorry no idea if it will cause a problem, will keep my fingers crossed :)

**Comment by Git-Forked** [comment] 2022-03-10 10:36
Logged back into the Synology NAS via SSH this morning and the file has changed itself back to user 'syncthing' from 'sc-syncthing'
-rw------- 1 sc-syncthing syncthing 21727 Mar  9 13:43 config.xml

**Comment by sandos187** [comment] 2022-03-10 10:47
> Logged back into the Synology NAS via SSH this morning and the file has changed itself back to user 'syncthing' from 'sc-syncthing'
> 
> -rw------- 1 sc-syncthing syncthing 21727 Mar 9 13:43 config.xml
> 
> PS: And things still seem to be working.

just for clarification: the first of the two columns is the user and the second is the group. so it is user 'sc-syncthing' and group 'syncthing'. But at least it is still working and will hopefully get fixed in the next release, so there is no hands-on needed again.

**Comment by tenwa** [comment] 2022-03-10 10:48
I'll keep my fingers crossed.

**Comment by Git-Forked** [comment] 2022-03-11 16:19
> Hi and sorry for not responding earlier. If you have problems with a package, try to @mention the respective maintainer listed on the package. Otherwise I won't get a notification and it's pure luck when issues will be discovered.
> 
> Regarding the actual failure: I don't think the config update is the real problem here. Syncthing was changed a while ago to first try an automatic upgrade before failing on a "future" configuration version. If the upgrade succeeds, the config will be read fine.
> 
> I still don't have enough information to diagnose this properly, so keeping fingers crossed won't help I'm afraid. How did you end up with these config.xml and Syncthing package versions? Did you update the package recently, and from which previous version? Did you save any other logs that might help in finding the actual cause?
> 
> All permission issues aside, the upgrade should Just Work without any copying of config files etc.

Yes, it was due to a upgrade of syncthing package, (and possibly the DSM).  Everything was working fine previously.  
Synology alerted to a newer DSM being available and some newer packages.  I updated.  Afterwards Syncthing would no longer launch.  Using the solutions from @gerricom and some tips from @sandos187 and @tenwa, I was able to get Syncthing running again. I'll check if I have any relevant logs to share.

**Comment by acolomb** [comment] 2022-03-14 20:02
I'd still really like to fix this, as it definitely seems to be a problem with the packaging.  It affected multiple users, but we don't have enough evidence to identify where things started to go wrong.  Maybe @publicarray or @hgy59 have an idea what could have happened?

**Comment by moJinn** [comment] 2022-03-16 23:39
Affected here too

**Comment by acolomb** [comment] 2022-03-17 00:06
Turns out this is an issue with upstream Syncthing which doesn't handle upgrades gracefully if it finds a configuration file from a newer version.  The related issue that was resolved in 2020 was about Syncthing's database folder, this time it's the configuration file.

I'm currently discussing with upstream how to best go about fixing this in the SPK package.  An approach already suggested two years ago by @Safihre would seem to avoid most problems: Just don't overwrite the syncthing binary during upgrades if it is newer than the one shipped in the SPK.  I'm still working out the details to prepare a fix for this package.

@moJinn the easiest workaround is to edit the `config.xml` file and replace `version="35"` in the first line with `version="36"`.  The difference in versions is purely cosmetic, so I don't expect any troubles.  Do you know where to find the file and how to edit it with root privileges?

**Comment by moJinn** [comment] 2022-03-17 00:10
@acolomb I do not, but I do know how to get to the file

**Comment by acolomb** [comment] 2022-03-17 00:13
Do you have SSH access ready?  I've never tried doing this from the DSM GUI, no idea if it's possible without a terminal.  If you have one and know the correct path, `sudo nano config.xml` should get you going.

**Comment by moJinn** [comment] 2022-03-17 00:14
@acolomb I'm not sure how to elevate to root privileges, I think i could take it from there

**Comment by acolomb** [comment] 2022-03-17 00:17
That's what `sudo` does. Try this:

    sudo nano /var/packages/syncthing/var/config.xml

**Comment by moJinn** [comment] 2022-03-17 00:19
yes I understand, but I've never set up a password, this is the first time I've SSH in to the nas. (and it does ask for a password) I'm trying to find some tutorials but not having much luck yet

**Comment by acolomb** [comment] 2022-03-17 00:22
Just don't `cd` there.  Enter the command with the absolute path as above.  If you do want to have a root shell instead, `sudo bash` will take you there.  The password is always the same one you log into DSM with (as admin account), and for SSH, as well as sudo.

**Comment by moJinn** [comment] 2022-03-17 00:35
lol I don't understand a lot of what you're saying. Can suggest that while you are looking in to whats going on, I can honestly say people would really really appreciate a tutorial or something as a workaround (as long as its not too much work)

**Comment by acolomb** [comment] 2022-03-17 00:51
Yea, totally understandable. This requires quite a bit of low-level understanding of the DSM system. Can't promise when I will be able to work on this, but rest assured I'm aware of the trouble it's causing.

**Comment by moJinn** [comment] 2022-03-17 21:56
@acolomb I got in to the file, and followed your instructions. Although the version is already 36

**Comment by moJinn** [comment] 2022-03-17 22:30
Found an error in the log, that it was expecting to see version 35, so changed it from 36 to 35 and it worked. running again

**Comment by moJinn** [comment] 2022-03-17 22:53
What worked for me,

Workaround instructions:

SSH into the NAS (if needed, enable SSH service) *google the instructions, youtube tutorials available*

Access via terminal and enter command

`sudo nano /var/packages/syncthing/var/config.xml` (if nano is not installed *google how to install nano on synology, youtube tutorials available*
(enter your password to access the DSM)

Once in nano and the config file is open, edit the version from 36 to 35 (top line), ctrl+X to exit and y to save

Go back to pakage center on DSM and find syncthing, click start.

Disable SSH service (just good practice to do so)

end.

When going back in to the config file, the version changed back to 36

**Comment by acolomb** [comment] 2022-03-18 05:20
Thanks for summarizing and sorry, I mixed up the versions when writing. Changing from 36 to 35 is correct. When Syncthing has successfully started, it switches back to 36 after upgrading itself.

**Comment by publicarray** [comment] 2022-03-23 09:36
@[acolomb](https://github.com/acolomb) does my reply help? https://discord.com/channels/732558169863225384/905064261984845836/955563629716062279

**Comment by acolomb** [comment] 2022-03-23 13:49
@publicarray I will test as soon as I have some spare time.

**Comment by acolomb** [comment] 2022-03-27 21:24
Anyone affected, you may want to try out if the tentative fix at #5181 avoids the issue in your case.  Just download the build artifact for your architecture: Look under the "Checks" section, click Details, then switch to the workflow runs using the three dots button on the top right.  Select the PR from that list again, then find your package file under "Artifacts".

Right now it will forcefully trigger the problematic situation, because the package still contains v1.19.0 but ya'll should be on v1.19.1 already.  This testing package will just keep the installed binary intact to avoid the error.

**Comment by acolomb** [comment] 2022-04-02 10:48
Another really quick way to fix the situation is this command run from an SSH session:

    sudo -u sc-syncthing /var/packages/syncthing/target/bin/syncthing --home /var/packages/syncthing/var/ --allow-newer-config

**Comment by Moisie2000** [comment] 2022-04-11 09:12
Hi @acolomb 

Slightly tangential, but also a victim of this recent package update...

After upgrading to 1.19.0-25 (sorry - can't remember exactly which version beforehand - but it was definitely a recent release), I also couldn't start the Syncthing package.

I've SSHed and changed the version number in config.xml - and though I can start Syncthing with the command-line invocation noted above, I still can't start it as a package.

Further investigation has shown my `options.conf` to be tripping it up: if I comment out this line, the package starts correctly:

```SYNCTHING_OPTIONS="${SYNCTHING_OPTIONS} -logfile /volume1/Admin/Logs/Syncthing/syncthing.log"```

This was working previously (and, indeed, adding the `-logfile` argument to the command-line invocation works as expected) - but now it seems the `options.conf` processing in the package is broken. This was previously investigated and fixed in https://github.com/SynoCommunity/spksrc/issues/3761 - but I don't know if this is the same issue again...

Thanks!

**Comment by acolomb** [comment] 2022-04-11 20:10
So the default behavior is to log Syncthing's console output to `/var/packages/syncthing/var/syncthing.log` now, see https://github.com/SynoCommunity/spksrc/wiki/Service-Support#service-startup.  You probably don't need the logfile argument anymore.

Your definition of `SYNCTHING_OPTIONS` looks strange though, as it references itself.  AFAIK you only need to assign a value to it, the variable will be undefined unless you set it in options.conf.  If that's the cause why it isn't starting -- I don't know.  Maybe better you start a new issue and post some error messages from the log.

**Comment by D4nte** [comment] 2022-04-28 01:45
@acolomb. thank you for that. Also faced the issue with an upgrade to 1.19.0-25. I had a `config,xml` file with `version="36"` containing all my folder and a `config.xml.new` file with `version="35"` which did not contain any of my folders.

I was able to fix the issue by changing `36` to `35` in `config.xml`.

Can you clarify how an _upgrade_ of the package led in getting an _older_ binary of syncthing?

**Comment by Moisie2000** [comment] 2022-05-03 10:36
@acolomb Many apologies for the delay in replying - and thanks for your quick response!

I've tried to find where the logging behaviour is now different - and failed. However, I'll take your word that it's changed - and so I'm sure my logging option was conflicting with the standard scripts - it certainly all seems to be ok now that I've removed it.

**Closed** 2022-05-03 20:21 UTC
Labels: bug
